var NAVTREEINDEX0 =
{
"@ref dev-build":[0,1,3],
"@ref dev-pull":[0,1,5],
"@ref dev-push":[0,1,6],
"@ref dev-remote-repo":[0,1,4],
"AboutJenkins.html":[0,0,2],
"ConfigurationParameters.html":[0,2,1,0],
"InputFileDescription.html":[0,2,1],
"InstallUsersDevelopers.html":[0],
"InstallViaConda.html":[0,0,1],
"IssueTracking.html":[0,3],
"MigrationTool.html":[0,2,1,2],
"OutputFileDescription.html":[0,2,4],
"ReqsInstallViaConda.html":[0,0,0],
"ReqsRun.html":[0,2,0],
"Running.html":[0,2],
"ScriptingInPython.html":[0,2,2,0],
"Simulating.html":[0,2,2],
"SimulationSteps.html":[0,2,3],
"SupplementaryFiles.html":[0,2,1,1],
"ViaConda.html":[0,0],
"dev-branching.html":[0,1,7],
"dev-dependencies.html":[0,1,2],
"dev-fork-clone.html":[0,1,1],
"dev-overview.html":[0,1],
"dev-reqs.html":[0,1,0],
"dev-wrap-up.html":[0,1,8],
"index.html":[],
"pages.html":[],
"tutorials.html":[0,2,2,1]
};
