#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l pmem=200mb
#PBS -l walltime=00:01:00
#PBS -l qos=debugging
#PBS -A default_project
#PBS -N output

cd $PBS_O_WORKDIR

module purge
module restore env-PlatoSim3

PLATO_PROJECT_HOME=$VSC_DATA/PlatoSim3
export PLATO_PROJECT_HOME
PLATO_WORKDIR=$VSC_DATA/sims
export PLATO_WORKDIR
PYTHONPATH=$PLATO_PROJECT_HOME/python:${VSC_DATA}/python_lib/lib/python3.7/site-packages/
export PYTHONPATH

python testPlatosim.py
