#!/usr/bin/env python3

"""
This script is an integrated part of PlatoSim's toolkit PLATOnium.
Call this script prior to running your simulations with "platonium"
to generate the following files:

  - instrumentGaps.txt : Realistic distribution of spacecraft down times
  - instrumentPRE.txt  : Pointing errors for each mission quarter pointing
  - instrumentAPE.txt  : Alignment errors between cameras and the optical bench
  - instrumentTED.txt  : Long-term camera drift due to Thermo-Elastic Distortion
  - run.pbs & data.pbs : Job and parameterisation file for SLURM parallelisation
  - inputfile.yaml     : Copy and adjust a YAML file (only if it doesn't exist)

While using the "--project" output path, the files will be generated
directly into your working directory and will immediately be known
and used when running "platonium". 
"""
#TOCOME   - instrumentGain.txt : Gain differences for the each CCD (F and E side) and FEE

# Python standard
import os
import math
import shutil
import datetime
import argparse
from textwrap import dedent

# PlatoSim standard
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
from pathlib import Path

# PlatoSim functions
import platosim.noise as ns
from platosim.utilities import errorcode, convertQuarterRange, getPointingField

# Default prefix
prefix = 'cluster'

#==============================================================#
#                         BEGIN CLASS                          #
#==============================================================#

class InstrumentSetup(object):

    """Class to generate a realistic setup for multi-camera simulations.
    
    This class makes it straight forward to generate a realistic random
    model for various systematic instrumental effects. It likewise add
    all the necessary files needed to launch the simulations on a high
    performance computing cluster

    Usage example for a single feather file:

    """

    def __init__(self, filename, mode="single", ncam=False):

        # Constants
        self.day2sec = 86400.

        # Output directory
        if args.outdir:
            self.odir = Path(args.outdir).resolve()
        elif args.project:
            self.project = args.project
            self.odir = Path(os.getenv('PLATO_WORKDIR')) / self.project / "input"
        else:
            self.odir = False

        # File names
        if self.odir:
            self.fileNamePRE = f"{self.odir}/instrumentPRE.txt"
            self.fileNameAPE = f"{self.odir}/instrumentAPE.txt"
            self.fileNameACS = f"{self.odir}/instrumentACS.txt"
            self.fileNameTED = f"{self.odir}/instrumentTED.txt"
        else:
            self.fileNamePRE = self.fileNameAPE = self.fileNameACS = self.fileNameTED = False

        # Number of images in a quarter
        self.nimg = (60 * 60 * 24 * 90) / 25.

        # Select pointng field
        self.ra, self.dec, self.kappa = getPointingField(args.field)
        
        # Short-hand definitions 
        N = args.stars
        G = args.group
        C = args.camera
        Q = args.quarter

        # Default ranges
        N = range(1, int(N)+1)
        if G is None: G = range(1, 4+1)
        if C is None: C = range(1, 6+1)
        if Q is None: Q = range(1, 8+1)

        # When number is given (also check for obvious mistakes)
        if len(G) == 1:
            if int(G) > 4:
                errorcode('warning', 'Maximum number of camera groups is 4!')
                parser.print_help()
            else:
                G = [int(G)]

        if len(C) == 1:
            if int(C) > 6:
                errorcode('warning', 'Maximum number of cameras in a group is 6!')
                parser.print_help()
            C = [int(C)]

        if len(Q) == 1:
            Q = [int(Q)]

        # When a range is given (also check for obvious mistakes)
        if len(G) == 3:
            if int(G[2]) > 4:
                errorcode('warning', 'Maximum number of camera groups is 4!')
                parser.print_help()
            else:
                G = range(int(G[0]), int(G[2])+1)

        if len(C) == 3:
            if int(C[2]) > 6:
                errorcode('warning', 'Maximum number of cameras in a group is 6!')
                parser.print_help()
            else:
                C = range(int(C[0]), int(C[2])+1)

        if isinstance(Q, str): 
            Q = convertQuarterRange(Q)
            Q = range(int(Q[0]), int(Q[1])+1)

        # Store parameters
        self.N = N
        self.G = G
        self.C = C
        self.Q = Q

        # Time column
        t0 = round(90. * (self.Q[0]  - 1) * self.day2sec)
        t1 = round(90. * (self.Q[-1])     * self.day2sec)
        self.time = np.arange(t0, t1, 25)


        
        
    

    def create_time_gaps(self):

        """Function to create a job script to be used on the VSC.

        All time gaps are based on knowledge from the Kepler mission.
        The following time gaps are considered:

          - Quarterly rolls
          - Monthly data donlinks
          - Loss of fine guidance
          - Save mode events
        
        The Quarterly rolls introduce a time gap of 1-2 days happening every
        three months (hence four times in a year). These are are needed in 
        order to align the spacecraft's solar panels towards the Sun. Note that
        the PES called PRE takes into account for the error in every pointing
        from quarter to quarter. 

        Montly data downlinks is needed during the mission. During these events
        the spacecraft changed its orientation once a month to point at Earth
        and downlink the last month of data. This caused a gap in the time series
        data, as the spacecraft can not collect while it was downlinking. When 
        the spacecraft returns to the regular pointing, its motion induced what
        is known as a “thermal transient.” This means that the telescope components
        and detector electronics underwent a temperature change, and the electron
        count reading was temporarily increased. A change in temperature can slightly
        change the camera focus. This manifests in the data as a downward slope 
        caused by “reheating,” while the flux returns to its previous level. 

        Loss of fine guidance and coarse pointing events which results in
        a lower photometric precision. Typically these cadences are not
        suggested for use in photometry. Since these event do not introduce
        thermal transients in the light curve, they can simply be removed 
        after the simulations have been generated by the user. 
        
        Safe modes (Kepler Data Characteristics Handbook, Section 4.2)
        are another type of thermal transient that appears in Kepler data. 
        A safe mode occured when the telescope temporarily shut off operation
        due to an unexpected event, usually caused by an issue with the 
        detector electronics. Typically a positive flux jump happens each event
        (probably due to an increased gain) an exponentially decrease to the
        count level before the event over a period of a few days.
        """

        errorcode('module', '\nDate gaps in time series\n')

        # Initialise random generator
        rng = np.random.default_rng()

        # Create pandas data frame for different flags
        #flags = ["time", "roll", "downlink", "safemode", "fineguidance",
        #         "attitude", "ccdanomaly", "argabrightning"]
        df = pd.DataFrame()

        # Create continous time array
        df["time"] = self.time
        
        # QUARTERLY ROLLS

        print('Downtime due to quater interuptions')
        roll_period   = 365.25/4
        roll_duration = 2.0
        roll_anomaly  = 0.5

        n_roll = len(self.Q)
        roll_events = self.Q
        roll_event0 = np.zeros(n_roll)
        roll_event1 = np.zeros(n_roll)
        
        for i, Q in zip(range(n_roll), roll_events):
            roll_gap = roll_duration + np.random.uniform(-roll_anomaly, roll_anomaly) # [d]
            roll_event0[i] = (roll_period * Q - roll_gap/2) * self.day2sec  # [s]
            roll_event1[i] = (roll_period * Q + roll_gap/2) * self.day2sec  # [s]
            df["roll"] = np.logical_and(self.time>=roll_event0[i], self.time<=roll_event1[i])

        # DOWNLINK GAPS

        print('Downtime due to montly data downlinks')
        link_period   = 365.25/4/3
        link_duration = 5/24.           # [d] i.e. 5 hours
        link_anomaly  = 0.5/24.         # [d] i.e. 0.5 hour
        link_events = np.arange((self.Q[0]-1)*roll_period, self.Q[-1]*roll_period, link_period)[1:]

        n_link = len(link_events)
        link_event0 = np.zeros(n_link)
        link_event1 = np.zeros(n_link)
        
        for i, L in zip(range(n_link), link_events):
            link_gap = link_duration + np.random.uniform(-link_anomaly, link_anomaly)
            link_event0[i] = (L - link_gap/2) * self.day2sec
            link_event1[i] = (L + link_gap/2) * self.day2sec
            df["downlink"] = np.logical_and(self.time>=link_event0[i], self.time<=link_event1[i])

        # LOSS OF FINE GUIDANCE

        print('Downtime due to loss of fine guidance')
        freq = 180
        t = self.Q[0] * roll_period
        jitter_duration = 0.5/24.
        jitter_anomaly  = 0.1/24.
        jitter_events   = []
        
        while t < self.Q[-1] * roll_period:            
            jitter_event = np.random.poisson(lam=freq)
            t += jitter_event
            jitter_events.append(t)

        n_jitter = len(jitter_events)
        jitter_event0 = np.zeros(n_jitter)
        jitter_event1 = np.zeros(n_jitter)

        for i, J in zip(range(n_jitter), jitter_events):
            jitter_gap = jitter_duration + np.random.uniform(-jitter_anomaly, jitter_anomaly)
            jitter_event0[i] = (J - jitter_gap/2) * self.day2sec
            jitter_event1[i] = (J + jitter_gap/2) * self.day2sec
            df["jitter"] = np.logical_and(self.time>=jitter_event0[i], self.time<=jitter_event1[i])

        # SAVE MODE EVENTS

        print('Downtime due to safe-mode events')
        freq = 270
        t = self.Q[0] * roll_period
        safe_duration = 1
        safe_anomaly  = 12/24.
        safe_events   = []
        
        while t < self.Q[-1] * roll_period:            
            safe_event = np.random.poisson(lam=freq)
            t += safe_event
            safe_events.append(t)

        n_safe = len(safe_events)
        safe_event0 = np.zeros(n_safe)
        safe_event1 = np.zeros(n_safe)

        for i, S in zip(range(n_safe), safe_events):
            safe_gap = safe_duration + np.random.uniform(-safe_anomaly, safe_anomaly)
            safe_event0[i] = (S - safe_gap/2) * self.day2sec
            safe_event1[i] = (S + safe_gap/2) * self.day2sec
            df["safe"] = np.logical_and(self.time>=safe_event0[i], self.time<=safe_event1[i])

        # Create new time array with all gaps
        # df["tsim"] = ~df.roll * ~df.downlink
        # df["tsim"] = df["tsim"].where(df["tsim"]!='T', 1) * df["time"]
        # df["tsim"].replace({0: np.nan}, inplace=True) 
        # df["tsim"].iloc[0] = 0

        # df["tgap"] = ~df.roll * ~df.downlink
        # df["tgap"] = ~df["tgap"]
        # df["tgap"] = df["tgap"].where(df["tgap"]!='T', 1) * df["time"]
        # df["tgap"].replace({0: np.nan}, inplace=True) 

        # Show figure

        if n_roll != 0:
            
            fig, ax = plt.subplots(figsize=(10, 3))

            # Plots
            ax.axhline(y=0, linestyle=':', color='k')

            for i in range(n_roll):
                roll = ax.axvspan(roll_event0[i]/self.day2sec, roll_event1[i]/self.day2sec,
                                 color='b', alpha=0.5)
                if i == n_roll-1: roll.set_label('Quarter rolls')
                
            for i in range(n_link):
                link = ax.axvspan(link_event0[i]/self.day2sec, link_event1[i]/self.day2sec,
                                 color='m', alpha=0.5)
                if i == n_roll-1: link.set_label('Downlinks')
                
            for i in range(n_jitter):
                jitter = ax.axvspan(jitter_event0[i]/self.day2sec, jitter_event1[i]/self.day2sec,
                                   color='orange', alpha=0.5)
                if i == n_roll-1: jitter.set_label('Loss of FGS')
                
            for i in range(n_safe):
                safe = ax.axvspan(safe_event0[i]/self.day2sec, safe_event1[i]/self.day2sec,
                                 color='r', alpha=0.5)
                if i == n_roll-1: safe.set_label('Safe modes')

            # for i, col in zip(range(3), cols):
            #     ax[i].plot(df["time"]/day2sec, df[col], 'k-')
            #     ax[i].axhline(y=0, linestyle=':', color='k')
            #     for k in range(N-1):
            #         ax[i].axvline(x=quarter[k]*90, linestyle='--', color='b')
            # # Settings
            # ax[1].set_ylabel("Pitch [arcsec]")
            # ax[2].set_ylabel("Roll [arcsec]")
            # for i in range(3):
            #     ax[i].set_xlim(df.time.min()/day2sec, df.time.max()/day2sec)
            # # Layout
            # ax[0].set_xticklabels([])
            # ax[1].set_xticklabels([])
            # plt.tight_layout(h_pad=0.2, w_pad=0)
            # plt.show()

            # Labels
            ax.set_xlabel("Time [days]")
            ax.set_ylabel("Arb.")
            ax.legend(ncol=4, loc="center", bbox_to_anchor=(0.5, 1.2))

            # Layout
            ax.set_yticklabels([])
            ax.set_xlim(df.time.iloc[0], df.time.iloc[-1]/self.day2sec+5)
            ax.set_ylim(-1,1)
            plt.tight_layout()
            plt.show()

        # APply start time relative mission BOL
        #self.beginExposureNr = round(self.timeStart / self.cadence)
        
        if self.odir:
            outfile = f'{self.odir}/instrumentGaps.txt'
            fig.savefig(f"{outfile[:-4]}.png", bbox_inches='tight', dpi=200)
            df.to_csv(outfile, sep=" ", header=False, index=False)
            print(f"File saved : {outfile}")




            
    def createPRE(self):

        """Function to create a Pointing Repeatability Error (PRE) file.
        Used to realistically include errors for each pointing.
        """

        # Generete PRE file
        errorcode('module', '\nPointing repeatability error (PRE)')
        ns.getPRE(self.ra, self.dec, self.kappa, self.Q, sigma=3,
                  outfile=self.fileNamePRE, show_table=True, plot=True)
        if self.odir: print(f"File saved: {self.fileNamePRE}")

        


        
    def createAPE(self):

        """Function to create a Absolute Pointing Error (APE) file.
        Used to realistically include camera misalignments errors.
        """

        # Generete APE file
        errorcode('module', '\nAbsolute Pointing Error (APE)')
        ns.getAPE(self.ra, self.dec, self.kappa, sigma=3,
                  outfile=self.fileNameAPE, show_table=True, plot=True)
        if self.odir: print(f"File saved: {self.fileNameAPE}")





    def createACS(self):

        """Function to create a Attitude and orbit Control System (ACS) jitter file. 
        """
        
        # Generate TED file
        errorcode('module', '\nAttitude Control System (ACS)')
        ns.getACS(self.time, outfile=self.fileNameACS, plot=True)
        if self.odir: print(f"File saved: {self.fileNameACS}")




        
    def createTED(self):

        """Function to create a Thermo-Elastic Distortion (TED) file.
        """
        
        # Generate TED file
        errorcode('module', '\nThermo-Elastic Distortion (TED)')
        ns.getTED(self.Q, outfile=self.fileNameTED, show_table=True, plot=True)
        if self.odir: print(f"File saved: {self.fileNameTED}")
            

        

        
    def create_job_script(self):

        """Function to create a job script to be used on the VSC.
        """

        errorcode('module', f'\nJob script for parallisation\n')

        # Max nodes used
        maxNodes = 1

        # Number of node-cores for cluster
        coresCluster = 36

        # Memory per node for cluster [gb]
        pmemCluster = 192 - 8

        # Memory needed for 1 image [kb]
        memoryPerImage = 4.25

        # Run time to produce 1 image [s]
        timePerImage = 1.1 / 1000.

        # Overestimation of calculated memory and walltime [%]
        limitSafe = 5
        
        # Number of idividual simulations
        numSim = self.N[-1] * self.G[-1] * self.C[-1] * self.Q[-1]

        # Estimate number of nodes
        nodes = int(math.ceil(numSim/float(coresCluster)))

        # Estimate number of node-cores
        if nodes == 1:
            cores = coresCluster
        elif nodes > maxNodes:
            nodes = maxNodes
            cores = int(coresCluster * nodes)
        else:
            cores = int(math.ceil(numSim/nodes))

        # Estimate memory per core-node [mb]
        pmemSim = memoryPerImage * self.nimg / (nodes * cores) * 1e-3
        pmem    = int(math.ceil(pmemSim + limitSafe/100 * pmemSim))
        pmem = 50
        
        # Check if simulation quarter is larger than 5gb per node-core
        if pmemSim > 5000:
            errorcode('warning', 'Memory per node-core exceedes 5 GB!')

        # Check if if the total memory exceedes that of the cluster [gb]
        memPerNode = coresCluster * pmemSim*1e-3
        if memPerNode > pmemCluster-8:
            errorcode('error', 'Simulation node-memory of {int(memPerNode)} GB ' +
                      'exceedes the cluster node-memory of {pmemCluster}-8 GB!')

        # Estimate wall time given the resources above:
        walltimeQuarter = timePerImage * self.nimg
        walltimeSafe    = walltimeQuarter + limitSafe/100 * walltimeQuarter
        walltime        = str(datetime.timedelta(seconds=int(walltimeSafe)))

        # Print if simulation will run and if so, with what resources
        print(f'Preparing {numSim} simulations with resources: ' +
              f'nodes={nodes}, cores={cores}, pmem={pmem}mb, walltime={walltime}')

        # Generate job script

        if self.odir:
            print(f"Creating parameterization job-script: {self.odir}/{prefix}.slurm")

        script = \
        """
        #!/bin/bash

        #SBATCH -A <account>       # Account name of cluster (mandatory)
        #SBATCH -o <stdout>        # Name of standard output
        #SBATCH -e <stderr>        # Name of standard errors
        #SBATCH -M <cluster>       # VSC: cpu, batch_debug, etc.
        #SBATCH -p <software>      # VSC: genius or wice
        #SBATCH -N 1               # Number of nodes
        #SBATCH -n 36              # Number of CPU per node
        #SBATCH --mem-per-cpu=1G   # Amount of RAM memory per CPU
        #SBATCH -t 00:15:00        # Totoal execution of slurm job 

        cd $SLURM_SUBMIT_DIR
        module purge
        module restore <name>      # Name of cluster env with modules 
        
        # User defined parameters
        PROJECT=test

        # Export paths
        export PLATO=$VSC_DATA/plato
        export PLATO_PROJECT_HOME=$VSC_DATA/PlatoSim3
        export PLATO_WORKDIR=$VSC_DATA/workdir
        export TEMDIR=$VSC_SCRATCH_NODE
        export OUTDIR=$VSC_SCRATCH/platosim/$PROJECT
        export PYTHONPATH=$PLATO:$PLATO_PROJECT_HOME/python
        export PYTHON=/data/leuven/341/vsc34166/miniconda3/envs/platosim/bin/python
        export PLATONIUM=$PLATO_PROJECT_HOME/python/platosim/platonium/platonium

        # Run PLATOnium
        $PYTHON $PLATONIUM $star $group $camera $quarter --project $PROJECT -o $TEMDIR --compress

        # Move data from the scrath node to output
        starID=$(printf "%09d" $star) 
        mkdir -p $OUTDIR/$starID
        zipfile=$TEMDIR/${starID}_Ncam${group}.${camera}_Q${quarter}.zip
        if [ -f $zipfile ]; then
            mv $zipfile $OUTDIR/$starID
        fi
        """

        # Save textfile for worker
        if self.odir:
            filename = f"{self.odir}/{prefix}.slurm"
            with open(filename, "w") as ofile:
                ofile.write(dedent(script).strip())




            
    def create_param_file(self):

        """Function to create a job script to be used on the VSC.
        """
        
        if self.odir:
            print(f"Creating HPC parameterization file : {self.odir}/{prefix}.data")

        # Add rows in a loop
        textfile = "star,group,camera,quarter\n"
        for starNo in self.N:
            for groupNo in self.G:
                for cameraNo in self.C:
                    for quarterNo in self.Q:
                        textfile += f"{starNo},{groupNo},{cameraNo},{quarterNo}\n"

        # Save textfile for worker
        if self.odir:
            filename = f"{self.odir}/{prefix}.data"
            with open(filename, "w") as ofile:
                ofile.write(dedent(textfile).strip())
        



    def create_input_yaml(self):

        """Function to copy and adjust a yaml ready to launch.
        """

        if self.odir:
            
            # Get files names of YAML files
            yaml_old = Path(os.getenv("PLATO_PROJECT_HOME") + "/inputfiles/inputfile.yaml")
            yaml_new = self.odir / "inputfile.yaml"
            
            # Copy YAML if it doesn't exist already
            if not yaml_new.is_file():

                print(f"Copying YAML configuration file: {yaml_new}")
                shutil.copy(yaml_old, yaml_new)

                # Find and replace a few strings:
                with open(yaml_new, 'r') as file:
                    filedata = file.read()
                    filedata = filedata.replace('inputfiles/starcatalog.txt', args.field)
                    # Photon flux of a P=0 G2V-star [phot/s/m^2/nm]
                    filedata = filedata.replace('1.00179e8       #', '0.73244782244e8 #')
                    filedata = filedata.replace( 'NumColumns:                      100',
                                                f'NumColumns:                      7  ')
                    filedata = filedata.replace( 'NumRows:                         100',
                                                f'NumRows:                         7  ')
                    filedata = filedata.replace('IncludePhotometry:               no ',
                                                'IncludePhotometry:               yes')
                    filedata = filedata.replace('MaskUpdateInterval:              14.0',
                                                'MaskUpdateInterval:              30.0')
                    filedata = filedata.replace('GroupByExposure:                 yes',
                                                'GroupByExposure:                 no ')
                    filedata = filedata.replace('WriteBiasMaps:                   yes',
                                                'WriteBiasMaps:                   no ')
                    filedata = filedata.replace('WriteSmearingMaps:               yes',
                                                'WriteSmearingMaps:               no ')
                    filedata = filedata.replace('WriteFlatfieldMap:               yes',
                                                'WriteFlatfieldMap:               no ')
                    filedata = filedata.replace('WriteThroughputMaps:             yes',
                                                'WriteThroughputMaps:             no ')
                    filedata = filedata.replace('WriteTransmissionEfficiency:     yes',
                                                'WriteTransmissionEfficiency:     no ')
                    filedata = filedata.replace('WriteBackgroundMap:              yes',
                                                'WriteBackgroundMap:              no ')
                    filedata = filedata.replace('WriteCTI:                        yes',
                                                'WriteCTI:                        no ')
                    filedata = filedata.replace('WriteACS:                        yes',
                                                'WriteACS:                        no ')
                    filedata = filedata.replace('WriteTelescopeACS:               yes',
                                                'WriteTelescopeACS:               no ')
                    filedata = filedata.replace('WriteStarCatalog:                yes',
                                                'WriteStarCatalog:                no ')
                    filedata = filedata.replace('WriteStarPositions:              yes',
                                                'WriteStarPositions:              no ')
                    filedata = filedata.replace('WriteGhostPositions:             yes',
                                                'WriteGhostPositions:             no ')
                    filedata = filedata.replace('WriteCosmics:                    yes',
                                                'WriteCosmics:                    no ')
                    # Write the file out again
                    with open(yaml_new, 'w') as file:
                        file.write(filedata)



                        
#--------------------------------------------------------------#
#                PARSING COMMAND-LINE ARGUMENTS                #
#--------------------------------------------------------------#

software = '\nInstrumental Noise Simulator'
parser = argparse.ArgumentParser(epilog=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter,
                                 description=errorcode('software', software))

man_group = parser.add_argument_group('MANDATORY PARAMETERS')
man_group.add_argument('field',   type=str, help='LOP (SPF, NPF)')
man_group.add_argument('stars',   type=str, help='Number of stars')

obs_group = parser.add_argument_group('OBSERVATION PARAMETERS')
obs_group.add_argument('--group',   metavar='NO.', type=str, help='Group   no.: 1, 2, .. (Default: 1-4 = all)')
obs_group.add_argument('--camera',  metavar='NO.', type=str, help='Camera  no.: 1, 2, .. (Default: 1-6 = all)')
obs_group.add_argument('--quarter', metavar='NO.', type=str, help='Quarter no.: 1, 2, .. (Default: 1-8 = 2yr)')

out_group = parser.add_argument_group('I/O PARAMETERS')
out_group.add_argument('-p', '--plot',   action='store_true',      help='Flag to plot each action')
out_group.add_argument('-o', '--outdir', metavar='PATH', type=str, help='Output directory to save')
out_group.add_argument('--project',      metavar='NAME', type=str, help='Name of PLATOnium project')

# Initialize instance of class
args = parser.parse_args()
x = InstrumentSetup(args)

# Run each module
x.create_time_gaps()
x.createPRE()
x.createAPE()
x.createACS()
x.createTED()
x.create_job_script()
x.create_param_file()
x.create_input_yaml()
print('')
