#!/usr/bin/env python3

"""
This script is an integrated part of PlatoSim's toolkit PLATOnium.
Call this script prior to running your simulations with "platonium"
to generate the following files:

  - instrumentPRE.txt  : Pointing errors for each mission quarter pointing
  - instrumentAPE.txt  : Alignment errors between cameras and the optical bench
  - instrumentTED.txt  : Long-term camera drift due to Thermo-Elastic Distortion
  - instrumentGain.txt : Gain differences for the each CCD (F and E side) and FEE
  - instrumentGaps.txt : Realistic distribution of spacecraft down times
  - run.pbs & data.pbs : Job and parameterisation file for array-like parallelisation

While using the "--project" output path, the files will be generated
directly into your working directory and will immediately be known
and used when running "platonium". 
"""

import os
import math
import datetime
import argparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
from pathlib import Path
from textwrap import dedent

import platosim.utilities  as ut
import platosim.instrument as it

#==============================================================#
#                         BEGIN CLASS                          #
#==============================================================#

class InstrumentSetup(object):

    """Class to generate a realistic setup for multi-camera simulations.
    
    This class makes it straight forward to generate a realistic random
    model for various systematic instrumental effects. It likewise add
    all the necessary files needed to launch the simulations on a high
    performance computing cluster

    Usage example for a single feather file:

    """

    def __init__(self, filename, mode="single", ncam=False):

        # Constants
        self.day2sec = 86400.

        # Output directory
        if args.outdir:
            self.odir = Path(args.outdir).resolve()
        elif args.project:
            self.project = args.project
            self.odir = Path(os.getenv('PLATO_WORKDIR')) / self.project / "input"
        else:
            self.odir = False

        # File names
        if self.odir:
            self.fileNamePRE = f"{self.odir}/instrumentPRE.txt"
            self.fileNameAPE = f"{self.odir}/instrumentAPE.txt"
            self.fileNameTED = f"{self.odir}/instrumentTED.txt"
        else:
            self.fileNamePRE = self.fileNameAPE = self.fileNameTED = False


        # Number of images in a quarter
        self.nimg = (60 * 60 * 24 * 90) / 25

        # Provisional Long-duration Observation Phases (LOP):
        PF = {'SPF': [ 86.79870508, -46.39594703, -8.5],  # Galactic [253.0, -30.0]
              'NPF': [265.08002279,  39.5836954,  +8,5]}  # Galactic [65.0,  +30.0]
        # Select pointng field
        self.ra, self.dec, self.kappa = PF[args.field]
        
        # Short-hand definitions 
        N = args.stars
        G = args.group
        C = args.camera
        Q = args.quarter

        # Default ranges
        N = range(1, int(N)+1)
        if G is None: G = range(1, 4+1)
        if C is None: C = range(1, 6+1)
        if Q is None: Q = range(1, 8+1)

        # When number is given (also check for obvious mistakes)
        if len(G) == 1:
            if int(G) > 4:
                ut.errorcode('warning', 'Maximum number of camera groups is 4!')
                parser.print_help()
            else:
                G = [int(G)]

        if len(C) == 1:
            if int(C) > 6:
                ut.errorcode('warning', 'Maximum number of cameras in a group is 6!')
                parser.print_help()
            C = [int(C)]

        if len(Q) == 1:
            Q = [int(Q)]

        # When a range is given (also check for obvious mistakes)
        if len(G) == 3:
            if int(G[2]) > 4:
                ut.errorcode('warning', 'Maximum number of camera groups is 4!')
                parser.print_help()
            else:
                G = range(int(G[0]), int(G[2])+1)

        if len(C) == 3:
            if int(C[2]) > 6:
                ut.errorcode('warning', 'Maximum number of cameras in a group is 6!')
                parser.print_help()
            else:
                C = range(int(C[0]), int(C[2])+1)

        if isinstance(Q, str): 
            Q = ut.convertQuarterRange(Q)
            Q = range(int(Q[0]), int(Q[1])+1)

        # Store parameters
        self.N = N
        self.G = G
        self.C = C
        self.Q = Q

        # Time column
        t0 = round(90. * (self.Q[0]  - 1) * self.day2sec)
        t1 = round(90. * (self.Q[-1] - 1) * self.day2sec)
        self.time = np.arange(t0, t1, 25)

        
    


    def createPRE(self):

        """Function to create a Pointing Repeatability Error (PRE) file.
        Used to realistically include errors for each pointing.
        """

        # Generete PRE file
        if self.odir: print("\nSaving PRE file")
        it.getPRE(self.ra, self.dec, self.kappa, self.Q, sigma=3,
                  outfile=self.fileNamePRE, show_table=True)

        

    def createAPE(self):

        """Function to create a Absolute Pointing Error (APE) file.
        Used to realistically include camera misalignments errors.
        """

        # Generete APE file
        if self.odir: print("\nSaving APE file")
        it.getAPE(self.ra, self.dec, self.kappa, sigma=3,
                  outfile=self.fileNameAPE, show_table=True)



    def createTED(self):

        """Function to create a Absolute Pointing Error (APE) file
        """
        
        # Generate TED file
        if self.odir: print("\nSaving TED file and plot")
        it.getTED(self.Q, outfile=self.fileNameTED, plot=True)





    def create_job_script(self):

        """Function to create a job script to be used on the VSC.
        """

        # prefix
        prefix = "run"
        
        # Name of yaml inputfile
        inputfile = "inputfile.yaml"

        # VSC project account details
        account = "default_project"

        # Email to recieve job notifications (use "None" to deactivate notifications)
        email = "nicholas.jannsen@kuleuven.be"

        # VSC module environment for PlatoSim3
        environment = "plato"

        # Max nodes used
        maxNodes = 10

        # Number of node-cores for cluster
        coresCluster = 36

        # Memory per node for cluster [gb]
        pmemCluster = 192 - 8

        # Memory needed for 1 image [kb]
        memoryPerImage = 4.25

        # Run time to produce 1 image [s]
        timePerImage = 1.1 / 1000.

        # Overestimation of calculated memory and walltime [%]
        limitSafe = 5
        
        # Number of idividual simulations
        numSim = self.N[-1] * self.G[-1] * self.C[-1] * self.Q[-1]

        # Estimate number of nodes
        nodes = int(math.ceil(numSim/float(coresCluster)))

        # Estimate number of node-cores
        if nodes == 1:
            cores = coresCluster
        elif nodes > maxNodes:
            nodes = maxNodes
            cores = int(coresCluster * nodes)
        else:
            cores = int(math.ceil(numSim/nodes))

        # Estimate memory per core-node [mb]
        pmemSim = memoryPerImage * self.nimg / (nodes * cores) * 1e-3
        pmem    = int(math.ceil(pmemSim + limitSafe/100 * pmemSim))

        # Check if simulation quarter is larger than 5gb per node-core
        if pmemSim > 5000:
            ut.errorcode('warning', 'Memory per node-core exceedes 5 GB!')

        # Check if if the total memory exceedes that of the cluster [gb]
        memPerNode = coresCluster * pmemSim*1e-3
        if memPerNode > pmemCluster-8:
            ut.errorcode('error', 'Simulation node-memory of {int(memPerNode)} GB ' +
                         'exceedes the cluster node-memory of {pmemCluster}-8 GB!')

        # Estimate wall time given the resources above:
        walltimeQuarter = timePerImage * self.nimg
        walltimeSafe    = walltimeQuarter + limitSafe/100 * walltimeQuarter
        walltime        = str(datetime.timedelta(seconds=int(walltimeSafe)))

        # Print if simulation will run and if so, with what resources
        ut.errorcode('message', f'\nPrepared {numSim} simulations with resources: ' +
                     'nodes={nodes}, cores={cores}, pmem={pmem}mb, walltime={walltime}')

        # Check email argument
        if email is None: email = ''

        # Generate job script

        if self.odir:
            print(f"Creating HPC parameterization job-script: {self.odir}/{prefix}.pbs")

        script = \
        """
        #!/bin/bash

        #PBS -A lp_mesa_modeling
        #PBS -N output
        #PBS -l nodes=10:ppn=36
        #PBS -l pmem=5gb
        #PBS -l walltime=100:00:00

        cd $PBS_O_WORKDIR
        module purge
        module restore plato

        # Define sample
        PX=<sample>
        PROJECT=<project>

        # Load paths
        POETRY=$VSC_DATA/poetry/virtualenvs/platonium-KLYW-dHg-py3.8/bin/activate
        PLATO=$VSC_DATA/plato
        PLATO_PROJECT_HOME=$VSC_DATA/PlatoSim3
        PLATO_WORKDIR=$VSC_DATA/workdir
        SIMDIR=$PLATO_PROJECT_HOME/python/platosim/platonium
        TEMDIR=$VSC_SCRATCH_NODE
        OUTDIR=/scratch/leuven/341/vsc34166/platonium/$PROJECT
        PYTHONPATH=$POETRY:$PLATO:$PLATO_PROJECT_HOME/python:$PLATO_WORKDIR:$SIMDIR:$TEMDIR:$OUTDIR
        export POETRY
        export PLATO
        export PLATO_PROJECT_HOME
        export PLATO_WORKDIR
        export SIMDIR
        export TEMDIR
        export OUTDIR
        export PYTHONPATH

        # Load python environment
        source $POETRY

        # Run PLATOnium
        starID=$(printf "%09d" $star)
        python $SIMDIR/platonium $star $group $camera $quarter --project $PROJECT --sample $PX -o $TEMDIR --compress

        # Move data from the scrath node to output
        mkdir -p $OUTDIR/$starID
        zipfile=$TEMDIR/reduced/$PX/$starID/${starID}_Ncam${group}.${camera}_Q${quarter}.zip
        if [ -f $zipfile ]; then
            mv $zipfile $OUTDIR/$starID
        fi

        # Check if directory is not removed
        olddir=$TEMDIR/$PX/$starID/Ncam${group}${camera}
        if [ -d $olddir ]; then
            rm -rf $$olddir
        fi
        """

        # Save textfile for worker
        if self.odir:
            filename = f"{self.odir}/{prefix}.pbs"
            with open(filename, "w") as ofile:
                ofile.write(dedent(script).strip())




            
    def create_param_file(self):

        """Function to create a job script to be used on the VSC.
        """

        # Select prefix
        prefix = "data"
        
        if self.odir:
            print(f"Creating HPC parameterization file : {self.odir}/{prefix}.txt")

        # Add rows in a loop
        textfile = "star,group,camera,quarter\n"
        for starNo in self.N:
            for groupNo in self.G:
                for cameraNo in self.C:
                    for quarterNo in self.Q:
                        textfile += f"{starNo},{groupNo},{cameraNo},{quarterNo}\n"

        # Save textfile for worker
        if self.odir:
            filename = f"{self.odir}/{prefix}.txt"
            with open(filename, "w") as ofile:
                ofile.write(dedent(textfile).strip())




                
    def create_time_gaps(self):

        """Function to create a job script to be used on the VSC.
        """

        # Initialise random generator
        rng = np.random.default_rng()

        # Create pandas data frame for different flags
        #flags = ["time", "roll", "downlink", "safemode", "fineguidance",
        #         "attitude", "ccdanomaly", "argabrightning"]
        df = pd.DataFrame()

        # Start time of simulation
        t0 = round(90. * (self.Q[0]  - 1) * self.day2sec)
        t1 = round(90. * (self.Q[-1] - 1) * self.day2sec)
        time = np.arange(t0, t1, 25)

        # Create continous time array
        df["time"] = time

        
        # QUARTERLY ROLLS

        roll_period   = 93.
        roll_duration = 2.0
        roll_anomaly  = 0.5

        n_roll = len(self.Q)
        roll_events = self.Q
        roll_event0 = np.zeros(n_roll)
        roll_event1 = np.zeros(n_roll)
        
        for i, Q in zip(range(n_roll), roll_events):
            roll_gap = roll_duration + np.random.uniform(-roll_anomaly, roll_anomaly) # [d]
            roll_event0[i] = (roll_period * Q - roll_gap/2) * self.day2sec  # [s]
            roll_event1[i] = (roll_period * Q + roll_gap/2) * self.day2sec  # [s]
            df["roll"] = np.logical_and(time>=roll_event0[i], time<=roll_event1[i])


        # DOWNLINK GAPS

        link_period   = 30.
        link_duration = 5/24.           # [d] i.e. 5 hours
        link_anomaly  = 0.5/24.         # [d] i.e. 0.5 hour
        link_events = np.arange((self.Q[0]-1)*roll_period, self.Q[-1]*roll_period, link_period)[1:]

        n_link = len(link_events)
        link_event0 = np.zeros(n_link)
        link_event1 = np.zeros(n_link)
        
        for i, L in zip(range(n_link), link_events):
            link_gap = link_duration + np.random.uniform(-link_anomaly, link_anomaly)
            link_event0[i] = (L - link_gap/2) * self.day2sec
            link_event1[i] = (L + link_gap/2) * self.day2sec
            df["downlink"] = np.logical_and(time>=link_event0[i], time<=link_event1[i])


        # LOSS OF FINE GUIDANCE

        freq = 180
        t = self.Q[0] * roll_period
        jitter_duration = 0.5/24.
        jitter_anomaly  = 0.1/24.
        jitter_events   = []
        
        while t < self.Q[-1] * roll_period:            
            jitter_event = np.random.poisson(lam=freq)
            t += jitter_event
            jitter_events.append(t)

        n_jitter = len(jitter_events)
        jitter_event0 = np.zeros(n_jitter)
        jitter_event1 = np.zeros(n_jitter)

        for i, J in zip(range(n_jitter), jitter_events):
            jitter_gap = jitter_duration + np.random.uniform(-jitter_anomaly, jitter_anomaly)
            jitter_event0[i] = (J - jitter_gap/2) * self.day2sec
            jitter_event1[i] = (J + jitter_gap/2) * self.day2sec
            df["jitter"] = np.logical_and(time>=jitter_event0[i], time<=jitter_event1[i])


        # SAVE MODE EVENTS

        freq = 270
        t = self.Q[0] * roll_period
        safe_duration = 1
        safe_anomaly  = 12/24.
        safe_events   = []
        
        while t < self.Q[-1] * roll_period:            
            safe_event = np.random.poisson(lam=freq)
            t += safe_event
            safe_events.append(t)

        n_safe = len(safe_events)
        safe_event0 = np.zeros(n_safe)
        safe_event1 = np.zeros(n_safe)

        for i, S in zip(range(n_safe), safe_events):
            safe_gap = safe_duration + np.random.uniform(-safe_anomaly, safe_anomaly)
            safe_event0[i] = (S - safe_gap/2) * self.day2sec
            safe_event1[i] = (S + safe_gap/2) * self.day2sec
            df["safe"] = np.logical_and(time>=safe_event0[i], time<=safe_event1[i])


        # Create new time array with all gaps
        # df["tsim"] = ~df.roll * ~df.downlink
        # df["tsim"] = df["tsim"].where(df["tsim"]!='T', 1) * df["time"]
        # df["tsim"].replace({0: np.nan}, inplace=True) 
        # df["tsim"].iloc[0] = 0

        # df["tgap"] = ~df.roll * ~df.downlink
        # df["tgap"] = ~df["tgap"]
        # df["tgap"] = df["tgap"].where(df["tgap"]!='T', 1) * df["time"]
        # df["tgap"].replace({0: np.nan}, inplace=True) 

        # Show figure

        if n_roll != 1:
            
            fig, ax = plt.subplots(figsize=(10, 3))

            # Plots
            ax.axhline(y=0, linestyle=':', color='k')

            for i in range(n_roll):
                roll =ax.axvspan(roll_event0[i]/self.day2sec, roll_event1[i]/self.day2sec,
                                 color='b', alpha=0.5)

            for i in range(n_link):
                link =ax.axvspan(link_event0[i]/self.day2sec, link_event1[i]/self.day2sec,
                                 color='m', alpha=0.5)

            for i in range(n_jitter):
                jitter =ax.axvspan(jitter_event0[i]/self.day2sec, jitter_event1[i]/self.day2sec,
                                   color='orange', alpha=0.5)

            for i in range(n_safe):
                safe =ax.axvspan(safe_event0[i]/self.day2sec, safe_event1[i]/self.day2sec,
                                 color='r', alpha=0.5)


            # for i, col in zip(range(3), cols):
            #     ax[i].plot(df["time"]/day2sec, df[col], 'k-')
            #     ax[i].axhline(y=0, linestyle=':', color='k')
            #     for k in range(N-1):
            #         ax[i].axvline(x=quarter[k]*90, linestyle='--', color='b')
            # # Settings
            # ax[1].set_ylabel("Pitch [arcsec]")
            # ax[2].set_ylabel("Roll [arcsec]")
            # for i in range(3):
            #     ax[i].set_xlim(df.time.min()/day2sec, df.time.max()/day2sec)
            # # Layout
            # ax[0].set_xticklabels([])
            # ax[1].set_xticklabels([])
            # plt.tight_layout(h_pad=0.2, w_pad=0)
            # plt.show()

            # Labels
            ax.set_xlabel("Time [days]")
            ax.set_ylabel("Arb.")
            roll.set_label('Quarter rolls')
            link.set_label('Downlinks')
            jitter.set_label('Loss of FGS')
            safe.set_label('Safe modes')
            ax.legend(ncol=4, loc="center", bbox_to_anchor=(0.5, 1.2))

            # Layout
            ax.set_yticklabels([])
            ax.set_xlim(df.time.iloc[0], df.time.iloc[-1]/self.day2sec+5)
            ax.set_ylim(-1,1)
            plt.tight_layout()
            plt.show()

        # APply start time relative mission BOL
        #self.beginExposureNr = round(self.timeStart / self.cadence)
        
        if self.odir:
            print(f"Creating file with instrumental time gaps : {self.odir}/instrumentDataGaps.txt")
            
        
        
#--------------------------------------------------------------#
#                PARSING COMMAND-LINE ARGUMENTS                #
#--------------------------------------------------------------#

software = '\nInstrument file generator'
parser = argparse.ArgumentParser(epilog=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter,
                                 description=ut.errorcode('software', software))

man_group = parser.add_argument_group('MANDATORY PARAMETERS')
man_group.add_argument('field',   type=str, help='LOP (SPF, NPF)')
man_group.add_argument('stars',   type=str, help='Number of stars')

obs_group = parser.add_argument_group('OBSERVATION PARAMETERS')
obs_group.add_argument('--group',   metavar='NO.', type=str, help='Group   no.: 1, 2, .. (Default: 1-4 = all)')
obs_group.add_argument('--camera',  metavar='NO.', type=str, help='Camera  no.: 1, 2, .. (Default: 1-6 = all)')
obs_group.add_argument('--quarter', metavar='NO.', type=str, help='Quarter no.: 1, 2, .. (Default: 1-8 = 2yr)')

out_group = parser.add_argument_group('I/O PARAMETERS')
out_group.add_argument('-p', '--plot',   action='store_true',      help='Flag to plot each action')
out_group.add_argument('-o', '--outdir', metavar='PATH', type=str, help='Output directory to save')
out_group.add_argument('--project',      metavar='NAME', type=str, help='Name of PLATOnium project')

# Initialize instance of class
args = parser.parse_args()
x = InstrumentSetup(args)

# Run each module
x.createPRE()
x.createAPE()
x.createTED()
x.create_time_gaps()
x.create_job_script()
x.create_param_file()
