#!/usr/bin/env python3

"""
This script uses the PIC targets and their contaminants to simulate realistic imagettes
or lightcurves using PlatoSim. It can simulate any of the 24 normal cameras/telescopes,
for an arbitary number of mission quarters. Since a nescessary rotation (along the roll
axis) of the spacecraft platform is required in order to repoint the solar panels every
90 days, simulations cannot realistically extend beyond a quarter of a year. Given an
PIC input sample, the script will automatically simulation all targets being visible by
any camera falling on one of the 4 CCDs. The fact that the PLATO spacecraft will be
equipped with 4 camera groups consisting of 6 cameras each, constrains the efficient use
of nodes and cores on the HPC. In order to make the simulation as realistic as possible,
random seats of various intrinsic- and instrumental effects are included, meaning that
each camera within each camera group needs to be simulated independently (which indeed
are the raw imaging output of PLATO).

User examples:
  $ platonium 1 1 1 1 --project sim1 -p
  $ platonium 2 1 3 5 --project sim2 -v 3
  $ platonium 3 4 2 8 -i </path/to/project> --nexp 600 -x <simPrefix>
"""

import os
import sys
import glob
import math
import h5py
import shutil
import argparse
import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from zipfile import ZipFile
from scipy.interpolate import interp1d, CubicSpline

# PlatoSim
import platosim.referenceFrames as rf
from platosim.simulation   import Simulation
from platosim.utilities    import errorcode, pdAddColumn
from platosim.plot         import drawStarInCCDfocalPlane
from platosim.matplotlibrc import setup
setup()

#==============================================================#
#                        PLATOnium CLASS                       #
#==============================================================#

class PLATOnium(object):
    """
    Class for running multi-camera and multi-quarter PlatoSim simulations.
    """
    
    def __init__(self, args):

        # PARSED ARGUMENTS
        
        self.targetNo     = args.starID
        self.group        = args.cameraGroupNr
        self.camera       = args.cameraNr
        self.quarter      = args.quarterNr

        self.inputDir      = args.inDir
        self.outputDir     = args.outdir
        self.project       = args.project
        self.simPrefix     = args.prefix
        self.varSourceFile = args.varfile
        self.varSourceList = args.varlist
        self.compress      = args.compress
        
        self.cadence      = args.cadence
        self.simTime      = args.tdur
        self.simExposures = args.nexp
        #simExpSkip   = args.mexp
        self.picID        = args.pic
        self.maskUpdate   = args.mask
        self.seed         = args.seed
        self.reuseJitter  = args.reusejitter
        
        self.sample         = args.sample
        self.conDeltaMag    = args.con_dmag
        self.conFluxError   = args.con_ferr
        self.tarFluxError   = args.tar_ferr
        self.tarAbsCenError = args.tar_cerr
        
        # Make sure that the input is physical
        if not self.group in [1,2,3,4]:
            errorcode('error', 'Camera-group can only be either 1, 2, 3, 4!')
        if not self.camera in [1,2,3,4,5,6]:
            errorcode('error', 'Camera can only be either 1, 2, 3, 4, 5, 6!')

        # VERBOSITY (a.k.a log level) -> Identical to PlatoSim usage
        # verbose = 0: Cluster mode: Disabling print and warnings, and no log files are saved
        # verbose = 1: Default mode: Print details to bash but do not save log files
        # verbose = 3: Debug mode  : Print details to bash and saves all log files
        if args.verbose == 0:
            self.verbose = 0
            self.verbose_platosim = 0
            # Bash extention to write no output for the L1 pipeline
            self.devnull = '> /dev/null'
            # Turn off warnings
            import warnings
            warnings.filterwarnings("ignore")
        elif args.verbose is None or args.verbose == 1:
            self.verbose = 1
            self.verbose_platosim = 0
            self.devnull = ''
            # Turn off warnings
            import warnings
            warnings.filterwarnings("ignore")
        else:
            self.verbose = 3
            self.verbose_platosim = 3
            self.devnull = ''

        # Overwrite simulation
        if args.overwrite:
            self.overwrite = True
        else:
            self.overwrite = False

            
        # PATHS AND INPUT

        # Absolute pwd path
        self.path = Path(__file__).parent.resolve()

        # PlatoSim inputfiles
        self.platosimInputDir = self.path.joinpath(os.getenv('PLATO_PROJECT_HOME'), 'inputfiles')

        # First priotity to project name
        if self.project:
            self.simDir = self.path.joinpath(os.getenv('PLATO_WORKDIR'), self.project)
        # Second priority to path to inputfiles
        elif self.inputDir:
            self.simDir = Path(self.inputDir).resolve()
        else:
            errorcode('error', 'Either -i or --project is needed to locate the inputfiles!')

        # Check if the inputfile.yaml exists
        self.inputDir  = self.simDir / 'input'
        self.inputFile = self.inputDir / 'inputfile.yaml'
        if not self.inputFile.is_file():
            errorcode('error', f'File {self.inputFile} do not exist!')        

        # L1 pipeline paths
        if self.sample:
            # platoBin: extract_contaminant.py
            # platoLib: pproc.py, invert_parabolic1_multi, psffit.py, lightcurve.py, jittercorrection.py
            self.platoBin = self.path.joinpath(os.getenv('PLATO'), 'bin')
            self.platoLib = Path(os.path.split(sys.executable)[0]).resolve()
            #self.platoBin = os.getenv('PLATO') + '/bin'
            #self.platoLib = os.getenv('PLATO') + '/lib/python/bin'
            
        # PHYSICAL PARAMETERS

        # Check for PLATO pointing field (in Galactic long. (deg) and lat. (deg))
        self.PF = {'SPF': [86.79870508, -46.39594703],  # Equivalent to Galactic [253.0, -30.0]
                   'NPF': [265.08002279, 39.5836954]}   # Equivalent to Galactic [65.0,  +30.0]

        # TODO Threshold (%) of variability to incldue for a contaminant
        # Signals: flare, pulsation, eclipse
        self.varStarLimit = 50
        if not self.conDeltaMag:    self.conDeltaMag    = 5     # Limit to include contaminants [delta mag]
        if not self.conFluxError:   self.conFluxError   = 10    # Flux error of contaminat stars [%]
        if not self.tarFluxError:   self.tarFluxError   = 1     # Flux error of target star [%]
        if not self.tarAbsCenError: self.tarAbsCenError = 0.02  # Absolute error of target centroid position [pixel]
        self.bsres = 10
        self.prnuError = 0.1
        
        # Monitor script speed
        self.tic  = datetime.datetime.now()
        self.tic0 = datetime.datetime.now()

        

        
    def load_stars(self):
        """
        Module to load the stellar targets and contaminants.
        """

        # Handle PIC catalog files
        if self.sample is not None: extra_str = f'_{self.sample}'
        else: extra_str = ''
        picTarFile = glob.glob(str(self.inputDir) + f'/starcat{extra_str}**targets.ftr')[0]
        picConFile = glob.glob(str(self.inputDir) + f'/starcat{extra_str}**contaminants.ftr')[0]

        if self.verbose > 0: print('Loading PIC stars..')
        df = pd.read_feather(picTarFile)
        dc = pd.read_feather(picConFile)

        # If a specific star is choosen
        if self.picID is not None:
            try:
                self.targetNo = np.where(df['ID'] == self.picID)[0][0]
            except IndexError:
                errorcode('error', f'PIC {self.picID} star does not exist in current catalogue:\n{picTarFile}')

        # TODO add full frames to sim
        # if self.targetNo == -1:
        #     self.df = df.append
        #     self

        # NOTE ID=1 is the first star!
        if self.targetNo == 0:
            errorcode('error', 'Star ID indicing starts from 1 and not 0!')
        else:
            # Select single star
            self.df = df.iloc[self.targetNo - 1]
            self.dc = dc[dc['ID'] == self.df['ID']]
            self.numCon = len(self.dc['ID'])





        



    def configure_output(self):
        """
        Module to create, configure, and select the correct output folders.
        """

        # Select proper name convension
        if self.simPrefix is None: self.simPrefix = ''
        else: self.simPrefix = self.simPrefix + '_'
        self.obsPrefix = f'Ncam{self.group}.{self.camera}_Q{self.quarter}'
        #self.picPrefix = f"{self.simPrefix}pic{self.df['ID']}_{self.obsPrefix}"

        # Default output path
        if self.outputDir is None: self.outputDir = self.simDir.joinpath('output')
        else: self.outputDir = Path(self.outputDir).resolve()
        try: os.mkdir(self.outputDir)
        except: pass

        # Set general output filename
        self.outputFileName = f'{self.targetNo}'.zfill(9)
        
        # NOTE the structure for the L1 pipeline are different from the default
        if self.sample is None:
            
            # PIC name convention
            self.outputFileName = f'{self.outputFileName}_{self.obsPrefix}'

        else:
            # Name convention for pipeline mode
            self.starID = self.outputFileName
            relativeDirStar = f'{self.sample}/Q{self.quarter}/Ncam{self.group}{self.camera}'

            # L1 pipeline paths
            self.pipelineDir = f'{self.outputDir}/{relativeDirStar}'
            self.outputDirStarIDsim = f'{self.pipelineDir}/{self.starID}'
            self.outputDirStarIDnew = f'{self.outputDir}/reduced/{self.sample}/{self.starID}'
                        
            # Microscan paths
            self.microscanDir = f'{self.outputDir}/microscan/{relativeDirStar}/{self.starID}'
            self.microscanDirStarID = f'{self.microscanDir}/{self.starID}'
            self.microscanDirInvers = f'{self.microscanDir}/inversion'
            
            # Create paths
            try: os.makedirs(self.outputDirStarIDsim)
            except: pass
            try : os.makedirs(self.outputDirStarIDnew)
            except: pass
            try: os.makedirs(self.microscanDirStarID)
            except: pass
            try: os.makedirs(self.microscanDirInvers)
            except: pass

            # Normal output path
            self.outputDir = Path(self.outputDirStarIDsim).resolve()

            # Path + Prefix of simulations
            self.microscanSimName = f'{self.microscanDirStarID}/{self.outputFileName}' 
        self.outputSimName = f'{self.outputDir}/{self.outputFileName}'

        


        
        
    def init_sim(self):
        """
        Module to initialize the the PlatoSim simulation object.
        """
        
        # INITIALIZE SIMULATION

        # Print to bash
        if self.verbose > 0:
            errorcode('module', '\nInitialising and running PlatoSim')

        # Setting up a test simulation environement
        sim = Simulation(self.outputFileName, self.inputFile)

        
        # CONFIGURE TIMING

        # NOTE the CCD offset is automatically set while using setSubfieldAroundCoordinates!
        
        # Cadence of time series [s]
        # NOTE if argument parsed it overwrites inputfile.yaml
        if self.cadence is None:
            self.cadence = sim['ObservingParameters/CycleTime']
        else:
            sim['ObservingParameters/CycleTime'] = self.cadence

        # Start time of simulation
        self.timeStart = round(90. * (self.quarter - 1) * 86400.)

        # Apply start time relative mission BOL
        self.beginExposureNr = round(self.timeStart / self.cadence)
        sim['ObservingParameters/BeginExposureNr'] = self.beginExposureNr

        # Duration of time series
        if self.simExposures:
            # Setting timeseries by N exposures given by user
            self.numExposures = self.simExposures
        elif self.simTime is not None:
            # Setting timeseries by time given by user
            self.numExposures = round(self.simTime * 86400. / self.cadence)
        else:
            # Setting time series to full quarter
            # NOTE Two days are lost due to platform roll, thermal stabilisation, downlink, microscanning, etc.
            # TODO make configurable/flag option to change inter-quarter downtime (normal distributed?)
            self.numExposures = round( (90. - 2.) * 86400. / self.cadence )

        # Print to bash
        if self.verbose > 0:
            if args.plot:
                print(f'Visualizing simulation for N-CAM {self.group}.{self.camera} Q{self.quarter}')
            else:
                print(f'Simulating N-CAM {self.group}.{self.camera} Q{self.quarter} for {self.numExposures} exposures')
            

        # PHYSICAL PARAMETERS
            
        # Photon flux of a P=0 G2V-star [phot/s/m^2/nm]
        sim["ObservingParameters/Fluxm0"] = 0.7324478224428527e8

        # Change sampling (not cadence) for quicker simulations
        # TODO find a way to to this!


        # PHOTOMETRY ALA MARCHIORI

        # The maskUpdate is given in days
        # The mask-update rate is event after number of exposures
        # NOTE argument parsing overwrites inputfile.yaml
        if self.maskUpdate:
            sim['Photometry/MaskUpdateInterval'] = self.maskUpdate
            self.maskUpdateRate = round(self.maskUpdate * 86400. / self.cadence)
        else:
            self.maskUpdateRate = round(sim['Photometry/MaskUpdateInterval'] * 86400. / self.cadence)
            
            
        # CONFIGURE PAYLOAD
                
        # Solar panel orientation: Q(N) = {0, 90, 180, 270} deg [deg]
        solarPanelOrientationDeg = sim["Platform/SolarPanelOrientation"] = math.fmod(self.quarter * 90., 360.)

        # Select PLATO pointing field from inputfile (e.g. SPF, NPF, etc.) [deg]
        self.pointingField = sim["ObservingParameters/StarCatalogFile"]
        sim["ObservingParameters/RApointing"]  = self.PF[self.pointingField][0]
        sim["ObservingParameters/DecPointing"] = self.PF[self.pointingField][1]
        
        # Set the Camera-group ID and Camera-group Alt (tilt) and Az [deg]
        sim["Telescope/GroupID"] = self.group        
        sim["Telescope/TiltAngle"]    = sim["CameraGroups/TiltAngle"][self.group-1]
        sim["Telescope/AzimuthAngle"] = sim["CameraGroups/AzimuthAngle"][self.group-1]       

        
        # POINTING ERRORS
        
        # Include spacecraft Pointing Repeatability Error (PRE) between consecutive quarters
        # NOTE: Will only be included if the file "PRE.txt" is available in the input folder
        inputFilePRE = self.inputDir.joinpath('PRE.txt')
        if inputFilePRE.is_file():
            PRE = np.loadtxt(inputFilePRE)
            dex = np.where(PRE[:,0] == self.quarter)[0]
            try: dex[0]
            except:
                errorcode('warning', 'Cannot apply Pointing Repeatability Error, no matching quarters in PRE.txt!')
            else:
                sim["ObservingParameters/RApointing"]  += PRE[dex, 1][0]
                sim["ObservingParameters/DecPointing"] += PRE[dex, 2][0]
                sim["Platform/SolarPanelOrientation"]  += PRE[dex, 3][0]

        # Include Absolute Pointing Error (APE) due to camera misalignments
        # NOTE: Will only be included if the file "APE.txt" is available in the input folder
        inputFileAPE = self.inputDir.joinpath('APE.txt')
        if inputFileAPE.is_file():
            APE = np.loadtxt(inputFileAPE)
            dex = (self.group - 1) * 6 + self.camera - 1
            sim["Telescope/TiltAngle"]    += APE[dex, 0]
            sim["Telescope/AzimuthAngle"] += APE[dex, 1]
        
        # Attitude Orbit Control System (AOCS) jitter
        # NOTE: Will only be included if file "AOCS_Q<quarterNo>.txt" is availale in the input folder
        if self.reuseJitter:
            sim["Platform/UseJitter"]    = True
            sim["Platform/JitterSource"] = 'FromFile'
            inputFileAOCS   = self.inputDir.joinpath(sim["Platform/JitterFileName"])
            inputFileAOCS_Q = f'{self.inputDir}/AOCS_Q{self.quarter}.txt'
            # Check if the exists or else create new time column
            if Path(inputFileAOCS_Q).is_file():
                pass
            elif self.quarter == 1:
                os.system(f'cp {inputFileAOCS} {inputFileAOCS_Q}')
            else:
                # Load file given in YAML input
                data = np.loadtxt(inputFileAOCS)
                t, x, y, z = data[:,0], data[:,1], data[:,2], data[:,3]
                # Generate new time column
                cadence = np.diff(t)[0]  # [s -> 8 Hz]
                t = np.arange(len(t)) * cadence + self.timeStart
                # Save data to input folder
                np.savetxt(inputFileAOCS_Q, np.transpose([t,x,y,z]), fmt=['%.3f', '%.9f', '%.9f', '%.9f'])
            # Set filepath to new file
            sim["Platform/JitterFileName"] = inputFileAOCS_Q
                                    
        # Thermal Elastic Distortion (TED):
        # NOTE: it is assumed that the TED is the same for each camera per quarter 
        inputFileTED = self.inputDir.joinpath('instrumentTED.txt')
        if inputFileTED.is_file():
            sim["Telescope/UseDrift"]         = True
            sim["Telescope/UseDriftFromFile"] = True
            sim["Telescope/DriftFileName"]    = inputFileTED

        # KDA
        #print(sim['Camera/AberrationCorrection/OrbitFile'])


        # SELECT SUBFIELD
        
        # Try to set a subfield around the coordinates on one of the 4 CCDs of the telescope.
        # This will fail (return = False) if the subfield is not visible by any of the 4 CCDs
        # or if the subfield is too large to entirely fit on a CCD. If successful, the function
        # sets the CCD and subfield parameters correctly in the 'sim' object.
        numColSubfield = sim["SubField/NumColumns"]
        numRowSubfield = sim["SubField/NumRows"]
        raTargetRad    = np.deg2rad(self.df['ra'])
        decTargetRad   = np.deg2rad(self.df['dec'])

        self.subfieldIsOnCCD = sim.setSubfieldAroundCoordinates(raTargetRad, decTargetRad,
                                                                numColSubfield, numRowSubfield,
                                                                normal=True)
        if self.subfieldIsOnCCD is False:
            if self.verbose > 0:
                message  = (f"PIC {self.df['ID']} (subfield {self.targetNo}) " +
                            'do not fall on any of the CCDs for ' +
                            f'N-CAM {self.group}.{self.camera} and Q{self.quarter}!')
                errorcode('warning', message)
            exit()

        # If the psf is MappedFromFile we need to include mapped field distortion
        if sim["PSF/Model"] == "MappedFromFile":
            includeFieldDistortion = True
            mappedDistortion       = True
            pathToPsfFile          = sim["PSF/MappedFromFile/Filename"]
            distortionCoefficients = None
        elif (sim["Camera/IncludeFieldDistortion"] == "yes" or
              sim["Camera/IncludeFieldDistortion"] == "1"   or
              sim["Camera/IncludeFieldDistortion"] == True):
            includeFieldDistortion = True
            mappedDistortion       = False
            pathToPsfFile          = None 
            distortionCoefficients = sim["Camera/FieldDistortion/ConstantCoefficients"]
        else:
            includeFieldDistortion = False
            mappedDistortion       = False
            pathToPsfFile          = None 
            distortionCoefficients = None

        # Fetch info from YAML file since setting the subfied figure the inputfile
        self.raPlatformDeg            = sim["ObservingParameters/RApointing"]
        self.decPlatformDeg           = sim["ObservingParameters/DecPointing"]
        self.tiltTelescopeDeg         = sim["Telescope/TiltAngle"]
        self.azimuthTelescopeDeg      = sim["Telescope/AzimuthAngle"]
        self.solarPanelOrientationDeg = sim["Platform/SolarPanelOrientation"]
        # Transform to radians
        raPlatformRad            = np.deg2rad(self.raPlatformDeg)
        decPlatformRad           = np.deg2rad(self.decPlatformDeg)
        tiltTelescopeRad         = np.deg2rad(self.tiltTelescopeDeg)
        azimuthTelescopeRad      = np.deg2rad(self.azimuthTelescopeDeg)
        solarPanelOrientationRad = np.deg2rad(self.solarPanelOrientationDeg)
        # Hardware parameters
        pixelSize       = float(sim["CCD/PixelSize"])
        focalLength     = float(sim["Camera/FocalLength/ConstantValue"]) * 1000.0  # [m] -> [mm]
        focalPlaneAngle = np.deg2rad(float(sim["Camera/FocalPlaneOrientation/ConstantValue"]))

        # Fetch focal plane coordinates [mm]
        xFPmm, yFPmm = rf.skyToFocalPlaneCoordinates(raTargetRad, decTargetRad,
                                                     raPlatformRad, decPlatformRad,
                                                     solarPanelOrientationRad,
                                                     tiltTelescopeRad, azimuthTelescopeRad,
                                                     focalPlaneAngle, focalLength)
        if includeFieldDistortion == True or includeFieldDistortion == "yes":
            if mappedDistortion:
                xFPmm, yFPmm = rf.mappedUndistortedToDistortedFocalPlaneCoordinates(xFPmm, yFPmm, pathToPsfFile)
            else: 
                xFPmm, yFPmm = rf.undistortedToDistortedFocalPlaneCoordinates(xFPmm, yFPmm, distortionCoefficients, focalLength)

                
        # Fetch CCD code and pixel coordinates (account for field distortion if included)
        ccdCode, xCCD, yCCD = rf.getCCDandPixelCoordinates(raTargetRad, decTargetRad,
                                                           raPlatformRad, decPlatformRad,
                                                           solarPanelOrientationRad,
                                                           tiltTelescopeRad, azimuthTelescopeRad,
                                                           focalPlaneAngle, focalLength, pixelSize,
                                                           includeFieldDistortion, normal=True,
                                                           mappedDistortion=mappedDistortion,
                                                           distortionCoefficients=distortionCoefficients,
                                                           pathToPsfFile=pathToPsfFile)
        

        # Calculate radial distance of coordinate away from OA
        # NOTE due to strong vinetting stars are barely detectable beyond 18.2 deg
        # TODO check if this is in fact due to the distortion model which is not accounted
        # for in the setSubfieldAroundCoordinates
        distanceOA = np.rad2deg(rf.gnomonicRadialDistanceFromOpticalAxis(xFPmm, yFPmm, focalLength))
        if distanceOA > 18.2:
            if self.verbose > 0:
                message  = (f"PIC {self.df['ID']} (subfield {self.targetNo}) " +
                            f'is outside camera FOV (d={distanceOA:.2f} deg) ' +
                            f'for N-CAM {self.group}.{self.camera} and Q{self.quarter}!')
                errorcode('warning', message)
            exit()

        # Create data frame for printing and saving
        c = ['ID', 'ra [deg]', 'dec [deg]', 'mag',
             'CCD', 'xCCD [pix]', 'yCCD [pix]',
             'rOA [deg]', 'xFP [mm]', 'yFP [mm]', 'Ncon']
        d = {'ID': [self.df['ID']], 'mag': [self.df['mag']],
             'ra [deg]': [self.df['ra']], 'dec [deg]': [self.df['dec']],
             'CCD': [ccdCode], 'xCCD [pix]': [xCCD], 'yCCD [pix]': [yCCD],
             'rOA [deg]': [distanceOA], 'xFP [mm]': [xFPmm], 'yFP [mm]': [yFPmm],
             'Ncon': self.numCon}
        self.df0 = pd.DataFrame(d, columns=c)

        # Print data frame
        if self.verbose > 0:
            print('\nInformation about stellar target')
            print(self.df0)

        # Add CCD time-shift to time points
        # Only continue if ccdCode is found:
        if ccdCode:
            self.timeStart += float(sim['CCDPositions/TimeShift'][int(ccdCode)-1])
            self.time = np.arange(self.numExposures) * self.cadence + self.timeStart
        else:
            errorcode('warning', 'Star falls within a CCD gap!')
            exit()
            
        # Finito!
        return sim
        
        
        


    
    def create_seeds(self, sim):
        """
        Module to select and load the random seeds.
        """

        # Initialise random number generator after user or clock
        if not self.seed:
            self.seed = 1234
            rng = np.random.default_rng()
        else:
            rng = np.random.default_rng(self.seed)
        
        # Random seed equal per quarter/camera but different per target
        self.seedTarget = self.seed * self.targetNo 

        # Seed different for each quarter, group, and camera
        self.seedObservation = self.seed * 8 * self.quarter + 10 * 4 * self.group + self.camera + 100000

        # Seed different for each star, quarter, group, and camera
        self.seedOffset = self.seedTarget + self.seedObservation
        
        # Set quarter specific random seed for jitter
        if sim["Platform/UseJitter"] == 'yes' and sim["Platoform/JitterSource"] != 'FromFile':
            sim["RandomSeeds/JitterSeed"] += 100 * self.quarter

        # Set camera and quarter specific random seed for TED
        if sim["Telescope/UseDrift"] and sim["Telescope/UseDriftFromFile"] is False:
            sim["RandomSeeds/DriftSeed"] += self.seedOffset

        # Lastly, the remaining seeds needs to differ for all times and for all subfields
        sim["RandomSeeds/ReadOutNoiseSeed"] += rng.integers(1e9, size=1)[0]
        sim["RandomSeeds/PhotonNoiseSeed"]  += rng.integers(1e9, size=1)[0]
        sim["RandomSeeds/DarkSignalSeed"]   += rng.integers(1e9, size=1)[0]
        sim["RandomSeeds/FlatFieldSeed"]    += rng.integers(1e9, size=1)[0]
        sim["RandomSeeds/CosmicSeed"]       += rng.integers(1e9, size=1)[0]



            



            
    def create_inputfiles(self, sim):
        """
        Function to create ascii input files for PlatoSim.
        """
        
        # SAVE STELLAR CATALOGS AND TARGET LISTS

        # Make a star catalog with all the stars in this subfield
        idStarCatalog  = np.arange(1, self.numCon+2)
        raStarCatalog  = np.append(self.df['ra'],  self.dc['ra'])
        decStarCatalog = np.append(self.df['dec'], self.dc['dec'])
        magStarCatalog = np.append(self.df['mag'], self.dc['mag'])

        # Save catalog and load it into the inputfile
        self.starCatalog = np.transpose([raStarCatalog, decStarCatalog, magStarCatalog, idStarCatalog])
        self.starCatalogFile = f'{self.outputDir}/{self.outputFileName}.cat'
        sim["ObservingParameters/StarCatalogFile"] = self.starCatalogFile
        np.savetxt(self.starCatalogFile, self.starCatalog, fmt=['%11.6f', '%11.6f', '%8.4f', '%i'])

        # Print catalogue
        if self.verbose:
            print('\nStar catalog used in simulation')
            df1 = pd.DataFrame({'RA [deg]': raStarCatalog,
                                'Dec [deg]': decStarCatalog,
                                'P [mag]': magStarCatalog,
                                'Dis [pix]': np.append(0, self.dc['dis'])/15.},
                               index=idStarCatalog)
            print(df1)

            
        # SAVE LIST OF VARIABLE SOURCES

        # NOTE if a user-defined filename for the variable data is parsed
        # then a variable source list is created automatically
        # TODO binary files are not yet compatible with PlatoSim!
        if sim['Sky/IncludeVariableSources'] is True:
            
            # First priority to varSourceList -> Allows variability for all stars
            if self.varSourceList:
                sim["Sky/VariableSourceList"] = Path(self.varSourceList).resolve()

            # Second priority to varSourceFile -> Allows variability for target only
            elif os.path.exists(str(self.varSourceList)) is False:

                # If varSourceFile is parsed or located within input
                if self.varSourceFile:
                    varSourceFile = Path(self.varSourceFile).absolute()
                elif os.path.exists(f'{self.inputDir}/varsource.txt'):
                    varSourceFile = f'{self.inputDir}/varsource.txt'
                else:
                    errorcode('error', 'No variable source list found from inputfiles! Create file or give as input')

                # Save varSourceList to file
                varSourceList = f'{self.outputDir}/{self.outputFileName}.var' 
                np.savetxt(varSourceList, np.array([]), header='1 '+ str(varSourceFile), comments='')
                sim["Sky/VariableSourceList"] = varSourceList
                # Store parameters for future deletion
                self.varSourceList = varSourceList
                self.varSourceFile = varSourceFile

                
        # SAVE PHOTOMETRY FILE
        
        # NOTE if a user defined file name for the photometry file is parsed
        # then a photometry file list is created automatically
        if sim['Photometry/IncludePhotometry'] is True:
            photometryList = self.inputDir.joinpath('photometry.txt')
            if os.path.exists(photometryList) is False:
                np.savetxt(photometryList, np.array([]), header='1', comments='')
            sim["Photometry/TargetFileName"] = photometryList


            


            
            
    def show_subfield(self, sim):
        """
        Function to show 
        (1) where the target star is situated in the CCD focal plane
        (2) the first subfield/imagette of the simulation
        This function exit the simulation.
        """

        # Control the content of the hdf5 output files
        sim.writeAllOutputToHDF5(write=False)
        sim["ObservingParameters/NumExposures"] = 1
        sim["ControlHDF5Content/WritePixelMaps"]      = True
        sim["ControlHDF5Content/WriteStarPositions"]  = True
        
        # Add photometric mask to plot if available
        if sim['Photometry/IncludePhotometry']: mask = 1
        else: mask = None

        # Run simulation for first image cadence
        self.outputSimName = self.outputDir.joinpath(self.outputFileName)
        sim.outputDir = self.outputDir
        simFile = sim.run(removeOutputFile=self.overwrite)
        
        # Plot star in CCD focal plane
        fig = plt.figure(figsize=(12,10))
        drawStarInCCDfocalPlane(fig, sim, self.df0['xCCD [pix]'][0], self.df0['yCCD [pix]'][0],
                                self.df0['CCD'][0], self.group,
                                self.raPlatformDeg, self.decPlatformDeg,
                                self.tiltTelescopeDeg, self.azimuthTelescopeDeg,
                                self.solarPanelOrientationDeg)
        
        # Show image (recommend cmaps: "hot", "gnuplot2", "magma", "Spectral_r")        
        title = 'Imagette of PIC {0} ({1:.2f} mag)'.format(int(self.df['ID']), float(self.df['mag']))
        simFile.showImage(self.beginExposureNr, showStarPositions='PIC', clipPercentile=7,
                          showMaskOfStarID=mask, useTitle=title, colorMap='cubehelix',
                          colorBar=True, imgScale="auto", showGrid=True, figsize=(6,6))

        # Remove the output files
        if os.path.isfile(str(self.outputSimName) + '.hdf5'):
            os.system(f'rm {self.outputDir}/* ')




            

    def run_sim_normal(self, sim):
        """
        Module to run PlatoSim only.
        """

        # Print to bash
        if self.verbose > 0:
            errorcode('message', '\n[PlatoSim]: Simulating Quarter imagette time-series')
     
        # Select the number of exposures
        sim["ObservingParameters/NumExposures"] = self.numExposures
        
        # Run simulation
        sim.outputDir = self.outputDir
        simFile = sim.run(removeOutputFile=self.overwrite, logLevel=self.verbose_platosim)
        
        # Common files to always remove
        if self.subfieldIsOnCCD:
            if self.varSourceFile: os.remove(self.varSourceList)
            if self.sample is None and self.verbose < 3:
                if os.path.isfile(str(self.outputSimName) + '.log'):  os.remove(str(self.outputSimName) + '.log')
                if os.path.isfile(str(self.outputSimName) + '.yaml'): os.remove(str(self.outputSimName) + '.yaml')
                if os.path.isfile(self.starCatalogFile): os.remove(self.starCatalogFile)
            
        # Compress files
        if self.compress and os.path.isfile(self.outputSimName + '.hdf5') and not self.sample:
            if self.verbose > 0:
                errorcode('module', '\nRestructuring data output')
                print('Compressing files')
            os.system(f'zip -j {self.outputSimName}.zip {self.outputSimName}*')
            os.remove(self.outputSimName + '.hdf5')

        # Execution time of module
        if self.verbose > 0:
            self.tocPlatoSim = datetime.datetime.now() - self.tic
            self.tic = datetime.datetime.now()
            self.byte2MB = 1024 * 1024 #* 1024
            self.memPlatoSim = os.path.getsize(self.outputDir) / self.byte2MB
            #self.memPlatoSim = shutil.disk_usage(self.outputDir)

            
    #--------------------------------------------------------------#
    #                    L1 PIPELINE MODULES                       #
    #--------------------------------------------------------------#

    def control_hdf5(self):
        """
        Module to control HDF5 content for L1 pipeline.
        """

        # Exclude photometry
        sim["Photometry/IncludePhotometry"] = 'no'

        # Include HDF5 content
        sim["ControlHDF5Content/WritePixelMaps"]              = True
        sim["ControlHDF5Content/WriteBiasMaps"]               = False
        sim["ControlHDF5Content/WriteSmearingMaps"]           = True
        sim["ControlHDF5Content/WriteThroughputMaps"]         = True
        sim["ControlHDF5Content/WriteFlatfieldMap"]           = True
        sim["ControlHDF5Content/WriteSubPixelImages"]         = False
        sim["ControlHDF5Content/WriteStarPositions"]          = True
        sim["ControlHDF5Content/WriteACS"]                    = True
        sim["ControlHDF5Content/WriteCosmics"]                = True
        sim["ControlHDF5Content/WriteDiffusedPSF"]            = False
        sim["ControlHDF5Content/WriteHighResolutionPSF"]      = True
        sim["ControlHDF5Content/WriteStarCatalog"]            = True
        sim["ControlHDF5Content/WriteTelescopeACS"]           = False
        sim["ControlHDF5Content/WriteTransmissionEfficiency"] = True
        sim["ControlHDF5Content/WriteCTI"]                    = False

        # Check for high res mapped PSF
        if sim["PSF/Model"] == 'MappedFromFile':
            sim["ControlHDF5Content/WriteDiffusedPSF"] = True




            
    def run_microscan(self, sim):
        """
        Module to run a microscan sequence with PlatoSim.
        """

        # Print to bash
        if self.verbose > 0:
            errorcode('module', 'Microscanning Sequence & PSF Inversion')

        # Check if mapped PSFs are used and apply correct resolution
        if sim["PSF/Model"] == 'MappedFromFile':
            sim["SubField/SubPixels"] = 64
        else:
            sim["SubField/SubPixels"] = 128
            
        # Prepare for the Archimedean jitter spiral pattern
        sim["Platform/UseJitter"]               = 'yes'
        sim["Platform/JitterSource"]            = 'FromFile'
        sim["ObservingParameters/NumExposures"] = 428
        sim['ObservingParameters/CycleTime']    = 25
        
        # Time of microscan simulation needs to match quarter for PlatoSim to run successfully
        # NOTE Here a new file is created with a appropriate time column to match the observation
        # NOTE This is done once per quarter and CCD time-shift and the file is saved to the simulation folder
        spiralFileName     = 'microscan_spiral_8Hz_3h_BC.txt'
        spiralFileBase     = f'{self.platosimInputDir}/{spiralFileName}'
        spiralFileQuarterN = f'{self.microscanDirStarID}/{spiralFileName}'

        if self.quarter == 1 and int(self.df0['CCD']) == 1:
            os.system(f'cp {spiralFileBase} {spiralFileQuarterN}')
        else:
            # Load file
            data = np.loadtxt(spiralFileBase)
            t, x, y, z = data[:,0], data[:,1], data[:,2], data[:,3]
            # Generate new time column
            cadence = np.diff(t)[0]  # [s -> 8 Hz]
            t = np.arange(len(t)) * cadence + self.timeStart
            # Save data to input folder
            np.savetxt(spiralFileQuarterN, np.transpose([t,x,y,z]), fmt=['%.3f', '%.9f', '%.9f', '%.9f'])

        # Load Archimedean spiral
        sim["Platform/JitterFileName"] = spiralFileQuarterN

        # HDF5 content to always exclude
        sim["Telescope/UseDrift"]                     = False
        sim["Sky/IncludeVariableSources"]             = False
        sim["Photometry/IncludePhotometry"]           = False
        sim["ControlHDF5Content/WriteSubPixelImages"] = False
        
        # HDF5 content to always include
        sim["ControlHDF5Content/WritePixelMaps"]              = True
        sim["ControlHDF5Content/WriteBiasMaps"]               = True
        sim["ControlHDF5Content/WriteSmearingMaps"]           = True
        sim["ControlHDF5Content/WriteThroughputMaps"]         = True
        sim["ControlHDF5Content/WriteFlatfieldMap"]           = True
        sim["ControlHDF5Content/WriteHighResolutionPSF"]      = True
        sim["ControlHDF5Content/WriteTransmissionEfficiency"] = True
        sim["ControlHDF5Content/WriteStarPositions"]          = True
        sim["ControlHDF5Content/WriteACS"]                    = True
        sim["ControlHDF5Content/WriteCosmics"]                = True
        sim["ControlHDF5Content/WriteStarCatalog"]            = True
        sim["ControlHDF5Content/WriteTelescopeACS"]           = True
        sim["ControlHDF5Content/WriteCTI"]                    = True

        # If mapped PSF is used the diffused PSFs need to be saved
        if sim["PSF/Model"] == 'MappedFromFile':
            sim["ControlHDF5Content/WriteDiffusedPSF"] = 'yes'
        
        # Save catalog and load it into the inputfile
        # NOTE we need to replace the target name for correct handling by the LESIA pipeline
        numStar = self.numCon + 1
        starIDs = np.arange(self.targetNo, self.targetNo + numStar, 1)
        starCatalog        = np.copy(self.starCatalog)
        starCatalog[:, -1] = starIDs
        starCatalogFile    = f'{self.microscanSimName}.coo'
        np.savetxt(starCatalogFile, starCatalog, fmt=['%11.6f', '%11.6f', '%8.4f', '%i'])
        sim["ObservingParameters/StarCatalogFile"] = starCatalogFile

        # MICROSCANNING SIMULATION

        if self.verbose > 0:
            errorcode('message', '\n[PlatoSim]: Simulating imagettes')
        sim.outputDir = self.microscanDirStarID
        simFile = sim.run(removeOutputFile=False, logLevel=self.verbose_platosim)

        # Execution time of module
        if self.verbose > 0:
            self.tocMicroscan = datetime.datetime.now() - self.tic
            self.tic = datetime.datetime.now()
            
        # PRE-PROCESSING

        # Change directory needed to execute scripts
        os.chdir(self.microscanDir)
        
        # Run pre-processing
        if self.verbose > 0:
            errorcode('message', '\n[pproc]: Pre-processing imagettes')
        os.system(f'{self.platoLib}/pproc.py --platosim --auto-bg -f {self.starID} {self.devnull}')
        
        # EXTRACT CONTAMINANTS

        # Run contaminant extraction
        if self.verbose > 0:
            errorcode('message', f'\n[extract_contaminants]: Model contaminants with dmag < {self.conDeltaMag} from target')
        os.system(f'{self.platoBin}/extract_contaminant.py ' +
                  f'-D {self.conDeltaMag} -e {self.conFluxError} ' + 
                  f'-s {self.seedTarget} {self.starID} {self.starID} {self.devnull}')

        # PSF INVERSION
        
        # Find Regularization parameter for each star
        PV   = -0.34  # P-V magnitude offset
        Vmag = self.df['mag'] - PV
        regs = np.format_float_scientific(10.**(0.51 * Vmag - 14.61))
        
        # Make sure to only use one thread since we will use the HPC
        os.system('export OMP_NUM_THREADS=1')
        
        # Run the inversion module
        # NOTE Type of microscanning (-t)
        # NOTE Sub-pixel resolution of invertion (-p)
        # NOTE Sub-pixel resolution of inverted PSF (-l)
        # NOTE Sub-pixel resolution of original PSF (-r)
        # NOTE Regularisation parameter for the wPRLS method (-u)
        # NOTE Number of elementary steps over which to calculate averaged positions (-N)
        if self.verbose > 0:
            errorcode('message', '\n[invert_parabolic_multi]: Run the PSF inversion')
        os.system(f'{self.platoLib}/invert_parabolic1_multi ' +
                  f'-Q -t continuous -m PRLS ' +
                  f'-N 1 -r 128 -l 128 -p {self.bsres} -u {regs} ' +
                  f'-d . -i {self.starID} -q {self.starID}/{self.starID}_offsets.txt ' + 
                  f'-o inversion {self.devnull}')
        
        # Execution time of module
        if self.verbose > 0:
            self.tocInversion = datetime.datetime.now() - self.tic
            self.tic = datetime.datetime.now()


            

        

        
    def run_L1_onground(self):
        """
        Module to for the on-ground L1 pipeline processing chain.
        """

        # Print to bash
        if self.verbose > 0:
            errorcode('module', '\nOn-ground L1 pipeline')

        # Change directory needed to execute scripts
        os.chdir(self.pipelineDir)

        # PRE-PROCESSING

        if self.verbose > 0:
             errorcode('message', '\n[pproc]: Pre-processing imagettes')
        os.system(f'{self.platoLib}/pproc.py --platosim --auto-bg -f {self.starID} {self.devnull}')

        # PSF FIITING

        # NOTE using Dierckx's knot distribution (-K 1)
        # NOTE using Levenberg-Marquardt minimization method (default: -M 0)
        # NOTE using B-spline resolution of 10 (-b) matching the PSF resolution!
        # NOTE PRNU knowledge errorin % (-p)
        if self.verbose > 0:
            errorcode('message', '\n[psffit]: PSF fitting for light curve generation')
        os.system(f'{self.platoLib}/psffit.py ' +
                  f'-K 1 -b {self.bsres} --seed {self.seedOffset} ' +
                  f'-F {self.tarFluxError} -s {self.tarAbsCenError} -p {self.prnuError} ' + 
                  f'-f {self.microscanDirInvers}/{self.starID}_PRLS.vec ' +
                  f'-o {self.starID} {self.starID} {self.devnull}')
        
        # PROLOGUE
                
        # Execution time of module
        if self.verbose > 0:
            self.tocOnground = datetime.datetime.now() - self.tic
            self.tic = datetime.datetime.now()





        

    def run_L1_onboard(self):
        """
        Module to for the on-board L1 pipeline processing chain.
        """

        # Print to bash
        if self.verbose > 0:
            errorcode('module', '\nOn-board L1 pipeline')
            
        # Change directory needed to execute scripts
        os.chdir(self.pipelineDir)

        # PRE-PROCESSING

        if self.verbose > 0:
            errorcode('message', '\n[pproc]: Pre-processing imagettes')
        os.system(f'{self.platoLib}/pproc.py --platosim --auto-bg -f {self.starID} {self.devnull}')
        
        # NOTE Binary mask is default (-T 1)
        # NOTE Write mask FITS files (-M)
        # NOTE Calculating SPR vs. time (--spr_tot) -> only binary masks!
        # NOTE Using B-spline PSF resolution (--bsres)
        # NOTE Using Dierckx's knot distribution (-K 1)
        # NOTE Update mask every 14 days (--update-period 48384)
        if self.verbose > 0:
            errorcode('message', '\n[lightcurve.py]: Aperture photometry ala Marchiori+2019')
        os.system(f'{self.platoLib}/lightcurve.py ' +
                  f'-M --input-hdf5 --spr_tot --include-contaminants --add_chromatic_abberation ' +
                  f'--update-period {self.maskUpdateRate} --bsres {self.bsres} ' +
                  f'-I {self.microscanDirInvers}/{self.starID}_PRLS.vec ' +
                  f'-B {self.starID} -o {self.starID} {self.starID} {self.devnull}')

        # JITTER AND DRIFT CORRECTION

        if self.verbose > 0:
            errorcode('message', '\n[jittercorrection.py]: Jitter & Drift Correction')
        os.system(f'{self.platoLib}/jittercorrection.py ' +
                  f'--add_chromatic_abberation ' +
                  f'-W 128 -r 128 ' +
                  f'--bsres {self.bsres} --seed {self.seedOffset} ' + 
                  f'-f {self.prnuError} -b {self.tarAbsCenError} -a {self.conDeltaMag} ' +
                  f'-I {self.microscanDirInvers}/{self.starID}_PRLS.vec ' +
                  f'-o {self.starID} {self.starID} {self.starID} {self.devnull}')
        
        # PROLOGUE
                
        # Execution time of module
        if self.verbose > 0:
            self.tocOnboard = datetime.datetime.now() - self.tic
            self.tic = datetime.datetime.now()


        


    def sort_output(self):
        """
        Module to move output files and delete redundant files.
        """

        # Print to bash
        if self.verbose > 0:
            errorcode('module', '\nRestructuring data output')
            print(f'L1 light curve is saved to {self.outputDirStarIDnew}')

        # Select prefix-files
        prefixInversion = self.microscanDirInvers + f'/{self.starID}'
        prefixStarIDtar = self.outputDirStarIDsim + f'/000000001'
        prefixStarIDsim = self.outputDirStarIDsim + f'/{self.starID}'
        prefixStarIDnew = self.outputDirStarIDnew + f'/{self.starID}_{self.obsPrefix}'

        # Rewrite data time series
        if args.sample == 'P1':
            cols = ['flux', 'cx', 'cy', 'bg', 'flux_err', 'cx_err', 'cy_err', 'bg_err',
                    'chi2', 'iter', 'lamb']
            try:
                df = pd.read_csv(prefixStarIDtar + '.dat', delimiter=' ', comment='#', names=cols, usecols=np.arange(0,len(cols), 1))
            except:
                # Open the file in append & read mode ('a+')
                with open(self.inputDir / 'failed.txt', 'a+') as f:
                    # Move read cursor to the start of file.
                    f.seek(0)
                    # If file is not empty then append '\n'
                    if len(f.read(100)) > 0: f.write("\n")
                    # Append text at the end of file
                    f.write(f'{int(self.starID)} {self.group} {self.camera} {self.quarter}')
                df = None
                
        if args.sample == 'P5':
            cols = ['flux', 'xc', 'yc', 'flux_cor']
            df = pd.read_csv(prefixStarIDtar + '-jc.dat', delimiter=' ', comment='#', names=cols, usecols=cols)
            shutil.move(prefixStarIDtar + '-sprtot.dat', prefixStarIDnew + '.spr')
            # Move mask files number after mask update exposure
            maskfits = glob.glob(f'{prefixStarIDtar}**mask.fits')
            for i in range(len(maskfits)):
                shutil.move(maskfits[i], prefixStarIDnew + maskfits[i][-17:])
        
        # Add a proper time column
        if df is not None:
            df = pdAddColumn(df, self.time, 'time')
            if args.sample == 'P1': df = df.astype({'time':np.float64, 'iter':int})
            if args.sample == 'P5': df = df.astype({'time':np.float64})
            # Feather format needs to be indiced!
            df = df.reset_index()
            # Save new data frame
            df.to_feather(prefixStarIDnew + '.ftr')

            # Move files to new data directory
            shutil.move(prefixInversion + f'_PRLS_invert.log', prefixStarIDnew + '.invert')
            shutil.move(prefixStarIDsim + f'_starcoord.dat',   prefixStarIDnew + '.cat')
        
        # Remove microscan-starID and simulation folder (and all its content)
        shutil.rmtree(self.microscanDirStarID)
        shutil.rmtree(self.microscanDirInvers)
        shutil.rmtree(self.outputDirStarIDsim)

        # Give full read/write access
        os.system(f'chmod 777 {prefixStarIDnew}*')
        
        # Compress files
        if self.compress:
            if self.verbose > 0:
                print('Compressing files')
            os.system(f'zip -j {prefixStarIDnew}.zip {prefixStarIDnew}* {self.devnull}')
            os.system(f"find {self.outputDirStarIDnew} -type f -not -name '*.zip' -delete {self.devnull}")
            os.system(f'chmod 777 {prefixStarIDnew}.zip')
            
        # Execution time of module
        if self.verbose > 0:
            self.tocPrologue = datetime.datetime.now() - self.tic
            self.tic = datetime.datetime.now()

            
            


    def resources(self):
        """
        Module to print resources used by PLATOnium.
        """
        if not args.plot:
            errorcode('module', '\nSimulation Statistics')
            print(f'Storage memory for PlatoSim      : {self.memPlatoSim} MB')
            print(f'Execution time for PlatoSim      : {self.tocPlatoSim} [hh:mm:ss]')
            if self.sample:
                print(f'Execution time for Microscanning : {self.tocMicroscan} [hh:mm:ss]')
                print(f'Execution time for PSF inversion : {self.tocInversion} [hh:mm:ss]')
                if self.sample == 'P1':
                    print(f'Execution time for L1 On-ground  : {self.tocOnground} [hh:mm:ss]')
                if self.sample == 'P5':
                    print(f'Execution time for L1 On-board   : {self.tocOnboard} [hh:mm:ss]')
                print(f'Execution time for Prologue      : {self.tocPrologue} [hh:mm:ss]')
            print('------------------------------------------------------------')
            print(f'Total execution time             : {datetime.datetime.now() - self.tic0} [hh:mm:ss]\n')

        
#==============================================================#
#               PARSING COMMAND-LINE ARGUMENTS                 #
#==============================================================#

parser = argparse.ArgumentParser(epilog=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter,
                                 description=errorcode('software', '\nPLATOnium Astrophysics'))

parser.add_argument('-p', '--plot',      action='store_true',   help='Flag to plot 1st subfield (this will not save the simulation)')
parser.add_argument('-w', '--overwrite', action='store_true',   help='Flag to overwrite an existing HDF5 output file that may exist')
parser.add_argument('-v', '--verbose', metavar='INT', type=int, help='Verbosity level [0, 1, 3] (Default: 1)')

man_group = parser.add_argument_group('MANDATORY PARAMETERS')
man_group.add_argument('starID',        type=int, help='ID in target list (Use -1 for full frame)')
man_group.add_argument('cameraGroupNr', type=int, help='Either: 1, 2, 3, 4')
man_group.add_argument('cameraNr',      type=int, help='Either: 1, 2, 3, 4, 5, 6')
man_group.add_argument('quarterNr',     type=int, help='Either: 1, 2, 3, 4, 5, 6, 7, 8, ..')

out_group = parser.add_argument_group('I/O PARAMETERS')
out_group.add_argument('-i', '--inDir',  metavar='PATH', type=str, help='Input directory for simulation')
out_group.add_argument('-o', '--outdir', metavar='PATH', type=str, help='Output directory for simulation')
out_group.add_argument('--project',      metavar='NAME', type=str, help='Project folder inside $PLATO_WORKDIR')
out_group.add_argument('--prefix',       metavar='NAME', type=str, help='Prefix extention to default generated name')
out_group.add_argument('--varfile',      metavar='FILE', type=str, help='Path to variable source file -> see PlatoSim docs')
out_group.add_argument('--varlist',      metavar='FILE', type=str, help='Path to variable source list -> see PlatoSim docs')
out_group.add_argument('--compress',     action='store_true',      help='Flag to compress output files')

sim_group = parser.add_argument_group('SIM PARAMETERS')
sim_group.add_argument('--cadence', metavar='SEC', type=float, help='Cadence or cycle time step for each exposure [seconds] (default: 25 s)')
sim_group.add_argument('--tdur',    metavar='DAY', type=float, help='Total lenght of shortened quarter time series [days]')
sim_group.add_argument('--nexp',    metavar='NO.', type=int,   help='Number of exposures of shortened quarter time series')
#obs_group.add_argument('--mexp', metavar='NO.',  type=int, help='Number of equidistant exposures in quarter or shortened time series.')
sim_group.add_argument('--pic',     metavar='ID',  type=int, help='ID from the PIC -> Simulate a specific star in the PIC catalog (Overwrites "starID")')
sim_group.add_argument('--seed',    metavar='INT', type=int,   help='Option to bootstrap seeds in order to reproduce results')
sim_group.add_argument('--mask',    metavar='DAY', type=float, help='Option to alter/overwrite the mask-update in inputfile [days]')
sim_group.add_argument('--reusejitter', action='store_true',   help='Flag to re-use AOCS jitter file across all quarters')

pip_group = parser.add_argument_group('L1 PIPELINE PARAMETERS')
pip_group.add_argument('--sample',   metavar='PIC', type=str, help='PIC sample to activate the correct L0-L1 pipeline chain [P1, P5]')
pip_group.add_argument('--con_dmag', metavar='MAG',     type=float, help='Relative magnitude inclusion threshold for contaminant(s) (Default: 5 mag)')
pip_group.add_argument('--con_ferr', metavar='PERCENT', type=float, help='Flux error assumption for Target')
pip_group.add_argument('--tar_ferr', metavar='PERCENT', type=float, help='Flux error assumption for Contaminant(s)')
pip_group.add_argument('--tar_cerr', metavar='PIXEL',   type=float, help='Centroid error assumption for Target')

args = parser.parse_args()

# Load and run modules
p = PLATOnium(args)
p.load_stars()
p.configure_output()
sim = p.init_sim()
p.create_seeds(sim)
p.create_inputfiles(sim)

if args.plot:
    # Only show imagette
    p.show_subfield(sim)
    
elif args.sample == 'P1':
    # Run the entire on-ground L0-L1 pipeline chain
    p.control_hdf5()
    p.run_sim_normal(sim)
    p.run_microscan(sim)
    p.run_L1_onground()
    p.sort_output()
    
elif args.sample == 'P5':
    # Run the entire on-board L0-L1 pipeline chain
    p.control_hdf5()
    p.run_sim_normal(sim)
    p.run_microscan(sim)
    p.run_L1_onboard()
    p.sort_output()
    
else:
    # Only run PlatoSim time series
    p.run_sim_normal(sim)

# Finito!
if args.verbose != 0:
    p.resources()
