#!/usr/bin/env python3

"""
This PlatoSim class is designed to ease the time series analysis.
The class can be applied to both the HDF5 output files produced
by PlatoSim or the Feather output files generated by PLATOnium
while is use the L1 proto-pipeline to extract the photometry.
"""

import os
import sys
import glob
import h5py
import scipy
import wotan
import shutil
import pathlib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.colors as colors
import statsmodels.api as sm

from scipy import constants as c
from zipfile import ZipFile
from tqdm import tqdm

#from numba import njit
#from numba_progress import ProgressBar

import platosim.plot            as pt
import platosim.utilities       as ut
import platosim.statistics      as st
import platosim.referenceFrames as rf
from platosim.simfile import SimFile

#==============================================================#
#                         BEGIN CLASS                          #
#==============================================================#

class LightCurve(object):

    """Class for PlatoSim photometry and time series analysis.
    
    This class provides the Python interface to an Feather file generated
    by the PLATO Photometric Pipeline that comes with the PlatoSim software.

    Usage example for a single feather file:
        >>> lc1 = LightCurve("000000001_Ncam1.1_Q1.ftr")

    Usage example for a batch of feather files:
        >>> phot = LightCurve("</path/to/files>", "multi")
    """

    def __init__(self, filename, mode="single", ncam=False):

        # Constants
        self.pixelSize = 18  # [micron]
        
        # Matplotlib
        self.aa = 0.5  # Alpha
        self.ms = 3    # MarkerSize
        self.lw = 2    # LineWidth
        
        # Read either a single file or multiple files
        self.mode = mode

        
        # SINGLE-CAMERA SIMULATION
        
        if mode == "single":

            self.filename = filename
            
            # Select Feather output file            
            self.fileExtention = pathlib.Path(filename).suffix

            if self.fileExtention == ".ftr":

                # Simply load file
                self.df = pd.read_feather(filename)

                # No mask updates
                self.mask_updates = np.array([])
                
            elif self.fileExtention == ".hdf5":
                
                # Load HDF5 file
                simfile = SimFile(filename)

                # Fetch light curve
                self.df = simfile.getLightCurve(0)

                # Mask updates
                #self.mask_apertures = simfile.getApertureMask(0)
                self.mask_updates = simfile.getMaskUpdateEvents()
                
            else:
                ut.errorcode("error", "File should be in the format of .ftr or .hdf5!")


        # MULTI-CAMERA SIMULATIONS
                
        elif mode == "multi":

            # Check if data frame or new files    
            if isinstance(filename, pd.DataFrame):
                self.df = filename
            else:
                self.path = filename

                
            # Correct obs info if it's a merged light curve
            self.ncam = ncam                




    def __del__(self):
        """
        PURPOSE: Destructor.
        """

        pass




    def reload(self):
        """
        PURPOSE: Close the file, and reload it. Useful when the file may have changed meanwhile.
        """

        self.hdf5file.close()
        self.hdf5file = h5py.File(self.filename, "r")

        return




    

    def getMaskUpdateEvents(self):

        """Exposure number of all mask updates.
        """
        
        # Fetch mask update events

        return np.array(self.hdf5file["Photometry/Masks/exposureNrOfMaskUpdate"])





    def axesMaskupdates(self, ax):
        """
        This is a small utility that takes an axes object, time points
        from a time series, and the mask-updates given in the same unit
        of time as the time points, and then plots vertical lines for
        every mask-update and quarter marks.
        """

        # Plot occurance of mask update
        mask_updates = self.getMaskUpdateEvents() * 25. / c.day

        # Skip first mask as that's the default one
        for update in mask_updates[1:]:
            if update == 1:
                ax.axvline(x=update, c='k', linestyle=':', linewidth=1, label='Mask updates')
            else:
                ax.axvline(x=update, c='k', linestyle=':', linewidth=1)





    #--------------------------------------------------------------#
    #                      STELLAR CATALOGUE                       #
    #--------------------------------------------------------------#


    def star(self):
        """
        PURPOSE: Function to fetch the info about star.
        """

        #
        print(self.filename)
        exit()
        
        # Fetch info about target star
        cols = ["id", "ra", "dec", "x", "y", "mag", "ccd", "xccd", "yccd", "xfp", "yfp"]
        df = pd.read_csv(filename, delimiter=' ', comment='#', names=cols)


        
    def star_info(self, filename):
        """
        Function to fetch the target star information.
        """
        
        # Fetch info about target star
        cols = ["id", "ra", "dec", "x", "y", "mag", "ccd", "xccd", "yccd", "xfp", "yfp"]
        df = pd.read_csv(filename, delimiter=' ', comment='#', names=cols)

        # Fetch V magnitude
        mag = df["mag"][0]

        # Number of contaminants
        ncon = len(df["id"]) - 1

        # Distance from optical axis [deg]
        f = 247.52 # [mm] 
        rOA = np.rad2deg(rf.gnomonicRadialDistanceFromOpticalAxis(df["xfp"][0], df["yfp"][0], f))
        
        # Intra-pixel position
        xcen = df["x"][0] % 1/2
        ycen = df["y"][0] % 1/2
        rCOB= np.sqrt(xcen**2 + ycen**2)        

        # Loop over contaminants
        SPR = 0
        rcon = 0
        dmag = 0
        n = len(df["mag"])

        if n > 1:

            # Sort after magnitude
            df = df.sort_values(by=["mag"])
            
            # Distance to main contaminant
            rcon = np.sqrt(df["x"].diff()[1]**2 + df["y"].diff()[1]**2)

            # Delta magnitude of main contaminant
            dmag = df["mag"].diff()[1]
            
            # Custom metric to measure the stellar pollution ratio
            for k in range(1, n):
                dm   = np.abs(df["mag"].diff()[k])
                rpix = np.sqrt(df["x"].diff()[k]**2 + df["y"].diff()[k]**2)
                SPR += 1/(1 + dm + rpix)
                # If the contaminants is brighter than the target SPR becomes negative.
                # Here we are only interested in the absolute pollution:
                #if SPR < 0: SPR += 1

        # Finito!   
        return mag, rOA, rCOB, ncon, rcon, dmag, SPR



    #--------------------------------------------------------------#
    #                        VARSOURCE SOURCES                     #
    #--------------------------------------------------------------#


    def varsource(self):
        """
        Function to fetch the noise-less light curve.
        """

        # Get correct path to varsource file
        path = pathlib.Path(self.filename)
        starID   = path.parts[-2]
        sample   = path.parts[-3]
        varpath = path.parents[2] / "varsource" / "P1" / f"varsource_{starID}_components.ftr"

        # Try to open the feather file or else use the ascii file
        try:
            df = pd.read_feather(varpath)
        except FileNotFoundError:
            varpath  = path.parents[2] / "varsource" / "P1" / f"varsource_{starID}.txt"
            df = pd.read_csv(varpath, names=["time", "sum"], sep=" ")
            df["spot"] = np.zeros_like(df["time"].to_numpy())
            df["gran"] = np.zeros_like(df["time"].to_numpy())
            df["puls"] = np.zeros_like(df["time"].to_numpy())
            df["tran"] = np.zeros_like(df["time"].to_numpy())
            df["sum"] = (10**(-df["sum"]/2.5) - 1) * 1e6

        return df



    def varsource_info(self):
        """
        Function to fetch the noise-less light curve.
        """

        # Get correct path to varsource file
        path    = pathlib.Path(self.filename)
        starID  = path.parts[-2]
        sample  = path.parts[-3]
        varpath = path.parents[2] / "varsource" / "P1" / f"varsource_{starID}_parameters.ftr"
        
        return pd.read_feather(varpath)

                
    
    #--------------------------------------------------------------#
    #                          PREPARE DATA                        #
    #--------------------------------------------------------------#


    def files(self, extension="zip", group=False, camera=False, quarter=False, path=None):
        """
        Function fetch all files with a common extention.
        """

        # Set path to files as default
        if path is None: path = self.path

        # Sort after group, camera, or quarter
        if group: G = f"{group}."
        else: G = ""
        if camera: C = f"{camera}_"
        else: C = ""
        if quarter: Q = f"Q{quarter}"
        else: Q = ""

        # Fetch all zip files and sort them
        files = np.sort(glob.glob(f"{path}/*{G}**{C}**{Q}.{extension}"))
        
        return files

    
    

    def unpack(self, files=None):
        """
        Function to unpack all files multi-camera and multi-quarter
        light curves simulated for a single star.
        """

        # Fetch all zip files
        if files is None:
            files = glob.glob(self.path + "/*.zip")

        # Unpack zip files
        for f in files:
            with ZipFile(f, 'r') as unzip:
                unzip.extractall(self.path)



    def remove(self, files=None):
        """
        PURPOSE: Function to remove all files, except for zip files,
                 for certain star folder.
        """

        # Remove all ftr, cat, and invert files
        os.system(f"rm {self.path}/*.ftr")
        os.system(f"rm {self.path}/*.cat")
        os.system(f"rm {self.path}/*.invert")



        
    def quality_flags(self):

        flag = {'0': 'Good data point',
                '1': 'Data downlink',
                '2': 'Quarterly roll',
                '3': 'Safe mode event',
                '4': 'Loss of fine guidance',
                '5': 'Attitude tweak',
                '6': 'Cosmic ray in optimal aperture',
                '7': 'Detector anomaly',
                '8': 'Argabrightening'}
        #256 ['Manual exclude']
        
        return flag
    
                
    
    #--------------------------------------------------------------#
    #                        EXTRACT COLUMNS                       #
    #--------------------------------------------------------------#
        

    def obs(self):
        """
        PURPOSE: Function to fetch the obs information.
        """

        # Distinguish between single camera and multi camera obs
        if self.mode == "single":

            # Get obs info from feather file
            if self.fileExtention == ".ftr":
                filename = pathlib.Path(self.filename).stem
                self.group   = int(filename[14])
                self.camera  = int(filename[16])
                self.quarter = int(filename[19:])
            elif self.fileExtention == ".hdf5":
                self.group   = False
                self.camera  = False
                self.quarter = False
        else:
            self.group   = False
            self.camera  = False
            self.quarter = False

        return self.group, self.camera, self.quarter

    

    
    def time(self, unit="d"):
        """
        PURPOSE: Function fetch the time column.
        """

        # Flux unit
        if   unit == "s": time = self.df["time"]
        elif unit == "h": time = self.df["time"] / c.hour
        elif unit == "d": time = self.df["time"] / c.day
        else: ut.errorcode("error", "No such time unit! Available unit: [s, h, d]")
        
        return time

    

    def flux(self, column="flux", unit="e/s"):
        """
        PURPOSE: Function to fetch the flux column.
        
        This function should be used to fetch the columns:
        flux, flux_err, flux_cor, bg, bg_err

        Note: flux_cor is only available for on-board photometry.
        """
        
        # Flux unit
        #if   unit == "e/exp": flux = self.df[column]
        if   unit == "e/s": flux = self.df[column] / 4.026526
        elif unit == "rel": flux = ut.normalize(self.df[column], factor=1)
        elif unit == "ppt": flux = ut.normalize(self.df[column], factor=1e3)
        elif unit == "ppm": flux = ut.normalize(self.df[column], factor=1e6)
        else: ut.errorcode("error", "No such flux unit! Availble option: [e/s, norm, ppt, ppm]")
        
        return flux



    def flux_med(self, carbox=144, unit="e/s", addColumn=False):
        """
        PURPOSE: Function normalize the input flux and change time units to days. 
        NOTE:    Function tailored to PLATOniums output format, feather.
        """

        # Flux unit
        flux = self.flux(unit=unit)
        
        # Normalize flux and find medina filter
        flux_med = scipy.ndimage.median_filter(flux, carbox)

        # Add column to data frame if requested
        if addColumn: self.df["flux_med"] = flux_med

        return flux_med


        

    
    def cen(self, column="cx", unit="pix"):
        """
        PURPOSE: Function to fetch the imagette X centroid column.
        """

        # Centroid unit
        if   unit == "pix": cen = self.df[column]
        elif unit == "mm":  cen = self.df[column] * self.pixelSize / 1000.0
        elif unit == "rel": cen = self.df[column] - np.mean(self.df[column])
        elif unit == "cen": cen = self.df[column] - 3
        else: ut.errorcode("error", "No such centroid unit! Availble option: [pix, mm, rel, cen]")
        
        return cen




    def xcen_err(self, unit="pix"):
        """
        PURPOSE: Function to fetch the imagette X centroid error column.
        """

        # Centroid unit
        if   unit == "pix": xcen_err = self.df["cx_err"]
        elif unit == "mm":  xcen_err = self.df["cx_err"] * self.pixelSize / 1000.0
        else: ut.errorcode("error", "No such centroid unit! Availble option: [pix, mm]")
        
        return xcen_err

    


    def data(self):
        """
        PURPOSE: Function to fetch the Pandas data frame.
        """
        return self.df


    
    #--------------------------------------------------------------#


    

    #--------------------------------------------------------------#
    #                   MEASURES FROM LIGHT CURVE                  #
    #--------------------------------------------------------------#
        

    def getMAD(self, column="flux", unit="e/s"):
        """
        PURPOSE: Calculates the Median Absolute Deviation of the light curve.
        """

        # Select default unit
        if not unit:
            if   column in set(("flux", "flux_err", "flux_med")): unit = "e/s"
            elif column is set(( "xcen", "yxen")):                unit = "pix"
            else: ut.errorcode("error", "No such column!")
            
        # Fetch column
        if   column == "flux":     array = self.flux(unit=unit)
        elif column == "flux_err": array = self.flux_err(unit=unit)
        elif column == "flux_med": array = self.flux_med(unit=unit)
        elif column == "xcen":     array = self.xcen(unit=unit)
        elif column == "ycen":     array = self.ycen(unit=unit)

        return ut.medianAbsoluteDeviation(array)




    def getRMS(self, column="flux", unit=False):
        """
        PURPOSE: Calculates the Median Absolute Deviation of the light curve.
        """

        # Select default unit
        if not unit:
            if   column in set(("flux", "flux_err", "flux_med")): unit = "e/s"
            elif column is set(( "xcen", "yxen")):                unit = "pix"
            else: ut.errorcode("error", "No such column!")

        # Fetch column
        if   column == "flux":     array = self.flux(unit=unit)
        elif column == "flux_err": array = self.flux_err(unit=unit)
        elif column == "flux_med": array = self.flux_med(unit=unit)
        elif column == "xcen":     array = self.xcen(unit=unit)
        elif column == "ycen":     array = self.ycen(unit=unit)

        return ut.medianAbsoluteDeviation(array)
    
    


    def getNSR(self, column="flux", binhour=1, unit="ppm", influx="e/s"):
        """
        PURPOSE: Calculates the Noise-to-Signal Ratio (NSR) of binned time series.
        """

        # Copy light curve object
        df = self.df.copy()
        
        # Fetch time and flux
        df["time"] = self.time(unit="d")

        # Fetch flux column and force to be ppm for correct NSR
        if influx == "e/s":
            df[column] = self.flux(column=column, unit="ppm")
                
        # Set the binned time scale [days]
        dt = binhour/24.

        # Bin to devide data
        if binhour == 0:
            sigma = df[column].std()
            nbin  = 1
        else:
            nbins = round( (df["time"].max() - df["time"].min()) / dt) + 1
            tbins = np.linspace(df["time"].min(), df["time"].max(), nbins)
            nbin  = len(df[df["time"].between(tbins[0], tbins[1])])
            # Bin data
            flux_dex = df.columns.get_loc(column)
            data  = [df[df["time"].between(tbins[i], tbins[i+1])].to_numpy() for i in range(nbins-1)]
            sigma = np.array([data[i][:,flux_dex].std()  for i in range(len(data))])

        # Find noise-to-signal ratio
        NSR = np.mean(sigma) #/ np.sqrt(nbin)
        
        return NSR


    
    #--------------------------------------------------------------#
    #                           DETRENDING                         #
    #--------------------------------------------------------------#


    
    def detrend(self, model="wotan", method="cosine", window=0.5,
                poly_deg=2, plot=False):
        """
        PURPOSE: Detrend data using a simply polynomial model.

        Parameters
        ----------
        model : wotan, poly
        """

        # Fit Wotan model optimal for transit searches
        if model == "wotan":
            flux_detrend, flux_trend = wotan.flatten(self.df.time/c.day,
                                                     self.df.flux,
                                                     method=method,
                                                     window_length=window,
                                                     return_trend=True,
                                                     robust=True)
            # Convert into ppm
            self.df['flux_trend']   = ut.normalize(flux_trend)
            self.df['flux_detrend'] = (flux_detrend - 1) * 1e6
            
        # Fit polynomial model
        elif model == "poly":
            poly = np.polyfit(self.df.time, self.df.flux, deg=poly_deg)
            flux_trend = np.polyval(poly, self.df.time)

            # Convert to ppm
            self.df['flux_trend']   = ut.normalize(flux_trend)
            self.df['flux_detrend'] = self.df.flux - flux_trend

        # Plot dianostic
        if plot: self.plot_detrend(self.df)

        return self.df
                



    def plot_detrend(self, df, figsize=(9,7)):
        """
        Function to plot a detrended light curve and make a O-C plot.
        """
        
        # Get varsource light curve
        lc_var = self.varsource()
        time_var = lc_var["time"] / c.day
        flux_var = lc_var["sum"]

        # Get detrending [time: days, flux: ppm]
        time = df.time / c.day
        flux_norm   = ut.normalize(df.flux)
        flux_median = scipy.ndimage.median_filter(df.flux_detrend, 144)
        
        # Start plotting
        
        fig, ax = plt.subplots(3, 1, figsize=figsize)

        # Plot simulation and trend
        ax[0].plot(time,  flux_norm/1e3,     '.', c='k', ms=1, alpha=0.2, label='Sim')
        ax[0].plot(time,  df.flux_trend/1e3, '-', c='b', lw=2,            label='Trend')
        ax[0].set_xlim(time.iloc[0], time.iloc[-1])
        ax[0].set_ylabel('Flux [ppt]')

        # Plot detrend and median
        ax[1].plot(time,  df.flux_detrend/1e3, '.', c='k', ms=1, alpha=0.2, label="Detrend")
        ax[1].plot(time,  flux_median/1e3,     '-', c='orange',  lw=0.5,    label="Detrend 1h")
        ax[1].set_xlim(time.iloc[0], time.iloc[-1])
        ax[1].set_ylabel('Flux [ppt]')
        
        # Plot detrend-median,  vs. input
        ax[2].plot(time,     flux_median,   '-', c='orange', lw=0.5)
        ax[2].plot(time_var, flux_var,      '-', c='m',      lw=0.5, label="Input")
        ax[2].plot(time,     df.flux_trend, '-', c='b',      lw=2.0)
        ax[2].set_xlim(time.iloc[0], time.iloc[-1])
        ax[2].set_ylabel('Flux [ppm]')
        ax[2].set_xlabel('Time [days]')
        
        # Labels
        #fig.text(0.005, 0.5, 'Flux [ppm]', va='center', rotation='vertical')
        #for i in range(3): ax[i].legend(ncol=2, loc="upper left")
        
        # Layout
        ax[0].set_xticklabels([])
        ax[1].set_xticklabels([])
        plt.tight_layout(h_pad=0.2, w_pad=0.6)
        
        return fig, ax




    #--------------------------------------------------------------#
    #                      SINGLE CAMERA/QUARTER                   #
    #--------------------------------------------------------------#

    

    def bin(self, binsize=1, time_unit="h", flux_unit="e/s"):
        """
        PURPOSE: Bin data after w.r.t. to the input time scale and cadence.
        """

        # Copy light curve object
        df = self.df.copy()
        
        # Fetch time and flux
        df["time"] = self.time(unit=time_unit) * 86400
        df["flux"] = self.flux(unit=flux_unit)
        
        # Set the binned time scale
        if   time_unit == "s": dt = binsize * 3600
        elif time_unit == "h": dt = binsize * 1
        elif time_unit == "d": dt = binsize * 1/24.
        else: ut.errorcode("error", "No such time unit! Available unit: [s, h, d]")

        # Define bins to devide data
        tbins = np.arange(df["time"].min(), df["time"].max().round(1)+1, binsize)

        # Correct number of bins used when last bin is less than binsize
        if (df["time"].max().round() - tbins[-1] < binsize): 
            nbins = len(tbins) - 1
        else:
            nbins = len(tbins)

        # Save number of data points in each time bin
        self.nbin = len(df[df["time"].between(tbins[0], tbins[1])])
        
        # Bin data
        # TODO Can be done in a better way?
        data = [df[df["time"].between(tbins[i], tbins[i+1])] for i in range(nbins)]
        time     = [data[i]["time"].mean()     for i in range(len(data))]
        flux     = [data[i]["flux"].mean()     for i in range(len(data))]
        sigma    = [data[i]["flux"].std()      for i in range(len(data))]
        # Specific column for P1 and P5 samples
        cols = ["time", "flux", "sigma"]
        if df.columns.str.startswith("flux_err").sum():
            flux_err = [data[i]["flux_err"].mean() for i in range(len(data))]
            cols.append("flux_err")
        if df.columns.str.startswith("flux_cor").sum():
            flux_err = [data[i]["flux_cor"].mean() for i in range(len(data))]
            cols.append("flux_err")
        data = np.transpose([time, flux, sigma, flux_err])
        
        return pd.DataFrame(data, columns=cols)





    

    def remove_outliers(self, plot=False):
        """
        This function use a moving median filter to reject 3 sigma outliers from
        the out-of-eclipsed data. This is done to secure that a simple median
        convolution do not mis-interp sharp and deep transit signatures as outliers.
        Use a 16 point-width moving median to reject 3 sigma outliers.
        """
        # Remove NaN in time:
        df = self.df.copy()

        # Remove NaN
        df = df[~df["time"].isnull()]
        df = df[~df["flux"].isnull()]

        # Remove flagged data:
        index_flag_bad = np.where(qual==0)
        time = time[index_flag_bad]
        flux = flux[index_flag_bad]

        # Mask transits and occultations
        df_mask = self.mask_eclipses(df)

        # Sigma-clipping
        df_clip = self.sigma_clipping(df, df_mask)
        
        # Locata LOCALIZE BAD DATA BY CONVOLUTION:
        #self.time, self.flux = self.locate(self.time, self.flux)

        # Correct data jumps
        df_jump = self.jumps(df_clip)

        # Plot results
        if plot:
            pt.plot_mask(self.ticid, time0, flux0, \
                         self.time_mask_out, self.flux_mask_out, \
                         self.time_mask_tra, self.flux_mask_tra, \
                         self.time_mask_occ, self.flux_mask_occ)




    def jumps(self, gapsize=500):
        """
        This function corrects for jumps larger than "gapsize" in a timeseries. Normally
        ajacent datapoint to a jump is effected, hence, a specified number of points
        of each side of a jump can be removed.
        """
        # Find distances/difference between data points:
        s_diff = np.diff(self.df.flux)
        print(s_dff)
        exit()
        # Find gaps:
        index = np.where(abs(s_diff)>gapsize)[0][:]
        # Move the data when a jump:
        for i in index:
            self.df.flux.iloc[i + 1:] -= s_diff[i]

        return self.df

            
    
    #--------------------------------------------------------------#
    #                       MULTI CAMERA/QUARTER                   #
    #--------------------------------------------------------------#
    


    def merge(self, quarter=False, detrend=False, filename=False):
        """
        Merge light curves from a single star.

        Function to merge multi-cameras and multi-quarter light curves into
        a single pandas data frame. If requested each of light curve can be
        detrended prior to the merge and as default it uses the Wotan is 
        used. This package is good for planet transit searches, however, not
        so much for preserving the stellar signal.

        
        """

        # Open a pandas data frame and write to it
        df_time = pd.DataFrame()
        df_flux = pd.DataFrame()
        df_flux_err = pd.DataFrame()
        df_flag = pd.DataFrame()
        dx = pd.DataFrame()

        # Fetch all zip files
        files    = self.files("ftr")
        numFiles = len(files)
        ncam     = 0
        flag     = 0

        # Loop over each group and camera

        for i in tqdm(range(numFiles), bar_format=ut.tqdm_bar_format()):

            # Get file names
            filename_ftr = files[i][:-3] + "ftr"            

            # Fetch light curve object
            try: lc = LightCurve(filename_ftr)
            except: pass
            else:
                
                # Force a correction
                # TODO remove for future simulations! Fixed in PLATOnium now
                #self.correct_cols(lc, filename_ftr)
                #lc = LightCurve(filename_ftr)

                # Fetch obs info
                G, C, Q = lc.obs()
                
                # Select quarter
                if Q == quarter:
                    ncam += 1
                
                # Flag for negative fluxes (bad behavior of L1 pipeline)
                if lc.flux(unit="e/s").mean() < 1: flag = 1

                # Detrend before merging
                if detrend:
                    df = lc.detrend(window=1.62)
                    time = df.time / c.day
                    flux = df.flux_detrend
                else:
                    time = lc.time(unit="d")
                    flux = lc.flux(unit=flux_unit)
                    
                # Fetch columns
                df_time[f"time_{Q}{G}{C}"] = time
                df_flux[f"flux_{Q}{G}{C}"] = flux
                df_flux_err[f"flux_err_{Q}{G}{C}"] = lc.flux(column='flux_err', unit='ppm')
                    
        # Melt coloumns together
        dx["time"] = df_time.melt()["value"]
        dx["flux"] = df_flux.melt()["value"]
        dx["flux_err"] = df_flux_err.melt()["value"]

        # Sort after logic structure and reset indices
        dx = dx.sort_values(by=["time"])
        dx = dx.reset_index(drop=True)

        # If requested save output file
        if filename:
            dx.to_feather(filename + '.ftr')
        
        # Set a global light curve object
        lc = LightCurve(dx, mode="multi", ncam=ncam)

        return lc, ncam, flag




    
    def analyse_single_camera(self, inputDir, outputFile, numStar):

        # Open a pandas data frame and write to it
        df = pd.DataFrame()
        cols = ["id", "ra", "dec", "x", "y", "mag", "ccd", "xccd", "yccd", "xfp", "yfp"]
        f = 247.52 # [mm] 

        # Loop over star simulated
        for i in tqdm(range(1, numStar+1), bar_format=ut.tqdm_bar_format()):

            # Fetch all zip files
            starID   = f"{i}".zfill(9)
            path     = f"{inputDir}/{starID}"
            files    = self.files(path=path)
            numFiles = len(files)

            # Loop over each group/cam/quarter simulation

            for j in range(numFiles):

                # Extract files
                with ZipFile(files[j], 'r') as unzip:
                    unzip.extractall(path)

                # Get file names
                filename_ftr = files[j][:-3] + "ftr"
                filename_cat = files[j][:-3] + "cat"
                filename_inv = files[j][:-3] + "invert"    

                # Fetch light curve object
                try: lc = LightCurve(filename_ftr)
                except: pass
                else:

                    # Fetch info about observation
                    group, camera, quarter = lc.obs()

                    # Fetch info about contaminants
                    mag, rOA, rCP, ncon, rcon, dmag, SPR = self.star_info(filename_cat)

                    # Force a correction and reload file
                    # TODO remove for future simulations! Fixed in PLATOnium now
                    #self.correct_cols(lc, filename_ftr)
                    #lc = LightCurve(filename_ftr)

                    # Flag for negative fluxes (bad behavior of L1 pipeline)
                    if lc.flux().iloc[0] < 1:
                        flag = 1
                        #print(filename_ftr)
                        #print(lc.data())
                        #exit()
                    else:
                        flag = 0
                    
                    # Fetch NSR from RMS [ppm/sqrt(h)]
                    NSR = lc.getNSR()
                    
                    # Mean centroid error in percent
                    xcen     = lc.xcen()
                    ycen     = lc.ycen()
                    xcen_err = lc.xcen_err()
                    ycen_err = lc.ycen_err()
                    rcen     = np.sqrt(xcen**2 + ycen**2)
                    rcen_err = np.sqrt(xcen_err**2 + ycen_err**2)
                    rcen_err_mean = rcen_err.mean() / rcen.mean() * 100
                    #if rcen_err_mean > 100: rcen_err_mean = 100

                    # Mean flux error in percent
                    flux     = np.abs(lc.flux())
                    flux_err = np.abs(lc.flux_err())
                    flux_err_mean = flux_err.mean() / flux.mean() * 100                
                    #if flux_err_mean > 100: flux_err_mean = 100

                    # Write data to feather
                    data = {"star":i, "group":group, "camera":camera, "quarter":quarter, "mag":mag,
                            "ferr":flux_err_mean, "rerr":rcen_err_mean, "flag":flag,
                            "rOA":rOA, "rCP":rCP, "ncon":ncon, "rcon":rcon, "dmag":dmag,
                            "SPR":SPR, "NSR":NSR}
                    df = df.append(data, ignore_index=True)
                    
                    # Delete unpacked files again to not overflow storage memory
                    os.remove(filename_ftr)
                    os.remove(filename_cat)
                    os.remove(filename_inv)

        # Save final feather
        df = df.astype({"star":int, "group":int, "camera":int, "quarter":int, "mag":np.float32,
                        "rOA":np.float32, "ferr":np.float32, "rerr":np.float32, "flag":int,
                        "rOA":np.float32, "rCP":np.float32, "ncon":int, "rcon":np.float32,
                        "dmag":np.float32, "SPR":np.float32, "NSR":np.float32})

        # Sort data frame
        df = df.sort_values(by=["star", "group", "camera", "quarter"])

        # Set new index and save
        df = df.reset_index()
        df.to_feather(outputFile)




    

    def merge_cameras(self, outputFile, numStar):

        # Open a pandas data frame and write to it
        df = pd.DataFrame()

        # Loop over star simulated

        for i in tqdm(range(1, numStar+1), bar_format=ut.tqdm_bar_format()):

            # Read path
            starID = f"{i}".zfill(9)
            path = f"{self.path}/{starID}/" 

            # Load all feather files
            phot = LightCurve(path, mode="multi")

            # Unpack all zip files in the path folder
            phot.unpack()

            # Check if any data exist for a given star

            try: filename_cat = glob.glob(path + "*.cat")[0]
            except: pass
            else:

                # Fetch star info
                mag, rOA, rCP, ncon, rcon, SPR = self.star_info(filename_cat)
                
                # Loop over each quarter
                
                for q in range(1,9):
                            
                    # Merge all observations for the same quarter 
                    lc, ncam, flag = phot.merge(quarter=q)

                    # Check that any light curve exist for a given quarter
                    if not ncam == 0:

                        # Estimate NSR
                        NSR = lc.getNSR(influx="ppm")

                        # Mean Flux error
                        flux_err = lc.flux_err().abs().mean()

                        # Write data to feather
                        data = {"star":i, "mag":mag, "rOA":rOA, "quarter":q, "ncam":ncam, 
                                "ncon":ncon, "rcon":rcon, "SPR":SPR, "NSR":NSR, "flux_err":flux_err,
                                "flag":flag}
                        df = df.append(data, ignore_index=True)

                # Delete unpacked files again to not overflow storage memory
                for files_ftr in glob.iglob(os.path.join(path, '*.ftr')):    os.remove(files_ftr)
                for files_cat in glob.iglob(os.path.join(path, '*.cat')):    os.remove(files_cat)
                for files_inv in glob.iglob(os.path.join(path, '*.invert')): os.remove(files_inv)

        # Save final feather
        df = df.astype({"star":int, "mag":np.float32,  "rOA":np.float32, "quarter":int, "ncam":int, 
                        "ncon":int, "rcon":np.float32, "SPR":np.float32, "NSR":np.float32,
                        "flux_err":np.float32, "flag":str})

        # Sort data frame
        df = df.sort_values(by=["star", "quarter"])

        # Set new index and save
        df = df.reset_index()
        df.to_feather(outputFile)






    def correct_cols(self, lc, filename_ftr):

        # Fetch data
        df = lc.data()

        # Number of columns to correct
        ncols = df.columns.str.startswith("level").sum()

        # TODO only needed for now!
        # if "level_5" in df.columns:
        if ncols == 6:
            cols = ['flux', 'cx', 'cy', 'bg', 'flux_err', 'cx_err', 'time',
                    'cy_err', 'bg_err', 'chi2', 'iter', 'lamb']
            df = df.iloc[:,:12]
            df.columns = cols
            df.to_feather(filename_ftr)
            
        elif ncols > 0: # in (12, 18, 22, 28):
            cols = ['flux', 'cx', 'cy', 'bg', 'flux_err',
                    'cx_err', 'cy_err', 'bg_err',
                    'chi2', 'iter', 'lamb', 'random1', 'time']
            df = df.iloc[:,:13]
            df.columns = cols
            df.to_feather(filename_ftr)







    def correct_and_save(self, inputDir, outputDir, numStar=False, numBegin=False, numEnd=False):
        """
        """

        # Open a pandas data frame and write to it
        df = pd.DataFrame()


        if numBegin and numEnd:
            start = numBegin
            end   = numEnd + 1
        else:
            start = 1
            end   = numStar + 1
        
        # Loop over star simulated

        for i in tqdm(range(start, end), bar_format=ut.tqdm_bar_format()):

            # Create star folder
            starID = f"{i}".zfill(9)
            path = f"{self.path}/{starID}/" 

            # Load all feather files
            phot = LightCurve(path, mode="multi")
            
            # Unpack all zip files in the path folder
            phot.unpack()

            # Check if any data exist for a given star

            try: filename_cat = glob.glob(path + "*.ftr")[0]
            except: pass
            else:
                
                # Fetch all zip files
                files    = self.files("ftr", path=path)
                numFiles = len(files)

                # Create directory for each star
                starDir = f"{outputDir}/{starID}"
                if not os.path.exists(starDir):
                    os.mkdir(starDir)

                # Loop over each group and camera

                for j in range(numFiles):

                    # Get file names
                    filename     = files[j][-25:]
                    filepath_all = files[j][:-3]
                    filepath_ftr = filepath_all + "ftr"
                    filepath_cat = filepath_all + "cat"
                    filepath_inv = filepath_all + "invert"
                    filepath_zip = filepath_all + "zip"

                    # Fetch light curve object
                    try: lc = LightCurve(filepath_ftr)
                    except: pass
                    else:

                        # Define filepaths
                        filepath_new_zip = f"{outputDir}/{starID}/{filename[:-4]}.zip"
                        filepath_old_all = f"{filepath_ftr} {filepath_cat} {filepath_inv}"
                        
                        # Check if any contaminant are present                        
                        ncon = self.star_info(filepath_cat)[3]

                        if ncon == 0:

                            # Copy the already existing file
                            os.system(f'cp {filepath_zip} {filepath_new_zip}')
                        
                        else:
                        
                            # Force a correction
                            self.correct_cols(lc, filepath_ftr)
                            
                            # Give full access to all files
                            os.system(f'chmod 777 {filepath_old_all}')

                            # Compress to new destination
                            os.system(f"zip -j {filepath_new_zip} {filepath_old_all} > /dev/null")

                            # Give full access to new zip file
                            os.system(f'chmod 777 {filepath_new_zip}')
                        
                        # Remove old files (except for zip file)
                        os.remove(filepath_ftr)
                        os.remove(filepath_cat)
                        try: os.remove(filepath_inv)
                        except: pass








    def bad_files(self, outputFile, numStar=False, numBegin=False, numEnd=False):
        """
        """

        # Open a pandas data frame and write to it
        df = pd.DataFrame()

        if numBegin and numEnd:
            start = numBegin
            end   = numEnd + 1
        else:
            start = 1
            end   = numStar + 1

        # Open file to write to

        with open(outputFile, 'a+') as f:
            
            # Loop over star simulated

            for i in tqdm(range(start, end), bar_format=ut.tqdm_bar_format()):

                # Create star folder
                starID = f"{i}".zfill(9)
                path = f"{self.path}/{starID}/" 

                # Load all feather files
                phot = LightCurve(path, mode="multi")

                # Unpack all zip files in the path folder
                phot.unpack()

                # Check if any data exist for a given star

                try: check = glob.glob(path + "*.ftr")[0]
                except: pass
                else:

                    # Fetch all zip Files
                    files    = self.files("ftr", path=path)
                    numFiles = len(files)

                    # Loop over each group and camera

                    for j in range(numFiles):

                        # Get file names
                        filename     = files[j][-25:]
                        filepath_all = files[j][:-3]
                        filepath_ftr = filepath_all + "ftr"
                        filepath_cat = filepath_all + "cat"
                        filepath_inv = filepath_all + "invert"

                        # Fetch light curve object
                        try: lc = LightCurve(filepath_ftr)
                        except: pass
                        else:

                            # Check if any contaminant are present                        
                            ncon = self.star_info(filepath_cat)[3]
                            
                            if ncon > 0:

                                # Force a correction
                                ncols = df.columns.str.startswith("level").sum()
                                
                                if ncols > 0:

                                    print("works")
                                    # Move read cursor to the start of file.
                                    f.seek(0)
                                    # If file is not empty then append '\n'
                                    if len(f.read(100)) > 0: f.write("\n")
                                    # Append text at the end of file
                                    f.write(f'{filepath_ftr} {ncols}')

                        # Remove old files (except for zip file)
                        os.remove(filepath_ftr)
                        os.remove(filepath_cat)
                        try: os.remove(filepath_inv)
                        except: pass
                        



    #--------------------------------------------------------------#
    #                        APERTURE MASKS                        #   
    #--------------------------------------------------------------#

    def time_limit(self, quarters):

        tmin = (min(quarters) - 1) * 90 - 2
        tmax = (max(quarters)    ) * 90

        return tmin, tmax


    
    def axes_quarter_marks(self):
                
        # Plot quarters
        quarters = np.arange(0, time[-1], 90)
        for Q in quarters:
            if Q == 0:
                ax.axvline(x=Q, c='darkgray', linestyle='-.', linewidth=1, label='Quarter marks')
            else:
                ax.axvline(x=Q, c='darkgray', linestyle='-.', linewidth=1)

                        

    #--------------------------------------------------------------#
    #                         PLOT MODULES                         #   
    #--------------------------------------------------------------#


    def plot_varsource(self, figsize=(9, 8)):
        """
        Function to plot the noise-less light curve.
        """

        # Fetch variable source
        df = self.varsource()

        # Plot varsim plot
        fig, ax = pt.plot_final_lc(df, figsize=figsize)

        return fig, ax



    
    def plot(self, time_unit="d", flux_unit="e/s", legend=True, errorbar=False,
             median_filter=False, binsize=False, cameras=False, quarter=False,
             figsize=(9,5)):
        """
        PURPOSE: Function normalize the input flux and change time units to days. 

        NOTE: Function tailored to PLATOniums output format feather!

        Parameters
        ----------
        time_unit : str
            Array containing at least a time and flux column (and potential flux_err)
        flux_err: boolen
           Wheather or not a flux_err column is present and should thus be added.

        Return
        ------
        data
        """
        #from  platosim.matplotlibrc import setup_paper
        #setup_paper()
        
        # Label for flux
        if   flux_unit == "e/s":  ylab = r"Flux [e$^-$ s$^{-1}$]"
        elif flux_unit == "norm": ylab = "Flux normalized"
        elif flux_unit == "ppt":  ylab = "Flux [ppt]"
        elif flux_unit == "ppm":  ylab = "Flux [ppm]"
        else: ut.errorcode("error", "No such flux unit!")
        
        # Fetch obs infoin range
        if cameras and quarter:
            lab = f"{cameras} N-CAMs, Q{quarter}"
            flux_unit="e/s"
            ylab = "Flux [ppm]"
        else:
            group, camera, quarter = self.obs()
            lab = f"N-CAM {group}.{camera} Q{quarter}"

        # Fetch columns
        time = self.time(unit=time_unit)
        flux = self.flux(unit=flux_unit)
        
        # Create matplotlib object 

        fig, ax = plt.subplots(1, 1, figsize=figsize)
        
        # Plot the input variable source
        if errorbar:
            flux_err = self.flux(column="flux_err", unit=flux_unit)
            ax.errorbar(time, flux, yerr=flux_err, fmt=".", color='k', ecolor='darkgray',
                        elinewidth=1, capsize=0, alpha=0.5, label=lab, zorder=1)
        else:
            ax.plot(time, flux, 'k.', ms=self.ms, alpha=0.2, label=lab, zorder=1)

        # Plot a median filter
        if median_filter:
            flux_med = self.flux_med(unit=flux_unit)
            ax.plot(time, flux_med, '-', c='royalblue', lw=self.lw,
                    label=f'{median_filter}h median', zorder=2)

        # Show binned mean points if requested
        if binsize:
            df = self.bin(binsize=binsize, time_unit=time_unit, flux_unit=flux_unit)
            ax.plot(df["time"], df["flux"], 'o', c='r', ms=8, mec='k',
                    label=f'{binsize}{time_unit} bins', zorder=3)

        # If any plot mask-update events
        if self.mask_updates.any():
            self.cadence = 25
            updates = self.mask_updates * self.cadence / c.day
            for update in updates[1:]:
                if update == updates[-1]:
                    ax.axvline(x=update, c='k', linestyle=':', linewidth=1, label='Mask updates')
                else:
                    ax.axvline(x=update, c='k', linestyle=':', linewidth=1)

        # Set legend
        if legend:
            ax.legend(loc='best')
            
        # Settings
        ax.set_xlim(time.iloc[0], time.iloc[-1])
        ax.set_xlabel(f'Time [{time_unit}]')
        ax.set_ylabel(ylab)
        plt.tight_layout()


        
        # if NSR is not False:

        #     ax1 = fig.add_subplot(2,1,2)
        #     ax1.plot(maskupdates, maskNSR, 'k--', alpha=0.5)
        #     ax1.plot(maskupdates, maskNSR, 'm*', label='Mask update NSR')
        #     ax1.legend(loc='upper right',  fancybox=True)
        #     ax1.set_xlabel('Time [days]')
        #     ax1.set_ylabel(r'NSR [ppm h$^{-1}$]')
        #     ax1.set_xlim(axes_minmax(x=time))

        # if COB is not False:

        #     # Fetch pixel coordinates

        #     rowPix, colPix = f.getStarPositions(1)

        #     # Plot row pixel on left y axis

        #     ax1 = fig.add_subplot(2,1,2)
        #     ax1.plot(time, rowPix, '-', c='darkcyan', label='Row pixel')
        #     ax1.set_ylabel('Row coordinate [pixel]')
        #     ax1.set_xlabel('Time [days]')
        #     ax1.set_title('Star position')
        #     ax1.set_xlim(axes_minmax(x=time))
        #     ax1.legend(loc='upper left')

        #     # Plot column pixel on right y axis

        #     ax2 = ax1.twinx()
        #     ax2.plot(time, colPix, '-', c='hotpink', label='Col pixel')
        #     ax2.set_ylabel('Column coordinate [pixel]')
        #     ax2.set_xlim(axes_minmax(x=time))
        #     ax2.legend(loc='lower right')

        
        return fig, ax
    




    def plot_centroid(self, time_unit="d", cen_unit="pix", figsize=(12,6)):
        """
        PURPOSE: Function normalize the input flux and change time units to days. 

        NOTE: Function tailored to PLATOniums output format feather!

        PARAMETERS
        ----------
        data : pdarray
            Array containing at least a time and flux column (and potential flux_err)
        flux_err: boolen
           Wheather or not a flux_err column is present and should thus be added.

        RETURN
        ------
        data
        """
        # Unit for centroid labels
        if   cen_unit == "pix": lab_unit = "[pixel]" 
        elif cen_unit == "rel": lab_unit = "- Mean [pixel]" 
        elif cen_unit == "cen": lab_unit = "- Center [pixel]"
        elif cen_unit == "mm":  lab_unit = "[mm]" 
        else: ut.errorcode("error", "No such centroid unit! Availble option: [pix, mm, rel, cen]")

        # Convert to days
        time = self.time(unit=time_unit)
        
        # Fetch centroid positions
        xcen = self.xcen(unit=cen_unit)
        ycen = self.ycen(unit=cen_unit)
        
        # Create matplotlib object 
        fig, ax = plt.subplots(1, 1, figsize=figsize)
        
        # Plot the input variable source
        ax.plot(time, xcen, 'b-', alpha=0.7, label="x centroid")
        ax.plot(time, ycen, 'r-', alpha=0.7, label="y centroid")

        # Settings
        ax.set_xlim(time.iloc[0], time.iloc[-1])
        #ax.set_ylim(ycen.iloc[0], ycen.iloc[-1])
        ax.set_xlabel(f'Time - BOL [day]')
        ax.set_ylabel(f'Centroid {lab_unit}')
        ax.legend(loc='best')
        
        # P1 sample has flux errors
        #try: self.df['flux_err'] = ut.normalize(self.df['flux_err'])
        #except: pass 

        return fig, ax



     

    
    
    def plot_multi(self, time_unit="d", flux_unit="e/s", fileExtention="ftr",
                   group=False, camera=False, quarter=False,
                   legend=True, median_filter=False, binsize=False,
                   figsize=(10,6)):
        """
        PURPOSE: Function normalize the input flux and change time units to days. 
        NOTE: Function tailored to PLATOniums output format feather!
        FIXME this function do not work currently

        Parameters
        ----------
        time_unit : str
            Array containing at least a time and flux column (and potential flux_err)
        flux_err: boolen
           Wheather or not a flux_err column is present and should thus be added.

        Return
        ------
        fig, ax : matplotlib objects
        """

        # Fetch all feather filenames
        filenames = self.files(fileExtention, group=group, camera=camera, quarter=quarter)
        nfiles    = len(filenames)

        # Find number of quarters set axes limit
        quarters = np.unique([int(pathlib.Path(filenames[i]).stem[19:]) for i in range(nfiles)])
        
        # Create matplotlib object 
        fig, ax = plt.subplots(1, 1, figsize=figsize)

        # Set colors
        cmap      = plt.get_cmap('nipy_spectral')
        cnorm     = colors.Normalize(vmin=0, vmax=nfiles-1)
        scalarMap = cm.ScalarMappable(norm=cnorm, cmap=cmap)
        ax.set_prop_cycle(color=[scalarMap.to_rgba(i) for i in range(nfiles)])
        
        # Loop over each observation

        for f in filenames:

            # Load single camera obs
            #df = pd.read_feather(f)

            lc = LightCurve(f)

            # Label for flux
            if   flux_unit == "e/s":  ylab = r"Flux [e$^-$ s$^{-1}$]"
            elif flux_unit == "norm": ylab = "Flux normalized"
            elif flux_unit == "ppt":  ylab = "Flux [ppt]"
            elif flux_unit == "ppm":  ylab = "Flux [ppm]"
            else: ut.errorcode("error", "No such flux unit!")
        
            # Fetch obs infoin range
            group, camera, quarter = lc.obs()
            lab = f"N-CAM {group}.{camera} Q{quarter}"

            # Fetch columns and plot
            time = lc.time(unit=time_unit)
            flux = lc.flux(unit=flux_unit)
            ax.plot(time, flux, '.', ms=self.ms, alpha=self.aa, label=lab, zorder=1)
            
        # Set legend
        if legend:
            pos = ax.get_position()
            ax.set_position([pos.x0, pos.y0, pos.width * 0.9, pos.height])
            ax.legend(bbox_to_anchor=(1.24, 1.0), prop={'size': 10})

        # Set title
        #ax.title(f"StarID : {}")
            
        # Settings
        ax.set_xlim(self.time_limit(quarters))
        #ax.set_xlim(time.iloc[0], time.iloc[-1])
        ax.set_xlabel(f'Time [{time_unit}]')
        ax.set_ylabel(ylab)
        plt.show()
            
            # Fetch mask updates
            # mask = f.getPhotometricMask(1)
            # maskupdates.append((mask[2] * 25.) / c.day)  # [days]

            # Save time series to dict
            #cameras['Ncam{}'.format(camera_i)] = [time, flux]

            
            # Compute median carbox filter of output signal
            #maskupdates = np.arange(0, 7*8*maskupdates[0][1], maskupdates[0][1])
            #axes_maskupdates(ax, time, maskupdates)


        return fig, ax








    def plot_oc(self, time_unit="d", figsize=(9,6)):
        """
        Function to plot observed - calculated light curve.
        """

        # Get varsource light curve
        lc = self.varsource()
        itime = lc["time"] / c.day
        iflux = lc["sum"]
        
        # Sorten simulation
        oflux = self.flux(unit="ppm")
        mflux = self.flux_med(unit="ppm")
        
        # Handle time column
        time = self.time(unit=time_unit)

        # Star plotting
        
        fig, ax = plt.subplots(2, 1, figsize=figsize)

        # Plot simulation, median, and input
        ax[0].plot(time,  oflux, '.', c='k', ms=self.ms, alpha=0.2, label='Corrected data')
        ax[0].plot(time,  mflux, '-', c='royalblue', lw=0.5,         label='1h median')
        ax[0].plot(itime, iflux, '-', c='m',         lw=0.5,         label='Input signal')
        ax[0].set_xlim(time.iloc[0], time.iloc[-1])
        ax[0].legend(ncol=3, loc="center",  bbox_to_anchor=(0.5, 1.1))

        # Plot median vs. input
        ax[1].plot(time,  mflux, '-', c='royalblue', lw=0.5)
        ax[1].plot(itime, iflux, '-', c='m',         lw=0.5)
        ax[1].set_xlim(time.iloc[0], time.iloc[-1])

        # Labels
        ax[1].set_xlabel('Time [days]')
        fig.text(0.005, 0.5, 'Flux [ppm]', va='center', rotation='vertical')

        # Layout
        ax[0].set_xticklabels([])
        plt.tight_layout(h_pad=0.2, w_pad=1)
        
        return fig, ax





        

    def plotComparison(self, fig, filenames, medfilt=None, title=None):
        """
        FIXME this function do not work currently

        Parameters
        ----------
        filename : str
            File name of HDF5 file containing photometry

        Retrun
        ------
        fig, ax : matplotlib objects
        """

        # User defined labels

        #title  = 'Drift test: 10.0 mag; All CCD effects ON; Jitter OFF'
        #labels = ['0.0', '0.5', '1.0', '1.5', '2.0', '2.5']

        #title  = 'Drift test: 10.0 mag; All CCD effects ON; Jitter of 0.04 RMS'
        #labels = ['0.1', '2.0', '3.0']

        # title  = 'Jitter test: All CCD effects on & drift off'
        # labels = ['0.00', '0.01', '0.02', '0.03', '0.04', '0.05', '0.06']

        #title  = 'Test of flux decrease: 10.0 mag; WASP-33b hot-Jupiter'
        #labels = ['TE con. + Drift/jitter OFF', 'TE reg. + Drift/jitter OFF', 'TE con. + 2.0/0.04 RMS', 'TE req. + 2.0/0.04 RMS']

        #title  = 'Magnitude test: All CCD effects ON; Drift 2.0 RMS; Jitter 0.04 RMS'
        #labels = ['8.0 mag', '9 mag', '10 mag']

        #title  = 'Test of exoplanet input model: 10.0 mag; Sun + hot-Jupiter'
        #labels = ['Disabled: Drift, Jitter, CTI, and TE']

        #title  = 'Test of exoplanet input model: 10.0 mag; Constant flux'
        #labels = ['Disabled: Drift, Jitter, CTI, and TE', 'Disabled: Drift, Jitter, CTI', 'Disabled: Drift, Jitter']

        #title  = 'Test Photometry: Constant flux; Jitter 0.04 arcsec RMS; TED yaw and pitch = 15 arcsec/quarter, roll from Prime'
        #labels = ['10.0 mag', '11.0 mag']

        # Fetch information about the observation

        n = len(filenames)

        method = 'median'
        maskupdate = 14
        df = 4e4
        aa = 0.2

        # Colvolution filter

        if medfilt is None: medfilt = 144

        # Plot each time series with an offset

        for i in range(n):

            photometryClass = PhotometricFile(filenames[i])
            signals = photometryClass.getPhotometricTimeSeries(1)

            if i == 0: time = signals[0]/c.day  # [days]

            flux = normalize(signals[2]) - df*(i)
            plt.plot(time, flux, 'o', c='k', markersize=1, alpha=aa)

            if method == 'model':

                flux_input = normalize(signals[1]) - df*(i)
                plt.plot(time, flux_input, '-', c=cb[i+1], label=labels[i])
                plt.axhline(y=-i*df, c='gray', linestyle='--', linewidth=1)

            if method == 'median':

                flux_med = median_filter(flux, medfilt)
                plt.plot(time, flux_med, '-', c=cb[i+1], markersize=1, label=labels[i])
                plt.axhline(y=np.median(flux_med[:1000]), c='gray',linestyle='--', linewidth=1)

        # Plot Quarters

        quarters = np.arange(0, time[-1]/(24*3600.), 120)
        for Q in quarters:
            if Q == 0:
                plt.axvline(x=Q, c='darkgray', linestyle='-.', linewidth=1, label='Quarter marks')
            else:
                plt.axvline(x=Q, c='darkgray', linestyle='-.', linewidth=1)

        # Plot mask update occurance

        updates = np.arange(0, 90, maskupdate)
        for update in updates:
            if update == 0:
                plt.axvline(x=update, c='k', linestyle=':', linewidth=1, label='Mask updates')
            else:
                plt.axvline(x=update, c='k', linestyle=':', linewidth=1)

        # Labels

        if title is not None: fig.text(0.5, 0.9, title, ha='center', fontsize=fs)
        plt.legend(loc='upper center', bbox_to_anchor=(0.5, 0.995), fancybox=True, ncol=n+2, fontsize=fs-3)
        plt.xlabel('Time [days]', fontsize=fs-3)
        plt.ylabel('Relative flux [ppm]', fontsize=fs-3)

        # Settings

        plt.xlim(axes_minmax(x=time))
        plt.ylim(-n*df, df)

        # That's it!

        return fig

