#!/usr/bin/env python3

"""
This python module contains plot utilities used in the minimal 
PlatoSim installation and in the extra PLATOnium installation.
"""

# Built-in
import os
import glob

# PlatoSim standard
import natsort
import numpy as np
import pandas as pd
from tqdm import tqdm
from pathlib import Path
import scipy
import scipy.stats as ss
import matplotlib.pyplot as plt
from matplotlib import patches, ticker
from mpl_toolkits.axes_grid1.inset_locator import inset_axes

# PlatoSim imports
import platosim.plot            as pt
import platosim.noise           as ns
import platosim.utilities       as ut
import platosim.referenceFrames as rf                                
from platosim.lightcurve   import LightCurve

# Random number generator
rng = ut.rng(12345)

#---------------------------------------------------------------
#  FUNCTIONS FOR NOTEBOOK: 1. Star catalogues
#---------------------------------------------------------------

# General CaMD cuts
def RG_lower(x): return 1.6*x - 0.6
def RG_upper(x): return 1.6*x - 3.6
def WD_upper(x): return 1.6*x + 3.5
def WD_lower(x): return 1.6*x + 9.5
def SL_upper(x): return -10*x + 8.0
def IMS_line(x): return -12.6*x + 7.76

def CaMD_ellipse(df, star):
    """Function to select all points enclosed within an ellipse.
    """
    cos_angle = np.cos(np.radians(180-star[3]))
    sin_angle = np.sin(np.radians(180-star[3]))
    xc = df.BP_RP - star[0][0]
    yc = df.Mg    - star[0][1]
    xct = xc * cos_angle - yc * sin_angle
    yct = xc * sin_angle + yc * cos_angle 
    rad_cc = (xct**2/(star[1]/2.)**2) + (yct**2/(star[2]/2.)**2)
    indices = np.where(rad_cc <= 1)[0]
    return df.loc[indices]



def spectype_density(col1, df0, idir, cut=25):  
    """Function to generate density maps for each spectral type.
    """ 
    print(f'Generating density map for: {col1}')
    spectype = np.array(['O', 'B', 'A', 'F', 'G', 'K', 'M', 'unknown', 'CSTAR'])
    
    # Generate catalogue for each spectral type
    for i in range(len(spectype)):
        
        # Select each spectral type
        dx = df0[df0.spec == spectype[i]]
        
        # Select cuts to manage dataset
        if spectype[i] in ['A', 'F', 'G', 'K']:
            xx = int(1 + dx.shape[0]/df0.shape[0] * 100)
        else:
            xx = 1
        uu = xx/100 + (cut-1)/100
        print(f'{spectype[i]}: Plot step: {xx}; Density cut: {int(uu*100)} %')
        
        # Fetch densities
        dx = dx.iloc[::xx]
        x, y, z, dex = ut.sortAfterDensity(dx[col1].to_numpy(), dx.BP_RP.to_numpy())
        
        # Remove less dense regions
        dx0 = pd.DataFrame()
        dx0[col1]      = x
        dx0['BP_RP']   = y
        dx0['density'] = z/z.max()
        dx0['dex']     = dex
        dx0['logg']    = dx.logg
        dx0['R']       = dx.R
        dx0['M']       = dx.M
        dx0['L']       = dx.L
        dx0 = dx0[dx0.density > uu]
        
        # Save df to feather
        dx0.reset_index(drop=True, inplace=True)
        dx0.to_feather(f'{idir}/starcat_GaiaDR3_{col1}_SpecType_{spectype[i]}.ftr')
        
        
    
def plot_spectype_density(col1, col2, df0):
    """Create a plot of the density maps generated by 'spectype_density()'.
    """   
    spectype = np.array(['O', 'B', 'A', 'F', 'G', 'K', 'M', 'unknown', 'CSTAR'])
    spectype = spectype.reshape(3,3)
    
    fig, ax = plt.subplots(3, 3, figsize=(8,9))
    for i in range(3):
        for j in range(3): 
            
            # Select smaller subset for fast plotting
            dx = pd.read_feather(f'{idir}/starcat_GaiaDR3_{col1}_SpecType_{spectype[i][j]}.ftr')
            if col1 == 'Teff': dx[col1] /= 1000
            ax[i][j].scatter(dx[col1], dx[col2], c=dx['density'], s=1, alpha=1, cmap="PuOr")
            ax[i][j].set_title(spectype[i][j], fontsize=20)
            ax[i][j].invert_xaxis()
            ax[i][j].invert_yaxis()

    # Settings
    plt.tight_layout(h_pad=0.4, w_pad=0.3)
    fig.text(0.5, 0.98, 'Spectral type', ha='center', fontsize=18)
    fig.text(0.00, 0.5, r'$G_{\rm BP} - G_{\rm RP}$', va='center', 
             rotation='vertical', fontsize=18)
    return fig



def plot_tracks(ax, tracks='mist'):
    """Plot stellar evolutionary tracks.
    This function is very specific for Gaia HRD, ande was made
    to show all the biases in the astrophysical parameters.
    """ 
    # Choose tracks to use
    if tracks == 'cole':
        f1 = f'{path}/tracks/Zini00140/deo_Zini00140_MLT180_Mini'
        f2 = '_fov00050_logDext000.history'
        cols = [0, 1, 3, 4]    
        skip = 6
        zams = 0
        Mini = ['0120', '0150', '0200', '0300', '0400', '0500', '0600', '0700']  
    elif tracks == 'mist':
        f1 = f'{path}/tracks/MIST_v1.2_feh_p0.00_afe_p0.0_vvcrit0.0_EEPS/0'
        f2 = 'M.track.eep'
        cols = [0, 1, 11, 6]
        skip = 12
        zams = 300
        Mini = ['0100', '0200', '0300', '0500', '0700']
        Agee = [11462.4, 1339.614, 458.7, 115.3, 47.4]
    
    # Plot tracks in lopp    
    for mini, agee in zip(Mini, Agee): 
        s = np.loadtxt(f1 + mini + f2, skiprows=skip, usecols=cols)
        age, mass, logT, logL = s[:,0], s[:,1], s[:,2], s[:,3]
        zams = 300
        a = ut.findNearestIndex(age/1e6, agee)
        
        # Correct ages
        if mini in ['0100', '0200']: 
            age_label = f'{float(age[a]/1e9):.1f} Gyr'
        else:
            age_label = f'{float(age[a]/1e6):.1f} Myr'   
        
        # Plot each track
        ax.plot(logT[zams:a], logL[zams:a], '-', c='k', lw=1.2)
        ax.text(logT[a], logL[a], age_label, size=10, rotation=60)
        box = ax.text(logT[zams]+0.01, logL[zams]-0.22, f'{mini[1]}'+r'$M_{\odot}$', size=14)
        box.set_bbox(dict(facecolor='w', alpha=0.7, edgecolor='w'))
        
        
        
def plot_mist_tracks(path, Mini, Agee, xoff=0.007, yoff=-0.07, labels_off=[]):
    """Generic function to plot MIST tracks.
    """
    # Prepare for reading in the tracks
    f1 = f'{path}/tracks/MIST_v1.2_feh_p0.00_afe_p0.0_vvcrit0.0_EEPS/0'
    f2 = 'M.track.eep'
    cols = [0, 1, 11, 6]
    skip = 12
    zams = 300
    
    # Plot tracks in lopp
    n = len(np.array(Mini))
    Teff_zams = np.zeros(n)
    logL_zams = np.zeros(n)
    
    # Plot tracks
    for i, mini, agee in zip(range(n), Mini, Agee): 
        
        # Load track
        s = np.loadtxt(f1 + mini + f2, skiprows=skip, usecols=cols)
        age, mass, logT, logL = s[:,0], s[:,1], s[:,2], s[:,3]
        zams = 300
        a = ut.findNearestIndex(age/1e6, agee)
        string = f'{mini[1]}.{mini[2]}'
        
        # Store ZAMS
        Teff_zams[i] = 10**logT[zams]
        logL_zams[i] = logL[zams]  
        
        # Plot each track
        ax.plot(10**logT[zams:a], logL[zams:a], '-', c='darkslategrey', lw=1.2)
        
        # Plot mass labels
        if string in labels_off:
            pass
        else:
            box = ax.text(10**(logT[zams]+xoff), logL[zams]+yoff, string+r'$M_{\odot}$', size=14)
            box.set_bbox(dict(facecolor='w', alpha=0.5, edgecolor='w'))
    
    # Lastly, plot the ZAMS line
    ax.plot(Teff_zams, logL_zams, '--', c='darkslategrey')
    
    return Teff_zams, logL_zams



def mist_tracks(path, ax, Mini, Agei=202, Agee=600, 
                plot=False, xoff=0.007, yoff=-0.07, labels_off=[]):
    """Generic function to plot MIST tracks.
    """
    # Prepare for reading in the tracks
    f1 = f'{path}/tracks/MIST_v1.2_feh_p0.00_afe_p0.0_vvcrit0.0_EEPS/'
    f2 = 'M.track.eep'
    cols = [0, 1, 11, 6]
    skip = 12
    zams = 202
    tams = 454
    if Agei == 'zams': Agei = zams
    if Agee == 'tams': Agee = tams
    
    # Plot tracks in lopp
    n = len(np.array(Mini))
    Teff_zams = np.zeros(n)
    Teff_tams = np.zeros(n)
    logL_zams = np.zeros(n)
    logL_tams = np.zeros(n)
    Teff_agei = np.zeros(n)
    logL_agei = np.zeros(n)
    
    # Plot tracks
    for i, mini in zip(range(n), Mini): 
        
        # Load track
        s = np.loadtxt(f1 + mini + f2, skiprows=skip, usecols=cols)
        age, mass, logT, logL = s[:,0], s[:,1], s[:,2], s[:,3]
        
        # Store ZAMS
        Teff_zams[i] = 10**logT[zams]
        Teff_tams[i] = 10**logT[tams]
        Teff_agei[i] = 10**logT[Agei]
        logL_zams[i] = logL[zams]  
        logL_tams[i] = logL[tams] 
        logL_agei[i] = logL[Agei]
        
        if plot:
            # Plot each track
            ax.plot(10**logT[Agei:Agee], logL[Agei:Agee], '-', c='darkslategrey', lw=1.2)
        
            # Plot mass labels
            if mini[1] == '0': string = f'{mini[2]}.{mini[3]}'
            else: string = f'{mini[1:3]}'
            if mini in labels_off:
                pass
            else:
                box = ax.text(10**(logT[Agei]+xoff), logL[Agei]+yoff, string+r'$M_{\odot}$', size=14)
                box.set_bbox(dict(facecolor='w', alpha=0.5, edgecolor='w'))
    
    # Lastly, plot the ZAMS line
    if plot:
        ax.plot(Teff_agei, logL_agei, '--', c='darkslategrey')
            
    return Teff_zams, Teff_tams, logL_zams, logL_tams


def mist_tracks_modes(path, ax, Mini, Agei=202, Agee=600, plot=False, log=False, 
                      xoff=0.007, yoff=-0.07, labels_off=[], box_off=False):
    """Generic function to plot MIST tracks.
    """
    # Prepare for reading in the tracks
    f1 = f'{path}/tracks/MIST_v1.2_feh_p0.00_afe_p0.0_vvcrit0.0_EEPS/'
    f2 = 'M.track.eep'
    cols = [0, 1, 11, 6]
    skip = 12
    zams = 202
    tams = 454
    if Agei == 'zams': Agei = zams
    if Agee == 'tams': Agee = tams
    
    # Plot tracks in lopp
    n = len(np.array(Mini))
    Teff_zams = np.zeros(n)
    Teff_tams = np.zeros(n)
    logL_zams = np.zeros(n)
    logL_tams = np.zeros(n)
    Teff_agei = np.zeros(n)
    logL_agei = np.zeros(n)
    
    # Plot tracks
    for i, mini in zip(range(n), Mini): 
        
        # Load track
        s = np.loadtxt(f1 + mini + f2, skiprows=skip, usecols=cols)
        age, mass, logT, logL = s[:,0], s[:,1], s[:,2], s[:,3]
        
        # Store ZAMS
        if log:
            Teff_zams[i] = logT[zams]
            Teff_tams[i] = logT[tams]
            Teff_agei[i] = logT[Agei]
        else:
            Teff_zams[i] = 10**logT[zams]
            Teff_tams[i] = 10**logT[tams]
            Teff_agei[i] = 10**logT[Agei]        
        logL_zams[i] = logL[zams]  
        logL_tams[i] = logL[tams] 
        logL_agei[i] = logL[Agei]
        
        # Plot each track
        if plot:
            if mini[1] == '0': string = f'{mini[2]}.{mini[3]}'
            else: string = f'{mini[1:3]}'
                
            if float(string) < 1.7 and float(string) > 1.5:
                xoff_box = xoff + 0.02
                yoff_box = yoff + 0.1
            elif float(string) < 1.5 and float(string) > 1.3:
                xoff_box = xoff + 0.032
                yoff_box = yoff + 0.14
            elif float(string) < 1.3:
                xoff_box = xoff +0.02
                yoff_box = yoff + 0.14
            else:
                xoff_box = xoff
                yoff_box = yoff
            # Extension of tracks
            if float(string) > 10:
                Agee_track = Agee + 80
            else:
                Agee_track = Agee   
            # Log plot ot not
            if log: 
                Teff = logT[Agei:Agee_track]
                Teff_box = logT[Agei]
            else: 
                Teff = 10**logT[Agei:Agee_track]
                Teff_box = 10**logT[Agei] 
            ax.plot(Teff, logL[Agei:Agee_track], '-', c='darkslategrey', lw=1.2)
            # Plot mass labels
            if mini in labels_off:pass
            else:
                box = ax.text(Teff_box+xoff_box, logL[Agei]+yoff_box, string+r'$M_{\odot}$', size=14)
                if not box_off:
                    box.set_bbox(dict(facecolor='w', alpha=0.5, edgecolor='w')) 

    # Lastly, plot the ZAMS line
    if plot:
        ax.plot(Teff_agei, logL_agei, '--', c='darkslategrey')
            
    return Teff_zams, Teff_tams, logL_zams, logL_tams




def Random_Points_in_Polygon(polygon, number):
    """Generate random point within a polygon.
    """
    from shapely.geometry import Point, Polygon

    points = []
    minx, miny, maxx, maxy = polygon.bounds
    while len(points) < number:
        pnt = Point(np.random.uniform(minx, maxx), np.random.uniform(miny, maxy))
        if polygon.contains(pnt):
            points.append(pnt) 
            
    return points


def IS_gDor(alpha=2):
    """Fetch gDor instability strip from Dupret+2004 (Teff vs. L).
    """    
    if alpha == 2:
        # alpha_MLT=2
        IS_lower = np.array([[3.8351, 0.525], [3.831, 0.75833], [3.821, 1.2], [3.819, 1.35]]).T
        IS_upper = np.array([[3.8275, 1.35], [3.8384, 1.25], [3.851, 1.075], [3.875, 0.775],]).T
    elif alpha == 1.5:
        # alpha_MLT=1.5
        IS_lower = np.array([[3.802, 1.200], [3.801, 1.095], [3.812, 0.695]]).T
        IS_upper = np.array([[3.851, 0.6865], [3.8166, 1.146], [3.809, 1.2]]).T
    elif alpha == 1.0:
        # alpha_MLT=1.0
        IS_lower = np.array([[3.77, 0.983], [3.77, 0.862], [3.777, 0.732]]).T
        IS_upper = np.array([[3.801, 0.783], [3.786, 0.921], [3.777, 0.983]]).T
    Teff_low, Teff_upp = 10**IS_lower[0], 10**IS_upper[0]
    logL_low, logL_upp = IS_lower[1], IS_upper[1]

    return Teff_low, Teff_upp, logL_low, logL_upp
    
    
def plot_IS_gDor(ax, alpha=2.0, c='b', ls='--', log=False, lw=1.5):
    """Plot instability strip from Dupret+2004 to HRD (Teff vs. logL). 
    """
    Teff_low, Teff_upp, logL_low, logL_upp = IS_gDor(alpha=alpha)
    if log:
        ax.plot(np.log10(Teff_low), logL_low, c=c, ls=ls, lw=lw, zorder=5)
        ax.plot(np.log10(Teff_upp), logL_upp, c=c, ls=ls, lw=lw, zorder=5)
    else:
        ax.plot(Teff_low, logL_low, c=c, ls=ls, lw=lw, zorder=5)
        ax.plot(Teff_upp, logL_upp, c=c, ls=ls, lw=lw, zorder=5)
        
        
def IS_dSct():
    """Fetch dSct instability strip from Murphy+2021 (Teff vs. L).
    """ 
    # dSct instability strip from Murphy+2021
    IS_lower = np.array([[7300, 6500], [0.7, 1.4]])
    IS_upper = np.array([[9300, 8500], [1.18, 2.05]])
    return IS_lower, IS_upper  
        
    
def plot_IS_dSct(ax, c='r', ls='--', log=False, lw=1.5):
    """Plot instability strip from Murphy+2021 to HRD (Teff vs. logL). 
    """
    IS_lower, IS_upper = IS_dSct()
    if log:
        ax.plot(np.log10(IS_lower[0]), IS_lower[1], c=c, ls=ls, lw=lw, zorder=5)
        ax.plot(np.log10(IS_upper[0]), IS_upper[1], c=c, ls=ls, lw=lw, zorder=5)
    else:
        ax.plot(IS_lower[0], IS_lower[1], c=c, ls=ls, lw=lw, zorder=5)
        ax.plot(IS_upper[0], IS_upper[1], c=c, ls=ls, lw=lw, zorder=5)

        
def IS_OB(path, modes='g', rot_roche=0):
    """Fetch OB-type stars instability strip from Burssens+2020 (Teff vs. L).
    """ 
    folder = f'{path}/strips'
    # g-mode pulastors
    if modes == 'g':
        if rot_roche == 0:
            name_gmode = 'instability_edges_g_modes_SB19_Z0014.txt'
        elif rot_roche == 25:
            name_gmode = 'instability_edges_g_modes_SB19_Z0014_rot_25_roche.txt'
        elif rot_roche == 50:
            name_gmode = 'instability_edges_g_modes_SB19_Z0014_rot_50_roche.txt'
        data = np.loadtxt(f'{folder}/{name_gmode}', skiprows=1)
    # p-mode pulsators
    if modes == 'p':
        name_pmode = 'instability_edges_p_modes_SB19_Z0014.txt'
        data = np.loadtxt(f'{folder}/{name_pmode}', skiprows=1)
        
    # Order data
    dv = pd.DataFrame()
    dv['Mini'] = data[:,0]
    dv['logT_low'] = data[:,4]
    dv['logT_upp'] = data[:,1]
    dv['logL_low'] = data[:,5]
    dv['logL_upp'] = data[:,2]
    return 10**dv.logT_low, 10**dv.logT_upp, dv.logL_low, dv.logL_upp


def plot_IS_OB(path, ax, modes='g', rot_roche=0, c='b', ls='--', log=False, lw=1.5):
    """Plot instability strip from Burssens+2020 to HRD (Teff vs. logL). 
    """
    Teff_low, Teff_upp, logL_low, logL_upp = IS_OB(path, modes=modes, rot_roche=rot_roche)
    if log:
        ax.plot(np.log10(Teff_low), logL_low, c=c, ls=ls, lw=lw, zorder=5)
        ax.plot(np.log10(Teff_upp), logL_upp, c=c, ls=ls, lw=lw, zorder=5)
    else:
        ax.plot(Teff_low, logL_low, c=c, ls=ls, lw=lw, zorder=5)
        ax.plot(Teff_upp, logL_upp, c=c, ls=ls, lw=lw, zorder=5)
    

def plot_HRD(fig, ax, x, y, c, clab, anchor, cmap='viridis', width="50%", height="3%",
             log=False, vmin=None, vmax=None, ticks=None):
    
    im = ax.scatter(x, y, c=c, s=20, vmin=vmin, vmax=vmax,
                    cmap=cmap, edgecolors='lightgray')
    axins = inset_axes(ax, width=width, height=height, loc="lower left",
                       bbox_to_anchor=anchor, bbox_transform=ax.transAxes)
    cbar = fig.colorbar(im, cax=axins, extend='both', orientation='horizontal',
                        ticks=ticks)
    cbar.set_label(clab, labelpad=3)                                    
    cbar.ax.tick_params()
    cbar.ax.invert_xaxis()
    tick_locator = ticker.MaxNLocator(nbins=5)
    cbar.locator = tick_locator
    cbar.update_ticks()
    if log:
        ax.set_xlabel(r'$\log T_{\rm eff}$ [K]')
    else:
        ax.set_xlabel(r'$T_{\rm eff}$ [K]')
    ax.set_ylabel(r'log $L / L_{\odot}$')
    ax.invert_xaxis()




def get_weight(w, df, ncams=6, N=1500, max_mag=17, max_weight=0.1):   
    """Function to use determine histogram weights to select each camera group.
    """

    # Magnitude range (is 1 element longer)
    mag_hist = w[1][:-1]

    # Weight of histogram (plus custom factor)
    w_hist = 1 / w[0]

    # Replace inf with offset
    w_hist[w_hist == np.inf] = w_hist.min()

    # Normalized weights
    wn_hist = w_hist / w_hist.max()

    # If requested, suppress faint regime
    dex = ut.findNearestIndex(mag_hist, max_mag)
    wn_hist[dex:] = max_weight
        

    # Interpolate weights over magnitude grid
    interpolate = scipy.interpolate.make_interp_spline(mag_hist, wn_hist, k=1)

    # Magnitude grid for interpolation
    mag = np.linspace(mag_hist[0], mag_hist[-1], df[df.ncams == ncams].shape[0])

    # Calculate interpolated weights
    return mag, interpolate(mag)



def fetch_sample(ds, nstars, max_mag=17, max_weight=0.1, seed=None, plot=True):
    """Function to use histogram weights to select each camera group.
    """
    
    # Inspect P magnitudes
    if plot:
        fig, ax = plt.subplots(3, 1, figsize=(8,8))
        N = 30
        w06 = ax[0].hist(ds[ds.ncams ==  6].Pmag, bins=N, histtype='step', label='6',  ec='blue')
        w12 = ax[0].hist(ds[ds.ncams == 12].Pmag, bins=N, histtype='step', label='12', ec='green')
        w18 = ax[0].hist(ds[ds.ncams == 18].Pmag, bins=N, histtype='step', label='18', ec='orange')
        w24 = ax[0].hist(ds[ds.ncams == 24].Pmag, bins=N, histtype='step', label='24', ec='red')
        ax[0].set_ylabel('Count')
        ax[0].set_yscale('log')

    if not isinstance(nstars, list):
        nstars = [nstars, nstars, nstars, nstars]
        
    # Calculate interpolated weights
    mag06, weight06 = get_weight(w06, ds, ncams=6,  N=nstars[0], max_mag=max_mag, max_weight=max_weight)
    mag12, weight12 = get_weight(w12, ds, ncams=12, N=nstars[1], max_mag=max_mag, max_weight=max_weight)
    mag18, weight18 = get_weight(w18, ds, ncams=18, N=nstars[2], max_mag=max_mag, max_weight=max_weight)
    mag24, weight24 = get_weight(w24, ds, ncams=24, N=nstars[3], max_mag=max_mag, max_weight=max_weight)    
    
    # Plot distributions
    if plot:
        ax[1].plot(mag06, weight06, label='6',  c='blue')
        ax[1].plot(mag12, weight12, label='12', c='green')    
        ax[1].plot(mag18, weight18, label='18', c='orange')    
        ax[1].plot(mag24, weight24, label='24', c='red')
        ax[1].set_ylabel('Weight')

    # Seperate stars
    ds06 = ds[ds.ncams ==  6]
    ds12 = ds[ds.ncams == 12]
    ds18 = ds[ds.ncams == 18]
    ds24 = ds[ds.ncams == 24]
    
    # Draw stars from weighted distribution
    if ds06.shape[0] >= nstars[0]: 
        ds06 = ds06.sample(n=nstars[0], weights=weight06, axis=0, random_state=seed)
    if ds12.shape[0] >= nstars[1]: 
        ds12 = ds12.sample(n=nstars[1], weights=weight12, axis=0, random_state=seed)
    if ds18.shape[0] >= nstars[2]:
        ds18 = ds18.sample(n=nstars[2], weights=weight18, axis=0, random_state=seed)
    if ds24.shape[0] >= nstars[3]:
        ds24 = ds24.sample(n=nstars[3], weights=weight24, axis=0, random_state=seed)

    # Conbime entries to new catalogue
    ds = pd.concat([ds06, ds12, ds18, ds24]).reset_index(drop=True)
    
    # Inspect magnitude counts
    if plot:
        ax[2].hist(ds06.Pmag, bins=N, histtype='step', label='6',  ec='blue')
        ax[2].hist(ds12.Pmag, bins=N, histtype='step', label='12', ec='green')
        ax[2].hist(ds18.Pmag, bins=N, histtype='step', label='18', ec='orange')
        ax[2].hist(ds24.Pmag, bins=N, histtype='step', label='24', ec='red')
        ax[2].set_xlabel(r'PLATO magnitude, $P$')
        ax[2].set_ylabel('Count')
        ax[2].legend(loc='best')
        plt.tight_layout();

    return ds


def draw_normal_Z(ds, rng, sigma=2, limit=-2):
    """Draw Z from normal distribution if any value is below -2.0.
    """
    mean = ds.Z.mean()
    sigm = sigma*ds.Z.std()
    dex  = ds[ds.Z < limit].index
    ds.Z.iloc[dex] = rng.normal(mean, sigm, len(dex))
    dex = ds[ds.Z < limit].index
    ds.Z.loc[dex] = 0
    return ds




def spectype_density(col1, df0, idir, cut=25):  
    """Function to generate density maps for each spectral type.
    """ 
    print(f'Generating density map for: {col1}')
    spectype = np.array(['O', 'B', 'A', 'F', 'G', 'K', 'M', 'unknown', 'CSTAR'])
    
    # Generate catalogue for each spectral type
    for i in range(len(spectype)):
        
        # Select each spectral type
        dx = df0[df0.spec == spectype[i]]
        
        # Select cuts to manage dataset
        if spectype[i] in ['A', 'F', 'G', 'K']:
            xx = int(1 + dx.shape[0]/df0.shape[0] * 100)
        else:
            xx = 1
        uu = xx/100 + (cut-1)/100
        print(f'{spectype[i]}: Plot step: {xx}; Density cut: {int(uu*100)} %')
        
        # Fetch densities
        dx0 = dx.iloc[::xx]
        x, y, z, dex = ut.sortAfterDensity(dx0[col1].to_numpy(), dx0.BP_RP.to_numpy())
        
        # Reduced dx
        dxx = dx.iloc[dex]
        
        # Remove less dense regions
        dx0 = pd.DataFrame()
        dx0[col1]      = x
        dx0['BP_RP']   = y
        dx0['density'] = z/z.max()
        dx0['dex']     = dex
        dx0['logg']    = dxx.logg.to_numpy()
        dx0['Z']       = dxx.Z.to_numpy()
        dx0['R']       = dxx.R.to_numpy()
        dx0['M']       = dxx.M.to_numpy()
        dx0['L']       = dxx.L.to_numpy()
        dx0 = dx0[dx0.density > uu]
            
        # Save df to feather
        dx0.reset_index(drop=True, inplace=True)
        dx0.to_feather(f'{idir}/starcat_GaiaDR3_{col1}_SpecType_{spectype[i]}.ftr')
        
        
    
def plot_spectype_density(col1, col2, df0):
    """Create a plot of the density maps generated by 'spectype_density()'.
    """   
    spectype = np.array(['O', 'B', 'A', 'F', 'G', 'K', 'M', 'unknown', 'CSTAR'])
    spectype = spectype.reshape(3,3)
    
    fig, ax = plt.subplots(3, 3, figsize=(8,9))
    for i in range(3):
        for j in range(3): 
            
            # Select smaller subset for fast plotting
            dx = pd.read_feather(f'{idir}/starcat_GaiaDR3_{col1}_SpecType_{spectype[i][j]}.ftr')
            if col1 == 'Teff': dx[col1] /= 1000
            ax[i][j].scatter(dx[col1], dx[col2], c=dx['density'], s=1, alpha=1, cmap="PuOr")
            ax[i][j].set_title(spectype[i][j], fontsize=20)
            ax[i][j].invert_xaxis()
            ax[i][j].invert_yaxis()

    # Settings
    plt.tight_layout(h_pad=0.4, w_pad=0.3)
    fig.text(0.5, 0.98, 'Spectral type', ha='center', fontsize=18)
    fig.text(0.00, 0.5, r'$G_{\rm BP} - G_{\rm RP}$', va='center', 
             rotation='vertical', fontsize=18)
    return fig


#---------------------------------------------------------------
#  FUNCTIONS FOR NOTEBOOK: 2. Variable Signals
#---------------------------------------------------------------


def fetch_lognorm_fit(ampl, show=False):
    grid = 1000

    # Log-norm fit to amplitudes [mag]
    A_range   = np.linspace(0, ampl.max(), grid)
    A_param   = ss.lognorm.fit(ampl)
    A_lognorm = ss.lognorm.pdf(A_range, 
                               A_param[0], 
                               loc=A_param[1], 
                               scale=A_param[2]) + 1e-5
    if show:
        print('Log-normal amplitude coefficients for varsim:\n', A_param)
        
    return A_range, A_lognorm, A_param


#---------------------------------------------------------------
#  FUNCTIONS FOR NOTEBOOK: 4. Simulation statistics
#---------------------------------------------------------------

def fetch_contaminants(path, star='GDOR', batch='affogato', old=False):
    """Fetch the star IDs that has a SPR > 0.
    """
    files_modes = natsort.natsorted(glob.glob(f'{path}/{star}/{batch}/table/*'))
    names_stars = [Path(files_modes[i]).stem[6:] for i in range(len(files_modes))]
    path_table  = f'{path}/{star}/{batch}/table'
    
    ids = []
    for i in tqdm(names_stars, bar_format=ut.tqdmBar()):
        dt = pd.read_feather(f'{path_table}/table_{i}.ftr') 
        if dt.SPR.iloc[0] > 0:
            ids.append(int(i))
    
    # Save and return IDs
    ids = np.array(ids)
    print(f'Number of {star} stars contaminated: {len(ids)}')
    np.savetxt(f'{path}/../../slurm/cluster_varlist_{star}.txt', ids, fmt=['%i'], header='ID')
    
    return ids


def fetch_table(path, star='GDOR', batch='finals_affogato', old=False):
    """Fetch a star's simulation tables and combine to a data frame.
    """
    df0 = pd.DataFrame()
    files = natsort.natsorted(glob.glob(f'{path}/{star}/{batch}/table/*'))
    
    for f in tqdm(files, bar_format=ut.tqdmBar()):
        dx = pd.read_feather(f)
        df1 = pd.DataFrame({
            'ID': [dx.ID.iloc[0]],
            'gaiaDR3': [dx.gaiaDR3.iloc[0]],
            'ra': [dx.ra.iloc[0]],
            'dec': [dx.dec.iloc[0]],
            'Pmag': [dx.mag.iloc[0]],
            'rOA': [dx.rOA.mean()],
            'SPR': [dx.SPR.mean()],
            'ncon': [dx.ncon.iloc[0]],
            'ncam': [int(dx.shape[0]/8)]})
        df0 = pd.concat([df0, df1])
        
    return df0.sort_values(by=['ncam', 'Pmag']).dropna()


def plot_ncam_hist(df, title=None):
    """Plot a N-CAM visibility histogram.
    """
    # Total number of stars after cuts
    fig, ax = plt.subplots(1,1, figsize=(8,5))
    order = df.ncam.unique()
    nstar = df.shape[0]
    df.ncam.value_counts().loc[order].plot.bar(rot=45)
    for p,i in zip(ax.patches, range(1, df.shape[0]+1)):
        if i in [6, 12, 18, 24]:
            dx = 0.97
        else:
            dx = 1
        ax.annotate(str(p.get_height()), (p.get_x()*dx, p.get_height()*1.1))
    if title is not None: ax.set_title(title)
    ax.set_xlabel(r'N-CAM visibility, $n_{\rm CAM}$')
    ax.set_ylabel('Star count')
    ax.set_yscale('log')
    ax.set_ylim(0, nstar/2)
    plt.tight_layout()
    plt.minorticks_off()
    plt.show()


def plot_lc_io(path, star, batch, ID,
               plot_input=True, figsize=(9,5)):
    
    # Choose simulation
    idir = f'{path}/{star}/{batch}'
    starID = f'{ID}'.zfill(9)

    # Fetch final ligth curve
    lc = LightCurve(f'{idir}/lightcurve/lc_{starID}.ftr', mode="final")
    df = lc.data()

    # Load sim table
    dt = pd.read_feather(f'{idir}/table/table_{starID}.ftr')

    # PLOT FINAL LIGHT CURVE

    fig, ax = lc.plot(flux_unit='ppt', median_filter=1, legend=False, figsize=figsize)
        
    # Create varsource from pulsations
    if plot_input:
        dx = pd.read_feather(f'{path}/{star}/varsource/pulsations/pulsations_{starID}_001.ftr')
        dv = pd.DataFrame()
        # Select correct power for signal creation
        if star in ['GDOR', 'SPB']:
            power = 2.2
        else:
            power = 1.0
        # Create data frame
        dv['time'] = df.time / 86400
        dv['dmag'] = ns.timeSeriesFromFourier(dv.time, dx.freq, dx.ampl, dx.phase, power=power)
        dv['flux'] = (10**(-0.4*dv.dmag) - 1) * 1e3
        ax.plot(dv.time, dv.flux, '-', c='orange', lw=0.3)

    ax.set_title(f'Star {int(starID)}: P = {dt.mag[0]:.3f}; NCAM = {int(dt.shape[0]/8)}; ' + 
                 f'SPR = {dt.SPR.mean():.3f}; rOA = {dt.rOA.mean():.2f}');
    return fig, ax


def plot_lc_io_compact(path, star, batch, name, ID, plot_input=True, figsize=(9,5)):

    # Choose simulation
    idir = f'{path}/{star}/{batch}/{name}'
    starID = f'{ID}'.zfill(9)

    # Fetch final ligth curve
    lc = LightCurve(f'{idir}/lightcurve/lc_{starID}.ftr', mode="final")
    df = lc.data()

    # Fetch target catalogue
    dt = pd.read_feather(f'{idir}/table/table_{starID}.ftr')

    # PLOT FINAL LIGHT CURVE
    
    fig, ax = lc.plot(flux_unit='ppt', median_filter=1, legend=False, figsize=(9,5))
    
    # Create varsource from pulsations
    if plot_input:
        dv = pd.read_csv(f'{path}/{star}/varsource/varsource/varsource_WD_{name}.txt', sep=' ', names=['time', 'dmag'])
        dv['time'] = dv.time / 86400
        dv['flux'] = (10**(-0.4*dv.dmag) - 1) * 1e3
        ax.plot(dv.time, dv.flux, '-', c='orange', lw=0.3)
    
    ax.set_title(f'Star {dt.ID[0]}: G = {dt.mag[0]:.3f}; N-CAMs = {int(dt.shape[0]/8)}; ' +
                 f'SPR = {dt.SPR.mean()*100:.2f}\%; rOA = {dt.rOA.mean():.2f}')
    return fig, ax


def ft_io_compact(path, star, batch, name, ID):
    
    # Choose simulation
    idir = f'{path}/{star}/{batch}'
    starID = f'{ID}'.zfill(9)

    # Fetch final ligth curve
    lc = LightCurve(f'{idir}/{name}/lightcurve/lc_{starID}.ftr', mode="final")
    df = lc.data()
    df.time /= 86400
    df.flux *= 1e3
    
    # Load sim table
    dt = pd.read_feather(f'{idir}/{name}/table/table_{starID}.ftr')    

    # Star with ampl [mma]
    star_with_mma_ampl = [
        'pulsations_DAV_TIC033986466.txt',
        'pulsations_DAV_TIC101014997.txt',
        'pulsations_DAV_TIC164772507.txt',
        'pulsations_DBV_TIC257459955.txt',
        'pulsations_DOV_TIC035062562.txt',
    ]

    # Fetch pulsation modes (freq [mhHz], ampl [ppt, mma])
    pfile = f'{path}/{star}/varsource/pulsations/pulsations_{name}.txt' 
    dp = pd.read_csv(pfile)
    dp.freq = ut.muhz2cpd(dp.freq)
    filename = Path(pfile).name
    if filename in star_with_mma_ampl:
        dp['ampl'] = ut.mmag2ppt(dp.ampl)
    dp['phase'] = rng.uniform(0, 2*np.pi, dp.shape[0])
    
    # Fetch and amplitude frequency limits
    flim = pt.getAxesMinMax(x=dp.freq, percentage=10)
    alim = pt.getAxesMinMax(x=dp.ampl, percentage=10)
    if flim[0] < 0: flim = [0, flim[1]]
    
    # Generate variable template
    dv = pd.DataFrame()
    dv['time'] = np.arange(0, 2*ut.year(), 25) / 86400
    dv['flux'] = ns.timeSeriesFromFourier(dv.time, dp.freq, dp.ampl, dp.phase, power=1)

    # Amplitude spectrum of varsource LC
    dv_freq, dv_ampl = ns.astropyLombScargle(dv.time, dv.flux, 
                                             f0=flim[0], 
                                             fn=flim[1], 
                                             df=np.diff(dv.time)[0], 
                                             norm='amplitude') 

    # Amplitude spectrum of varsource LC
    df_freq, df_ampl = ns.astropyLombScargle(df.time, df.flux, 
                                             f0=flim[0], 
                                             fn=flim[1], 
                                             df=np.diff(df.time)[0], 
                                             norm='amplitude') 
    
    # Plot
    title= (f'Star {dt.ID[0]}: G = {dt.mag[0]:.3f}; N-CAMs = {int(dt.shape[0]/8)}; ' +
            f'SPR = {dt.SPR.mean()*100:.2f}\%; rOA = {dt.rOA.mean():.2f}')

    return df_freq, df_ampl, dv_freq, dv_ampl, flim, alim, dt


def plot_ft_io_compact(path, star, batch, name, ID, figsize=(9,5)):
    
    df_freq, df_ampl, dv_freq, dv_ampl, flim, alim, dt = ft_io_compact(path, star, batch, name, ID)
    
    # Plot
    fig, ax = plt.subplots(1,1, figsize=(9,5))
    ax.plot(ut.cpd2muhz(df_freq), df_ampl*2, '-', lw=1, c='k', label='Simulation')
    ax.plot(ut.cpd2muhz(dv_freq), dv_ampl*2, '-', lw=0.3, c='orange', label='Template')
    ax.set_ylabel(r'Amplitude, $A$ [ppt]')
    ax.set_xlabel(r'Frequency, $\nu$ [$\mu$Hz]')
    ax.set_title(f'ID {dt.ID[0]}: ' +  
                 r'$n_{\rm CAM} = $' + f'{int(dt.shape[0]/8)}, ' +
                 r'$G = $' + f'{dt.mag[0]:.1f}, ' +
                 f'SPR = {dt.SPR.mean()*100:.1f}\%, ' +
                 r'$\vartheta_{\rm OA} = $' + f'{dt.rOA.mean():.2f}'+r'$^\circ$')
    ax.set_xlim(ut.cpd2muhz(flim[0]), ut.cpd2muhz(flim[1]))
    ax.set_ylim(0, alim[1])
    ax.legend()
    plt.tight_layout()
    
    return fig, ax


def plot_ft_io_compact_all(path, star, batch, name, figsize=(15, 10)):

    if star == 'WD':
        N = 20
    elif star == 'SDBV':
        N = 12
    n = int(N/4)
    
    fig = plt.figure(figsize=figsize)
    fs = 9
    
    for i in tqdm(range(1,N+1), bar_format=ut.tqdmBar()):
        df_freq, df_ampl, dv_freq, dv_ampl, flim, alim, dt = ft_io_compact(path, star, batch, name, i)
        ax = fig.add_subplot(n,n,i)
        ax.plot(ut.cpd2muhz(df_freq), df_ampl*2, '-', lw=1, c='k', label='Simulation')
        ax.plot(ut.cpd2muhz(dv_freq), dv_ampl*2, '-', lw=0.3, c='orange', label='Template')
        ax.set_title(f'ID {dt.ID[0]}\n' +  
                     r'$n_{\rm CAM} = $' + f'{int(dt.shape[0]/8)}, ' +
                     r'$G = $' + f'{dt.mag[0]:.1f}, ' +
                     f'SPR = {dt.SPR.mean()*100:.1f}\%, ' +
                     r'$\vartheta_{\rm OA} = $' + f'{dt.rOA.mean():.2f}'+r'$^\circ$', 
                     fontsize=fs)
        ax.set_xlim(ut.cpd2muhz(flim[0]), ut.cpd2muhz(flim[1]))
        ax.set_ylim(0, alim[1]+0.15*alim[1])
        plt.xticks(fontsize=fs)
        plt.yticks(fontsize=fs)
    fig.suptitle(f'{name}', size=15)
    fig.text(0.5, 0.17, r'Frequency, $\nu$ [$\mu$Hz]', ha='center')
    fig.text(-0.01, 0.5, r'Amplitude, $A$ [ppt]', va='center', rotation='vertical')
    plt.tight_layout()

    return fig, ax

#---------------------------------------------------------------
#  FUNCTIONS FOR NOTEBOOK: 5. Analysis
#---------------------------------------------------------------

def create_timeseries(ids, idir, odir, power=2.2):
    
    """Function create time series from the pulsation modes.
    """

    # Time array of 2 years
    duration = ut.year() * 2
    time_sec = np.arange(0, duration, 25)
    time_day = np.arange(0, duration/86400, 25/86400)

    for i in tqdm(ids, bar_format=ut.tqdmBar()):

        # Fetch simulation table
        starID = f'{i}'.zfill(9)

        # Check if file exist
        output_dir = Path(f'{odir}/{starID}')
        ofile = output_dir / 'varsource_001.txt'
        #if not ofile.is_file():
        
        # Create varsource from pulsations
        dx = pd.read_feather(f'{idir}/pulsations_{starID}_001.ftr')
        dv = pd.DataFrame()
        dv['time'] = time_sec
        dv['dmag'] = ns.timeSeriesFromFourier(time_day, dx.freq, dx.ampl, dx.phase, power=power)

        # Save light curve
        output_dir.mkdir(parents=True, exist_ok=True)
        data = np.transpose([dv.time, dv.dmag])
        np.savetxt(str(ofile), data, fmt=['%.1f', '%.8f'])




        
def fetch_amplitude_correction(path, PC_name='PC_kepler'):
    
    """Function to fetch the amplitudes before and after the passband correction
    """
    
    folders_parameters = natsort.natsorted(glob.glob(f'{path}/parameters/*'))
    folders_pulsations = natsort.natsorted(glob.glob(f'{path}/pulsations/*'))

    # Load all pulsation modes
    N = len(folders_parameters)
    N_modes = np.zeros(N)
    PC = np.zeros(N)
    df = pd.DataFrame()
    
    for m,i,j in zip(range(N), folders_parameters, tqdm(folders_pulsations, bar_format=ut.tqdmBar())):    

        # Parameter file
        df_parameters = pd.read_feather(i)
        PC[m] = df_parameters[PC_name]

        # Pulsation file
        df_pulsations = pd.read_feather(j)
        n = df_pulsations.shape[0]
        N_modes[m] = n
        df_pulsations['A_PC'] = df_pulsations.ampl / PC[m]

        # Save only pulsation modes
        df = pd.concat([df, df_pulsations[:n]])

    # Convert to mmag
    A_sim = df.ampl * 1e3
    A_PC  = df.A_PC * 1e3
    
    return df, PC, A_sim, A_PC




def match_modes(ID, file_parameters, file_pulsations, file_modes, file_table):

    """Function to match input with output modes detected above BIC/SNR threshold.
    """

    # Load files from for varsource
    dp = pd.read_feather(file_parameters)
    do = pd.read_feather(file_pulsations)
    
    # Load results from simulations
    dt = pd.read_feather(file_table)
    dm = pd.read_feather(file_modes)
    
    # Correct for gamma factor
    do.ampl /= 2.2

    # Convert amplitudes [dmag -> ppm]
    do.ampl = (1 - ut.fromMagToFlux(do.ampl)) * 1e6

    # All modes passed SNR
    dm_all_snr = dm[dm.passed_snr].reset_index(drop=True)
    
    # Fetch input frequencies in pettern [c/d]
    f_i = 1 / np.array([dp.DeltaP0_day * ((1 + dp.slope)**i - 1)/dp.slope + dp.P0_day 
                        for i in range(dp.N_modes[0])])

    # Find indices of matching frequencies
    dex_do = np.array([ut.findNearestIndex(do.freq, f_i[i]) for i in range(dp.N_modes[0])])
    dex_dm = np.array([ut.findNearestIndex(dm.freq, f_i[i]) for i in range(dp.N_modes[0])])

    # print(file_parameters)
    # print(file_pulsations)
    # print(file_table)
    # print(file_modes)    
    # print(dex_do)
    # print(dex_dm)
    # exit()
    
    # Get pattern passed BIC criterion
    do_bic = do.loc[dex_do].reset_index(drop=True)
    dm_bic = dm.loc[dex_dm].reset_index(drop=True)
    
    # Get pattern passed SNR criterion
    do_snr = do_bic[dm_bic.passed_snr].reset_index(drop=True)
    dm_snr = dm_bic[dm_bic.passed_snr].reset_index(drop=True)

    # Compute O-C values [ppm]
    f_oc_bic = (dm_bic.freq.to_numpy() - do_bic.freq.to_numpy())
    f_oc_snr = (dm_snr.freq.to_numpy() - do_snr.freq.to_numpy())
    A_oc_bic = (dm_bic.ampl.to_numpy() - do_bic.ampl.to_numpy())
    A_oc_snr = (dm_snr.ampl.to_numpy() - do_snr.ampl.to_numpy())

    # Remove matches above O-C threshold
    x = 0.0005
    dex_bic = np.where((np.abs(f_oc_bic) > x))[0]
    dex_snr = np.where((np.abs(f_oc_snr) > x))[0]
    dm_bic = dm_bic.drop(index=dex_bic)
    dm_snr = dm_snr.drop(index=dex_snr)
    f_oc_bic = np.delete(f_oc_bic, dex_bic) * 1e6
    f_oc_snr = np.delete(f_oc_snr, dex_snr) * 1e6
    A_oc_bic = np.delete(A_oc_bic, dex_bic)
    A_oc_snr = np.delete(A_oc_snr, dex_snr)

    # Store values into data frame
    df_oc_bic = pd.DataFrame({'freq':dm_bic.freq, 'ampl':dm_bic.ampl,
                              'freq_oc':f_oc_bic, 'ampl_oc':A_oc_bic})
    df_oc_snr = pd.DataFrame({'freq':dm_snr.freq, 'ampl':dm_snr.ampl,
                              'freq_oc':f_oc_snr, 'ampl_oc':A_oc_snr})
    
    # Store in data frame
    dx = pd.DataFrame({'ID': ID,
                       'Pmag': dp.Pmag,
                       'ncam': int(dt.shape[0]/8),
                       'rOA': dt.rOA.mean(),
                       'SPR': dt.SPR.mean(),
                       'N_bic': dm_bic.shape[0],
                       'N_snr': dm_snr.shape[0],
                       'N_input': dp.N_modes[0],
                       'A_max': dm.ampl.max(),
                       'A_limit_bic': dm.ampl.min(), 
                       'A_limit_snr': dm_all_snr.ampl.min(),
                       'A_ampl_bic': dm_bic.ampl.min(),
                       'A_ampl_snr': dm_snr.ampl.min(),
                       'f_rms_bic': ut.rootMeanSquare(f_oc_bic),
                       'f_rms_snr': ut.rootMeanSquare(f_oc_snr),
                       'A_rms_bic': ut.rootMeanSquare(A_oc_bic),
                       'A_rms_snr': ut.rootMeanSquare(A_oc_snr),
                      })
    
    return dx, df_oc_bic, df_oc_snr 





def fetch_all_modes(path, star='GDOR', batch='finals_affogato', old=False):
    
    # files_parameters = natsort.natsorted(glob.glob(f'{path}/{star}/varsource/parameters/*'))
    # files_pulsations = natsort.natsorted(glob.glob(f'{path}/{star}/varsource/pulsations/*'))
    
    # files_table = natsort.natsorted(glob.glob(f'{path}/{star}/{batch}/table/*'))

    files_modes = natsort.natsorted(glob.glob(f'{path}/{star}/{batch}/modes/*'))
    names_stars = [Path(files_modes[i]).stem[6:] for i in range(len(files_modes))]

    path_parameters = f'{path}/{star}/varsource/parameters'
    path_pulsations = f'{path}/{star}/varsource/pulsations'
    path_modes = f'{path}/{star}/{batch}/modes'
    path_table = f'{path}/{star}/{batch}/table'
    
    dx = pd.DataFrame()
    df_bic = pd.DataFrame()
    df_snr = pd.DataFrame()

    for i in tqdm(names_stars, bar_format=ut.tqdmBar()):

        if old:
            file_parameters = f'{path_parameters}/{i}_parameters.ftr'
            file_pulsations = f'{path_pulsations}/{i}_pulsations.ftr'
        else:
            file_parameters = f'{path_parameters}/parameters_{i}_001.ftr'
            file_pulsations = f'{path_pulsations}/pulsations_{i}_001.ftr'

        dx0, df0_bic, df0_snr = match_modes(int(i),
                                            file_parameters,
                                            file_pulsations,
                                            f'{path_modes}/modes_{i}.ftr',
                                            f'{path_table}/table_{i}.ftr')
        dx = pd.concat([dx, dx0])
        df_bic = pd.concat([df_bic, df0_bic])
        df_snr = pd.concat([df_snr, df0_snr])        

    # Sort data and return
    return dx.sort_values(by=['ncam', 'Pmag'])






def plot_percentage_heatmap(dx, mag_min=7.5, mag_max=16.5, col='limit', cmap='rainbow',
                            title=None, clab=None, clim=None, cext=None):

    fig, ax = plt.subplots(1, 1, figsize=(9,5))

    # Plot a detection matrix
    P_bins = np.arange(mag_min, mag_max+1, 1) 
    ncams = [6, 12, 18, 24]
    xlab = P_bins[:-1] + 0.5
    ylab = ncams 
    
    # Create data to be plotted
    if isinstance(dx, pd.DataFrame):
        data = np.zeros((4, len(P_bins)-1))
        for i,n in zip(range(4), ncams):
            dx0 = dx[dx.ncam == n]
            data0 = [dx0[dx0["Pmag"].between(P_bins[i], P_bins[i+1])] for i in range(len(P_bins)-1)]
            if col == 'limit':
                Ebins = [data0[i]["N_snr"].mean() / data0[i]["N_input"].mean() * 100 for i in range(len(data0))]
            elif col == 'N_bic-N_snr':
                Ebins = [data0[i]["N_bic"].mean() - data0[i]["N_snr"].mean() for i in range(len(data0))]
            elif col == 'N_bic-N_snr/N_input':
                Ebins = [(np.mean(data0[i]["N_bic"]/data0[i]["N_input"]) - np.mean(data0[i]["N_snr"]/data0[i]["N_input"])) * 100 for i in range(len(data0))]
            else:
                Ebins = [data0[i][col].mean() for i in range(len(data0))]
            data[i,:] = np.array([Ebins])
    else:
        data = dx

    # Plot data
    if clim:
        im = ax.imshow(data, cmap=cmap, vmin=clim[0], vmax=clim[1])
    else:
        im = ax.imshow(data, cmap=cmap)
    for i in range(len(ylab)):
        for j in range(len(xlab)):
            if col in ['limit', 'phi', 'A_rms_snr', 'f_rms_snr']:
                text = ax.text(j, i, f'{data[i, j]:.1f}', ha="center", va="center", color="k")
            else:
                text = ax.text(j, i, f'{data[i, j]:.2f}', ha="center", va="center", color="k")

    ax.set_xticks(np.arange(len(xlab)), labels=xlab)
    ax.set_yticks(np.arange(len(ylab)), labels=ylab)

    ax.set_xticks(np.arange(data.shape[1] + 1) - 0.5, minor = True)
    ax.set_yticks(np.arange(data.shape[0] + 1) - 0.5, minor = True)
    ax.grid(which='minor', color='k', linestyle='-', linewidth=1) 
    ax.tick_params(which =  "minor", bottom = False, left = False)

    if clim == [0, 100]:
        ticks = [0, 25, 50, 75, 100]
    elif clim == [0, 90]:
        ticks = [0, 30, 60, 90]
    elif clim == [0, 55]:
        ticks = [0, 10, 20, 30, 40, 50]        
    elif clim == [0, 30]:
        ticks = [0, 10, 20, 30]
    elif clim == [40, 95]:
        ticks = [40, 50, 60, 70, 80, 90]        
    else:
        ticks = None

    cbar = plt.colorbar(im, extend=cext, pad=0.02, shrink=0.65, orientation='vertical', ticks=ticks)
    
    if clab:
        cbar.set_label(clab)
        
    ax.set_xlabel('PLATO magnitude, $\mathcal{P}$')
    ax.set_ylabel(r'Camera visibility, $n_{\rm CAM}$')
    
    if title: 
        ax.set_title(title, pad=15)
                
    plt.tight_layout()
    
    return fig, ax, data


