import h5py
import numpy as np

class PhotometricFile (object):

    """
    This class provides the Python interface to an HDF5 file generated by the Plato Photometric Pipeline
    that comes with the PlatoSim software.
    
    Usage examples:
        >>> myFile = PhotometricFile("Phot01.hdf5")
    """


    def __init__(self, filename):

        """
        PURPOSE: Open the HDF5 file.

        INPUT: 
            - filename: String containing the full path of the HDF5 file
        """

        self.filename = filename
        self.hdf5file = h5py.File(filename, "r")





    def __del__(self):

        """
        PURPOSE: Destructor.
        """

        pass





    def reload(self):

        """
        PURPOSE: Close the file, and reload it. Useful when the file may have changed meanwhile.
        """

        self.hdf5file.close()
        self.hdf5file = h5py.File(self.filename, "r")

        return




    
def getOffset(self):

    return np.array(self.hdf5file["/Offset/OffsetValueFastCadence"])




    def getPhotometricTimeSeries(self, targetId):

        """
        PURPOSE: Return time points, input flux, and output flux for the given target star.

        INPUT:
            - targetID: Star ID for the target star for which to return the photometric time series.

        OUTPUT:
            - time: Time points [s]
            - inputFlux: Flux as derived from the input catalogue [photons]
            - outputFlux: Flux as estimated by the photometric pipeline [photons]
        """

        time = np.array(self.hdf5file["/Photometry/Time"])
        numExposures = len(time)

        inputFlux = []
        outputFlux = []

        for exposure in range(numExposures):

            targetIds = np.array(self.hdf5file["/Photometry/Exposure{0:06d}/TargetIDs".format(exposure)])
        
            if targetId in targetIds:

                inputFluxAllTargets = np.array(self.hdf5file["Photometry/Exposure{0:06d}/InputFlux".format(exposure)])
                outputFluxAllTargets = np.array(self.hdf5file["Photometry/Exposure{0:06d}/FluxFastCadence".format(exposure)])

                inputFlux.append(inputFluxAllTargets[np.where(targetIds == targetId)][0])
                outputFlux.append(outputFluxAllTargets[np.where(targetIds == targetId)][0])

        inputFlux = np.array(inputFlux)
        outputFlux = np.array(outputFlux)

        return time, inputFlux, outputFlux