"""
Extract information from the PlatoSim HDF5 output file.

This SimFile class provides a direct interface to extract and inspect the HDF5 output file
that PlatoSim produce upon execution.

For usage see the Jupyter tutorial notebooks available at "PlatoSim/docs/tutorials".
"""

import os
import h5py
import numpy as np
from matplotlib import pyplot as plt
from matplotlib.colors import Normalize, LogNorm
import matplotlib.patches as patches
import ipywidgets as widgets
from astropy.io import fits

from platosim.utilities import imageNorm




class SimFile (object):

    """Class that provides the Python interface to an HDF5 file generated by PlatoSim.

    Usage example:
        >>> f = SimFile("output.hdf5")
    """


    def __init__(self, filename):
        """
        PURPOSE: open the HDF5 file

        INPUT: filename: string containing the full path of the HDF5 file

        OUTPUT: None.
        """

        self.filename = filename
        self.hdf5file = h5py.File(filename, "r")




    def __del__(self):
        """
        PURPOSE: destructor
        """

        pass



    
    def reload(self):
        """
        PURPOSE: close the file, and reload it. Useful when the file may have changed meanwhile.
        """

        self.hdf5file.close()
        self.hdf5file = h5py.File(self.filename, "r")
        return


    
    #--------------------------------------------------------------#
    #                    SIMULATION PARAMETERS                     #
    #--------------------------------------------------------------#


    def getInputParameter(self, groupName, parameterName):

        """
        PURPOSE: Get an input parameter that was read from the Yaml input file and copied into the HDF5 file.
        INPUT: groupName: a parameter group as present in the Yaml input file (e.g. "Platform", "Camera")
               parameterName: name of the input parameter as present in the Yaml input file (e.g. "CycleTime")
        OUTPUT: value of the input parameter
        EXAMPLE: 
            >>> file = SimFile("Simul01.hdf5")
            >>> file.getInputParameter("ObservingParameters", "CycleTime")
            23.0
        """

        return self.hdf5file["/InputParameters/" + groupName].attrs[parameterName]



    

    def getTime(self):

        """
        Returns time points.
        """

        return self.hdf5file["/StarPositions/Time"]

    

    

    def getExposureTime(self):

        """
        Return exposure time.

        OUTPUT:
            - Exposure time [s]
        """

        cycleTime = self.getInputParameter("ObservingParameters", "CycleTime")
        readoutTimeBeforeNextExposure = self.getReadoutTime()[0]

        return cycleTime - readoutTimeBeforeNextExposure


    

    
    def getTimeOffset(self):

        """
        PURPOSE: Fetch offset value of the F-CAMS
        """

        return np.array(self.hdf5file["/Offset/OffsetValueFastCadence"])





    def getReadoutTime(self):

        """Get the CCD readout time.

        Return the readout time before the next exposure starts and the readout
        time during the next exposure.

        OUTPUT:
            - readout time before the next exposure starts [s]
            - readout time during the next exposure [s]
        """

        #encoding = "utf-8"
        # isFastCamera = self.getInputParameter("Telescope", "GroupID").decode(encoding) == "Fast"
        # ccdPosition  = self.getInputParameter("CCD", "Position").decode(encoding)

        isFastCamera = self.getInputParameter("Telescope", "GroupID")
        ccdPosition  = self.getInputParameter("CCD", "Position")

        if ccdPosition == "Custom":

            numRows         = self.getInputParameter("CCD", "NumRows")
            numColumns      = self.getInputParameter("CCD", "NumColumns")
            firstRowExposed = self.getInputParameter("CCD", "FirstRowExposed")

        else:
            if isFastCamera:
                index = int(ccdPosition[0]) - 1
            else:
                index = int(ccdPosition) - 1
            
            numRows    = self.getInputParameter("CCDPositions", "NumRows")[index]
            numColumns = self.getInputParameter("CCDPositions", "NumColumns")[index]

            if isFastCamera:
                firstRowExposed = self.getInputParameter("CCDPositions", "FirstRowForFastCamera")[index]
            else:
                firstRowExposed = self.getInputParameter("CCDPositions", "FirstRowForNormalCamera")[index]

        readoutMode = self.getInputParameter("CCD/ReadoutMode", "ReadoutMode")

        # Unit for serial: # [ns] -> [s], and for parallel: [µs] -> [s]
        serialTransferTime       = self.getInputParameter("CCD", "SerialTransferTime")       * 1e-9
        parallelTransferTime     = self.getInputParameter("CCD", "ParallelTransferTime")     * 1e-6
        parallelTransferTimeFast = self.getInputParameter("CCD", "ParallelTransferTimeFast") * 1e-6
        
        numColumnsBiasMap  = self.getInputParameter("SubField", "NumBiasPrescanColumns")
        numRowsSmearingMap = self.getInputParameter("SubField", "NumSmearingOverscanRows")
        
        #Both detector halves are read out simultaneously
        # -> columns read out by the FEE:
        # 	- half of the CCD
        # 	- serial pre-scan
        # 	- (serial over-scan)
        
        numColumnsReadout = numColumns / 2 + numColumnsBiasMap # + numRowsSerialOverScan
        
        # How many rows will be actually read out by the FEE?
        #  	- nominal mode: image area + parallel over-scan
        #       normal camera: image area = whole CCD
        #       fast camera: image area = lower half of the CCD
        # 	- partial readout: configurable
        # The rest of the image area will be dumped
        
        numRowsReadout = 0
        numRowsDump = 0
        
        #############
        # Fast camera
        #############
        
        if isFastCamera:
            
            # Move the upper half of the CCD down to the lower half, row-by-row
            
            numRowsFrameTransfer = numRows - firstRowExposed
            
            readoutTimeBeforeNextExposure = numRowsFrameTransfer * parallelTransferTimeFast
            
            # The actual readout of the lower half of the CCD (after frame transfer) is done
            # while the next exposure has already started

            # Nominal mode
            
            if readoutMode == "Nominal":
                
                numRowsReadout = firstRowExposed + numRowsSmearingMap
                numRowsDump = 0

            # Partial mode
		    # Rows read out by the FEE: rows in the block (other rows in image area are dumped)
		    # Note: no parallel over-scan

            elif readoutMode == "Partial":

                numRowsReadout = self.getInputParameter("CCD/ReadoutMode/Partial", "NumRowsReadout")
                numRowsDump = firstRowExposed - numRowsReadout
            
            readoutTimeDuringNextExposure = numRowsDump * parallelTransferTimeFast \
                + numRowsReadout * (parallelTransferTime + numColumnsReadout * serialTransferTime)
        
        ###############
        # Normal camera
        ###############

        else:
            
            # Nominal mode (full-frame readout)
            
            if readoutMode == "Nominal":

                # Rows read out by the FEE:
                #  		- rows of image area
                #  		- parallel over-scan
                
                numRowsReadout = numRows + numRowsSmearingMap
                
                # No rows dumped
                
                numRowsDump = 0
            
            # Partial readout
            
            elif readoutMode == "Partial":
                
                # Rows read out by the FEE: rows in the block (other rows in image area are dumped)
                # Note: no parallel over-scan
                
                numRowsReadout = self.getInputParameter("CCD/ReadoutMode/Partial", "NumRowsReadout")
                numRowsDump = numRows - numRowsReadout
            
            readoutTimeBeforeNextExposure = numRowsDump * parallelTransferTimeFast \
				+ numRowsReadout * (numColumnsReadout * serialTransferTime + parallelTransferTime)
            readoutTimeDuringNextExposure = 0

        return readoutTimeBeforeNextExposure, readoutTimeDuringNextExposure

    

    #--------------------------------------------------------------#
    #                          PIXEL MAPS                          #
    #--------------------------------------------------------------#


    def getThroughputMap(self, imageNr):

        """
        Return the throughput map for the given exposure.
        """
        
        return self.hdf5file["/ThroughputMaps/throughputMap{0:06d}".format(imageNr)]



    

    def getSmearingMap(self, exposureNr):
        """
        PURPOSE: extract the smearing map of the given exposure # from the HDF5 file (if present)

        INPUT: exposureNr: integer sequential number of the smearing map

        OUTPUT: smearingMap: 2D numpy array containing the smearing map
        """

        # Construct the smearing map name that was used to store the map

        smearingMapName = "smearingMap{0:06d}".format(exposureNr)

        # Check if the smearing map is in the file. If not: complain, if yes: copy the contents into a numpy array.

        if smearingMapName not in self.hdf5file["SmearingMaps"].keys():

            readoutMode = self["CCD/ReadoutMode/ReadoutMode"]
            if(readoutMode == "Partial"):
                print("Warning: No smearing map created in case of partial readout")
            else:
                print("Error: SimfFile.getSmearingMap(): {0} not in hdf5 file".format(smearingMapName))
            return
        else:
            dataset = self.hdf5file["SmearingMaps"][smearingMapName]
            smearingMap = np.zeros(dataset.shape, dataset.dtype)
            dataset.read_direct(smearingMap)
            return smearingMap




        
    def getBiasMapLeft(self, exposureNr):
        """
        PURPOSE: extract the bias map of the given exposure # 
        from the HDF5 file (if present) for the left detector half

        INPUT: exposureNr: integer sequential number of the bias map

        OUTPUT: biasMap: 2D numpy array containing the bias map
        """

        # Construct the bias map name that was used to store the map

        biasMapName = "biasMap{0:06d}".format(exposureNr)

        # Check if the bias map is in the file:
        # If not: complain,
        # if yes: copy the contents into a numpy array.

        if biasMapName not in self.hdf5file["BiasMapsLeft"].keys():
            print("Error: SimfFile.getBiasMapLeft(): {0} not in hdf5 file".format(biasMapName))
            return
        else:
            dataset = self.hdf5file["BiasMapsLeft"][biasMapName]
            biasMap = np.zeros(dataset.shape, dataset.dtype)
            dataset.read_direct(biasMap)
            return biasMap

        



    def getBiasMapRight(self, exposureNr):

        """
        PURPOSE: extract the bias map of the given exposure from 
        the HDF5 file (if present) for the left detector half

        INPUT: exposureNr: integer sequential number of the bias map

        OUTPUT: biasMap: 2D numpy array containing the bias map
        """

        # Construct the bias map name that was used to store the map

        biasMapName = "biasMap{0:06d}".format(exposureNr)

        # Check if the bias map is in the file:
        # If not: complain,
        # If yes: copy the contents into a numpy array.

        if biasMapName not in self.hdf5file["BiasMapsRight"].keys():
            print("Error: SimfFile.getBiasMapRight(): {0} not in hdf5 file".format(biasMapName))
            return
        else:
            dataset = self.hdf5file["BiasMapsRight"][biasMapName]
            biasMap = np.zeros(dataset.shape, dataset.dtype)
            dataset.read_direct(biasMap)
            return biasMap





    def getPRNU(self):

        """
        PURPOSE: retrieve the Pixel Response Non-Uniformity map from the HDF5 file
                 for the subfield on the CCD that was simulated. 

        INPUT: None

        OUTPUT: 2D float numpy array containing the flatfield map
        """

        # Extract the flatfield map

        dataset = self.hdf5file["Flatfield"]["PRNU"]
        PRNU = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(PRNU)

        # That's it!

        return PRNU





    def getIRNU(self):

        """
        PURPOSE: retrieve the Intra-pixel Response Non-Uniformity map from the HDF5 file
                 for the subfield on the CCD that was simulated

        INPUT: None

        OUTPUT: 2D float numpy array containing the intrapixel flatfield map
        """

        allTimePoints = np.array(self.hdf5file["/StarPositions/Time"])

        colPix = []
        rowPix = []
        xFPmm = []
        yFPmm = []
        time = []

        for k in range(len(allTimePoints)):
            allStarIDsInImage = np.array(self.hdf5file["StarPositions/Exposure{0:06d}/starID".format(k)])
            if starID in allStarIDsInImage:
                colPixOfAllStars  = np.array(self.hdf5file["StarPositions/Exposure{0:06d}/colPix".format(k)])
                rowPixOfAllStars  = np.array(self.hdf5file["StarPositions/Exposure{0:06d}/rowPix".format(k)])
                xFPmmOfAllStars   = np.array(self.hdf5file["StarPositions/Exposure{0:06d}/xFPmm".format(k)])
                yFPmmOfAllStars   = np.array(self.hdf5file["StarPositions/Exposure{0:06d}/yFPmm".format(k)])

                starIndex = np.where(allStarIDsInImage==starID)[0]
                colPix.append(colPixOfAllStars[starIndex])
                rowPix.append(rowPixOfAllStars[starIndex])
                xFPmm.append(xFPmmOfAllStars[starIndex])
                yFPmm.append(yFPmmOfAllStars[starIndex])
                time.append(allTimePoints[k])

        return np.array(time).flatten(), np.array(rowPix).flatten(), np.array(colPix).flatten(),  \
               np.array(xFPmm).flatten(), np.array(yFPmm).flatten()



        
        
    def getImage(self, imageNr):
        """
        PURPOSE: extract the image with seq. nr. 'imageNr' from the HDF5 file (if present)

        INPUT: imageNr: integer sequential number of the image

        OUTPUT: image: 2D numpy array containing the image [ADU]
        """

        # Construct the image name that was used to store the image

        imageName = "image{0:06d}".format(imageNr)

        # Check if the image is in the file

        if imageName not in self.hdf5file["Images"].keys():
            print("Error: SimfFile.getImage(): {0} not in hdf5 file".format(imageName))
            return
        else:
            dataset = self.hdf5file["Images"][imageName]
            image = np.zeros(dataset.shape, dataset.dtype)
            dataset.read_direct(image)
            return image 





    def getImagette(self, starID, imageNr, radius=2):

        """
        PURPOSE: returns a small square imagette around a specified star in a specified image.

        INPUT: starID: integer star identifier. Equals the line number of the star in the input 
                       star catalog (counting from 0). 
               imageNr: integer sequential number of the image in the HDF5 file
               radius: output imagette has size 2*radius+1 pixels in both x and y direction. [pixels]

        OUTPUT: imagette: float numpy array, rectangular imagette.
                          if pixel coordinates of the star are x and y, then imagette is extracted as
                          image[x-radius:x+radius+1, y-radius:y+radius+1]
        """

        # Construct the image name that was used to store the image

        imageName = "image{0:06d}".format(imageNr)

        # Check if the image is in the file. If not: complain, if yes: copy the contents into a numpy array.

        if imageName not in self.hdf5file["Images"].keys():
            print("Error: SimfFile.getImagette(): {0} not in hdf5 file".format(imageName))
            return None
        else:
            dataset = self.hdf5file["Images"][imageName]
            image = np.zeros(dataset.shape, dataset.dtype)
            dataset.read_direct(image)
        

        # Get a list of the stars visible in the subimage and their coordinates
        # Check if our star is in this list. If not, complain.

        IDs, row, col, Xmm, Ymm, flux = self.getStarCoordinates(imageNr)
        if starID not in IDs:
            print("Error: SimfFile.getImagette(): star {0} not in image {1}".format(starID, imageName))
            return None

        # Get the pixel coordinates of our star, and use it to construct the imagette borders

        rowStar     = row[IDs == starID][0]
        columnStar  = col[IDs == starID][0]
        rowBegin    = max(0, int(np.round(rowStar - radius)))
        columnBegin = max(0, int(np.round(columnStar - radius)))
        rowEnd      = min(image.shape[0], int(np.round(rowStar + radius + 1)))
        columnEnd   = min(image.shape[1], int(np.round(columnStar + radius + 1)))

        # Extract the imagette

        imagette = image[rowBegin:rowEnd, columnBegin:columnEnd]

        # That's it!

        return imagette



        

    def getSubPixelImage(self, exposureNr):

        """
        PURPOSE: extract the subpixel image (if present) 
        with seq. nr. 'exposureNr' from the HDF5 file

        INPUT: exposureNr: integer sequential number of the subpixel image

        OUTPUT: subPixelImage: 2D numpy array containing the sub-pixel image [electrons]
        """

        # Construct the subpixel image name that was used to store the subpixel image

        subPixelImageName = "subPixelImage{0:06d}".format(exposureNr)

        # Check if the subpixel image is in the file. If not: complain, if yes: copy the contents into a numpy array.

        if "SubPixelImages" not in self.hdf5file:
            print("Error: SimFile.getSubPixelImage(): there is no SubPixelImages group in the HDF5 file")
        else:
            if subPixelImageName not in self.hdf5file["SubPixelImages"]:
                print("Error: SimfFile.getSubPixelImage(): {0} not in hdf5 file".format(subPixelImageName))
                return
            else:
                dataset = self.hdf5file["SubPixelImages"][subPixelImageName]
                subPixelImage = np.zeros(dataset.shape, dataset.dtype)
                dataset.read_direct(subPixelImage)
                return subPixelImage 




            
    def getPSF(self, datasetName):

        """
        PURPOSE: extract the PSF from the HDF5 file (if present)

        INPUT:   the PSF name: "rebinnedPSFpixel", "rebinnedPSFsubPixel", "rotatedPSF" or "diffusedPSF"
                 where rotatedPSF is at subpixel level.

        OUTPUT:  psf: 2D numpy array containing the image
        """


        # Check if the image is in the file. If not: complain, if yes: copy the contents into a numpy array.

        if datasetName not in self.hdf5file["PSF"].keys():
            print("Error: SimfFile.getPsf(): {0} not in hdf5 file".format(datasetName))
            return
        else:
            dataset = self.hdf5file["PSF"][datasetName]
            image = np.zeros(dataset.shape, dataset.dtype)
            dataset.read_direct(image)
            return image 






    def getImages(self, imageNr=False):
        """
        PURPOSE: extract the image with seq. nr. 'imageNr' from the HDF5 file (if present)

        INPUT: imageNr: integer sequential number of the image

        OUTPUT: image: 2D numpy array containing the image [ADU]
        """

        # Construct the image name that was used to store the image

        imageName = "image{0:06d}".format(0)

        # Check if the image is in the file

        if imageName not in self.hdf5file["Images"].keys():
            print("Error: SimfFile.getImage(): {0} not in hdf5 file".format(imageName))
            return
        else:
            # Fetch images names
            imgNames = list(self.hdf5file["Images"].keys())
            # Create numpy data cube
            nimg = len(imgNames)
            nrow = self.hdf5file["InputParameters/SubField"].attrs["NumRows"]
            ncol = self.hdf5file["InputParameters/SubField"].attrs["NumColumns"]
            cube = np.zeros((nimg, nrow, ncol))
            for i in range(nimg):
                cube[i,:,:] = np.array(self.hdf5file["Images"][imgNames[i]])
            return cube 



        

    #--------------------------------------------------------------#
    #                         SAVE PIXEL MAPS                      #
    #--------------------------------------------------------------#


    def saveHighResolutionPSFtoFITS(self, FITSfileName):
        """
        In case of the analytic non-Gaussian PSF, a high-resolution PSF corresponding to the center
        of the subfield is stored in the HDF5 file. Extract this image and save it to a FITS file
        This function will fail when PlatoSim was not run with an analytic non-Gaussian PSF.
        """

        imageName = "HighResPSFmapCenterSubfield"
        if imageName not in self.hdf5file["PSF"].keys():
            print("Error: Could not find PSF/{0} in HDF5 file")
            return None
        else:
            dataset = self.hdf5file["PSF"][imageName]
            image = np.zeros(dataset.shape, dataset.dtype)
            dataset.read_direct(image)
            hduList = [fits.PrimaryHDU(image)]
            myFits = fits.HDUList(hduList)
            myFits.writeto(FITSfileName)




            
    def saveImagesToFITS(self, fileName):
        """
        Save all subfield images in the HDF5 file to a FITS file with the given file name.
        This will go horribly wrong when the number of images is too large or when the images 
        themselves are too large.
        """

        hduList = []
        Nimages = self.getInputParameter("ObservingParameters", "NumExposures")
        for imageNr in range(Nimages):
            image = self.getImage(imageNr)
            imageName = "Image{0:06d}".format(imageNr)
            if imageNr == 0:
                hdu = fits.PrimaryHDU(image)
            else:
                hdu = fits.ImageHDU(image, name=imageName)
            hduList.append(hdu)
        
        myFits = fits.HDUList(hduList)
        myFits.writeto(fileName)





    def saveSmearingMapsToFITS(self, fileName):
            """
            Save all smearing maps in the HDF5 file to a FITS file with the given file name.
            This will go horribly wrong when the number of exposures is too large or when the maps 
            themselves are too large.
            """

            hduList = []
            Nimages = self.getInputParameter("ObservingParameters", "NumExposures")
            for imageNr in range(Nimages):
                image = self.getSmearingMap(imageNr)
                imageName = "SmearingMap{0:06d}".format(imageNr)
                if imageNr == 0:
                    hdu = fits.PrimaryHDU(image)
                else:
                    hdu = fits.ImageHDU(image, name=imageName)
                hduList.append(hdu)
            
            myFits = fits.HDUList(hduList)
            myFits.writeto(fileName)





    def saveBiasMapsLeftToFITS(self, fileName):
            """
            Save all bias maps in the HDF5 file to a FITS file with the given file name.
            This will go horribly wrong when the number of exposures is too large or when the maps 
            themselves are too large.
            """

            hduList = []
            Nimages = self.getInputParameter("ObservingParameters", "NumExposures")
            for imageNr in range(Nimages):
                image = self.getBiasMapLeft(imageNr)
                imageName = "BiasMap{0:06d}".format(imageNr)
                if imageNr == 0:
                    hdu = fits.PrimaryHDU(image)
                else:
                    hdu = fits.ImageHDU(image, name=imageName)
                hduList.append(hdu)
            
            myFits = fits.HDUList(hduList)
            myFits.writeto(fileName)
            
            
            
            
            
    def saveBiasMapRightToFITS(self, fileName):
            """
            Save all bias maps in the HDF5 file to a FITS file with the given file name.
            This will go horribly wrong when the number of exposures is too large or when the maps 
            themselves are too large.
            """

            hduList = []
            Nimages = self.getInputParameter("ObservingParameters", "NumExposures")
            for imageNr in range(Nimages):
                image = self.getBiasMapRight(imageNr)
                imageName = "BiasMap{0:06d}".format(imageNr)
                if imageNr == 0:
                    hdu = fits.PrimaryHDU(image)
                else:
                    hdu = fits.ImageHDU(image, name=imageName)
                hduList.append(hdu)
            
            myFits = fits.HDUList(hduList)
            myFits.writeto(fileName)


        
        
    #--------------------------------------------------------------#
    #                         PLOT FUNCTIONS                       #
    #--------------------------------------------------------------#

    
    def showImage(self, imageNr=False, clipPercentile=5.0, imgScale="clip",
                  showStarPositions=False, showPointLikeGhostPositions=False,
                  minVmag=None, maxVmag=None, showStarIDs=False,
                  tarMarkerSize=200, showMaskOfStarID=None,
                  useTitle=False, showGrid=False, colorBar=False, colorMap="hot",
                  origin="lower", figsize=(7,7), fontSize=15):

        """Make a plot of the a requested image or the entire cube in HDF5.

        Parameters
        ----------
        imageNr: False, int
            False : Will plot all images in HDF5 using a slider
            int   : Integer sequential number of the image in the HDF5 file
        clipPercentile: int, float
            Intensities will be clipped between [value, 100-value] to improve the image contrast.
        showStarPositions: bool
            False : Default
            True  : Plot the average star positions (averaged over the exposure) 
            "PIC" : Differentiate between a target and contaminants (useful for imagettes)
        showPointLikeGhostPositions: bool
            False : Default
            True  : Plot the average pointlike ghost position (averaged over the exposure)
        minVmag: int, float
            The minimum V magnitude of the stars/ghosts for which the position should be plotted.
            Only relevant if either showStarPositions or showPointLikeGhostPositions is True.
        maxVmag: int, float
            The maximum V magnitude of the stars/ghosts for which the position should be plotted.
            Only relevant if either showStarPositions or showPointLikeGhostPositions is True.
        showStarIDs: bool
            Put small labels with the star IDs next to the star positions
            Will only be executed if showStarPositions=True is set.
        showMaskOfStarID: bool
            Draw rectangles around the pixels of the mask that is used to extract the flux
            value of the star with the given ID. Only works if photometry was activated
            in the yaml inputfile.
        useTitle: bool, str
            False : Default
            True  : Show a default image title of the star ID
            str   : Provide custom title as a string
        colorMap: str
            Option to select your preferred colormap from the matplotlib library.
            Default is the colormap "hot".
        showGrid: bool -> False
            option to select a dim gray grid for a higher visibility of teh pixel grid.
            Will only be executed if showGrid=True is set.
        
        Return
        ------
        fig, ax : object
            Axes matplotlib.pyplot handle objects to modify plot

        Example
        -------
            >>> simfile = SimFile("Simul01.hdf5")
            >>> simfile.showImage(23)
        """

        # As default, add slider if all images are requested
        # Else get the requested image from the HDF5 file
        
        if not imageNr:
            images = self.getImages()
            image = images[0]
            Nimg = images.shape[0]
            Nrows, Ncols = image.shape
            
        else:
            image = self.getImage(imageNr)
            if image is None:
                ut.errorcode(f"Cannot extract image nr {imageNr}")
            Nrows, Ncols = image.shape

        # Plot the image. Note that pixel coordinates start at the left bottom side of each pixel.

        fig = plt.figure(figsize=figsize)
        ax = fig.add_subplot(111)

        # Add ticks
        ax.tick_params(axis='both', which='major', labelsize=fontSize)
        ax.tick_params(axis='both', which='minor', labelsize=fontSize)

        # Show image either using clip-procentage scaling or linear scaling if using a colorbar
        # The large dynamic range of the pixel values often results in images where only
        # the brightest stars are visible. To improve the contrast, clip the color mapping.
        
        if imgScale == "clip":
            clabel = "Counts [ADU]"
            vmin   = np.percentile(image, clipPercentile).astype(int)
            vmax   = np.percentile(image, 100-clipPercentile).astype(int)
            norm   = Normalize(vmin, vmax)
                        
        elif imgScale == "minmax":
            image  = image/1e3
            clabel = "Counts [kADU]"
            vmin   = image.min() 
            vmax   = image.max()
            norm   = Normalize(vmin, vmax)
            
        elif imgScale == 'log':
            clabel = "Count [ADU]"
            vmin   = image.min() 
            vmax   = image.max()
            norm   = LogNorm(vmin, vmax)

        elif imgScale == "auto":
            clabel = "Norm. Count"
            image = imageNorm(image, "linear", sigma=0.5)
            vmin, vmax = image.min(), image.max()
            norm  = Normalize(vmin, vmax)

        else:
            print("Not valid scaling for imgScale!"); exit()

        # Generate image

        if imgScale == "clip":
            imagePlot = ax.imshow(image, cmap=colorMap, interpolation="nearest",
                                    origin=origin, extent=[0, Nrows, 0, Ncols], zorder=0)
            imagePlot.set_clim(vmin, vmax)
        else:
            imagePlot = ax.imshow(image, norm=norm, cmap=colorMap, interpolation="nearest",
                                    origin=origin, extent=[0, Nrows, 0, Ncols], zorder=0)

        # Add colorbar if requested
        
        if colorBar:
            cbar = fig.colorbar(imagePlot, extend='max', shrink=0.84, pad=0.015)
            cbar.set_label(clabel, fontsize=fontSize, labelpad=3)
            cbar.ax.tick_params(labelsize=fontSize)

        # If requiered, overplot a gray semi-transparent grid
        # Note: this is only meaningsful for smaller imagettes

        if showGrid is True:
            ax.grid(c='gray', ls='-', alpha=0.5, zorder=1)

        # Overplot rectangles over those pixels that are part of the mask
        # Note: imshow reverses rows and columns

        if showMaskOfStarID is not None:
            rowIndices, colIndices, _, _, _ = self.getPhotometricMask(showMaskOfStarID, imageNr)
            for k in range(len(rowIndices)):
                rect = patches.Rectangle((colIndices[k], rowIndices[k]), 1, 1, linewidth=2.0,
                                         edgecolor='b', facecolor='none', zorder=2)
                ax.add_patch(rect)

        # If required, overplot the true averaged star positions

        if showStarPositions:
            ID, row, col, Xmm, Ymm, flux = self.getStarCoordinates(imageNr, minVmag=minVmag, maxVmag=maxVmag)

            # Allow differentiating between a target and its contaminants
            if showStarPositions == 'PIC':
                mag = -2.5*np.log10(flux) + 25                
                ax.scatter(col[0], row[0], s=tarMarkerSize, marker='o', c='lime', edgecolor='k', linewidth=1, zorder=4)
                if len(col) > 1:
                    dm  = mag[1:] - mag[0]*np.ones(len(mag)-1)
                    conMarkerSize = tarMarkerSize - np.abs(tarMarkerSize - tarMarkerSize/dm).astype(int)
                    ax.scatter(col[1:], row[1:], s=conMarkerSize, marker='o', c='gold', edgecolor='k', linewidth=1, zorder=4)
                    
            # Or hightligth all stars the same
            else:
                ax.scatter(col, row, marker='x', c='g')
            if showStarIDs:
                for k in range(len(ID)):
                    label = "{0}".format(ID[k])
                    ax.annotate(label, (col[k], row[k]), fontsize='small', fontweight='extra bold', color="black")

        # If required, overplot the true averaged point-like ghost positions

        if showPointLikeGhostPositions:
            ID, row, col, Xmm, Ymm, flux = self.getPointLikeGhostCoordinates(imageNr, minVmag=minVmag, maxVmag=maxVmag)
            ax.scatter(col, row, marker='o', s=6, c='b')
            if showStarIDs:
                for k in range(len(ID)):
                    label = "{0}".format(ID[k])
                    ax.annotate(label, (col[k], row[k]), fontsize='small', fontweight='extra bold', color="black")

        # Ensure that the ax limits are properly set.

        ax.set_xlim(0,Ncols)
        ax.set_ylim(0,Nrows)

        # If required, put the title

        # User defined title-string
        if isinstance(useTitle, str):
            plt.title(useTitle, fontsize=fontSize)
        # With the .hdf5
        if useTitle is True:
            fileBasename = os.path.splitext(self.filename)[0]
            title = fileBasename + " - image{0:06d}".format(imageNr)
            plt.title(title, fontsize=fontSize)

        # By default, matplotlib only shows the (x,y) coordinates of each pixel, but not the pixel value itself.
        # Change this by redefining the ax.format_coord

        Nrows, Ncols = image.shape
        def format_coord(x, y):
            col = int(x)
            row = int(y)
            if col>=0 and col<Ncols and row>=0 and row<Nrows:
                z = image[row,col]
                return "x={:.1f}, y={:.1f}, z={:.1f}".format(x, y, z)
            else:
                return "x={:.1f}, y={:.1f}".format(x, y)

        ax.format_coord = format_coord

        # Show all ticks for smaller subfields or otherwise 10

        if Ncols <= 15:
            plt.xticks(np.arange(0, Nrows+1))
            plt.yticks(np.arange(0, Ncols+1))
        elif Ncols > 15 and Ncols <= 100:
            plt.xticks(np.arange(0, Nrows+1, 10))
            plt.yticks(np.arange(0, Ncols+1, 10))
        elif Ncols > 100 and Ncols <= 300:
            plt.xticks(np.arange(0, Nrows+1, 50))
            plt.yticks(np.arange(0, Ncols+1, 50))
        elif Ncols > 300 and Ncols <= 1000:
            plt.xticks(np.arange(0, Nrows+1, 100))
            plt.yticks(np.arange(0, Ncols+1, 100))
        else:
            plt.xticks(np.arange(0, Nrows+1, 500))
            plt.yticks(np.arange(0, Ncols+1, 500))

        # Set labels if requested

        plt.xlabel(r"$x$ [pixel]", fontsize=fontSize)
        plt.ylabel(r"$y$ [pixel]", fontsize=fontSize)


        # Plot with or without a slider
        
        if not imageNr:

            # Function to update slider
            def update_image(n=0):
                image = images[n]
                imagePlot.set_data(image)
                fig.canvas.draw()
            # Create slider
            slider = widgets.IntSlider(description='Image:',
                                       value=0, min=0, max=Nimg-1, step=1,
                                       layout=widgets.Layout(width='80%'))
            widgets.interact(update_image, n=slider)
            
        else:
            plt.draw()
            plt.show()

        plt.tight_layout()
            
        # That's it!
        
        return fig, ax





    def showPSF(self, datasetName, useTitle=False):

        """
        PURPOSE: make a plot of the requested PSF

        INPUT: datasetName: the name of the dataset that contains the PSF in the HDF5 file
               This is set by the Simulator and is currently: 
                    rebinnedPSFpixel, rebinnedPSFsubPixel,  or  rotatedPSF
               useTitle: True is a title should be plotted, False otherwise

        OUTPUT: None
        """

        # Get the image from the HDF5 file
        # Flip (left-right) the image, then rotate it 90 degrees. This way the smearing lines
        # are vertical, and the image is oriented in such a way that overplotting the 
        # star x,y coordinates from getStarPixelCoordinates() becomes straightforward.

        image = np.rot90(np.fliplr(self.getPSF(datasetName)))
        Nrows, Ncols = image.shape

        # Plot the image. 

        figure = plt.figure()
        ax = figure.add_subplot(111)
        imagePlot = ax.imshow(image, cmap="jet", interpolation="nearest", origin='lower', extent=[0,Nrows,0,Ncols])

        # The large dynamic range of the pixel values often results in images where only
        # the brightest stars are visible. To improve the contrast, clip the color mapping.

        #imagePlot.set_clim(np.percentile(image, 1), np.percentile(image, 99))

        # If required, put the title

        if useTitle:
            fileBasename = os.path.splitext(self.filename)[0]                  # with the .hdf5
            title = fileBasename + " - {}".format(datasetName)
            plt.title(title)

        # By default, matplotlib only shows the (x,y) coordinates of each pixel, but not the pixel value itself.
        # Change this by redefining the ax.format_coord

        # Nrows, Ncols = image.shape
        # def format_coord(x, y):
        #     col = int(x+0.5)
        #     row = int(y+0.5)
        #     if col>=0 and col<Ncols and row>=0 and row<Nrows:
        #         z = image[row,col]
        #         return "x={:.1f}, y={:.1f}, z={:.1f}".format(x, y, z)
        #     else:
        #         return "x={:.1f}, y={:.1f}".format(x, y)

        # ax.format_coord = format_coord

        # plt.xticks(np.arange(0, Nrows, 10))
        # plt.yticks(np.arange(0, Ncols, 10))

        # Labels

        plt.xlabel("x [subpixel]")
        plt.ylabel("y [subpixel]")
        
        # Show the image

        plt.draw()
        plt.show()

        # That's it!

        return




    #--------------------------------------------------------------#
    #                      PLATFORM & TELESCOPE                    #
    #--------------------------------------------------------------#


    def getYawPitchRoll(self, getTime = False):
    
        """
        PURPOSE: Get the yaw, pitch and roll angle values at the end of each exposure

        INPUT: set to False by defaut, if True the function also returns the jitter time

        OUTPUT: yaw:  [arcsec]
                pitch: [arcsec]
                roll: [arcsec]

        NOTE: The yaw, pitch, roll values at the end of an exposure are not the same as the ones at 
              the beginning of the next exposure, because between two exposures there is the CCD readout time
              during which the ACS jitter continues.
        """

        # Extract the yaw values

        dataset = self.hdf5file["ACS"]["Yaw"]
        yaw = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(yaw)

        # Extract the pitch values

        dataset = self.hdf5file["ACS"]["Pitch"]
        pitch = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(pitch)

        # Extract the roll values

        dataset = self.hdf5file["ACS"]["Roll"]
        roll = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(roll)

        if (getTime):
            # Extract the time values
            
            dataset = self.hdf5file["ACS"]["Time"]
            time    = np.zeros(dataset.shape, dataset.dtype)
            dataset.read_direct(time)

            return yaw, pitch, roll, time

        else:
            return yaw, pitch, roll





    def getYawPitchRollFromDrift(self, getTime = False):
        """
        PURPOSE: Get the telescop yaw, pitch and roll angle values at the end of each exposure 

        INPUT: set to False by defaut, if True the function also returns the drift time

        OUTPUT: yaw:  [arcsec]
                pitch: [arcsec]
                roll: [arcsec]

        NOTE: The yaw, pitch, roll values at the end of an exposure are not the same as the ones at 
              the beginning of the next exposure, because between two exposures there is the CCD readout time
              during which the drift continues.
        """

        # Extract the yaw values

        dataset = self.hdf5file["Telescope"]["TelescopeYaw"]
        yaw = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(yaw)

        # Extract the pitch values

        dataset = self.hdf5file["Telescope"]["TelescopePitch"]
        pitch = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(pitch)

        # Extract the roll values

        dataset = self.hdf5file["Telescope"]["TelescopeRoll"]
        roll = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(roll)

        if (getTime):
            # Extract the time values
            
            dataset = self.hdf5file["Telescope"]["Time"]
            time    = np.zeros(dataset.shape, dataset.dtype)
            dataset.read_direct(time)

            return yaw, pitch, roll, time

        else:
            return yaw, pitch, roll



        

    def getPlatformPointingCoordinates(self):

        """
        PURPOSE: Get the right ascension and declination values of the Platform pointing ax at the end of each exposure

        INPUT: None

        OUTPUT: rightAscension:  [degrees]
                declination: [degrees]

        NOTE: The coordinate values at the end of an exposure are not the same as the ones at 
              the beginning of the next exposure, because between two exposures there is the CCD readout time
              during which the ACS jitter continues.
        """

        # Extract the right ascension values

        dataset = self.hdf5file["ACS"]["PlatformRA"]
        rightAscension = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(rightAscension)

        # Extract the pitch values

        dataset = self.hdf5file["ACS"]["PlatformDec"]
        declination = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(declination)

        # That's it

        return rightAscension, declination


    

    #--------------------------------------------------------------#
    #                       STELLAR INFORMATION                    #
    #--------------------------------------------------------------#
    

    def getStarCatalog(self):

        """
        PURPOSE: retrieve a catalog of stars that were observed during the time series. Most stars 
                 are observed during every exposure, but at the edge of the subfield some stars may 
                 be observed during a few exposures only, depending on the ACS. The source of the 
                 information is the Star Input Catalog that the user specified before running the 
                 simulation.

                 The initial planar focal plane and pixel coordinates are the coordinates of the 
                 stars on the CCD before any Jitter or thermal distortions took place. Field distortion
                 is however taken into account when requested by the user in the YAML input file.

        INPUT: None

        OUTPUT: starIDs:        Sequential number of those stars in the input catalog that were detected
                                on the subfield in one or more exposures.
                RA:             Right ascension                                                       [deg]
                decl:           Equatorial declination                                                [deg]
                Vmag:           V magnitude
                xFPmm, yFPmm:   Initial planar focal plane coordinates of the stars                   [mm]
                rowPix, colPix: Initial CCD (not subfield) real-valued pixel coordinates of the stars [pix]
        """

        # First some checks. Failure will lead to meaningful error messages

        if "starIDs" not in self.hdf5file["StarCatalog"].keys():
            print("Error: SimfFile.getStarCatalog(): not starIDs found in hdf5 file")
            return None, None, None, None, None, None, None, None

        elif "RA" not in self.hdf5file["StarCatalog"].keys():
            print("Error: SimfFile.getStarCatalog(): not RA values found in hdf5 file")
            return None, None, None, None, None, None, None, None

        elif "Dec" not in self.hdf5file["StarCatalog"].keys():
            print("Error: SimfFile.getStarCatalog(): no declination values found in hdf5 file")
            return None, None, None, None, None, None, None, None

        elif "Vmag" not in self.hdf5file["StarCatalog"].keys():
            print("Error: SimfFile.getStarCatalog(): no V magnitudes found in hdf5 file")
            return None, None, None, None, None, None, None, None


        # Extract the data from the HDF5 file

        dataset = self.hdf5file["StarCatalog"]["starIDs"]
        starIDs = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(starIDs)

        dataset = self.hdf5file["StarCatalog"]["RA"]
        RA = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(RA)

        dataset = self.hdf5file["StarCatalog"]["Dec"]
        declination = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(declination)

        dataset = self.hdf5file["StarCatalog"]["Vmag"]
        Vmag = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(Vmag)

        # xFPmm, yFPmm, rowPix, and colPix were all introduced with the same commit
        # So, testing if xFPmm is present in the StarCatalog group is sufficient

        if "xFPmm" in self.hdf5file["StarCatalog"].keys():
            dataset = self.hdf5file["StarCatalog"]["xFPmm"]
            xFPmm = np.zeros(dataset.shape, dataset.dtype)
            dataset.read_direct(xFPmm)

            dataset = self.hdf5file["StarCatalog"]["yFPmm"]
            yFPmm = np.zeros(dataset.shape, dataset.dtype)
            dataset.read_direct(yFPmm)

            dataset = self.hdf5file["StarCatalog"]["colPix"]
            colPix = np.zeros(dataset.shape, dataset.dtype)
            dataset.read_direct(colPix)

            dataset = self.hdf5file["StarCatalog"]["rowPix"]
            rowPix = np.zeros(dataset.shape, dataset.dtype)
            dataset.read_direct(rowPix)

            return starIDs, RA, declination, Vmag, xFPmm, yFPmm, rowPix, colPix

        # That's it!

        return starIDs, RA, declination, Vmag, None, None, None, None





    def getStarPositions(self, starID):

        """This function fetch the pixel coordinates of a desired star ID from the output file.

        Parameters
        ----------
        starID : int
           Star ID in simulated catalogue.

        Return
        ------
        rowPix : ndarray [pixels]
            Stellar row pixel coordinate
        colPix : ndarray [pixels]
            Stellar column pixel coordinate
        """

        # Get all Exposure00.. strings and avoid the time array being the last entry

        exposureStrings = np.array(self.hdf5file['StarPositions'])[:-1]
        N = len(exposureStrings)

        # Loop over each image to fetch pixel coordinates

        rowPix = np.zeros(N)
        colPix = np.zeros(N)

        for i in range(N):

            rowPix[i] = np.array(self.hdf5file['StarPositions'][exposureStrings[i]]['rowPix'][starID-1])
            colPix[i] = np.array(self.hdf5file['StarPositions'][exposureStrings[i]]['colPix'][starID-1])

        return rowPix, colPix





    def getStarCoordinates(self, imageNr, minVmag=None, maxVmag=None):

        """
        PURPOSE: get the (fractional) pixel coordinates of all stars in the given image

        INPUT: imageNr: integer sequential number of the image in the HDF5 file
               minVmag: minimum V magnitiude. Only return stars fainter than minVmag.
                        Should be 'None' if no cut in minimum magnitude should be made.
               maxVmag: maximum V magnitude. Only return stars brighter than maxVmag.
                        Should be 'None' if no cut in minimum magnitude should be made.

        OUTPUT: starIDs: integer numpy array containing the star identifiers of those
                         stars visible in the current image (subfield). The star 
                         identifier equals the line number of the star in the input 
                         star catalog (counting from 0). 
                row: The pixel row coordinates of each star in the image (float).
                col: The pixel column coordinates of each star in the image (float).
                Xmm: The focal plane FP' x-coordinates of each star in the image
                Ymm: The focal plane FP' y-coordinates of each star in the image
                flux: The flux of each star in the image [photons]

        REMARKS: 
            - The coordinates returned are the time-averaged coordinates of the stars during the exposure.

            - To get the pixel with the higest flux of star #0, given its (row, col) coordinates:
              >>> im = file.getImage(0)
              >>> ID, row, col, Xmm, Ymm, flux = file.getStarCoordinates(4, minVmag=6.0, maxVmag=9.0)  
              >>> im[int(row[0]), int(col[0])]

            - To use this function to overplot the positions of the stars on an image plotted by 
              showImage(), use plt.scatter(floor(col), floor(row)) because showImage uses 
              matplotlib.imshow() which switches rows and columns.
        """

        # Construct the exposure name that was used to store the image

        exposureGroupName = "Exposure{0:06d}".format(imageNr)

        # Check if the arrays are in the file. If not: complain, if yes: copy the contents into a numpy array.

        if exposureGroupName not in self.hdf5file["StarPositions"].keys():
            print("Error: SimfFile.getStarCoordinates(): {0} not in hdf5 file".format(exposureGroupName))
            return None, None, None, None, None, None

        # Extract the arrays from the HDF5 file

        dataset = self.hdf5file["StarPositions"][exposureGroupName]["starID"]
        starIDs = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(starIDs)

        dataset = self.hdf5file["StarPositions"][exposureGroupName]["rowPix"]
        row = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(row)

        dataset = self.hdf5file["StarPositions"][exposureGroupName]["colPix"]
        col = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(col)

        dataset = self.hdf5file["StarPositions"][exposureGroupName]["xFPmm"]
        Xmm = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(Xmm)

        dataset = self.hdf5file["StarPositions"][exposureGroupName]["yFPmm"]
        Ymm = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(Ymm)

        dataset = self.hdf5file["StarPositions"][exposureGroupName]["flux"]
        flux = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(flux)

        # Make sure that the star IDs are sorted

        sorted = np.argsort(starIDs)
        starIDs = starIDs[sorted]
        row = row[sorted]
        col = col[sorted]
        Xmm = Xmm[sorted]
        Ymm = Ymm[sorted]
        flux = flux[sorted]

        # If no cut in V magnitude is required, we're finished.

        if (minVmag == None) and (maxVmag == None):
            return starIDs, row, col, Xmm, Ymm, flux

        # If a cut in magnitude is required, first get the magnitudes from the star input catalog.

        inputStarIDs, RA, decl, Vmag, xFPmm, yFPmm, rowPix, colPix = self.getStarCatalog()
        subFieldVmag = Vmag[np.in1d(inputStarIDs, starIDs)]

        # If the min or max V magnitude is set to None, use the default values

        if minVmag == None:
            minVmag = subFieldVmag.min()
        if maxVmag == None:
            maxVmag = subFieldVmag.max()

        # Make the magnitude cut

        selection = (subFieldVmag >= minVmag) & (subFieldVmag <= maxVmag)

        # That's it!

        return starIDs[selection], row[selection], col[selection], Xmm[selection], Ymm[selection], flux[selection]



    #--------------------------------------------------------------#
    #                         SKY BACKGROUND                       #
    #--------------------------------------------------------------#


    def getSkyBackground(self, imageNr):

        """
        Return the sky background, expressed in photons / pixel, for the given exposure.
        """

        return self.hdf5file["/Background/skyBackground"][imageNr]

    


    
    def getCosmicsInfo(self, imageNr, field="SubField"):
        """
        PURPOSE: returns for all cosmics that hit the CCD in a given field, the entry rows, the entry columns,
                 the entry angles, the intensities, and the trail lengths. If this information is not stored in 
                 the HDF5 file, it return (None, None, None, None, None)

        INPUT:
            - imageNr: Integer sequential number of the image in the HDF5 file.
            - field: String that determines from what field the Cosmics should be returned. Can be:
                     "SubField", "BiasMapLeft", "BiasMapRight" or "SmearingMap". 
                     If input doesn't match any of these values the function returns (None, None, None, None).

        OUTPUT:
            - entryRows[0..N-1]:    the row where the cosmic hit the CCD                                         [integer pixel]
            - entryColumns[0..N-1]: the column where the cosmic hit the CCD                                      [integer pixel]
            - entryAngles[0..N-1]:  the angle in which the cosmic hit the CCD                                    [rad]
            - intensities[0..N-1]:  the total number of e- of the cosmic before they were spread out in a trail  [e-]
            - trailLengths[0..N-1]: the length of the trail caused by the cosmic                                 [pixels]

            Here N is the total number of cosmics that hit the CCD. If there were no hits in the field, the arrays will be empty.
            The latter is especially likely for the bias
        """

        # Check if the field variables matches the allowed values

        if not field in ["SubField", "BiasMapLeft", "BiasMapRight", "SmearingMap"]:
            print("Error: SimFile.getCosmicsInfo(): field variable doesn't match one of the allowed values: SubField, BiasMapLeft, BiasMapRight or SmearingMap ")
            return None, None, None, None, None

        # Check if the Cosmics info was saved to the HDF5 file

        if "Cosmics" not in self.hdf5file["/"].keys():
            print("Error: SimFile.getCosmicsInfo(): no cosmics information was saved in the HDF5 file.")
            return None, None, None, None, None


        # Construct the exposure name that was used to store the image

        exposureGroupName = "exposure{0:06d}".format(imageNr)


        # Check if the arrays are in the file. If not: complain, if yes: copy the contents into a numpy array.

        if field not in self.hdf5file["Cosmics"].keys():
            print("Error: SimFile.getCosmicsInfo(): {0} not in hdf5 file".format(field))
            return None, None, None, None, None

        if exposureGroupName not in self.hdf5file["Cosmics/" + field].keys():
            print(self.hdf5file["Cosmics/" + field].keys())
            print("Error: SimFile.getCosmicsInfo(): {0} not in hdf5 file".format(exposureGroupName))
            return None, None, None, None, None

        # Extract the arrays from the HDF5 file

        dataset = self.hdf5file["Cosmics"][field][exposureGroupName]["EntryRows"]
        entryRows = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(entryRows)

        dataset = self.hdf5file["Cosmics"][field][exposureGroupName]["EntryColumns"]
        entryColumns = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(entryColumns)

        dataset = self.hdf5file["Cosmics"][field][exposureGroupName]["EntryAngles"]
        entryAngles = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(entryAngles)

        dataset = self.hdf5file["Cosmics"][field][exposureGroupName]["Intensities"]
        intensities = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(intensities)

        dataset = self.hdf5file["Cosmics"][field][exposureGroupName]["TrailLengths"]
        trailLengths = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(trailLengths)

        # That's it!

        if len(intensities) == 1 and intensities[0] == -1.0:
            empty = np.array([])
            return empty, empty, empty, empty, empty
        else:
            return entryRows, entryColumns, entryAngles, intensities, trailLengths






    def getCosmicsAffectedPixels(self, imageNr, field="SubField"):
        """
        PURPOSE: Get the pixel coordinates and flux for those pixels that are affected by a cosmics,
                 for a particular field (e.g. SubField, SmearingMap, etc). 

        INPUT: 
            - imageNr: Integer sequential number of the image in the HDF5 file.
            - field: String that determines from what field the Cosmics should be returned. Can be:
                     "SubField", "BiasMapLeft", "BiasMapRight" or "SmearingMap". 
                     If input doesn't match any of these values the function returns (None, None, None).

        OUTPUT:
            - row: Pixel row coordinates of each star in the image (integer).
            - col: Pixel column coordinates of each star in the image (integer).
            - flux: Flux of cosmics [electrons].
        """

        # Check if the field variables matches the allowed values

        if not field in ["SubField", "BiasMapLeft", "BiasMapRight", "SmearingMap"]:
            print("Error: SimFile:getCosmicsAffectedPixels(): field variable doesn't match one of the allowed values: SubField, BiasMapLeft, BiasMapRight or SmearingMap ")
            return None, None, None

        # Check if the Cosmics info was saved to the HDF5 file

        if "Cosmics" not in self.hdf5file["/"].keys():
            print("Error: SimFile.getCosmicsAffectedPixels(): no cosmics data was saved in the HDF5 file.")
            return None, None, None

        # Construct the exposure name that was used to store the image

        exposureGroupName = "exposure{0:06d}".format(imageNr)

        # Check if the arrays are in the file. If not: complain, if yes: copy the contents into a numpy array.

        if field not in self.hdf5file["Cosmics"].keys():

            print("Error: SimFile.getCosmicsAffectedPixels(): field {0} not in hdf5 file".format(field))
            return None, None, None
        if exposureGroupName not in self.hdf5file["Cosmics/" + field].keys():
            print(self.hdf5file["Cosmics/" + field].keys())
            print("Error: SimFile.getCosmicsAffectedPixels(): field {0} not in hdf5 file".format(exposureGroupName))
            return None, None, None

        # Extract the arrays from the HDF5 file

        dataset = self.hdf5file["Cosmics"][field][exposureGroupName]["Columns"]
        col = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(col)

        dataset = self.hdf5file["Cosmics"][field][exposureGroupName]["Rows"]
        row = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(row)

        dataset = self.hdf5file["Cosmics"][field][exposureGroupName]["Flux"]
        flux = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(flux)

        # That's it!

        return row, col, flux






    def getPointLikeGhostCoordinates(self, imageNr, minVmag = None, maxVmag = None):

        """
        PURPOSE: Get the star ID, pixel and focal-plane coordinates, and flux of all point-like ghosts
                 in the given image.

        INPUT:
            - imageNr: Integer sequential number of the image in the HDF5 file.
            - minVmag: Minimum V magnitude of the stars causing the point-like ghosts. Only return ghosts for which
                       the originating star is fainter than minVmag.
                       Should be 'None' if no cut in minimum magnitude should be made.
            - maxVmag: Maximum V magnitude of the stars causing the point-like ghosts. Only return ghosts for which
                       the originating star is brighter than maxVmag.
                       Should be 'None' if no cut in maximum magnitude should be made.

        OUTPUT: 
            - starIDs: Integer numpy array containing the star IDs of the stars (as mentioned in the
                       input catalogue) that cause point-like ghosts in the current image.  If no star ID
                       was given in the input star catalogue file, the identifier equals the line number 
                       of the star in the input star catalogue (counting from 0). 
            - row: Pixel row coordinates of each star in the image (float).
            - col: Pixel column coordinates of each star in the image (float).
            - Xmm: Focal-plane x-coordinates of each star in the image.
            - Ymm: Focal plane y-coordinates of each star in the image.
            - flux: Flux of each point-like ghost in the image [photons].


        REMARKS: 
            - The coordinates returned are the time-averaged coordinates of the point-like ghosts during the exposure.

            - To get the pixel with the higest flux of star #0, given its (row, col) coordinates:
              >>> im = file.getImage(0)
              >>> ID, row, col, Xmm, Ymm, flux = file.getPointLikeGhostCoordinates(4, minVmag=6.0, maxVmag=9.0)  
              >>> im[int(row[0]), int(col[0])]

            - To use this function to overplot the positions of the point-like ghost on an image plotted by 
              showImage(), use plt.scatter(floor(col), floor(row)) because showImage uses 
              matplotlib.imshow() which switches rows and columns.
        """

        # Check if the point-like ghost info was saved to the HDF5 file

        if "PointLikeGhostPositions" not in self.hdf5file["/"].keys():

            print("Error: no group PointLikeGhostPositions in the HDF5 file.")
            return None, None, None, None, None, None

        # Construct the exposure name that was used to store the image

        exposureGroupName = "Exposure{0:06d}".format(imageNr)

        # Check if the arrays are in the file. If not: complain, if yes: copy the contents into a numpy array.

        if exposureGroupName not in self.hdf5file["PointLikeGhostPositions"].keys():

            print("Error: SimfFile.getPointLikeGhostCoordinates(): {0} not in hdf5 file".format(exposureGroupName))
            return None, None, None, None, None, None

        # Extract the arrays from the HDF5 file

        dataset = self.hdf5file["PointLikeGhostPositions"][exposureGroupName]["starID"]
        starIDs = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(starIDs)

        dataset = self.hdf5file["PointLikeGhostPositions"][exposureGroupName]["rowPix"]
        row = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(row)

        dataset = self.hdf5file["PointLikeGhostPositions"][exposureGroupName]["colPix"]
        col = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(col)

        dataset = self.hdf5file["PointLikeGhostPositions"][exposureGroupName]["xFPmm"]
        Xmm = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(Xmm)

        dataset = self.hdf5file["PointLikeGhostPositions"][exposureGroupName]["yFPmm"]
        Ymm = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(Ymm)

        dataset = self.hdf5file["PointLikeGhostPositions"][exposureGroupName]["flux"]
        flux = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(flux)

        # Make sure that the point-like ghost star IDs are sorted

        sorted = np.argsort(starIDs)
        starIDs = starIDs[sorted]
        row = row[sorted]
        col = col[sorted]
        Xmm = Xmm[sorted]
        Ymm = Ymm[sorted]
        flux = flux[sorted]

        # If no cut in V magnitude is required, we're finished.

        if (minVmag == None) and (maxVmag == None):
            return starIDs, row, col, Xmm, Ymm, flux

        # If a cut in magnitude is required, first get the magnitudes from the star input catalogue

        inputStarIDs, RA, decl, Vmag, xFPmm, yFPmm, rowPix, colPix = self.getStarCatalog()
        subFieldVmag = Vmag[np.in1d(inputStarIDs, starIDs)]

        # If the min or max V magnitude is set to None, use the default values

        if minVmag == None:
            minVmag = subFieldVmag.min()
        if maxVmag == None:
            maxVmag = subFieldVmag.max()

        # Make the magnitude cut

        selection = (subFieldVmag >= minVmag) & (subFieldVmag <= maxVmag)

        # That's it!

        return starIDs[selection], row[selection], col[selection], Xmm[selection], Ymm[selection], flux[selection]










    def getExtendedGhostCoordinates(self, imageNr, minVmag = None, maxVmag = None):

        """
        PURPOSE: Get the star ID, pixel and focal-plane coordinates, flux, and radius of all extended ghosts
                 in the given image.

        INPUT:
            - imageNr: Integer sequential number of the image in the HDF5 file.
            - minVmag: Minimum V magnitude of the stars causing the extended ghosts. Only return ghosts for which
                       the originating star is fainter than minVmag.
                       Should be 'None' if no cut in minimum magnitude should be made.
            - maxVmag: Maximum V magnitude of the stars causing the extended ghosts. Only return ghosts for which
                       the originating star is brighter than maxVmag.
                       Should be 'None' if no cut in maximum magnitude should be made.

        OUTPUT: 
            - starIDs: Integer numpy array containing the star IDs of the stars (as mentioned in the
                       input catalogue) that cause extended ghosts in the current image.  If no star ID
                       was given in the input star catalogue file, the identifier equals the line number 
                       of the star in the input star catalogue (counting from 0). 
            - row: Pixel row coordinates of each star in the image (float).
            - col: Pixel column coordinates of each star in the image (float).
            - Xmm: Focal-plane x-coordinates of each star in the image.
            - Ymm: Focal plane y-coordinates of each star in the image.
            - flux: Flux of each extended ghost in the image [photons].
            - radius: Radius of the extended ghost [mm].

        REMARKS: 
            - The coordinates returned are the time-averaged coordinates of the extended ghosts during the exposure.

            - To get the pixel with the higest flux of star #0, given its (row, col) coordinates:
              >>> im = file.getImage(0)
              >>> ID, row, col, Xmm, Ymm, flux, radius = file.getExtendedGhostCoordinates(4, minVmag=6.0, maxVmag=9.0)  
              >>> im[int(row[0]), int(col[0])]

            - To use this function to overplot the positions of the extended ghost on an image plotted by 
              showImage(), use plt.scatter(floor(col), floor(row)) because showImage uses 
              matplotlib.imshow() which switches rows and columns.
        """

        # Check if the extended ghost info was saved to the HDF5 file

        if "ExtendedGhostPositions" not in self.hdf5file["/"].keys():

            print("Error: no group ExtendedGhostPositions in the HDF5 file.")
            return None, None, None, None, None, None, None

        # Construct the exposure name that was used to store the image

        exposureGroupName = "Exposure{0:06d}".format(imageNr)

        # Check if the arrays are in the file. If not: complain, if yes: copy the contents into a numpy array.

        if exposureGroupName not in self.hdf5file["ExtendedGhostPositions"].keys():

            print("Error: SimfFile.getExtendedGhostCoordinates(): {0} not in hdf5 file".format(exposureGroupName))
            return None, None, None, None, None, None, None

        # Extract the arrays from the HDF5 file

        dataset = self.hdf5file["ExtendedGhostPositions"][exposureGroupName]["starID"]
        starIDs = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(starIDs)

        dataset = self.hdf5file["ExtendedGhostPositions"][exposureGroupName]["rowPix"]
        row = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(row)

        dataset = self.hdf5file["ExtendedGhostPositions"][exposureGroupName]["colPix"]
        col = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(col)

        dataset = self.hdf5file["ExtendedGhostPositions"][exposureGroupName]["xFPmm"]
        Xmm = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(Xmm)

        dataset = self.hdf5file["ExtendedGhostPositions"][exposureGroupName]["yFPmm"]
        Ymm = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(Ymm)

        dataset = self.hdf5file["ExtendedGhostPositions"][exposureGroupName]["flux"]
        flux = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(flux)

        dataset = self.hdf5file["ExtendedGhostPositions"][exposureGroupName]["radius"]
        radius = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(radius)

        # Make sure that the extended ghost star IDs are sorted

        sorted = np.argsort(starIDs)
        starIDs = starIDs[sorted]
        row = row[sorted]
        col = col[sorted]
        Xmm = Xmm[sorted]
        Ymm = Ymm[sorted]
        flux = flux[sorted]
        radius = radius[sorted]

        # If no cut in V magnitude is required, we're finished.

        if (minVmag == None) and (maxVmag == None):
            return starIDs, row, col, Xmm, Ymm, flux, radius

        # If a cut in magnitude is required, first get the magnitudes from the star input catalogue

        inputStarIDs, RA, decl, Vmag, xFPmm, yFPmm, rowPix, colPix = self.getStarCatalog()
        subFieldVmag = Vmag[np.in1d(inputStarIDs, starIDs)]

        # If the min or max V magnitude is set to None, use the default values

        if minVmag == None:
            minVmag = subFieldVmag.min()
        if maxVmag == None:
            maxVmag = subFieldVmag.max()

        # Make the magnitude cut

        selection = (subFieldVmag >= minVmag) & (subFieldVmag <= maxVmag)

        # That's it!

        return starIDs[selection], row[selection], col[selection], Xmm[selection], Ymm[selection], flux[selection], radius[selection]



    #--------------------------------------------------------------#
    #                          PHOTOMETRY                          #
    #--------------------------------------------------------------#


    def getLightCurve(self, starID, lctype="estimated"):
        """
        PURPOSE: Extract the light curve of the star with the given ID.

        INPUT: starID: ID of the star as mentioned in the last column of the star catalog file
               lctype: either "estimated" or "input". The estimated one is derived from a binary mask.
                       the input one is derived from the mean input magnitude specified in the star catalog
                       and (for variable stars) the delta-magnitude time series given as an input file.

        OUTPUT: time: [s]
                flux: [electrons/exposure]
        """

        # Verify if the necessary info is in the HDF5 file

        if "Photometry" not in self.hdf5file["/"].keys():
            print("Error: getLightCurve(): No photometry present in the HDF5 file")
            return None, None

        starIDgroupName = "starID{0}".format(starID)
        if starIDgroupName not in self.hdf5file["Photometry"]["Lightcurves"].keys():
            print("Error: getLightCurve(): " + starIDgroupName + " not present in Photometry/Lightcurves/ in the HDF5 file")
            return None, None

        if "Time" not in self.hdf5file["StarPositions"].keys():
            print("Error: getLightCurve(): Time array not present in StarPositions group. Configure HDF5 output in yaml input file.")
            return None, None

        # Select the proper flux name

        if lctype == "estimated":
            datasetName = "estimatedFlux"
        elif lctype == "input":
            datasetName = "inputFlux"
        else:
            print("Error: getLightCurve(): lctype can only be 'estimated' or 'input'")
            return None, None

        # Extract the flux and the time points

        dataset = self.hdf5file["Photometry"]["Lightcurves"][starIDgroupName][datasetName]
        flux = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(flux)

        dataset = self.hdf5file["StarPositions"]["Time"]
        time = np.zeros(dataset.shape, dataset.dtype)
        dataset.read_direct(time)

        return time, flux




    

    def getPhotometry(self, starID, quarterNo=1):
        """
        PURPOSE: Extract the light curve of the star with the given ID.
        NOTE The estimated one is derived from a binary mask. The input one is derived
        from the mean input magnitude specified in the star catalog and
        (for variable stars) the delta-mag time series given as an input file.

        PARAMETERS
        ----------
        starID : int
            ID of the star as mentioned in the last column of the star catalog file
        quarterNo : int
            Mission quarter number used to return correct relative time points.

        RETURN
        ------
        time : ndarray
            Time points of time series [s]
        flux : ndarray
            Flux points of time series [electrons/exposure]
        """

        # Verify if the necessary info is in the HDF5 file

        if "Photometry" not in self.hdf5file["/"].keys():
            print("Error: getLightCurve(): No photometry present in the HDF5 file")
            return None, None

        starIDgroupName = "starID{0}".format(starID)
        if starIDgroupName not in self.hdf5file["Photometry"]["Lightcurves"].keys():
            print("Error: getLightCurve(): " + starIDgroupName + " not present in Photometry/Lightcurves/ in the HDF5 file")
            return None, None

        # Fetch time points

        time = self.getTimeQuarter(quarterNo)

        # Extract the flux and the time points

        photometry = self.hdf5file["Photometry"]["Lightcurves"][starIDgroupName]
        inputFlux     = np.array(photometry["inputFlux"])
        estimatedFlux = np.array(photometry["estimatedFlux"])

        return time, inputFlux, estimatedFlux






    def getPhotometricTimeSeries(self, targetIDs):

        """
        PURPOSE: Return time points, input flux, and output flux for the given target star.

        PARAMETERS
        ----------
        targetID : int
            Star ID for the target star for which to return the photometric time series.

        RETURNS
        -------
        time : narray
            Time points [s]
        inputFlux : narray
            Flux as derived from the input catalogue [photons]
        outputFlux : narray
            Flux as estimated by the photometric pipeline [photons]
        """

        # Fetch time points

        #time = np.array(self.hdf5file["/Photometry/Time"])
        time = np.array(self.hdf5file["Telescope/Time"])

        # Fetch mask update events

        maskUpdateEvents = np.array(self.hdf5file["Photometry/Masks/exposureNrOfMaskUpdate"])

        # Fetch stellar input and simulated flux for all targetIDs

        if isinstance(targetIDs, int):

            fluxInput  = np.array(self.hdf5file["Photometry/Lightcurves/starID{0}/inputFlux".format(targetIDs)])
            fluxOutput = np.array(self.hdf5file["Photometry/Lightcurves/starID{0}/estimatedFlux".format(targetIDs)])

        else:

            fluxInput = fluxOutput = np.zeros((len(time), len(targetIDs)))

            for targetID in targetIDs:

                fluxInput  = np.array(self.hdf5file["Photometry/Lightcurves/StarID{0}/inputFlux".format(targetID)])
                fluxOutput = np.array(self.hdf5file["Photometry/Lightcurves/StarID{0}/estimatedFlux".format(targetID)])

        # Finito!

        return time, fluxInput, fluxOutput, maskUpdateEvents


    

    
    
    def getApertureMask(self, starID, imageNr=None):
        """
        PURPOSE: return the subfield row and column indices of the mask that is used to extract
                 the flux of star with the given ID for the given exposure number. This only makes
                 sense if the photometry was activated in the configuration yaml file.

        INPUT: starID:  ID of the star as mentioned in the last column of the star catalog file
               imageNr: integer sequential number of the image in the HDF5 file

        OUTPUT: rowIndices: subimage row indices for each of the mask pixels
                colIndices: subimage column indices for each of the mask pixels
                exposureNr: the image number in which the mask was derived.
                            exposureNr <= imageNr

        NOTE: Masks are not update continuously, but only once in a while. This function searches
              for the most recent mask. This mask may have thus been derived from a previous image
              rather than from the given image Nr.
        """

        # Check if photometric data exists

        if "Photometry" not in self.hdf5file["/"].keys():
            print("Error: getPhotometricMask(): No photometry present in the HDF5 file")
            return None, None, None, None, None

        starIDgroupName = "starID{0}".format(starID)
        if starIDgroupName not in self.hdf5file["Photometry"]["Masks"].keys():
            print("Error: getPhotometricMask(): " + starIDgroupName + " not present in Photometry/Masks/ in the HDF5 file")
            return None, None, None, None, None

        # Fetch mask info and mask updates

        mask = self.hdf5file["Photometry"]["Masks"]
        exposureNrOfMaskUpdate = np.array(mask["exposureNrOfMaskUpdate"])
        numMaskUpdates = len(exposureNrOfMaskUpdate)

        # If a specific image number for the mask update is requested:
        # NOTE Masks are not updated for every exposure hence find most recent mask

        if isinstance(imageNr, int):

            idx = np.searchsorted(exposureNrOfMaskUpdate, imageNr, side='right') - 1
            if idx < 0:
                print("Error: getPhotometricMask(): requesting an imageNr that is too early for this HDF5 file")
                return None, None, None, None, None

            exposureNrOfMaskUpdate = exposureNrOfMaskUpdate[idx]

            # Extact mask size and NSR

            maskSize = np.array(mask[starIDgroupName]['maskSize'])[idx]
            maskNSR  = np.array(mask[starIDgroupName]['maskNSR'])[idx]

            # Extract the indices of the proper mask

            exposureGroupName = "Exposure{0:06d}".format(exposureNrOfMaskUpdate)
            rowIndices = np.array(mask[starIDgroupName][exposureGroupName]["maskRowIndices"])
            colIndices = np.array(mask[starIDgroupName][exposureGroupName]["maskColumnIndices"])

        # Else fetch all the indices for all mask updates

        else:

            # Extact mask size and NSR

            maskSize = np.array(mask[starIDgroupName]['maskSize'])
            maskNSR  = np.array(mask[starIDgroupName]['maskNSR'])

            # Extract the indices of all masks

            rowIndices = []
            colIndices = []
            for i in range(numMaskUpdates):
                exposureGroupName = "Exposure{0:06d}".format(exposureNrOfMaskUpdate[i])
                rowIndices.append(mask[starIDgroupName][exposureGroupName]["maskRowIndices"])
                colIndices.append(mask[starIDgroupName][exposureGroupName]["maskColumnIndices"])
            rowIndices = np.array(rowIndices)
            colIndices = np.array(colIndices)

        # Finito!

        return rowIndices, colIndices, exposureNrOfMaskUpdate, maskSize, maskNSR




    

    def getTimeQuarter(self, quarterNo):

        """Function to create and return quarter-long time column.

        This function creates a time array for a quarter long simulation. It uses
        the quarter number and the hdf5 output file to correct for the time shift
        of the parent CCD.

        Parameters
        ----------
        outputFile : str
           Full path to the HDF5 outputfile.
        quarterNo : int
           Integer specifying which quarter the time array should be created for.

        Return
        ------
        time : ndarray 
            Time array matching the parent quarter defined by the user.
        """

        # Fetch times

        numExposures = self.hdf5file['InputParameters/ObservingParameters'].attrs['NumExposures']
        timeStep     = self.hdf5file['InputParameters/ObservingParameters'].attrs['CycleTime']
        timeShift    = self.hdf5file['InputParameters/CCD'].attrs['TimeShift']

        # Create time array from start and end times

        timeStart = (quarterNo-1) * 90. * 86400. + float(timeShift)
        timeEnd   = timeStart + timeStep * numExposures
        time      = np.arange(timeStart, timeEnd, timeStep)

        return time
