import numpy as np
import os
import sys
import h5py
from analyticpsf import AnalyticPSF
from numpy.random import uniform







def photometry(inputFilePath, outputFilePath, targetIDs, maxNexposures = None, contaminationRadius = 4, verbose=True):

    """
    Flux extraction from stars in imagettes generated by PlatoSim

    INPUT:
        . inputFilePath:       Path + name of the PlatoSim output HDF5 file that contains the imagettes
        . outputFilePath:      Path + name of the HDF outputfile which will contain the extracted fluxes
        . targetIDs:           A list containing the IDs of the targets for which to compute the lightcurves
        . maxNexposures:       Process the first `maxNexposures` of the input file
        . contaminationRadius: The radius of the neigbourhood in which contaminants are taken into account [pix]
        . verbose:             Whether to print info messages on the screen or not

    OUTPUT:
        . None. The extracted fluxes will be written to the HDF5 file specified above.
    """

    # Open the input and the output HDF5 files

    inputFile = h5py.File(inputFilePath, "r")
    
    if not os.path.isfile(outputFilePath):
        outputFile = h5py.File(outputFilePath, "w")
    else:
        raise IOError("Output file already exists")


    # Create the necessary groups in the output hdf5 file

    photometryGroup = outputFile.create_group("/Photometry");
    maskGroup = outputFile.create_group("/Masks");

    # Find out if the subfield is on the left or righthand side of the CCD, this affects
    # which gain, and which bias map we should use.

    zeroPointColumn = inputFile["/InputParameters/SubField/"].attrs["ZeroPointColumn"]    
    NumColumnsCCD = inputFile["/InputParameters/CCD/"].attrs["NumColumns"]

    if zeroPointColumn > NumColumnsCCD/2:
        isOnRightSideOfCCD = True
    else:
        isOnRightSideOfCCD = False

    # Collect the gain (ADU / e-), the QE (e-/photon) and Readout Noise from the HDF5 file

    if isOnRightSideOfCCD:
        gain = inputFile["InputParameters/FEE/Gain"].attrs["RefValueRight"] * inputFile["InputParameters/CCD/Gain"].attrs["RefValueRight"]
    else:
        gain = inputFile["InputParameters/FEE/Gain"].attrs["RefValueLeft"] * inputFile["InputParameters/CCD/Gain"].attrs["RefValueLeft"]
    quantumEfficiency = inputFile["/InputParameters/CCD/QuantumEfficiency"].attrs["MeanQuantumEfficiency"]   
    varianceRON = inputFile["/InputParameters/FEE"].attrs["ReadoutNoise"]**2 + inputFile["/InputParameters/CCD"].attrs["ReadoutNoise"]**2

    # Extract the sky background for all exposures

    skyBackgrounds = np.array(inputFile["/Background/skyBackground"])                       # [phot/pix/exposure]
    

    # Get the magnitudes of all the stars found in any of the images. The number of stars 
    # can differ from image to image because some stars may jitter out of the subfield. 
    # Extract numpy arrays from the HDF5 file, but put it in a more convenient dictionary 'Vmag'.
    # E.g. magnitude[12445] contains the magnitude of the star with ID 12445.

    starIDs = np.array(inputFile["StarCatalog/starIDs"])
    mag = np.array(inputFile["StarCatalog/Vmag"])
    magnitude = dict([(starIDs[n], mag[n]) for n in range(len(mag))])


    # The following arrays will be filled for each target and for each exposure

    Ntargets = len(targetIDs)
    maskSizeTarget = np.zeros(Ntargets, dtype=np.int)
    inputFluxTarget = np.zeros(Ntargets)
    estimatedFluxTarget = np.zeros(Ntargets)
    varFluxTarget = np.zeros(Ntargets)
    NSRtarget = np.zeros(Ntargets)
    rowTarget =  np.zeros(Ntargets)                                     # Subfield coordinate, not CCD
    colTarget = np.zeros(Ntargets)                                      # Subfield coordinate, not CCD
    numContaminantsOfTarget = np.zeros(Ntargets, dtype=np.int)
    rowIndexOfMaskOfTarget  = np.zeros((Ntargets,7*7), dtype=np.int)    # Mask is maximum (3+1)*(3+1) pixels large
    colIndexOfMaskOfTarget  = np.zeros((Ntargets,7*7), dtype=np.int)
    Vmag = np.zeros(Ntargets)


    # Find out how many exposures we should process

    beginExposureNr = int(inputFile["/InputParameters/ObservingParameters/"].attrs["BeginExposureNr"])
    Nexposures = int(inputFile["/InputParameters/ObservingParameters/"].attrs["NumExposures"])

    photometryGroup.attrs["beginExposureNr"] = beginExposureNr
    photometryGroup.attrs["Nexposures"] = Nexposures

    if (maxNexposures is not None):
        if maxNexposures < Nexposures:
            Nexposures = maxNexposures       # Cap the # exposures to a user-set limit


    print (beginExposureNr, Nexposures)
    # Copy the time points of the input HDF5 file to the output file.

    time = np.array(inputFile["/StarPositions/Time"])[:Nexposures]
    photometryGroup.create_dataset("time", data=time)


    # Loop over all exposures, and apply mask photometry on each image
    
    if verbose:
        print("Looping over all images in HDF5 file.")

    for imageNr in range(beginExposureNr, beginExposureNr + Nexposures):

        if (imageNr % 100) == 0:
            print("Image # {0}".format(imageNr))

        # Read the bias and smearing map, and the image itself

        image = np.array(inputFile["/Images/image{0:06d}".format(imageNr)], dtype=np.float)
        smearingMap = np.array(inputFile["/SmearingMaps/smearingMap{0:06d}".format(imageNr)], dtype=np.float)
        if isOnRightSideOfCCD:
            biasMap = np.array(inputFile["/BiasMapsRight/biasMap{0:06d}".format(imageNr)])
        else:
            biasMap = np.array(inputFile["/BiasMapsLeft/biasMap{0:06d}".format(imageNr)])

        # Correct for the bias
        
        meanBias = biasMap.mean()
        image -= meanBias
        smearingMap -= meanBias

        if verbose:
            print("    Subtracted bias level of {0} ADU".format(meanBias))

        # Correct for open shutter smearing using the smearing maps
        # meanSmearing contains a smearing value for each column

        meanSmearing = smearingMap.mean(axis=0)
        image -= meanSmearing

        if verbose:
            print("    Corrected for open-shutter smearing")

        # Convert from [ADU] to [electrons] using the gain

        image /= gain

        if verbose:
            print("    Converted from [ADU] to [electrons] using a Gain of {0} e-/ADU".format(1.0 / gain))

        # Correct for the throughput. This includes natural vignetting, mechanical vignetting, polarization,
        # the quantum efficiency, and particulate & molecular contamination. 
        # The construct with np.divide is to prevent a division by zero, which would happen when the imagette
        # suffers from mechanical vignetting.
        # This division converts from [e-/exposure] to [photons/exposure]

        throughputMap = np.array(inputFile["/ThroughputMaps/throughputMap{0:06d}".format(imageNr)])
        image = np.divide(image, throughputMap, out=np.zeros_like(image), where=throughputMap!=0)      # [phot/exposure]

        # Correct for the flatfield

        if "PRNU" in inputFile["/Flatfield"].keys():
            flatfield = np.array(inputFile["Flatfield/PRNU"])
            image /= flatfield
            if verbose:
                print("    Corrected for PRNU")
        

        # Subtract the sky background [phot/exposure]
        # This is not the measured but the theoretical value.

        skyBackground = skyBackgrounds[imageNr - beginExposureNr] 
        image -= skyBackground

        # Create the groups in the output HDF5 file in which we will store all the photometric info

        exposureGroupName = "/Photometry/Exposure{0:06d}".format(imageNr)
        exposureGroup = outputFile.create_group(exposureGroupName) 

        # Use the exact star positions which differs for each exposure, although in reality we don't have them on-board.

        starIDs   = np.array(inputFile["StarPositions/Exposure{0:06d}/starID".format(imageNr)])
        colPix    = np.array(inputFile["StarPositions/Exposure{0:06d}/colPix".format(imageNr)])
        rowPix    = np.array(inputFile["StarPositions/Exposure{0:06d}/rowPix".format(imageNr)])
        inputFlux = np.array(inputFile["StarPositions/Exposure{0:06d}/flux".format(imageNr)]) 

        # The following information is needed to compute analytic PSFs which in turn is needed
        # to compute the photometric masks for each target. 
        # Note: it's assumed that Simulation.setSubfieldAroundCoordinates() was used to configure the simulation
        #       That function sets all the CCD parameters correctly, even when the CCD Position is not Custom.
        
        path           = os.environ["PLATO_PROJECT_HOME"] + "/inputfiles/psfallv3.txt"     
        sigmaPSF       = inputFile["InputParameters/PSF/AnalyticNonGaussian/Sigma"].attrs["ConstantValue"]              # [pix]
        sigmaDiffusion = inputFile["InputParameters/PSF/AnalyticNonGaussian"].attrs["ChargeDiffusionStrength"]          # [pix]
        focalLength    = inputFile["InputParameters/Camera/FocalLength"].attrs["ConstantValue"] * 1000                  # [mm]
        ccdOrientation = inputFile["InputParameters/CCD"].attrs["Orientation"] / 180 * np.pi                            # [rad]
        ccdZeroPointX  = inputFile["InputParameters/CCD"].attrs["OriginOffsetX"]                                        # [mm]
        ccdZeroPointY  = inputFile["InputParameters/CCD"].attrs["OriginOffsetY"]                                        # [mm]
        pixelSize      = inputFile["InputParameters/CCD"].attrs["PixelSize"]                                            # [micron]
        zeroPointRowSubfield = inputFile["InputParameters/SubField"].attrs["ZeroPointRow"] 
        zeroPointColSubfield = inputFile["InputParameters/SubField"].attrs["ZeroPointColumn"] 
        # numSubPixels = inputFile["InputParameters/SubField"].attrs["SubPixels"]
        
        analyticPSF = AnalyticPSF(path, sigmaPSF, sigmaDiffusion, focalLength, ccdOrientation, ccdZeroPointX, ccdZeroPointY, pixelSize, 1)


        # Loop over all targets to do the photometry.

        print("Number of targets: ", Ntargets)

        print(starIDs)
        print(targetIDs)

        for k in range(Ntargets):

            # Collect information on the position and input flux of the target
            # Note: 'starIDs' contain the IDs of all stars in the subfield, while 'targetIDs' contain the IDs of those stars
            #       for which we need photometry. So targetIDs is a subset of starIDs.

            for n in range(len(starIDs)):
                if targetIDs[k] == starIDs[n]:
                    rowTarget[k] = rowPix[n]
                    colTarget[k] = colPix[n]
                
                    # The input flux stored in the HDF5 file, is expressed in [phot/exposure],
                    # and the passband and the transmission efficiency of the telescope are already included
                    # in the value. We still need to convert from [photons/exposure] to [e-/exposure].

                    inputFluxTarget[k] = inputFlux[n] * throughputMap[int(rowTarget[k]), int(colTarget[k])]

            Vmag[k] = magnitude[starIDs[k]]

            # If this is the first exposure, generate the masks for each target.
            # These masks are not updated every exposure, but only once in a while.

            if imageNr == beginExposureNr:

                # Create a theoretical subfield image as if only one target was on the CCD 

                singleTargetMap = analyticPSF.getPSF(rowTarget[k], colTarget[k], inputFluxTarget[k], zeroPointRowSubfield, zeroPointColSubfield, image.shape[0], image.shape[1])

                # Create a theoretical subfield image as if only the contaminants are on the CCD

                contaminantMap = np.zeros_like(image)
                for n in range(len(starIDs)):
                
                    # Skip those stars that are too distant to be a contaminant of the current target

                    if (abs(colPix[n] - colTarget[k]) > contaminationRadius) or (abs(rowPix[n] - rowTarget[k]) > contaminationRadius): 
                        continue

                    # A target is never its own contaminant

                    if starIDs[n] == targetIDs[k]:
                        continue

                    numContaminantsOfTarget[k] += 1
                    inputFluxContaminant = inputFlux[n] * throughputMap[int(rowPix[n]), int(colPix[n])]
                    contaminantMap += analyticPSF.getPSF(rowPix[n], colPix[n], inputFluxContaminant, zeroPointRowSubfield, zeroPointColSubfield, image.shape[0], image.shape[1])

                # Given the contaminant map decide which pixels should be included in the mask
                # First, get the boundaries of the mask.

                minRow = max(0, int(rowTarget[k])-3)
                maxRow = min(image.shape[0] - 1, int(rowTarget[k])+3)             # maxRow inclusive
                minCol = max(0, int(colTarget[k])-3)
                maxCol = min(image.shape[1] - 1, int(colTarget[k])+3)             # maxCol inclusive
                
                NSRmap = np.zeros_like(image)                                 # NSR = Noise-To-Signal Ratio
                varianceMap = np.zeros_like(image) 
                for irow in range(minRow, maxRow+1):
                    for icol in range(minCol, maxCol+1):
                        varianceMap[irow, icol] = singleTargetMap[irow, icol] + contaminantMap[irow, icol] + varianceRON + skyBackground * throughputMap[irow, icol] 
                        NSRmap[irow, icol] = np.sqrt(varianceMap[irow, icol]) / singleTargetMap[irow, icol]

                # Order the pixels in the NSR map from low to high N/S ratio

                subNSRmap = NSRmap[minRow:maxRow+1,minCol:maxCol+1]
                rowIndex, colIndex = np.unravel_index(np.argsort(subNSRmap.ravel()), subNSRmap.shape)
                rowIndex += minRow                                            # Transform from indices in subNSRmap to indices in NSRmap
                colIndex += minCol
                
                # Build the mask, starting with the pixel with the best NSR, adding one pixel at the time,
                # with the condition that adding a pixel should contribute more to the aggregated signal than to the aggregated noise.

                # Initialize with the first pixel

                aggregatedVariance              = varianceMap[rowIndex[0], colIndex[0]]
                aggregatedTheoreticalTargetFlux = singleTargetMap[rowIndex[0], colIndex[0]]
                aggregatedObservedTargetFlux    = image[rowIndex[0], colIndex[0]]
                aggregatedNSR                   = NSRmap[rowIndex[0], colIndex[0]]
                maskSizeTarget[k] = 1
 
                # Then add other pixels

                for i in range(1, len(rowIndex)):
                    temp = np.sqrt(aggregatedVariance + varianceMap[rowIndex[i], colIndex[i]]) / (aggregatedTheoreticalTargetFlux + singleTargetMap[rowIndex[i], colIndex[i]])
                    if temp < aggregatedNSR:
                        aggregatedVariance              += varianceMap[rowIndex[i], colIndex[i]]
                        aggregatedTheoreticalTargetFlux += singleTargetMap[rowIndex[i], colIndex[i]]
                        aggregatedObservedTargetFlux    += image[rowIndex[i], colIndex[i]]
                        aggregatedNSR = temp
                        maskSizeTarget[k] += 1
                    else:
                        estimatedFluxTarget[k] = aggregatedObservedTargetFlux 
                        varFluxTarget[k] = aggregatedVariance 
                        NSRtarget[k] = aggregatedNSR

                        # Copy the exact pixels of the mask, so that we can persist them in the HDF5 file

                        for n in range(maskSizeTarget[k]):
                            rowIndexOfMaskOfTarget[k,n] = rowIndex[n]
                            colIndexOfMaskOfTarget[k,n] = colIndex[n]

                        # Disregard all other pixels of the window around the target star:
                        # they all contribute more to the noise than to the signal.

                        break


            else:

                # For all other exposures, simply use the same mask

                estimatedFluxTarget[k] = 0.0
                for n in range(maskSizeTarget[k]):
                    estimatedFluxTarget[k] += image[rowIndexOfMaskOfTarget[k,n], colIndexOfMaskOfTarget[k,n]]

                # We reuse the NSR of the previous mask, so no need to recompute it.

                pass



        # Save the masks to HDF5. Don't do this every exposure, but only after the mask changed.

        if imageNr == beginExposureNr:
            maskGroupName = "/Masks/Mask{0:06d}".format(imageNr)
            maskGroup = outputFile.create_group(maskGroupName) 
            maskGroup.create_dataset("maskPixelRows", data = rowIndexOfMaskOfTarget)
            maskGroup.create_dataset("maskPixelColumns", data = colIndexOfMaskOfTarget)




        # Save all computed arrays for this image to the HDF5 file

        exposureGroup.create_dataset("starID",           data = targetIDs)
        exposureGroup.create_dataset("trueFlux",         data = inputFluxTarget)              # [e-/exposure]
        exposureGroup.create_dataset("estimatedFlux",    data = estimatedFluxTarget)          # [e-/exposure]
        exposureGroup.create_dataset("varFlux",          data = varFluxTarget)                # [e-/exposure]^2
        exposureGroup.create_dataset("NSR",              data = NSRtarget)                                   
        exposureGroup.create_dataset("maskSize",         data = maskSizeTarget)
        exposureGroup.create_dataset("numContaminants",  data = numContaminantsOfTarget)
        exposureGroup.create_dataset("trueRow",         data = rowTarget)
        exposureGroup.create_dataset("trueCol",         data = colTarget)
        exposureGroup.create_dataset("Vmag",             data=Vmag) 
        
        



    # All images have now been processed. Close the HDF5 files.

    inputFile.close();
    outputFile.close();
    
    # That's it!

    return








def getPhotometryTimeSeries(photometryFile, starID):

    """
    PURPOSE: extract the flux time series of star with a given identifier.

    INPUT: photometryFile: an HDF5 output file written by the photometry() function above
           starID:  star identifier (integer, e.g. 9789)

    OUTPUT: time: a numpy np.array containing the time points [s]
            trueRow: the true (but in reality unknown) row positions (subfield not CCD) of the star [pix]
            trueCol: the true (but in reality unknown) column positions (subfield not CCD) of the star [pix]
            trueFlux: the true (but in reality unknown) fluxes of the stars [e-/exposure]
            outputFlux: the estimated fluxes of the stars [e-/exposure]

    REMARK: To find out which star identifiers are in the photometry file, look in the HDF5 simulation
            output file of PlatoSim: 
            allStarIDs = np.array(platosimOutputFile["StarCatalog/starIDs"])

    EXAMPLE: >>> time, trueRow, trueCol, trueFlux, outputFlux = getPhotometryTimeSeries("photoutput.hdf5", 124)

    """

    photFile = h5py.File(photometryFile)
    allTimePoints = np.array(photFile["/Photometry/time"])

    beginExposureNr = photFile['Photometry'].attrs['beginExposureNr'] 
    Nexposures = photFile['Photometry'].attrs['Nexposures']
    
    time = []
    outputFlux = []
    trueFlux = []
    trueRow = []
    trueCol = []

    for k in range(beginExposureNr, beginExposureNr + Nexposures):
        allStarIDsInImage = np.array(photFile["/Photometry/Exposure{0:06d}/starID".format(k)])
        if starID in allStarIDsInImage:
            estimatedFlux = np.array(photFile["/Photometry/Exposure{0:06d}/estimatedFlux".format(k)])
            theoreticalFlux = np.array(photFile["/Photometry/Exposure{0:06d}/trueFlux".format(k)])
            inputRow = np.array(photFile["/Photometry/Exposure{0:06d}/trueRow".format(k)])
            inputCol = np.array(photFile["/Photometry/Exposure{0:06d}/trueCol".format(k)])
            
            outputFlux.append(estimatedFlux[np.where(allStarIDsInImage==starID)][0])
            trueFlux.append(theoreticalFlux[np.where(allStarIDsInImage==starID)][0])
            trueRow.append(inputRow[np.where(allStarIDsInImage==starID)][0])
            trueCol.append(inputCol[np.where(allStarIDsInImage==starID)][0])
            
            time.append(allTimePoints[k-beginExposureNr])

    outputFlux = np.array(outputFlux)
    trueRow = np.array(trueRow)
    trueCol = np.array(trueCol)
    time = np.array(time)

    photFile.close()

    return time, trueRow, trueCol, trueFlux, outputFlux
   










def computePSFsigma(psf, Nsubpixels, Nsamples=10000):

    """
    PURPOSE: Approximate the PSF with a 2D symmetric Gaussian distribution, to compute 
             its standard deviation, assuming that the barycenter is in the middle of the image. 
             This standard deviation will be used for the weighted mask photometry

    INPUT: psf:        2D numpy image containing the rotated PSF at subpixel level
           Nsubpixels: the number of subpixels per pixel (1D)
           Nsamples:   the number of monte carlo samples of the PSF to fit a Gaussian

    OUTPUT: sigma: the standard deviation of the symmetric PSF  [pix]

    """

    sumPSF = sum(sum(psf))
    randomNumber = uniform(0.0, 1.0, Nsamples)

    rows = []
    cols = []

    for n in range(Nsamples):

        # Go through the PSF pixels <Nsamples> time, storing the pixel coordinates 
        # with higher PSF values more often than those with low values. 

        cumulative = 0.0;
        skipRestOfPSF = False

        # Sum up the PSF values until you exceed the generated random number
        # Then keep the (row,col) value that made the sum exceed the threshold,
        # and skip the rest of the PSF pixels.

        for i in range(psf.shape[0]):

            if skipRestOfPSF is True: break

            for j in range(psf.shape[1]):

                if skipRestOfPSF is True: break

                cumulative = cumulative + psf[i,j];

                if cumulative >= randomNumber[n] * sumPSF:

                    rows.append(i)
                    cols.append(i)
                    skipRestOfPSF = True
                    break

    # Compute the standard deviation of the PSF as the average of the sigma in the row direction
    # and the sigma in the colum  direction    
    
    sigmaPSF = (np.array(rows).std() + np.array(cols).std())/2.0                       # [supixels]
    
    # Convert the stdev of the PSF from subpixels to pixels

    sigmaPSF = sigmaPSF / Nsubpixels                                             # [pixels]

    # That's it!

    return sigmaPSF
