"""
Run the PLATO Simulator from Python.

The Simulation class provides the opportunity to interactively tune the input parameters 
before the simulator is started. The parameters that are available can be inspected by 
just printing the Simulation object, i.e. print (sim), which will dump all the parameters 
and their current values on the command line.

Parameter values can be set as follows (sim is a Simulation object):

    sim["ObservingParameters/BeginExposureNr"] = 0
    sim["ObservingParameters/NumExposures"] = 10

Before executing the run() method on the Simulation, the directory for the 
output files generated by the PLATO simulator must be specified using

    sim.outputDir = <dirname>

The outputDir can also be specified during construction:

    sim = Simulation("Run-01", outputDir="/Users/rik/Work/PLATO/Simulations")

Usage example:

    Nsimulations = 4
    alpha = [100, 120, 140, 150]
    delta = [20, 30, 20, 30]
    
    for n in range(Nsimulations):
        sim = Simulation("Simul-{:02d}".format(n), outputDir="/Users/rik/Work/PLATO/Simulations")
		sim["CCD/CTI/Model"] = "Simple"
        sim["CCD/CTI/Simple/MeanCTE"] = 0.98
        sim["ObservingParameters/ExposureTime"] = 3.0
        sim["ObservingParameters/RApointing"] = alpha[n]
        sim["ObservingParameters/DecPointing"] = delta[n]

        sim.run()

    simFile = SimFile("/Users/rik/Work/PLATO/Simulations/Simul-01.hdf5")

Interactive usage example:

    >>> sim = Simulation("Simul01")
    >>> sim.outputDir = "/Users/rik/Work/PLATO/Simulations"
    >>> print (sim)
    YAML Configuration:
    CCD:
    	CTI:
    		Model: Simple
    		Simple:
		        MeanCTE: 0. 99999
        DigitalSaturation: 65535
        ElectronicOffset: 100
        FlatfieldPtPNoise: 0.016
        FullWellSaturation: 1000000
        Gain: 16
        ...
    >>> sim["CCD/CTI/Model"] = "Simple"
    >>> sim["CCD/Simple/MeanCTE"] = 0.98
    >>> print (sim["General/ProjectLocation"])
    /Users/rik/Git/PlatoSim3
    >>> simFile = sim.run()
    ...

"""

import yaml
import pyaml
import inspect
import subprocess
import os
import sys
import ast
import numpy as np

import referenceFrames as rf
import simfile
from simfile import SimFile




class Simulation(object):
    
    """
    Simulation class allows running the PLATO simulator interactively from Python
    and tuning the input parameters before each run. For more help, type:

    >>> import simulation
    >>> print(simulation)
    """


    def __init__(self, runName, configurationFile=None, outputDir=None, debug=False):

        """
        Initialise class variables and read the default input files.
        """

        self.debug = debug
        self.runName = runName
        
        # flag to check if output directory has been specified before running the Simulation.
        
        self.hasTargetLocation = False
        self.targetOutputFilesLocation = None

        if outputDir != None:
            self.outputDir = outputDir

        self.setSimulatorLocation();

        if configurationFile:
            self.readConfigurationFile( configurationFile )
        else:
            self.readConfigurationFile( self.originalInputFilesLocation + "/inputfile.yaml" )






    def setSimulatorLocation(self):
        
        """
        Given the location of the simfile.py module, try to find the build/ folder where
        the simulator executable should be. Then set the default locations for the platosim 
        executable (i.e. build directory), and the original input files location.        
        """

        # Find the absolute path of the simfile.py. This will allow us to located the other
        # default project directories. Build in a test to check that the build sub-directory 
        # exists, otherwise this is probably not a correct default installation.

        path = inspect.getabsfile(simfile)
        path = os.path.dirname(path)  # strip off filename of the simfile module: simfile.py
        path = os.path.dirname(path)  # strip off python sub-directory
        if not os.path.isdir(path + "/build"):
            raise Exception("Unexpected directory structure for this PLATO Simulator distribution: no build sub-directory")
        
        self.platosimLocation = path

        # This is the location of the platosim executable

        self.platosimBuildLocation = self.platosimLocation + "/build"

        # This is the location of the original input files as distributed by the PLATO Simulator
        
        self.originalInputFilesLocation = self.platosimLocation + "/inputfiles"
        self.originalOutputFilesLocation = self.platosimLocation + "/outputfiles"






    @property
    def outputDir(self):
        """
        Return the output files location.
        """
        return self.targetOutputFilesLocation




    @outputDir.setter
    def outputDir(self, path):

        """
        Specify the absolute path for the output directory. This directory will contain
        a copy of the modified input file and the HDF5 output file for this simulation.
        
        If the output path doesn't exist, it is created.
        """

        if not os.path.exists(path):
            if self.debug:
                print("DEBUG: creating output directory {}.".format(path))
            self.createDirectory(path)
        
        self.targetOutputFilesLocation = path
        self.hasTargetLocation = True

        if self.debug:
            print("DEBUG: output dir set to {}.".format(path))







    def readConfigurationFile(self, filename):
        """
        Read the YAML input configuration file. 
        """
        self.configurationFilename = filename

        if self.debug:
            print ("Parsing YAML configuration file {}.".format(filename))
        
        with open(filename, 'r') as stream:
            try:
                self.yamlDocument = yaml.load(stream)
            except yaml.YAMLError as exc:
                print(exc)
        





    def getYamlConfiguration(self):
        """
        Return the YAML configuration as a dictionary.
        """
        return self.yamlDocument








    def __contains__(self, key):
        """
        Returns true if the input parameter (key) is known/exists.

        Usage: if "Group/ParameterName" in sim: # do something

        Param: key - a string containing the parameter name or "Group/ParameterName" combination

        Return: true if key exists, false otherwise

        """
        if key.find('/') == -1:
            nodeNames = [key]
        else:
            nodeNames = key.split("/")

        node = self.yamlDocument

        for nodeName in nodeNames:
            print("> {}, {}".format(nodeName, type(node)))
            try:
                node = node[nodeName]
            except:
                return False

        return True









    def __getitem__(self, key):

        """
        Returns the value of the input parameter (key).

        Param: key - a string containing the parameter name or "Group/ParameterName" combination

        Return: the value of the parameter
        """
        
        # Split the path into node names
        # E.g. "PSF/MappedGaussian/Sigma" into ["PSF", "MappedGaussian", "Sigma"]

        if key.find('/') == -1:
            parentNodeName, nodeName = key, None
            print ("usage: the given parameter name (key) should include the group name of the group that contains the parameter.")
            print ("       E.g in 'Camera/PlateScale', Camera is the group, PlateScale is the parameter.")
            return None
        else:
            nodeNames = key.split("/")

        # Navigate to the deepest node, starting from the document root

        node = self.yamlDocument 

        for nodeName in nodeNames:
            if nodeName in node:
                node = node[nodeName]
            else:
                print("ERROR: The group '{}' was not found in the yaml inputfile '{}'.".format(key, self.configurationFilename))
                return None

        # node is a string, so cast it to its proper value

        try:
            value = ast.literal_eval(node)
        except ValueError:
            value = node
        
        # Return the value of the deepest node

        return value








    def __setitem__(self, key, item):
        
        """
        Update a specific node.

        Param: key - a string with parent node name and node name seperated by a slash
        Param: item - a string with the new node value, if not a string the value is converted using str()

        Return: True if node could be updated, False otherwise
        """
        
        # Ensure that the given item is a string

        item = str(item)

        # Split the path into node names
        # E.g. "PSF/MappedGaussian/Sigma" into ["PSF", "MappedGaussian", "Sigma"]

        if key.find('/') == -1:
            print ("usage: the given parameter name (key) should include the group name of the group that contains the parameter.")
            print ("       E.g in 'Camera/PlateScale', Camera is the group, PlatScale is the parameter.")
            return None
        else:
            nodeNames = key.split("/")

        # Check whether the parent node is in the document. If not, complain

        if nodeNames[0] not in self.yamlDocument:
             print("Error: no node with the name {0} found in input yaml file".format(nodeNames[0]))
             return False

        # If there is only 1 node in the path, we're finished after setting its value

        if len(nodeNames) == 1:
            self.yamlDocument[nodeNames[0]] = item
            return True

        # If we arrive here, there are at least 2 node in the path, check if 2nd parent node exists

        if nodeNames[1] not in self.yamlDocument[nodeNames[0]]:
             print("Error: no node with the name {0} found in input yaml file".format(nodeNames[0]+"/"+nodeNames[1]))
             return False

        # If there are only 2 nodes in the path, we're finished after setting its value

        if len(nodeNames) == 2:
            self.yamlDocument[nodeNames[0]][nodeNames[1]] = item
            return True

        # If we arrive here, there are at least 3 nodes in the path, check if 3rd parent node exists

        if nodeNames[2] not in self.yamlDocument[nodeNames[0]][nodeNames[1]]:
             print("Error: no node with the name {0} found in input yaml file".format(nodeNames[0]+"/"+nodeNames[1]+"/"+nodeNames[2]))
             return False

        # If there are only 3 nodes in the path, we're finished after setting its value

        if len(nodeNames) == 3:
            self.yamlDocument[nodeNames[0]][nodeNames[1]][nodeNames[2]] = item
            return True

        # If we arrive here, there are at least 4 nodes in the path, check if 4th parent node exists

        if nodeNames[3] not in self.yamlDocument[nodeNames[0]][nodeNames[1]][nodeNames[2]]:
             print("Error: no node with the name {0} found in input yaml file".format(nodeNames[0]+"/"+nodeNames[1]+"/"+nodeNames[2]+"/"+nodeNames[3]))
             return False

        # If there are only 34nodes in the path, we're finished after setting its value

        if len(nodeNames) == 4:
            self.yamlDocument[nodeNames[0]][nodeNames[1]][nodeNames[2]][nodeNames[3]] = item
            return True
  

        # If we arrive here, there are at least 5 nodes in the path. Issue a not-implemented error message.

        print("Error: detected 5 or more nodes in the path {0}".format(key))
        return False










    def createDirectory(self, path):
        try: 
            os.makedirs(path)
        except OSError as ose:
            print (ose)
            if not os.path.isdir(path):
                raise Exception("Couldn't create directory {}".format(path))

        return









    def writeYamlConfigurationFile(self, filename):
        """
        Write the modified configuration to output file location. This configuration will 
        be loaded by the PLATO Simulator when the run() method is executed.
        """
        if self.debug:
            print ("Writing the Yaml configuration file {}.".format(filename))
        with open(filename, 'w') as outfile:
            outfile.write( pyaml.dump(self.yamlDocument, indent=4, width=120) )








    def run(self, removeOutputFile=False):
        """
        Run the PLATO Simulator.

        param removeOutputFile: if the outputfile already exists before the run started, simply delete it.

        When PlatoSim fails for some reason and returns an error code (!= 0), an Exception is raised.
        """

        if not self.hasTargetLocation:
            raise Exception("Output location not set for this Simulation. Set the outputDir before executing the run() method.")

        inputFilename = "{}/{}.yaml".format(self.targetOutputFilesLocation, self.runName)
        outputFilename = "{}/{}.hdf5".format(self.targetOutputFilesLocation, self.runName)
        logFilename = "{}/{}.log".format(self.targetOutputFilesLocation, self.runName)

        if removeOutputFile:
            try:
                os.remove(outputFilename)
            except OSError:
                pass

        self.writeYamlConfigurationFile(inputFilename)

        # The run() method was only introduced with Python 3.5, use the older call() method when running e.g. Python 2.7

        if sys.version_info < (3, 5):   
            rc = subprocess.call([self.platosimBuildLocation + "/platosim", inputFilename, outputFilename, logFilename])
            if rc:
                raise Exception("Simulation.run(): PlatoSim returned with exit code {}.".format(rc))
        else:
            completedProcess = subprocess.run([self.platosimBuildLocation + "/platosim", inputFilename, outputFilename, logFilename], 
                stdout=subprocess.PIPE, stderr=subprocess.PIPE)

            if completedProcess.returncode:
                if completedProcess.stdout:
                    print (str(completedProcess.stdout.decode("utf-8")))
                if completedProcess.stderr:
                    print (str(completedProcess.stderr.decode("utf-8")))
                raise Exception("Simulation.run(): PlatoSim returned with exit code {}.".format(completedProcess.returncode))

        simFile = SimFile(outputFilename)

        return simFile 







    def __str__(self):

        """
        Return a listing of all settings from both the CCD and the Photometry input files.
        If a parameter value has been updated for this Simulation, [updated] will be printed
        after the value.
        """
        root = self.yamlDocument
        msg = "YAML Configuration:\n"
        msg += pyaml.dump(root, indent=4)

        return msg







    def useNominalCamera(self):

        """
        PURPOSE: Change the input parameters to use the nominal camera's.

        REMARKS: The following parameters are updated:

                 CCD/NumColumns = 4510
                 CCD/NumRows = 4510
                 ObservingParameters/ExposureTime = 23
        """

        self.__setitem__("CCD/NumColumns", "4510")
        self.__setitem__("CCD/NumRows",    "4510")
        self.__setitem__("ObservingParameters/ExposureTime", "23")

        return







    def useFastCamera(self):

        """
        PURPOSE: Change the input parameters to use the fast camera's.

        REMARKS: The following parameters are updated:

                 CCD/NumColumns = 4510
                 CCD/NumRows = 2255
                 ObservingParameters/ExposureTime = 2.3
        """

        self.__setitem__("CCD/NumColumns", "4510")
        self.__setitem__("CCD/NumRows",    "2255")
        self.__setitem__("ObservingParameters/ExposureTime", "23")

        return








    def setSubfieldAroundPixelCoordinates(self, ccdCode, xCCDpixel, yCCDpixel, subfieldSizeX, subfieldSizeY):
        """
        PURPOSE:  Calculate the location of the subField such that it is centered on the star with 
              the given pixel coordinates.

        INPUTS: ccdCode:       for nominal camera: either '1', '2', '3', '4'
                               for fast camera: either '1F', '2F', '3F', '4F'
                xCCDpixel:     x-coordinate (column-number) of the star on the CCD  [pixel/float]
                yCCDpixel:     y-coordinate (row-number) of the star on the CCD  [pixel/float]
                subfieldSizeX: width (i.e. number of columns) of the sub-field [pixels]
                subfieldSizeY: height (i.e. number of rows) of the sub-field [pixels]

        OUTPUTS:  None
        """

        raStar, decStar = rf.pixelToSkyCoordinates(self, ccdCode, xCCDpixel, yCCDpixel)
        
        # TODO: determine nominal from the given ccdCode
        
        nominal = True
        
        success = self.setSubfieldAroundCoordinates(raStar, decStar, subfieldSizeX, subfieldSizeY, True)
        
        if not success:
            print ("Warning: setSubfieldAroundPixelCoordinates() failed to set subField around the star.")
            
        return









    def setSubfieldAroundCoordinates(self, raStar, decStar, subfieldSizeX, subfieldSizeY, normal):
        
        """
        PURPOSE: Set the location of the sub-field such that it is centred on the star 
                 with the given sky coordinates.  Depending on the CCD (in nomincal mode:
                 "1", "2", "3", or "4"; in fast mode: "1F", "2F", "3F", or "4F"), the 
                 configuration file for the given simulation is adapted.  These include the
                 pre-defined CCD position, the dimensions of the CCD (and also of the sub-field,
                 although this is not affected by the calculations), the sub-field zeropoint
                 and the exposure time. 

        NOTE: This function calls the calculateSubfieldAroundCoordinates() function in reference frames

        NOTE: It is assumed that the configuration parameters in the sim object contains
              a correct (ra, dec)  of the platform, a correct (azimuth, tilt) of the telescope,
              a valid values for the focal length, the plate scale, the pixel size, and that
              the switch to include distortion or not is set correctly

        INPUT:  raStar:                 right ascension of the star [radians]
                decStar:                declination [radians]
                subfieldSizeX:          width (i.e. number of columns) of the subiield [pixels]
                subfieldSizeY:          height (i.e. number of rows) of the sub-field [pixels]
                normal:                 True for the normal camera configuration, False for the fast cameras

        OUTPUT: True if the CCD code (i.e. the pre-defined CCD position) could be determined, False otherwise 

        REMARKS: - If the coordinates do not fall on any CCD, an error message is shown, followed by an exit(1)
                 - If the star is too close to the edge for the given subfield size, and error message is shown,
                   followed by an exit(1)
        """
        

        # Find out some instrumental characteristics from the sim object

        raPlatform       = np.deg2rad(float(self["ObservingParameters/RApointing"]))
        decPlatform      = np.deg2rad(float(self["ObservingParameters/DecPointing"]))
        azimuthTelescope = np.deg2rad(float(self["Telescope/AzimuthAngle"]))
        tiltTelescope    = np.deg2rad(float(self["Telescope/TiltAngle"]))
        focalLength      = float(self["Camera/FocalLength"]) * 1000.0                     # [m] -> [mm]
        plateScale       = float(self["Camera/PlateScale"])          
        focalPlaneAngle  = np.deg2rad(float(self["Camera/FocalPlaneOrientation"]))
        pixelSize        = float(self["CCD/PixelSize"]) 

        if (self["Camera/IncludeFieldDistortion"] == "yes")  or (self["Camera/IncludeFieldDistortion"] == "1"):
            includeFieldDistortion = True
            distortionCoefficients = sim["Camera/FieldDistortion/Coefficients"]
        else:
            includeFieldDistortion = False
            distortionCoefficients = None


        # Compute the position of the subfield.
        # xPix and yPix are the CCD coordinates of the star, given a 4510x4510 CCD [colNumber, rowNumber].

        ccdCode, xPix, yPix = rf.calculateSubfieldAroundCoordinates(subfieldSizeX, subfieldSizeY, raStar, decStar, raPlatform, decPlatform, \
                                                                    tiltTelescope, azimuthTelescope, focalPlaneAngle, focalLength, pixelSize,              \
                                                                    includeFieldDistortion, distortionCoefficients, normal)
        
        if ccdCode == None:
            return False
        
        CCDSizeX         = rf.CCD[ccdCode]["Ncols"]
        CCDSizeY         = rf.CCD[ccdCode]["Nrows"]
        CCDOriginOffsetX = rf.CCD[ccdCode]["zeroPointXmm"]
        CCDOriginOffsetY = rf.CCD[ccdCode]["zeroPointYmm"]
        CCDOrientation   = rf.CCD[ccdCode]["angle"]

        # If we arrive here, there is no problem accommodating the entire sufield on the CCD

        self["CCD/OriginOffsetX"] = str(CCDOriginOffsetX)
        self["CCD/OriginOffsetY"] = str(CCDOriginOffsetY)
        self["CCD/Orientation"] = str(np.rad2deg(CCDOrientation))

        self["CCD/NumColumns"] = CCDSizeX
        self["CCD/NumRows"] = CCDSizeY

        self["SubField/ZeroPointRow"] = str(int(yPix - subfieldSizeY/2))
        self["SubField/ZeroPointColumn"] = str(int(xPix - subfieldSizeX/2))
        self["SubField/NumRows"] = str(subfieldSizeY)
        self["SubField/NumColumns"] = str(subfieldSizeX)

        # Set the exposure and the readout time, depending on fast vs nominal cams

        if normal:
            self["ObservingParameters/ExposureTime"] = 23
            self["CCD/ReadoutTime"] = 2.5
        else:
            self["ObservingParameters/ExposureTime"] = 2.3
            self["CCD/ReadoutTime"] = 0.2
        
        # That's it

        return True











    def createStarCatalogFileFromPixelCoordinates(self, rows, cols, magnitudes, starCatalogFileName):

        """
        PURPOSE: Create a star catalog ascii file given the pixel coordinates (row and column) of the stars.
                 This requires the orientation of the spacecraft, telescopes, focal plane, hence it's a 
                 member function of the Simulation class. 
 
        INPUT: rows:       Numpy array with fractional row coordinates of the stars (CCD, not subfield) [pix]     
               cols:       Numpy array with fractional column coordinates of the stars (CCD, not subfield) [pix]  
               magnitudes: Johnson V magnitudes of the stars
               starCatalogFileName: Path of the star catalog file that will be written.

        OUTPUT: None. A file will be saved, containing, ra, dec, and magnitude of the stars.
        """

        # Extract the needed information from the yaml input file

        pixelSize       = self["CCD/PixelSize"]
        ccdZeroPointX   = self["CCD/OriginOffsetX"]
        ccdZeroPointY   = self["CCD/OriginOffsetY"]
        CCDangle        = np.deg2rad(self["CCD/Orientation"])
        raPlatform      = np.deg2rad(self["ObservingParameters/RApointing"])
        decPlatform     = np.deg2rad(self["ObservingParameters/DecPointing"])
        azimuthAngle    = np.deg2rad(self["Telescope/AzimuthAngle"])
        tiltAngle       = np.deg2rad(self["Telescope/TiltAngle"])
        focalPlaneAngle = np.deg2rad(self["Camera/FocalPlaneOrientation"])
        focalLength     = self["Camera/FocalLength"] * 1000.0                     # [m] -> [mm]
        includeFieldDistortion = self["Camera/IncludeFieldDistortion"]
        inverseDistortionCoefficients = self["Camera/FieldDistortion/InverseCoefficients"]

        # Convert the pixel coordinates to focal plane coordinates [mm]
        
        xFPmm, yFPmm = rf.pixelToFocalPlaneCoordinates(cols, rows, pixelSize, ccdZeroPointX, ccdZeroPointY, CCDangle)
        
        # If distortion is required in the yaml input file, distort the focal plane coordinates [mm]

        if (includeFieldDistortion == "yes"):
            xFPmm, yFPmm = rf.distortedToUndistortedFocalPlaneCoordinates(xFPmm, yFPmm, inverseDistortionCoefficients)

        # Convert the focal plane coordinates to equatorial sky coordinates [rad]

        ra, dec = rf.focalPlaneToSkyCoordinates(xFPmm, yFPmm, raPlatform, decPlatform, tiltAngle, azimuthAngle, focalPlaneAngle, focalLength)

        # Save the sky coordinates (in [deg]) to the star catalog file

        np.savetxt(starCatalogFileName, np.transpose([np.rad2deg(ra), np.rad2deg(dec), magnitudes]))

        # That's it

        return

