#!/usr/bin/env python3

"""
This PlatoSim class is designed to ease the time series analysis.
The class can be applied to both the HDF5 output files produced
by PlatoSim or the Feather output files generated by PLATOnium
while is use the L1 proto-pipeline to extract the photometry.
"""

import os
import sys
import wotan
import argparse
import numpy as np
import pandas as pd
from pathlib import Path
from platosim.utilities import errorcode
from platosim.lightcurve import LightCurve

#==============================================================#
#               PARSING COMMAND-LINE ARGUMENTS                 #
#==============================================================#

parser = argparse.ArgumentParser(epilog=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)

man_group = parser.add_argument_group('MANDATORY PARAMETERS')
man_group.add_argument('star',    type=int, help='ID in target list')
man_group.add_argument('group',   type=int, help='Either: 1, 2, 3, 4')
man_group.add_argument('camera',  type=int, help='Either: 1, 2, 3, 4, 5, 6')
man_group.add_argument('quarter', type=int, help='Either: 1, 2, 3, 4, 5, 6, 7, 8, ..')
man_group.add_argument('P',  type=np.float32, help='Orbital period')
man_group.add_argument('t0', type=np.float32, help='First transit')
man_group.add_argument('R',  type=np.float32, help='Stellar radius')
man_group.add_argument('M',  type=np.float32, help='Stellar mass')

out_group = parser.add_argument_group('I/O PARAMETERS')
out_group.add_argument('-i', '--idir', metavar='PATH', type=str, help='Input directory')
out_group.add_argument('-o', '--odir', metavar='PATH', type=str, help='Output directory')

args = parser.parse_args()

idir    = args.idir
odir    = args.odir
starid  = args.star
group   = args.group
camera  = args.camera
quarter = args.quarter

P  = args.P
t0 = args.t0
R  = args.R
M  = args.M

# Inputs and outputs
idir = Path(idir).resolve()
if odir is not None:
    odir = Path(odir).resolve()
else:
    odir = idir / "detrended"
os.system(f"mkdir -p {odir}")

# Set general output filename
star  = f'{starid}'.zfill(9)
zfile = idir / f'{star}_Ncam{group}.{camera}_Q{quarter}.zip'
ifile = idir / f'{star}_Ncam{group}.{camera}_Q{quarter}.ftr'
ofile = odir / f'{star}_Ncam{group}.{camera}_Q{quarter}.ftr'

# Check if the file exist and if not try to unzipped
if not ifile.is_file():
    try: os.system(f'cd {idir}; unzip -q -o {zfile}')
    except: pass

# Fetch light curve object
try: lc = LightCurve(ifile)
except: sys.exit()

# Fetch obs info
G, C, Q = lc.obs()

# Detrend before merging
#print("Detrending")
tdur = wotan.t14(R_s=R, M_s=M, P=P, small_planet=True)
lc.detrend(window=3*tdur, mask=[P, tdur, t0])

# Course outlier rejection
#print("Sigma clipping")
df = lc.clip(model='sigma', low=4, high=4)

# Store data in data frame
df1 = pd.DataFrame()
df1['time']         = df.time
df1['flux']         = df.flux
df1['flux_err']     = lc.flux(column='flux_err')
df1['flux_trend']   = df.flux_trend
df1['flux_detrend'] = df.flux_detrend
df1['flux_clip']    = df.flux_clip
df1['bg']           = df.bg
df1['bg_err']       = df.bg_err
df1['cx']           = df.cx
df1['cx_err']       = df.cx_err
df1['cy']           = df.cy
df1['cy_err']       = df.cy_err

# Sort after logic structure and reset indices
df1 = df1.sort_values(by=["time"])
df1 = df1.reset_index(drop=True)

# If requested save output file
df1.to_feather(ofile)
os.system(f'chmod 777 {ofile}')
