
#include "Camera.h"










/**
 * \brief      Constructor
 *
 * \param configParam   Configuration parameters for the Camera
 * \param hdf5file      HFD5 file to write the camera information to
 * \param telescope     Telescope on which the camera is mounted on
 * \param sky           Sky object to query which stars we are seeing
 */

Camera::Camera(ConfigurationParameters &configParam, HDF5File &hdf5file, Platform &platform, Telescope &telescope, Sky &sky)
: HDF5Writer(hdf5file), platform(platform), telescope(telescope), sky(sky), focalLength(nullptr), focalPlaneAngle(nullptr),
  distortionCoef(nullptr), inverseDistortionCoef(nullptr), internalTime(0.0), includeFieldDistortion(true),
  userGivenSkyBackground(-1.0), fluxOfV0Star(0.0)
{

    // Parse the parameters from the configuration file.

    configure(configParam);

    // Create the groups in the HDF5 file where the different arrays generated by Camera will be saved.

    initHDF5Groups();

    // Get the equatorial sky coordinates of the Sun, which is know by platform since it's pointing its sunshield towards it.

    tie(raSun, decSun) = platform.getRADecSun();
}









/**
 * \brief  Destructor, free memory for psf
 */

Camera::~Camera()
{
    flushOutput();
    delete focalLength;
    delete focalPlaneAngle;

    // if includeDistortion was set to false, the following parameters were never
    // allocated, but the were initialised to null pointers in the constructor,
    // so it always OK to delete them.

    delete distortionCoef;
    delete inverseDistortionCoef;
}













/**
 * \brief Creates the group(s) in the HDF5 file where the star information will be stored.
 *        These group(s) have to be created once, at the very beginning.
 */

void Camera::initHDF5Groups()
{
    Log.debug("Camera: initialising HDF5 groups");
    
    hdf5File.createGroup("/StarPositions");
    hdf5File.createGroup("/Background");
    if (writeTransmissionEfficiency)
    {
      hdf5File.createGroup("/TransmissionEfficiency");
    }

    hdf5File.createGroup("/PointLikeGhostPositions");
    hdf5File.createGroup("/ExtendedGhostPositions");
}








/**
 * \brief Collect and returns the IDs of all stars that fall on the sub-field or produce a ghost
 *        that falls on the sub-field (if ghosts are to be included in the simulation).
 *
 * \details Note that this method pulls the detected stars from a map that is filled by
 *          exposeDetector for each exposure. So, depending on when this method is called,
 *          the returned set might be empty or incomplete.
 *
 * \return Set of unique IDs for stars that fall on the sub-field or produce a ghost on the
 *         sub-field (if ghosts are to be included in the simulation).
 */
set<unsigned int> Camera::getAllStarIDs()
{
    set<unsigned int> allStarIDs;            // A set<> stores only unique members

    // Stars on the sub-field

    for(auto timeMapPair: detectedStarInfo)
    {
        for (auto idArrayPair: timeMapPair.second)
        {
            allStarIDs.insert(idArrayPair.first);
        }
    }

    // Originators of extended ghosts on the sub-field

    for (auto timeMapPair: detectedExtendedGhostInfo)
    {
        for (auto idArrayPair: timeMapPair.second)
        {
            allStarIDs.insert(idArrayPair.first);
        }
    }

    // Originators of symmetric point-like ghosts on the sub-field

    for (auto timeMapPair: detectedPointLikeGhostInfo)
    {
        for (auto idArrayPair: timeMapPair.second)
        {
            allStarIDs.insert(idArrayPair.first);
        }
    }

    return allStarIDs;

}






/**
 * \brief Return the mean position on the CCD, and flux of the star with given ID for the last exposure.
 *
 * \details Mean refers to the mean position during the jittering during the exposure. If the star ID
 *          is not found in the list, the value -1 is returned for each quantity.
 *
 * \return A tuple with the following quantities:
 *    timeStamp: the time stamp of the last exposure                              [s]
 *    xFPmean: mean (during the exposure) focal plane x-coordinate of the star    [mm]
 *    yFPmean: mean focal plane y-coordinate of the star                          [mm]
 *    rowPixMean: mean subfield (fractional) row coordinate                       [pix]
 *    colPixMean: mean subfield (fractional) column coordinate                    [pix]
 *    sumFlux: the integrated flux of the star during one exposure                [photons/exposure]
 */

tuple<double, double, double, double, double, double> Camera::getInfoForTheMostRecentExposureForStar(int starID)
{
    // The detected star info is stored in a map as:   map<double, map<unsigned int, array<double, 6>>> detectedStarInfo;
    // so that  detectedStarInfo[startTime][starID] contains the values (xFPsum, yFPsum, rowPixSum, colPixSum, sumFlux, Ndetections)
    // In C++ maps are sorted on key values (in ascending order). To find the time stamp of the most recent exposure,
    // we simply need to access the last element. rbegin() is a reverse-iterator, starting with the last element

    double timeStamp = detectedStarInfo.rbegin()->first;

    // Find the map item with the given starID

    auto it = detectedStarInfo[timeStamp].find(starID);
    if (it == detectedStarInfo[timeStamp].end())
    {
        // The starID couldn't be found in the map.

        return make_tuple(-1, -1, -1, -1, -1, -1);
    }
    else
    {
        double xFPmean    = detectedStarInfo[timeStamp][starID][0] / detectedStarInfo[timeStamp][starID][5];
        double yFPmean    = detectedStarInfo[timeStamp][starID][1] / detectedStarInfo[timeStamp][starID][5];
        double rowPixMean = detectedStarInfo[timeStamp][starID][2] / detectedStarInfo[timeStamp][starID][5];
        double colPixMean = detectedStarInfo[timeStamp][starID][3] / detectedStarInfo[timeStamp][starID][5];
        double sumFlux    = detectedStarInfo[timeStamp][starID][4];

        return make_tuple(timeStamp, xFPmean, yFPmean, rowPixMean, colPixMean, sumFlux);
    }

}






/**
 *  \brief return the begin and end iterator of the star info of detectedStarInfo[most_recent_time];
 */

pair<starInfoIterator, starInfoIterator> Camera::getInfoForTheMostRecentExposureForAllStars()
{
   // The detected star info is stored in a map as:   map<double, map<unsigned int, array<double, 6>>> detectedStarInfo;
    // so that  detectedStarInfo[startTime][starID] contains all the information.
    // In C++ maps are sorted on key values (in ascending order). To find the time stamp of the most recent exposure,
    // we simply need to access the last element. rbegin() is a reverse-iterator, starting with the last element

    double timeStamp = detectedStarInfo.rbegin()->first;
    return make_pair(detectedStarInfo[timeStamp].begin(), detectedStarInfo[timeStamp].end());
}




/**
 * \brief Write all recorded information to the HDF5 output file
 *
 */

void Camera::flushOutput()
{

    // Extract and save the time points of all exposures
    // Note: keyValuePair is (key, value) pair, where key is also a pair consisting of the startTime and StarID

    if (writeStarPositions)
    {
        Log.info("Camera: writing star positions to HDF5 file");

        vector<double> time;
        for(auto keyValuePair: detectedStarInfo) time.push_back(keyValuePair.first);
        if (!time.empty())
        {
            hdf5File.writeArray("StarPositions/", "Time", time.data(), time.size());
        }
        else
        {
            Log.warning("Camera: No star positions to write to HDF5 file.");
        }

        // For each of the exposures, make a subgroup and write the position and flux of all detected stars.
        // Because some stars at the edge may jitter in and out of the subfield from one exposure to the other,
        // the written arrays may not be equally long for each exposure.

        for (int n = 0; n < time.size(); n++)
        {
            // Make the sub-group

            stringstream myStream;
            myStream << "Exposure" << setfill('0') << setw(6) << beginExposureNr + n;
            const string exposureGroupName = "/StarPositions/" + myStream.str();
            hdf5File.createGroup(exposureGroupName);

            // Collect the different time series. For the positions, we only compute the sum, so we still need
            // to divide by N to compute the average, where N is the number of times the star was detected to be
            // in the subfield during an exposure.

            vector<unsigned int> starIDs;
            vector<double> xFPmm;
            vector<double> yFPmm;
            vector<double> rowPix;
            vector<double> colPix;
            vector<double> flux;

            for(auto keyValuePair: detectedStarInfo[time[n]])
            {
                const unsigned int starID = keyValuePair.first;
                starIDs.push_back(starID);                       // list of starIDs for this exposure only
                xFPmm.push_back(detectedStarInfo[time[n]][starID][0] / detectedStarInfo[time[n]][starID][5]);
                yFPmm.push_back(detectedStarInfo[time[n]][starID][1] / detectedStarInfo[time[n]][starID][5]);
                rowPix.push_back(detectedStarInfo[time[n]][starID][2] / detectedStarInfo[time[n]][starID][5]);
                colPix.push_back(detectedStarInfo[time[n]][starID][3] / detectedStarInfo[time[n]][starID][5]);
                flux.push_back(detectedStarInfo[time[n]][starID][4]);
            }

            // Write the time series to HDF5

            if(!starIDs.empty())
            {
                hdf5File.writeArray(exposureGroupName, "starID", starIDs.data(), starIDs.size());
                hdf5File.writeArray(exposureGroupName, "xFPmm",  xFPmm.data(),   xFPmm.size());
                hdf5File.writeArray(exposureGroupName, "yFPmm",  yFPmm.data(),   yFPmm.size());
                hdf5File.writeArray(exposureGroupName, "rowPix", rowPix.data(),  rowPix.size());
                hdf5File.writeArray(exposureGroupName, "colPix", colPix.data(),  colPix.size());
                hdf5File.writeArray(exposureGroupName, "flux",   flux.data(),    flux.size());
            }
        }
    }
    else 
    {
        Log.warning("Camera: No star positions written to HDF5 file by user demand (see input file).");
    }


    // If the ghost option was set, also write for each exposure the info of the ghost stars to the HDF5 file.

    if (includeGhosts && writeGhostPositions)
    {
        Log.info("Camera: writing pointlike ghost positions to HDF5 file");

        vector<double> time;
        for(auto keyValuePair: detectedPointLikeGhostInfo) time.push_back(keyValuePair.first);
        if (!time.empty())
        {
            hdf5File.writeArray("PointLikeGhostPositions/", "Time", time.data(), time.size());
        }
        else
        {
            Log.warning("Camera: No point-like ghost positions to write to HDF5 file.");
        }

        for (int n = 0; n < time.size(); n++)
        {
            stringstream myStream;
            myStream << "Exposure" << setfill('0') << setw(6) << beginExposureNr + n;

            // Write the info for the point-like ghost star positions to HDF5

            vector<unsigned int> starIDs;
            vector<double> xFPmm;
            vector<double> yFPmm;
            vector<double> rowPix;
            vector<double> colPix;
            vector<double> flux;
            vector<double> ghostRadius;

            for(auto keyValuePair: detectedPointLikeGhostInfo[time[n]])
            {
                const unsigned int starID = keyValuePair.first;
                starIDs.push_back(starID);                       // list of starIDs for this exposure only
                xFPmm.push_back(detectedPointLikeGhostInfo[time[n]][starID][0] / detectedPointLikeGhostInfo[time[n]][starID][5]);
                yFPmm.push_back(detectedPointLikeGhostInfo[time[n]][starID][1] / detectedPointLikeGhostInfo[time[n]][starID][5]);
                rowPix.push_back(detectedPointLikeGhostInfo[time[n]][starID][2] / detectedPointLikeGhostInfo[time[n]][starID][5]);
                colPix.push_back(detectedPointLikeGhostInfo[time[n]][starID][3] / detectedPointLikeGhostInfo[time[n]][starID][5]);
                flux.push_back(detectedPointLikeGhostInfo[time[n]][starID][4]);
            }

            const string pointLikeGhostGroupName = "/PointLikeGhostPositions/" + myStream.str();
            hdf5File.createGroup(pointLikeGhostGroupName);

            if(!starIDs.empty())
            {
                hdf5File.writeArray(pointLikeGhostGroupName, "starID", starIDs.data(), starIDs.size());
                hdf5File.writeArray(pointLikeGhostGroupName, "xFPmm",  xFPmm.data(),   xFPmm.size());
                hdf5File.writeArray(pointLikeGhostGroupName, "yFPmm",  yFPmm.data(),   yFPmm.size());
                hdf5File.writeArray(pointLikeGhostGroupName, "rowPix", rowPix.data(),  rowPix.size());
                hdf5File.writeArray(pointLikeGhostGroupName, "colPix", colPix.data(),  colPix.size());
                hdf5File.writeArray(pointLikeGhostGroupName, "flux",   flux.data(),    flux.size());
            }


            // Write the info for the extended ghost star positions to HDF5

            Log.info("Camera: writing extended ghost positions to HDF5 file");

            starIDs.clear();
            xFPmm.clear();
            yFPmm.clear();
            rowPix.clear();
            colPix.clear();
            flux.clear();
            ghostRadius.clear();
        }

        time.clear();
        for(auto keyValuePair: detectedExtendedGhostInfo) time.push_back(keyValuePair.first);
        if (!time.empty())
        {
            hdf5File.writeArray("ExtendedGhostPositions/", "Time", time.data(), time.size());
        }
        else
        {
            Log.warning("Camera: No extended ghost positions to write to HDF5 file.");
        }

        for (int n = 0; n < time.size(); n++)
        {
            stringstream myStream;
            myStream << "Exposure" << setfill('0') << setw(6) << beginExposureNr + n;


            // Write the info for the extended ghost star positions to HDF5

            vector<unsigned int> starIDs;
            vector<double> xFPmm;
            vector<double> yFPmm;
            vector<double> rowPix;
            vector<double> colPix;
            vector<double> flux;
            vector<double> ghostRadius;


            for(auto keyValuePair: detectedExtendedGhostInfo[time[n]])
            {
                const unsigned int starID = keyValuePair.first;
                starIDs.push_back(starID);                       // list of starIDs for this exposure only
                xFPmm.push_back(detectedExtendedGhostInfo[time[n]][starID][0] / detectedExtendedGhostInfo[time[n]][starID][5]);
                yFPmm.push_back(detectedExtendedGhostInfo[time[n]][starID][1] / detectedExtendedGhostInfo[time[n]][starID][5]);
                rowPix.push_back(detectedExtendedGhostInfo[time[n]][starID][2] / detectedExtendedGhostInfo[time[n]][starID][5]);
                colPix.push_back(detectedExtendedGhostInfo[time[n]][starID][3] / detectedExtendedGhostInfo[time[n]][starID][5]);
                flux.push_back(detectedExtendedGhostInfo[time[n]][starID][4]);
                ghostRadius.push_back(detectedExtendedGhostInfo[time[n]][starID][6] / detectedExtendedGhostInfo[time[n]][starID][5]);
            }
        
            const string extendedGhostGroupName = "/ExtendedGhostPositions/" + myStream.str();
            hdf5File.createGroup(extendedGhostGroupName);
        
            if(!starIDs.empty())
            {
                hdf5File.writeArray(extendedGhostGroupName, "starID", starIDs.data(), starIDs.size());
                hdf5File.writeArray(extendedGhostGroupName, "xFPmm",  xFPmm.data(),   xFPmm.size());
                hdf5File.writeArray(extendedGhostGroupName, "yFPmm",  yFPmm.data(),   yFPmm.size());
                hdf5File.writeArray(extendedGhostGroupName, "rowPix", rowPix.data(),  rowPix.size());
                hdf5File.writeArray(extendedGhostGroupName, "colPix", colPix.data(),  colPix.size());
                hdf5File.writeArray(extendedGhostGroupName, "flux",   flux.data(),    flux.size());
                hdf5File.writeArray(extendedGhostGroupName, "radius", ghostRadius.data(), ghostRadius.size());
            }
        }
    } 

    

    // Write the total sky background flux values [photons/pixel/exposure] to HDF5 in a custom group

    hdf5File.writeArray("Background/", "skyBackground", skyBackgroundValues.data(), skyBackgroundValues.size());

    // Write the transmissionEfficiency values for each exposureTime to HDF5 in a custom group
    if (writeTransmissionEfficiency)
    {
    hdf5File.writeArray("TransmissionEfficiency/", "transmissionEfficiency", transmissionEfficiencyValues.data(), transmissionEfficiencyValues.size());
    }

}












/**
 * \brief Configure the Camera object using the ConfigurationParameters
 *
 * \param configParam: the configuration parameters
 */

void Camera::configure(ConfigurationParameters &configParam)
{
    numExposures           = configParam.getInteger("ObservingParameters/NumExposures");
    beginExposureNr        = configParam.getInteger("ObservingParameters/BeginExposureNr");


    // The focal length can either be a fixed value, or given by a time series in a file

    string focalLengthSource = configParam.getString("Camera/FocalLength/Source");
    if (focalLengthSource == "ConstantValue")
    {
        double focalLengthValue = configParam.getDouble("Camera/FocalLength/ConstantValue") * 1000;     // [m] -> [mm]
        focalLength = new Parameter<double>(focalLengthValue);

        Log.info("Camera: Using a constant focal length: " + to_string(focalLengthValue) + " m");
    }
    else if (focalLengthSource == "FromFile")
    {
        string focalLengthInputFile = configParam.getAbsoluteFilename("Camera/FocalLength/FromFile");
        focalLength = new Parameter<double>(focalLengthInputFile, 1000);                                // [m] -> [mm]

        Log.info("Camera: Reading focal length values from " + focalLengthInputFile);
    }



    // The focal plane orientation can either be a fixed value, or given by a time series in a file

    string focalPlaneAngleSource = configParam.getString("Camera/FocalPlaneOrientation/Source");
    if (focalPlaneAngleSource == "ConstantValue")
    {
        double focalPlaneAngleValue = deg2rad(configParam.getDouble("Camera/FocalPlaneOrientation/ConstantValue")); // [deg]->[rad]
        focalPlaneAngle = new Parameter<double>(focalPlaneAngleValue);                                              // [rad]

        Log.info("Camera: Using a constant focal plane orientation: " + to_string(focalPlaneAngleValue) + " m");
    }
    else if (focalPlaneAngleSource == "FromFile")
    {
        string focalPlaneAngleInputFile = configParam.getAbsoluteFilename("Camera/FocalPlaneOrientation/FromFile");
        focalPlaneAngle = new Parameter<double>(focalPlaneAngleInputFile, deg2rad(1.0));                           // [deg]->[rad]

        Log.info("Camera: Reading focal plane orientation from " + focalPlaneAngleInputFile);
    }



    // The distortion coefficients can either be a fixed value, or given by a time series in a file
    // Idem for the inverse distortion coefficients.

    includeFieldDistortion = configParam.getBoolean("Camera/IncludeFieldDistortion");

    if (includeFieldDistortion)
    {
        distortionModel              = configParam.getString("Camera/FieldDistortion/Type");
        string fieldDistortionSource = configParam.getString("Camera/FieldDistortion/Source");
        if (fieldDistortionSource == "ConstantValue")
        {
            // Read the distortion coefficients from the yaml input file. Currently vector<>s are
            // being read while Parameter<> expects array<>s. So we'll have to do some overhead
            // to convert one to the other.

            vector<double> distortionCoefVector        = configParam.getDoubleVector("Camera/FieldDistortion/ConstantCoefficients");
            vector<double> inverseDistortionCoefVector = configParam.getDoubleVector("Camera/FieldDistortion/ConstantInverseCoefficients");
            array<double, 3> distortionCoefArray, inverseDistortionCoefArray;

            if ((distortionCoefVector.size() != 3) || (inverseDistortionCoefVector.size() != 3))
            {
                string msg = "Camera::configure(): number of (inverse) distortion coefficients in input yaml file != 3.";
                throw ConfigurationException(msg);
            }
            else
            {
                copy(distortionCoefVector.begin(), distortionCoefVector.end(), distortionCoefArray.begin());
                copy(inverseDistortionCoefVector.begin(), inverseDistortionCoefVector.end(), inverseDistortionCoefArray.begin());
            }

            distortionCoef        = new Parameter<double, 3>(distortionCoefArray);
            inverseDistortionCoef = new Parameter<double, 3>(inverseDistortionCoefArray);

            Log.info("Camera: Using a constant distortion law");
        }
        else if (fieldDistortionSource == "FromFile")
        {
            string distortionInputFile = configParam.getAbsoluteFilename("Camera/FieldDistortion/CoefficientsFromFile");
            string invDistortionInputFile = configParam.getAbsoluteFilename("Camera/FieldDistortion/InverseCoefficientsFromFile");
            distortionCoef = new Parameter<double, 3>(distortionInputFile, 1);
            inverseDistortionCoef = new Parameter<double, 3>(invDistortionInputFile, 1);

            Log.info("Camera: Reading distortion coefficients from " + distortionInputFile);
            Log.info("Camera: Reading inverse distortion coefficients from " + invDistortionInputFile);
        }
    }
    else
    {
        Log.info("Camera: Ignoring field distortion");
    }


    // Configure the ghost star parameters 

    includeGhosts = configParam.getBoolean("Camera/IncludeGhosts");

    if(includeGhosts)
    {
        distanceCutOffPointLikeGhosts = deg2rad(configParam.getDouble("Camera/Ghosts/PointLike/DistanceCutOff"));   // [radians]
        fluxRatioOnAxisPointLikeGhosts = configParam.getDouble("Camera/Ghosts/PointLike/FluxRatio") / 100.0;
        distanceRatioExtendedGhosts = configParam.getDouble("Camera/Ghosts/Extended/DistanceRatio");
        fluxRatioExtendedGhosts = configParam.getDouble("Camera/Ghosts/Extended/FluxRatio") / 100.0;

        vector<double> extendedGhostRadiusCoefVector = configParam.getDoubleVector("Camera/Ghosts/Extended/RadiusCoefficients");
        array<double, 3> extendedGhostRadiusCoefArray;
        copy(extendedGhostRadiusCoefVector.begin(), extendedGhostRadiusCoefVector.end(), extendedGhostRadiusCoefArray.begin());

        extendedGhostRadiusCoefficients = new Parameter<double, 3>(extendedGhostRadiusCoefArray);
    }
    else
    {
        Log.info("Camera: Ignoring ghosts");
    }


    plateScale             = configParam.getDouble("Camera/PlateScale");
    throughputBandwidth    = configParam.getDouble("Camera/ThroughputBandwidth");
    throughputLambdaC      = configParam.getDouble("Camera/ThroughputLambdaC");

    includeAberrationCorrection = configParam.getBoolean("Camera/IncludeAberrationCorrection");
    aberrationCorrectionType    = configParam.getString("Camera/AberrationCorrection/Type");


    fluxOfV0Star           = configParam.getDouble("ObservingParameters/Fluxm0");                 // [phot/s/m^2/nm]
    userGivenSkyBackground = configParam.getDouble("Sky/SkyBackground");          // [phot/pix/s]

    writeStarPositions     = configParam.getBoolean("ControlHDF5Content/WriteStarPositions");
    writeGhostPositions    = configParam.getBoolean("ControlHDF5Content/WriteGhostPositions");
    writeTransmissionEfficiency = configParam.getBoolean("ControlHDF5Content/WriteTransmissionEfficiency");
    
}











/**
 * \brief Update the time dependent parameters of the Camera to their
 *        value at the given time point
 *
 * \param time: current time
 *
 * \return
 */

void Camera::updateParameters(double time)
{
    focalLength->updateValue(time);
    focalPlaneAngle->updateValue(time);

    if (includeFieldDistortion)
    {
        distortionCoef->updateValue(time);
        inverseDistortionCoef->updateValue(time);
    }
}










/**
 * \brief      Specify the type of fit function used to fit the distortion
 *
 * \param      polynomial         The polynomial that describes the distortion
 * \param      inversePolynomial  The inverse polynomial
 */

//void Camera::setDistortionPolynomial(Polynomial1D &polynomial, Polynomial1D &inversePolynomial)
//{
//    this->polynomial = polynomial;
//    this->inversePolynomial = inversePolynomial;
//}













/**
 * \brief Expose the sub-field to the stars.
 *
 * \param detector: Detector for which to make a rough selection of stars.
 * \param startTime: Start time of the exposure [s].
 * \param exposureTime: Duration of one exposure [s].
 * \param readoutTimeBeforeNextExposure: Duration of the readout that takes place before the next exposure starts [s].
 */
void Camera::exposeDetectorWithStars(Detector &detector, double startTime, double exposureTime, double readoutTimeBeforeNextExposure)
{
    // Make a rough selection of:
    //  - stars that are on or near the sub-field (or will produce an extended ghost on or near the sub-field)
    //  - stars that produce a symmetric point-like ghost on or near the sub-field the sub-field (without 
    //    accounting for the distance cut-off)

    unsigned long numStars, numPointLikeGhosts;
    tie(numStars, numPointLikeGhosts) = makeStarCatalogSelection(detector, startTime, exposureTime, readoutTimeBeforeNextExposure);

    // If the telescope and/or platform show small variations (e.g. due to jitter) during the exposure,
    // the exposure time is split up in many small intervals, to track the effect of these variations
    // on the exposure. The largest time interval for which the variations can still be reliably tracked
    // is called the heartbeatInterval. The time step used should be either the heartbeat interval or the
    // expsosure time whatever is smallest.

    double timeStep = min(telescope.getHeartbeatInterval(), exposureTime);

    // Later we will have to convert the magnitudes from the star catalogues to fluxes.  Here we
    // pre-compute a constant flux factor [photons / s] that we will need for the conversion of 
    // all stars.
    // The value of the degrading transmission efficiency that is used here, is the one at the start
    // of the current exposure.

    double transmissionEfficiency = telescope.getTransmissionEfficiency(startTime);
    const double fluxFactor = fluxOfV0Star * throughputBandwidth * transmissionEfficiency * telescope.getLightCollectingArea();

    // Update the internal clock

    internalTime = startTime;

    // Placeholders

    unsigned int numStarsInSubField, numExtendedGhostsInSubField, numPointLikeGhostsInSubField;
    unsigned long starID;
    double raStar, decStar, magStar, rowStar, columnStar, xStar, yStar, fluxStar;
    double rowGhost, columnGhost, xGhost, yGhost, fluxGhost, radiusExtendedGhost, distanceOA, fluxRatioPointLikeGhosts;
    bool isStarInSubField, isGhostInSubField;
    array<double, 3> coefficients;
    
    // Take the flux of the stars and ghosts (if enabled) into account, breaking up the
    // exposure time in small (heartbeat) intervals to track jitter during exposure

    while (internalTime < startTime + exposureTime)
    {
        // Update the time-dependent parameters (if any) of some classes to to their value at the current time.

        this->updateParameters(internalTime);
        telescope.updateParameters(internalTime);
        detector.updateParameters(internalTime);
        sky.updateParameters(internalTime);

        if(includeGhosts)
            coefficients = (*extendedGhostRadiusCoefficients)();

        // Loop over the selected stars and add their flux to the sub-fild
        // Also add the extended ghosts (if enabled)

        numStarsInSubField = 0;
        numExtendedGhostsInSubField = 0;

        for (unsigned int starIndex = 0; starIndex < numStars; starIndex++)
        {
            // Calculate the focal-plane coordinates of the current star
            // (apply field distortion, if enabled)

            tie(starID, raStar, decStar, magStar) = sky.getSelectedStar(starIndex);     // Sky coordinates in radians
            tie(xStar, yStar) = skyToFocalPlaneCoordinates(raStar, decStar);            // [mm]

            if (includeFieldDistortion)

                tie(xStar, yStar) = undistortedToDistortedFocalPlaneCoordinates(xStar, yStar);

            // Total flux of the star acquired over the time step [photons]
            // (photons are always an integer number, so round down)

            fluxStar = floor(fluxFactor * pow(10.0, -0.4 * magStar) * timeStep);

            // Try to add the flux at the appropriate pixel in the sub-field
            // Returned:
            //      - whether or not the source falls in the sub-field
            //      - sub-field (not CCD) row and column number at which the flux was added

            tie(isStarInSubField, rowStar, columnStar) = detector.addFlux(xStar, yStar, fluxStar);

            // If the star is indeed in the sub-field, collect the following information to later write to HDF5:
            //    1) average focal-plane coordinates (x, y) of the star during the exposure [mm]
            //    2) average pixel coordinates (row, column) of the star on the CCD during the exposure [pixels]
            //    3) the total number of photons gathered of this star during the exposure [photons]
            //    4) the total number of times that the star was in the sub-field during the exposure
            // Note: Due to jitter, the star can move in and out the sub-field during the exposure

            if (isStarInSubField)
            {
                numStarsInSubField++;

                // If this is the first time we encounter this startTime, initialise the information

                if (detectedStarInfo.find(startTime) == detectedStarInfo.end())
                {
                    detectedStarInfo[startTime][starID] = {{xStar, yStar, rowStar, columnStar, fluxStar, 1.0}};
                }
                else
                {
                    // If this is the first time that we encounter this star ID associated with this start time,
                    // initialise the information. If not, just update the info.

                    if (detectedStarInfo[startTime].find(starID) == detectedStarInfo[startTime].end())
                    {
                        detectedStarInfo[startTime][starID] = {{xStar, yStar, rowStar, columnStar, fluxStar, 1.0}};
                    }
                    else
                    {
                        detectedStarInfo[startTime][starID][0] += xStar;        // Will be used to compute average focal-plane x-coordinate during the exposure
                        detectedStarInfo[startTime][starID][1] += yStar;        // Will be used to compute average focal-plane y-cooridnate during the exposure
                        detectedStarInfo[startTime][starID][2] += rowStar;      // Will be used to compute average pixel row coordinate during the exposure
                        detectedStarInfo[startTime][starID][3] += columnStar;   // Will be used to compute average pixel column coodinate during the exposure
                        detectedStarInfo[startTime][starID][4] += fluxStar;     // Total flux [photons]
                        detectedStarInfo[startTime][starID][5] += 1;            // # of times a star was on the subfield during an exposure
                    }
                }
            }

            if(includeGhosts)
            {
                // Focal-plane coordinates of the centre of the extended ghost

                xGhost = distanceRatioExtendedGhosts * xStar;
                yGhost = distanceRatioExtendedGhosts * yStar;

                // Total flux of the extended ghost acquired over the time step [photons]
                //  -> fraction of the flux of the originating star
                // (photons are always an integer number, so round down)

                fluxGhost = floor(fluxFactor * pow(10.0, -0.4 * magStar) * timeStep * fluxRatioExtendedGhosts);

                // The radius of the extended ghost is described by a 2nd-degree polynomial

                distanceOA = rad2deg(this->getGnomonicRadialDistanceFromOpticalAxis(xGhost, yGhost));    // [degrees]
                radiusExtendedGhost = coefficients[0] * pow(distanceOA, 2) + coefficients[1] * distanceOA + coefficients[2];    // [mm]

                // Try to add the flux at the appropriate pixels in the sub-field
                // Returned:
                //      - whether or not the extended ghost falls in the sub-field (at least part of it)
                //      - sub-field (not CCD) row and column number of the centre of the extended ghost

                tie(isGhostInSubField, rowGhost, columnGhost) = detector.addExtendedGhost(xGhost, yGhost, radiusExtendedGhost, fluxGhost);

                // If the extended ghosts is indeed in the sub-field, collect the following information to later write to HDF5:
                //    1) average focal-plane coordinates (x, y) of the centre of the extended ghost during the exposure [mm]
                //    2) average pixel coordinates (row, column) of the extended ghost on the CCD during the exposure [pixels]
                //    3) the total number of photons gathered of this extended ghost during the exposure [photons]
                //    4) the total number of times that the extended ghost was in the sub-field during the exposure
                //    5) the average size of the extended ghost during the exposure [mm]
                // Note: Due to jitter, the extended ghost can move in and out the sub-field during the exposure

                if(isGhostInSubField)
                {
                    numExtendedGhostsInSubField++;

                    if(detectedExtendedGhostInfo.find(startTime) == detectedExtendedGhostInfo.end())
                    {   
                        detectedExtendedGhostInfo[startTime][starID] = {{xGhost, yGhost, rowGhost, columnGhost, fluxGhost, 1.0, radiusExtendedGhost}};
                    }

                    else
                    {
                        detectedExtendedGhostInfo[startTime][starID][0] += xGhost;        // Will be used to compute average focal-plane x-coordinate during the exposure
                        detectedExtendedGhostInfo[startTime][starID][1] += yGhost;        // Will be used to compute average focal-plane y-coorindate during the exposure
                        detectedExtendedGhostInfo[startTime][starID][2] += rowGhost;      // Will be used to compute average pixel row coordinate during the exposure
                        detectedExtendedGhostInfo[startTime][starID][3] += columnGhost;   // Will be used to compute average pixel column coordinate during the exposure
                        detectedExtendedGhostInfo[startTime][starID][4] += fluxGhost;     // Total flux [photons]
                        detectedExtendedGhostInfo[startTime][starID][5] += 1;             // # of times a star was on the subfield during an exposure
                        detectedExtendedGhostInfo[startTime][starID][6] += radiusExtendedGhost;     // Radius of the extended ghost [mm]
                    }
                }
            }
        }

        if(includeGhosts)
        {
            // Loop over the selected originators of symmetric point-like ghosts and
            // add their flux to the sub-field (if enabled)

            numPointLikeGhostsInSubField = 0;

            for (unsigned int starIndex = 0; starIndex < numPointLikeGhosts; starIndex++)
            {
                // Calculate the focal-plane coordinates of the ghost produced by the current star
                // (apply field distortion, if enabled)

                tie(starID, raStar, decStar, magStar) = sky.getSelectedGhostOrig(starIndex);    // Sky coordinates of the originator [radians]
                tie(xStar, yStar) = skyToFocalPlaneCoordinates(raStar, decStar);                // Focal-plane coordinate of the originator [mm]

                if (includeFieldDistortion)
                {
                    tie(xStar, xStar) = undistortedToDistortedFocalPlaneCoordinates(xStar, xStar);
                }

                // Consider the distance cut-off
                // (only sources that are close enough to the OA will produce a symmetric point-like ghost)

                distanceOA = this->getGnomonicRadialDistanceFromOpticalAxis(xStar, yStar);      // [radians]
                
                if(distanceOA < distanceCutOffPointLikeGhosts)
                {
                    // Linear decrease in flux ratio from on-axis (fluxRatioOnAxisPointLikeGhosts) to the distance
                    // cut-off (distanceCutOffPointLikeGhosts), where the fluxRatio is zero.  Beyond the distance
                    // cut-off no point-like ghosts will occur (as the reflected rays will not make it through the
                    // pupil around L3)
    
                    fluxRatioPointLikeGhosts = (-fluxRatioOnAxisPointLikeGhosts * distanceOA / distanceCutOffPointLikeGhosts) + fluxRatioOnAxisPointLikeGhosts;

                    // Focal-plane coordinates of the centre of the symmetric point-like ghost

                    xGhost = -xStar;     // Symmetry w.r.t. OA
                    yGhost = -yStar;     // Symmetry w.r.t. OA

                    // Total flux of the originator acquired over the time step [photons]
                    // (photons are always an integer number, so round down)

                    // fluxStar = floor(fluxFactor * pow(10.0, -0.4 * magStar) * timeStep);

                    // Total flux of the symmetric point-like source ghost acquired over the time step [photons]
                    //  -> fraction of the flux of the originating star
                    // (photons are always an integer number, so round down)

                    fluxGhost = floor(fluxFactor * pow(10.0, -0.4 * magStar) * timeStep * fluxRatioPointLikeGhosts);

                    // Try to add the flux at the appropriate pixel in the sub-field
                    // Returned:
                    //      - whether or not the source falls in the sub-field
                    //      - sub-field (not CCD) row and column number at which the flux was added

                    tie(isGhostInSubField, rowGhost, columnGhost) = detector.addFlux(xGhost, yGhost, fluxGhost);

                    // If the symmetric point-like ghosts is indeed in the sub-field, collect the following information to later write to HDF5:
                    //    1) average focal-plane coordinates (x, y) of the symmetric point-like during the exposure [mm]
                    //    2) average pixel coordinates (row, column) of the symmetric point-like on the CCD during the exposure [pixels]
                    //    3) the total number of photons gathered of this symmetric point-like during the exposure [photons]
                    //    4) the total number of times that the symmetric point-like was in the sub-field during the exposure
                    // Note: Due to jitter, the symmetric point-like can move in and out the sub-field during the exposure

                    if(isGhostInSubField)
                    {
                        numPointLikeGhostsInSubField++;

                        if(detectedPointLikeGhostInfo.find(startTime) == detectedPointLikeGhostInfo.end())
                        {
                            detectedPointLikeGhostInfo[startTime][starID] = {{xGhost, yGhost, rowGhost, columnGhost, fluxGhost, 1.0}};
                        }

                        else
                        {
                            detectedPointLikeGhostInfo[startTime][starID][0] += xGhost;        // Will be used to compute average focal-plane x-coordinate during the exposure
                            detectedPointLikeGhostInfo[startTime][starID][1] += yGhost;        // Will be used to compute average focal-plane y-coordinate during the exposure
                            detectedPointLikeGhostInfo[startTime][starID][2] += rowGhost;      // Will be used to compute average pixel row coordinate during the exposure
                            detectedPointLikeGhostInfo[startTime][starID][3] += columnGhost;   // Will be used to compute average pixel column coordinate during the exposure
                            detectedPointLikeGhostInfo[startTime][starID][4] += fluxGhost;     // Total flux [photons]
                            detectedPointLikeGhostInfo[startTime][starID][5] += 1;             // # of times a star was on the sub-field during an exposure
                        }
                    }
                }
            }
        }


        Log.debug("Camera: at time " + to_string(internalTime) + ": incremented flux of " + to_string(numStarsInSubField) + " stars in sub-field");
        Log.debug("Camera: at time " + to_string(internalTime) + ": incremented flux of " + to_string(numPointLikeGhostsInSubField) + " point-like ghosts in sub-field");
        Log.debug("Camera: at time " + to_string(internalTime) + ": incremented flux of " + to_string(numExtendedGhostsInSubField) + " extended ghosts in sub-field");


        // Update the clock. Normally with 'timeStep', but if adding timeStep would overstep
        // the total exposure time, take the small rest time instead (but update the internal time first!).

        internalTime += timeStep;
        timeStep = min(timeStep, startTime + exposureTime - internalTime);
    }
}

/**
 * \brief Make a rough selection of stars in the star catalogue, that are on or near the sub-field,
 *        and the are on or near the field that produces symmetric point-like ghosts on or near the
 *        sub-field (without accounting for the distance cut-off).  The latter stars are only selected
 *        if ghosts are to be included in the simulation.
 * 
 * To make a rough selection of the stars from the input catalogue that are on or near the sub-field, 
 * consider all stars that are within a certain distance from the centre of the sub-field:
 *      - calculate the sky coordinates of the centre of the sub-field (taking field distortion into account, if enabled);
 *      - the distance between the lower left (00) and the upper right (11) corner of the sub-field will be a 1st-order
 *        estimate of the diameter of the circle around the centre of the sub-field -> we will enlarge this a bit to be
 *        on the safe side.
 * Take a similar approach to select the stars on the opposite side of the optical axis as potential originators of
 * symmetric point-like ghosts.
 * 
 * \param detector: Detector for which to make a rough selection of stars.
 * \param startTime: Start time of the exposure [s].
 * \param exposureTime: Duration of one exposure [s].
 * \param readoutTimeBeforeNextExposure: Duration of the readout that takes place before the next exposure starts [s].
 * 
 * \return: Number of selected stars that are on or near the sub-field, and number of selected stars that produces
 *          symmetric point-like ghosts on or near the sub-field (without accounting for the distance cut-off).  The
 *          latter is zero if ghosts are not to be included in the simulation.
 */
tuple<unsigned long, unsigned long> Camera::makeStarCatalogSelection(Detector &detector, double startTime, double exposureTime, double readoutTimeBeforeNextExposure)
{
    // Undistorted focal-plane coordinates of the centre, and the lower left and upper right corner
    // of the sub-field

    double centerSubFieldXmm, centerSubFieldYmm;
    tie(centerSubFieldXmm, centerSubFieldYmm) = detector.getFocalPlaneCoordinatesOfSubfieldCenter();

    double corner00Xmm, corner00Ymm, corner11Xmm, corner11Ymm, dummy;
    tie(corner00Xmm, corner00Ymm, dummy, dummy, corner11Xmm, corner11Ymm, dummy, dummy) = detector.getFocalPlaneCoordinatesOfSubfieldCorners();

    // Apply field distortion (if enabled)

    if (includeFieldDistortion)
    {
        Log.info("Camera: including field distortion");

        tie(centerSubFieldXmm, centerSubFieldYmm) = distortedToUndistortedFocalPlaneCoordinates(centerSubFieldXmm, centerSubFieldYmm);
        tie(corner00Xmm, corner00Ymm) = distortedToUndistortedFocalPlaneCoordinates(corner00Xmm, corner00Ymm);
        tie(corner11Xmm, corner11Ymm) = distortedToUndistortedFocalPlaneCoordinates(corner11Xmm, corner11Ymm);
    }

    // Calculate the pixel coordinates of the sub-field centre in the CCD reference frame
    // (just for logging purposes)

    double centerRow, centerCol;
    tie(centerRow, centerCol) = detector.focalPlaneToPixelCoordinates(centerSubFieldXmm, centerSubFieldYmm);

    Log.debug("Camera: center of subfield at CCD (row, col) = (" + to_string(centerRow) + ", " + to_string(centerCol) + ") pix");
    Log.debug("Camera: center of subfield at (Xmm, Ymm) = (" + to_string(centerSubFieldXmm) + ", " + to_string(centerSubFieldYmm) + ") mm");
    Log.debug("Camera: lower left corner of subfield at (Xmm, Ymm) = (" + to_string(corner00Xmm) + ", " + to_string(corner00Ymm) + ") mm");
    Log.debug("Camera: upper right corner of subfield at (Xmm, Ymm) = (" + to_string(corner11Xmm) + ", " + to_string(corner11Ymm) + ") mm");

    // Conversion to equatorial sky coordinates (alpha, delta) [radians]

    double centerSubFieldRA, centerSubFieldDec;
    tie(centerSubFieldRA, centerSubFieldDec) = focalPlaneToSkyCoordinates(centerSubFieldXmm, centerSubFieldYmm);

    double corner00RA, corner00Dec;
    tie(corner00RA, corner00Dec) = focalPlaneToSkyCoordinates(corner00Xmm, corner00Ymm);

    double corner11RA, corner11Dec;
    tie(corner11RA, corner11Dec) = focalPlaneToSkyCoordinates(corner11Xmm, corner11Ymm);

    Log.debug("Camera: center of subfield at (alpha, delta) = (" + to_string(rad2deg(centerSubFieldRA)) + ", " + to_string(rad2deg(centerSubFieldDec)) + ") deg");
    Log.debug("Camera: lower left corner of subfield at (alpha, delta) = (" + to_string(rad2deg(corner00RA)) + ", " + to_string(rad2deg(corner00Dec)) + ") deg");
    Log.debug("Camera: upper right corner of subfield at (alpha, delta) = (" + to_string(rad2deg(corner11RA)) + ", " + to_string(rad2deg(corner11Dec)) + ") deg");

    // Compute the angular distance on the sky between the lower left and the upper right corner
    // of the sub-field, to estimate the "radius" of the sub-field.

    SkyCoordinates skyCoordinates00(corner00RA, corner00Dec, Angle::radians);
    SkyCoordinates skyCoordinates11(corner11RA, corner11Dec, Angle::radians);

    double radius = angularDistanceBetween(skyCoordinates00, skyCoordinates11, Angle::radians) / 2.0;   // [radians]

    Log.debug("Camera: semi-diagonal of subfield = " + to_string(rad2deg(radius)) + " deg");

    // Select the stars from the catalogue that are on or near the sub-field (i.e. in a radius 
    // around the centre of the sub-field). Take the radius a bit larger so that the queried area includes 
    // possible small shifts of the projected subfield because of jitter.

    const unsigned long numStars = sky.selectStarsWithinRadiusFrom(centerSubFieldRA, centerSubFieldDec, radius * 1.1, Angle::radians);
    Log.info("Camera: Found " + to_string(numStars) + " stars on and near the sub-field");

    // Select the stars on the opposite side of the optical axis that potentially cause symmetric point-like
    // ghosts on or near the sub-field.  The cut-off on the distance to the OA is not considered yet.

    unsigned long numPointLikeGhosts = 0;

    if(includeGhosts)
    {
        // Apply the same procedure for the originators of symmetric point-like ghosts on or near
        // the sub-field

        Log.debug("Camera: center of ghost field at (Xmm, Ymm) = (" + to_string(-centerSubFieldXmm) + ", " + to_string(-centerSubFieldYmm) + ") mm");

        double centerGhostFieldRA, centerGhostFieldDec;
        tie(centerGhostFieldRA, centerGhostFieldDec) = focalPlaneToSkyCoordinates(-centerSubFieldXmm, -centerSubFieldYmm);

        Log.debug("Camera: center of ghost field at (alpha, delta) = (" + to_string(rad2deg(centerGhostFieldRA)) + ", " + to_string(rad2deg(centerGhostFieldDec)) + ") deg");

        numPointLikeGhosts = sky.selectGhostOrigsWithinRadiusFrom(centerGhostFieldRA, centerGhostFieldDec, radius * 1.1, Angle::radians);
        Log.info("Camera: Found " + to_string(numPointLikeGhosts) + " point-like ghosts on and near the sub-field (not distance cut-off incl. yet)");
    }

    // Apply aberration correction

    if (includeAberrationCorrection)
    {
        // The time at the middle of the time series is the time when the Sun is defined to be 180 degrees away from platform pointing

        double timeMiddle = numExposures * (exposureTime + readoutTimeBeforeNextExposure) / 2.0;

        // Get the apparent position of the stars, i.e. apply the differential aberration correction to
        // the positions of the selected stars and originators of symmetrical point-like ghosts
        // We do this calcuation only once per exposure as the effect is negligible within the exposure time

        Log.info("Camera: applying " + aberrationCorrectionType + " aberration correction to the selected stars.");
        sky.aberrateSelectedStarPositions(platform, aberrationCorrectionType, startTime, timeMiddle);

        if(includeGhosts)
        {
            Log.info("Camera: applying " + aberrationCorrectionType + " aberration correction to the selected originators of symmetrical point-like ghosts.");
            sky.aberrateSelectedGhostOrigPositions(platform, aberrationCorrectionType, startTime, timeMiddle);
        }
    }

    return tie(numStars, numPointLikeGhosts);
}





/**
 * \brief Expose the sub-field to the sky background.
 *
 * \param[in]  detector      the Detector class
 * \param[in]  startTime     start time of the exposure [seconds]
 * \param[in]  exposureTime  duration of one exposure [seconds]
 * \param readoutTimeBeforeNextExposure Duration of the readout that takes place before the next exposure can start [seconds]
 */
void Camera::exposeDetectorWithSkyBackground(Detector &detector, double startTime, double exposureTime, double readoutTimeBeforeNextExposure)
{
    // Get the value for the degrading TransmissionEfficiency parameter at the startTime of this exposure

    double transmissionEfficiency = telescope.getTransmissionEfficiency(startTime);

    double centerXmm, centerYmm;
    tie(centerXmm, centerYmm) = detector.getFocalPlaneCoordinatesOfSubfieldCenter();

    if (includeFieldDistortion)
    {
        Log.info("Camera: correct FP coordinates of subfield center for field distortion");

        tie(centerXmm, centerYmm) = distortedToUndistortedFocalPlaneCoordinates(centerXmm, centerYmm);
    }

    // Convert the focal plane coordinates [mm] to (alpha, delta) equatorial sky coordinates [rad]

    double centerRA, centerDec;
    tie(centerRA, centerDec) = focalPlaneToSkyCoordinates(centerXmm, centerYmm);

    // Take the flux of the stellar background and the zodiacal light into account. Use one value for the entire subfield.
    // A negative value for the user given sky background value [phot/pix/s] signals that we should compute it ourselves.
    // Note: - The output of sky.zodiacalFlux() is in [J s^{-1} m^{-2} sr^{-1} m^{-1}]
    //       - As wavelength range we take the entire throughput band.
    //       - Photons are always an integer number, thus round down.
    //
    // The small sky background contribution during the readout with open shutter is not taken into account here
    // but in the function Detector::applyOpenShutterSmearing().

    totalSkyBackground = 0.0;

    if (userGivenSkyBackground < 0.0)
    {
        const double energyOfOnePhoton = Constants::CLIGHT * Constants::HPLANCK / (throughputLambdaC * 1.e-9);                // [J]
        const double lambda1 = (throughputLambdaC - throughputBandwidth/2.0) * 1.e-9;                                         // [m]
        const double lambda2 = (throughputLambdaC + throughputBandwidth/2.0) * 1.e-9;                                         // [m]

        const double zodiacalFlux = sky.zodiacalFlux(centerRA, centerDec, lambda1, lambda2)                                   // [phot/exposure]
                                    * (exposureTime + readoutTimeBeforeNextExposure) * transmissionEfficiency * telescope.getLightCollectingArea()
                                    * detector.getSolidAngleOfOnePixel(plateScale) / energyOfOnePhoton;

        const double stellarBackgroundFlux = sky.stellarBackgroundFlux(centerRA, centerDec, lambda1, lambda2)                 // [phot/exposure]
                                             * (exposureTime + readoutTimeBeforeNextExposure) * transmissionEfficiency * telescope.getLightCollectingArea()
                                             * detector.getSolidAngleOfOnePixel(plateScale) / energyOfOnePhoton;


        totalSkyBackground = floor(zodiacalFlux + stellarBackgroundFlux);
        detector.addFlux(totalSkyBackground);

        Log.debug("Camera: zodiacal flux level in subfield = " + to_string(zodiacalFlux) + " photons/pixel/exposure");
        Log.debug("Camera: stellar background flux level in subfield = " + to_string(stellarBackgroundFlux) + " photons/pixel/exposure");
    }
    else
    {
        totalSkyBackground = floor(userGivenSkyBackground * exposureTime * transmissionEfficiency);
        detector.addFlux(totalSkyBackground);

        Log.debug("Camera: user-given sky background flux over exposure= " + to_string(userGivenSkyBackground * exposureTime) + " photons/pixel/exposure");
    }

    // Save the sky background value that we added. [photons/pix/exposure]

    skyBackgroundValues.push_back(totalSkyBackground);

    // Save the transmissionEfficiency value that was calculated for this exposure.

    transmissionEfficiencyValues.push_back(transmissionEfficiency);
}












/**
 * @brief      Calculate the gnomonic radial distance with respect to the optical axis in the focal plane
 *
 * @param[in]  xFP  Focal plane x-coordinate [mm]
 * @param[in]  yFP  Focal plane y-coordinate [mm]
 *
 * @return     the angular distance of the star w.r.t. the optical axis [rad]
 *
 */
double Camera::getGnomonicRadialDistanceFromOpticalAxis(double xFP, double yFP)
{
    const double tanx = xFP / (*focalLength)();
    const double tany = yFP / (*focalLength)();

    double angularDistance = acos(1.0/sqrt(1.0 + tanx*tanx + tany*tany));

    // Take care that the angle is between [0, 2*PI]

    if (angularDistance < 0.0)
    {
        angularDistance += 2.0 * Constants::PI;
    }

    if (angularDistance > 2.0 * Constants::PI)
    {
        angularDistance -= 2.0 * Constants::PI;
    }

    // That's it!

    return angularDistance;
}











/**
 * \brief      Computes the (x,y) coordinates in the focal plane, of a star with given equatorial
 *             sky coordinates, assuming a pinhole camera.
 *
 * \details    The transformation is done with the 'current' orientations of the telescope and the platform.
 *
 * \param raStar          Right ascension of the star [rad]
 * \param decStar         Declination of the star [rad]
 * \param useInitialOrientation  true: use initial orientation of telescope and platform (i.e. before first exposure)
 *                               false: use current (jittered and drifted) telescope and platform orientation
 *
 * return pair (xFP,yFP): Cartesian coordinate of the projected star in the focal plane in the FP system.
 *                        The unit is the same as the one of the focal length, usually [mm].
 */

pair<double, double> Camera::skyToFocalPlaneCoordinates(double raStar, double decStar, bool useInitialOrientation)
{
    // Get the rotation matrices Equatorial -> Spacecraft and Spacecraft -> Telescope

    arma::mat rotEQ2SC;
    arma::mat rotSC2TL;

    if (useInitialOrientation)
    {
        rotEQ2SC = platform.getEquatorialToUnjitteredSpacecraftRotationMatrix();
        rotSC2TL = telescope.getPlatformToUndriftedTelescopeRotationMatrix();
    }
    else
    {
        rotEQ2SC = platform.getEquatorialToJitteredSpacecraftRotationMatrix();
        rotSC2TL = telescope.getPlatformToDriftedTelescopeRotationMatrix();
    }

    // Compute the rotation matrix to convert cartesian coordinates in the telescope reference frame to
    // cartesian coordinates in the focal plane reference frame

    arma::mat rotTL2FP;
    const double fpAngle = (*focalPlaneAngle)();
    rotTL2FP <<  cos(fpAngle) << sin(fpAngle) << 0 << arma::endr
             << -sin(fpAngle) << cos(fpAngle) << 0 << arma::endr
             <<     0         <<      0       << 1 << arma::endr;


    // Combine all the rotation matrices

    arma::mat rotEQ2FP = rotTL2FP * rotSC2TL * rotEQ2SC;

    // Compute the cartesian coordinates of the star in the equatorial reference frame

    arma::colvec starEQ = {cos(decStar)*cos(raStar), cos(decStar)*sin(raStar), sin(decStar)};

    // Transform these coordinates to the corresponding ones in the focal plane reference frame:

    arma::colvec starFP = rotEQ2FP * starEQ;

    // Convert the units to the one of focalLength (usually [mm]), and normalize the coordinates
    // to take into account the pinhole camera projection.

    double xFP = -(*focalLength)() * starFP[0]/starFP[2];
    double yFP = -(*focalLength)() * starFP[1]/starFP[2];

    // That's it

    return make_pair(xFP, yFP);
}













/**
 * \brief Compute the equatorial sky coordinates of a star which has the given focal plane (FP) coordinates (x,y),
 *        assuming a pinhole camera model
 *
 * \param xFP     Undistorted focal plane x-coordinate in the FP system [mm]
 * \param yFP     Undistorted focal plane y-coordinate in the FP system [mm]
 * \param useInitialOrientation  true: use initial orientation of telescope and platform (i.e. before first exposure)
 *                               false: use current (jittered and drifted) telescope and platform orientation
 *
 * \return (alpha, delta)  Equatorial coordinates (RA & Dec) of the star [rad]
 */

pair<double, double> Camera::focalPlaneToSkyCoordinates(double xFP, double yFP, bool useInitialOrientation)
{

    // Undo the reverse-image projection effect of the pinhole

    arma::colvec vecFP = {-xFP / (*focalLength)(), -yFP / (*focalLength)(), 1.0};

    // Compute the rotation matrix to convert cartesian coordinates in the focal plane reference frame to
    // cartesian coordinates in the telescope (TL) reference frame

    arma::mat rotFP2TL;
    const double fpAngle = (*focalPlaneAngle)();
    rotFP2TL << cos(fpAngle) << -sin(fpAngle) << 0 << arma::endr
             << sin(fpAngle) <<  cos(fpAngle) << 0 << arma::endr
             <<     0        <<       0       << 1 << arma::endr;

    // Get the rotation matrices Telescope (TL) -> Spacecraft (SC) and Spacecraft -> Equatorial (EQ)

    arma::mat rotSC2EQ;
    arma::mat rotTL2SC;

    if (useInitialOrientation)
    {
        rotSC2EQ = platform.getUnjitteredSpacecraftToEquatorialRotationMatrix();
        rotTL2SC = telescope.getUndriftedTelescopeToPlatformRotationMatrix();
    }
    else
    {
        rotSC2EQ = platform.getJitteredSpacecraftToEquatorialRotationMatrix();
        rotTL2SC = telescope.getDriftedTelescopeToPlatformRotationMatrix();
    }

    // Combine all the rotation matrices

    arma::mat rotFP2EQ = rotSC2EQ * rotTL2SC * rotFP2TL;

    // Transform the unnormalized focal plane coordinates to the corresponding ones in the equatorial reference frame

    arma::colvec vecEQ = rotFP2EQ * vecFP;

    // Convert the cartesian equatorial coordinates to equatorial sky coordinates

    double norm = sqrt(vecEQ[0]*vecEQ[0] + vecEQ[1]*vecEQ[1] + vecEQ[2]*vecEQ[2]);
    double decStar = Constants::PI/2.0 - acos(vecEQ[2]/norm);
    double raStar = atan2(vecEQ[1], vecEQ[0]);

    // Ensure that the right ascension is positive

    if (raStar < 0.0) { raStar += 2.*Constants::PI; }

    // That's it!

    return make_pair(raStar, decStar);
}














/**
 * @brief      Convert from undistorted to distorted focal plane coordinates
 *
 * @param[in]  xFPmm  Undistorted focal plane x-coordinate [mm]
 * @param[in]  yFPmm  Undistorted focal plane y-coordinate [mm]
 *
 * @return     (xFPdist, yFPdist) distorted x and y focal plane coordinates [mm]
 */
pair<double, double> Camera::undistortedToDistortedFocalPlaneCoordinates(double xFPmm, double yFPmm)
{
	const array<double, 3> coefficients = (*distortionCoef)();

    double alpha = atan2(yFPmm, xFPmm);  // Position angle on the focal plane [radians]

    double rFP = sqrt(xFPmm * xFPmm + yFPmm * yFPmm) / (*focalLength)();	// Undistorted radial distance [normalised pixels]
    double distortion = (coefficients[0] * pow(rFP, 3) + coefficients[1] * pow(rFP, 5) + coefficients[2] * pow(rFP, 7)) * (*focalLength)();	// Distortion [mm]

    double xFPdist = xFPmm + cos(alpha) * distortion;
    double yFPdist = yFPmm + sin(alpha) * distortion;

    return make_pair(xFPdist, yFPdist);
}











/**
 * @brief      Convert from distorted to undistorted focal plane coordinates
 *
 * @param[in]  xFPdist  Distorted focal plane x-coordinate [mm]
 * @param[in]  yFPdist  DIstorted focal plane y-coordinate [mm]
 *
 * @return     (xFPmm, yFPmm) distorted x and y coordinates [mm]
 */
pair<double, double> Camera::distortedToUndistortedFocalPlaneCoordinates(double xFPdist, double yFPdist)
{
	const array<double, 3> inverseCoefficients = (*inverseDistortionCoef)();

    double alpha = atan2(yFPdist, xFPdist);  // Position angle on the focal plane [radians]

    double rFP = sqrt(xFPdist * xFPdist + yFPdist * yFPdist) / (*focalLength)();	// Distorted radial distance [normalised pixels]
    double distortion = (inverseCoefficients[0] * pow(rFP, 3) + inverseCoefficients[1] * pow(rFP, 5) + inverseCoefficients[2] * pow(rFP, 7)) * (*focalLength)();	// Distortion [mm] -> negative

    double xFPmm = xFPdist +  cos(alpha) * distortion;
    double yFPmm = yFPdist + sin(alpha) * distortion;

    return make_pair(xFPmm, yFPmm);
}






/**
 * @brief   Returns the total sky background, expressed in photons / pixel / exposure.
 *
 * @ return  Total sky background [photons / pixel / exposure].
 */
double Camera::getTotalSkyBackground()
{
    if (skyBackgroundValues.size() != 0)
    {
        return skyBackgroundValues.back();
    }
    else
    {
        throw std::runtime_error("Camera::getTotalSkyBackground() was called with no skybackground being available");
    }
}












/**
 * \brief Returns the focal length of the camera, expressed in mm.
 *
 * \return Focal length of the camera, expressed in mm.
 */
double Camera::getFocalLength()
{
    return (*focalLength)();
}
