#include "Camera.h"
#include "Units.h"
#include "Constants.h"
#include "PointSpreadFunction.h"





/**
 * \brief      Constructor
 *
 * \param configParam   Configuration parameters for the Camera
 * \param hdf5file      HFD5 file to write the camera information to
 * \param telescope     Telescope on which the camera is mounted on
 * \param sky           Sky object to query which stars we are seeing
 */

Camera::Camera(ConfigurationParameters &configParam, HDF5File &hdf5file, Telescope &telescope, Sky &sky)
: HDF5Writer(hdf5file), telescope(telescope), sky(sky), internalTime(0.0)
{
    // Create the groups in the HDF5 file where the different arrays generated by Camera will be saved.

    initHDF5Groups();

    // Parse the parameters from the configuration file.

    configure(configParam);

    // Initialize and load the PSF. This will open the PSF HDF5 file and perform some basic checking, 
    // but the psf itself will only be loaded by the psf.select(radius) method.

    psf = new PointSpreadFunction(configParam);

    polynomial = Polynomial1D(polynomialDegree, polynomialCoefficients);
}









/**
 * \brief  Destructor, free memory for psf and polynomial
 */

Camera::~Camera()
{
    flushOutput();
    delete psf;
}













/**
 * \brief Creates the group(s) in the HDF5 file where the star information will be stored. 
 *        These group(s) have to be created once, at the very beginning.
 */

void Camera::initHDF5Groups()
{
    Log.debug("Camera: initialising HDF5 groups");

    hdf5File.createGroup("/StarInfo");
}











/**
 * \brief [brief description]
 * 
 */

void Camera::flushOutput()
{
    Log.info("Camera: Flushing output to HDf5 file.");

    // Extract and save the IDs of all stars that were at some point in time, detected in the subfield
    // Note: keu is (key, value) pair, where key is also a pair consisting of the starID and the startTime

    vector<unsigned int> starIDs;
    for(auto keyValuePair: detectedStarInfo) starIDs.push_back(keyValuePair.first);
    if (starIDs.size() != 0)
    {
        hdf5File.writeArray("StarInfo/", "DetectedStarIDs", starIDs.data(), starIDs.size());
    }
    else
    {
        Log.warning("Camera: No star positions to write to HDF5 file.");
    }

    // For each of the detected stars, make a subgroup, and write their position and flux for each exposure.
    // Because some stars at the edge may jitter in and out of the subfield during the sequence of exposures,
    // the written arrays may not be equally long for each star.

    for (auto starID: starIDs)
    {
        // Make the proper group

        stringstream myStream;
        myStream << "star" << setfill('0') << setw(6) << starID;
        const string starGroupName = "/StarInfo/" + myStream.str();
        hdf5File.createGroup(starGroupName);

        // Collect the different time series. For the positions, we only compute the sum, so we still need
        // to divide by N to compute the average, where N is the number of times the star was detected to be
        // in the subfield during an exposure.

        vector<double> time;
        vector<double> xFPmm;
        vector<double> yFPmm;
        vector<double> rowPix;
        vector<double> colPix;
        vector<double> flux;

        for(auto keyValuePair: detectedStarInfo[starID])
        {
            const double t = keyValuePair.first;  // time
            time.push_back(t);
            xFPmm.push_back(detectedStarInfo[starID][t][0] / detectedStarInfo[starID][t][5]);
            yFPmm.push_back(detectedStarInfo[starID][t][1] / detectedStarInfo[starID][t][5]);
            rowPix.push_back(detectedStarInfo[starID][t][2] / detectedStarInfo[starID][t][5]);
            colPix.push_back(detectedStarInfo[starID][t][3] / detectedStarInfo[starID][t][5]);
            flux.push_back(detectedStarInfo[starID][t][4]);
        }

        // Write the time series to HDF5

        hdf5File.writeArray(starGroupName, "time",   time.data(),   time.size());
        hdf5File.writeArray(starGroupName, "xFPmm",  xFPmm.data(),  xFPmm.size());
        hdf5File.writeArray(starGroupName, "yFPmm",  yFPmm.data(),  yFPmm.size());
        hdf5File.writeArray(starGroupName, "rowPix", rowPix.data(), rowPix.size());
        hdf5File.writeArray(starGroupName, "colPix", colPix.data(), colPix.size());
        hdf5File.writeArray(starGroupName, "flux",   flux.data(),   flux.size());
    }
}












/**
 * \brief Configure the Camera object using the ConfigurationParameters
 * 
 * \param configParam: the configuration parameters 
 */

void Camera::configure(ConfigurationParameters &configParam)
{
    plateScale             = configParam.getDouble("Camera/PlateScale");
    focalLength            = configParam.getDouble("Camera/FocalLength") * 1000; // [m] -> [mm]
    focalPlaneOrientation  = deg2rad(configParam.getDouble("Camera/FocalPlaneOrientation"));
    throughputBandwidth    = configParam.getDouble("Camera/ThroughputBandwidth");
    throughputLambdaC      = configParam.getDouble("Camera/ThroughputLambdaC");

    polynomialType         = configParam.getString("Camera/FieldDistortion/Type");
    polynomialDegree       = configParam.getInteger("Camera/FieldDistortion/Degree");
    polynomialCoefficients = configParam.getDoubleVector("Camera/FieldDistortion/Coefficients");
}










/** \brief  Specify the type of fit function used to fit the distortion
  *
  * \param  polynomial
  */

void Camera::setDistortionPolynomial(Polynomial1D &polynomial)
{
    this->polynomial = polynomial;
}













/**
 * \brief      Expose the subField to the Sky, i.e. add flux to the detector,
 *             add the sky background, and convolve with the PSF.
 *
 * \param[in]  detector      the Detector class
 * \param[in]  startTime     start time of the exposure [seconds]
 * \param[in]  exposureTime  duration of one exposure [seconds]
 */

void Camera::exposeDetector(Detector &detector, double startTime, double exposureTime)
{
    // Get the focal plane coordinates of the center and the corners of the subfield (in [mm]).
    // To compute the diagonal length of the subfield, we only need the lower left (X00, Y00)
    // and the upper right (X11, Y11) corner of the subfield.

    double centerXmm, centerYmm;
    tie(centerXmm, centerYmm) = detector.getPlanarFocalPlaneCoordinatesOfSubfieldCenter();

    double corner00Xmm, corner00Ymm, corner11Xmm, corner11Ymm, dummy;
    tie(corner00Xmm, corner00Ymm, dummy, dummy, corner11Xmm, corner11Ymm, dummy, dummy) = detector.getPlanarFocalPlaneCoordinatesOfSubfieldCorners();

    Log.debug("Camera: center of subfield at (Xmm, Ymm) = (" + to_string(centerXmm) + ", " + to_string(centerYmm) + ") mm");
    Log.debug("Camera: lower left corner of subfield at (Xmm, Ymm) = (" + to_string(corner00Xmm) + ", " + to_string(corner00Ymm) + ") mm");
    Log.debug("Camera: upper right corner of subfield at (Xmm, Ymm) = (" + to_string(corner11Xmm) + ", " + to_string(corner11Ymm) + ") mm");



    // Convert the planar [mm] to angular [rad] focal plane coordinates 

    double centerXrad, centerYrad;
    tie(centerXrad, centerYrad) = planarToAngularFocalPlaneCoordinates(centerXmm, centerYmm);

    double corner00Xrad, corner00Yrad;
    tie(corner00Xrad, corner00Yrad) = planarToAngularFocalPlaneCoordinates(corner00Xmm, corner00Ymm);

    double corner11Xrad, corner11Yrad;
    tie(corner11Xrad, corner11Yrad) = planarToAngularFocalPlaneCoordinates(corner11Xmm, corner11Ymm);


    // Convert the angular [rad] focal plane coordinates to (alpha, delta) equatorial coordinates [rad]

    double centerRA, centerDec;
    tie(centerRA, centerDec) = angularFocalPlaneToSkyCoordinates(centerXrad, centerYrad);

    double corner00RA, corner00Dec;
    tie(corner00RA, corner00Dec) = angularFocalPlaneToSkyCoordinates(corner00Xrad, corner00Yrad);

    double corner11RA, corner11Dec;
    tie(corner11RA, corner11Dec) = angularFocalPlaneToSkyCoordinates(corner11Xrad, corner11Yrad);

    Log.debug("Camera: center of subfield at (alpha, delta) = (" + to_string(rad2deg(centerRA)) + ", " + to_string(rad2deg(centerDec)) + ") deg");
    Log.debug("Camera: lower left corner of subfield at (alpha, delta) = (" + to_string(rad2deg(corner00RA)) + ", " + to_string(rad2deg(corner00Dec)) + ") deg");
    Log.debug("Camera: upper right corner of subfield at (alpha, delta) = (" + to_string(rad2deg(corner11RA)) + ", " + to_string(rad2deg(corner11Dec)) + ") deg");


    // Compute the angular distance on the sky between the lower left and the upper right corner
    // of the subfield, to estimate the "radius" of the subfield.

    SkyCoordinates skyCoordinates00(corner00RA, corner00Dec, Angle::radians);
    SkyCoordinates skyCoordinates11(corner11RA, corner11Dec, Angle::radians);
    
    double radius = angularDistanceBetween(skyCoordinates00, skyCoordinates11, Angle::radians) / 2.0;

    Log.debug("Camera: semi-diagonal of subfield = " + to_string(rad2deg(radius)) + " deg");


    // Get a catalog of stars that fall on the subfield. Take the radius a bit larger so that the 
    // queried area includes possible small shifts of the projected subfield because of jitter.

    auto starCatalog = sky.getStarsWithinRadiusFrom(centerRA, centerDec, radius * 1.1, Angle::radians);

    Log.debug("Camera: Found " + to_string(starCatalog.size()) + " stars on and near the subfield");  


    // If the telescope and/or platform show small variations (e.g. due to jitter) during the exposure,
    // the exposure time is split up in many small intervals, to track the effect of these variations
    // on the exposure. The largest time interval for which the variations can still be reliably tracked
    // is called the heartbeatInterval. The time step used should be either the heartbeat interval or the
    // expsosure time whatever is smallest. 

    double timeStep = min(telescope.getHeartbeatInterval(), exposureTime);


    // Later on we will have to convert from magnitudes to fluxes. Precompute a constant prefactor.
    // 1.000238 is the photon flux [photons/s/m^2/nm] for a V=0 G2V-star.
    // Units of fluxFactor: [photons/s]
  
    const double fluxFactor = 1.00238 * throughputBandwidth * telescope.getTransmissionEfficiency() * telescope.getLightCollectingArea(); 


    // Update the internal clock

    internalTime = startTime;

    // Take the flux of point sources (stars) into account.
    // Break up the exposure time in small intervals (hearbeat intervals) to track jitter while exposing.

    while (internalTime < startTime + exposureTime)
    {
        // Let the telescope pointing evolve over a small time interval

        telescope.updatePointingCoordinates(internalTime);

        // Loop over all stars in the catalog, and add their flux to the subfield

        for (int n = 0; n < starCatalog.size(); n++)
        {
            // Get the focal plane coordinates (in [mm]) of this particular star
            
            auto star = starCatalog[n];
            double Xrad, Yrad;
            tie(Xrad, Yrad) = skyToAngularFocalPlaneCoordinates(star.RA, star.dec);

            // Convert the angular [rad] to planar [mm] focal plane coordinates 

            double Xmm, Ymm;
            tie(Xmm, Ymm) = angularToPlanarFocalPlaneCoordinates(Xrad, Yrad);

            // Compute the flux [photons] of this star

            double flux = fluxFactor * pow(10.0, -0.4 * star.Vmag) * timeStep;

            // Let the detector add the flux to the appropriate pixel. 
            // Detector.flux() returns the pixel coordinates to which the flux was added.

            bool isInSubfield;
            double rowPix, colPix;

            tie(isInSubfield, rowPix, colPix) = detector.addFlux(Xmm, Ymm, flux);

            // If the star is indeed in the subfield, collect the following information to later write to HDF5
            //    1) average (Xmm, Ymm) coordinates of the star during the exposure [mm]
            //    2) average (row, col) pixel coordinates of the star on the CCD during the exposure  [pix]
            //    3) the total number of photons gathered of this star during the exposure [photons]
            //    4) the total number of times that the star was in the subfield during the exposure
            //
            // Note: Due to jitter, the star can move in and out the subfield during the exposure

            if (isInSubfield)
            {
                // If this is the first time we encounter this star, initialise the information

                if (detectedStarInfo.find(star.ID) == detectedStarInfo.end())
                {
                    detectedStarInfo[star.ID][startTime] = {{Xmm, Ymm, rowPix, colPix, flux, 1.0}};
                }
                else
                {
                    // If this is the first time that we encounter this startTime associated with this star,
                    // initialise the information. If not, just update the info.

                    if (detectedStarInfo[star.ID].find(startTime) == detectedStarInfo[star.ID].end())
                    {
                        detectedStarInfo[star.ID][startTime] = {{Xmm, Ymm, rowPix, colPix, flux, 1.0}};
                    }
                    else
                    {
                        detectedStarInfo[star.ID][startTime][0] += Xmm;      // Will be used to compute average Xmm during the exposure
                        detectedStarInfo[star.ID][startTime][1] += Ymm;      // Will be used to compute average Ymm during the exposure
                        detectedStarInfo[star.ID][startTime][2] += rowPix;   // Will be used to compute average pixel row during the exposure
                        detectedStarInfo[star.ID][startTime][3] += colPix;   // Will be used to compute average pixel column during the exposure
                        detectedStarInfo[star.ID][startTime][4] += flux;     // Total flux
                        detectedStarInfo[star.ID][startTime][5] += 1;        // # of times a star was on the subfield during an exposure 
                    }
                }
            }
        }

        // Update the clock. Normally with 'timeStep', but if adding timeStep would overstep
        // the total exposure time, take the small rest time instead.

        timeStep = min(timeStep, startTime + exposureTime - internalTime);
        internalTime += timeStep;

    }


    // Take the flux of the stellar background and the zodiacal light into account.
    // Use one value for the entire subfield. As wavelength range we take the entire throughput band.

    const double energyOfOnePhoton = Constants::CLIGHT * Constants::HPLANCK / (throughputLambdaC * 1.e-9);                       // [J]
    const double lambda1 = (throughputLambdaC - throughputBandwidth/2.0) * 1.e-9;                                                // [m]
    const double lambda2 = (throughputLambdaC + throughputBandwidth/2.0) * 1.e-9;                                                // [m]
    
    const double zodiacalFlux = sky.zodiacalFlux(centerRA, centerDec, lambda1, lambda2)                                                      // [phot/exposure]
                                * exposureTime * telescope.getTransmissionEfficiency() * telescope.getLightCollectingArea()
                                * telescope.getFOVsolidAngle() / energyOfOnePhoton; 

    const double stellarBackgroundFlux = sky.stellarBackgroundFlux(centerRA, centerDec, lambda1, lambda2)                                    // [phot/exposure]
                                         * exposureTime * telescope.getTransmissionEfficiency() * telescope.getLightCollectingArea()
                                         * telescope.getFOVsolidAngle() / energyOfOnePhoton;      

    detector.addFlux(zodiacalFlux + stellarBackgroundFlux);

    Log.debug("Camera: zodiacal flux level in subfield = " + to_string(zodiacalFlux) + " photons/pixel/exposure");
    Log.debug("Camera: stellar background flux level in subfield = " + to_string(stellarBackgroundFlux) + " photons/pixel/exposure");



    // Convolve with the point spread function

    // subField.convolveWithPSF(psf);

    return;
}












/**
 * \brief      select the PSF for the given star coordinates.
 * 
 * \details
 * 
 * This method selects and rotates the PSF.
 *
 * \param[in]  raStar   right ascension of the star [rad]
 * \param[in]  decStar  declination of the star     [rad]
 */

void Camera::selectPsf(double raStar, double decStar)
{

    double xFPrad, yFPrad;

    // Calculate the angular separation (in [radians]) between the star and the optical axis.
    // Use that angle to select the proper PSF.

    tie(xFPrad, yFPrad) = skyToAngularFocalPlaneCoordinates(raStar, decStar);

    double radius = getGnomonicRadialDistanceFromOpticalAxis(xFPrad, yFPrad);

    psf->select(rad2deg(radius));

    // Calculate the rotation angle [rad]

    double xFPmm, yFPmm;
    tie(xFPmm, yFPmm) = angularToPlanarFocalPlaneCoordinates(xFPrad, yFPrad);

    double angle = atan2(yFPmm, xFPmm);

    psf->rotate(angle);

}












/**
 * @brief      Calculate the gnomonic radial distance with respect to the optical axis in the focal plane
 *
 * @param[in]  xFPprime  angular focal plane x-coordinate [rad]
 * @param[in]  yFPprime  angular focal plane y-coordinate [rad]
 *
 * @return     the field radial distance (gnomonic) with respect to the line of sight in the sky [rad]
 */
double Camera::getGnomonicRadialDistanceFromOpticalAxis(double xFPprime, double yFPprime)
{
    double tanx = tan(xFPprime);
    double tany = tan(yFPprime);

    return acos(1.0/sqrt(1.0 + tanx*tanx + tany*tany));
}












/**
 * \brief Computes the (x,y) coordinates in the normalized focal plane of a star with given equatorial coordinates
 *        using a gnomonic projection.
 *
 * \param raStar       Right ascension of the star [rad]
 * \param decStar      Declination of the star [rad]
 *
 * return pair (x,y):  Cartesian coordinate of the projected star in the focal plane in the FP-prime system [radians]
 */

pair<double, double> Camera::skyToAngularFocalPlaneCoordinates(double raStar, double decStar)
{
    // Get the equatorial coordinates of the optical axis [rad]

    double raOpticalAxis, decOpticalAxis;
    tie(raOpticalAxis, decOpticalAxis) = telescope.getCurrentPointingCoordinates();

    // Project the sky to the focal plane in the "FP" coordinate system (gnomonic projection)

    double denominator = cos(decOpticalAxis) * cos(decStar) * cos(raStar - raOpticalAxis) + sin(decOpticalAxis) * sin(decStar);
    double xFP = ( sin(decOpticalAxis) * cos(decStar) * cos(raStar - raOpticalAxis) - cos(decOpticalAxis) * sin(decStar)) / denominator;
    double yFP =  cos(decStar) * sin(raStar - raOpticalAxis) / denominator;

    // Convert the FP coordinates into FP' coordinates 

    double xFPprime =  xFP * cos(focalPlaneOrientation) + yFP * sin(focalPlaneOrientation);
    double yFPprime = -xFP * sin(focalPlaneOrientation) + yFP * cos(focalPlaneOrientation);

    // Return the angular focal plane coordinates [rad]

    return make_pair(xFPprime, yFPprime);
}











/**
 * \brief Compute the equatorial sky coordinates of a star which has the given angular focal plane (FP') coordinates (x,y)
 *        
 * \param xFPprime     Angular focal plane x-coordinate in the FP-prime system [rad]
 * \param yFPprime     Angular focal plane y-coordinate in the FP-prime system [rad]
 *
 * \return (alpha, delta)  Equatorial coordinates (RA & Dec) of the star [rad]
 */

pair<double, double> Camera::angularFocalPlaneToSkyCoordinates(double xFPprime, double yFPprime)
{    
    // Convert from the FP' to the FP reference system.

    const double xFP =  xFPprime * cos(focalPlaneOrientation) - yFPprime * sin(focalPlaneOrientation);
    const double yFP =  xFPprime * sin(focalPlaneOrientation) + yFPprime * cos(focalPlaneOrientation);


    // Get the equatorial coordinates of the optical axis [rad]

    double raOpticalAxis, decOpticalAxis;
    tie(raOpticalAxis, decOpticalAxis) = telescope.getCurrentPointingCoordinates();


    // Project the focal plane in the "FP" coordinate system to the sky

    if (xFP == 0.0 and yFP == 0.0)
    {
        return make_pair(raOpticalAxis, decOpticalAxis);
    }
    else
    {
        const double rho = sqrt(xFP*xFP+yFP*yFP);
        const double c = atan(rho);
        const double ra = raOpticalAxis + atan2(yFP * sin(c), rho * cos(decOpticalAxis) * cos(c) + xFP * sin(decOpticalAxis) * sin(c));
        const double dec = asin(cos(c) * sin(decOpticalAxis) - (xFP * sin(c) * cos(decOpticalAxis)) / rho);

        return make_pair(ra, dec);
    }
}









/**
 * \brief Convert from angular to planar focal plane coordinates, assuming no optical distortion.
 * 
 * \note This conversion depends on the focal length of the camera
 * 
 * \param xFPrad   Angular focal plane x-coordinate [rad]
 * \param yFPrad   Angular focal plane y-coordinate [rad]
 * 
 * \return (xFPmm, yFPmm)    Planar focal plane x and y coordinates [mm]
 */

pair<double, double> Camera::angularToPlanarFocalPlaneCoordinates(double xFPrad, double yFPrad)
{
    const double xFPmm = tan(xFPrad) * focalLength;
    const double yFPmm = tan(yFPrad) * focalLength;
    
    return make_pair(xFPmm, yFPmm);   
}












/**
 * \brief Convert from planar to angular focal plane coordinates, assuming no optical distortion.
 * 
 * \note This conversion depends on the focal length of the camera
 * 
 * \param xFPrad   Planar focal plane x-coordinate [mm]
 * \param yFPrad   Planar focal plane y-coordinate [mm]
 * 
 * \return (xFPrad, yFPrad)    Angular focal plane x and y coordinates [rad]
 */

pair<double, double> Camera::planarToAngularFocalPlaneCoordinates(double xFPmm, double yFPmm)
{
    const double xFPrad = atan(xFPmm / focalLength);
    const double yFPrad = atan(yFPmm / focalLength);
    
    return make_pair(xFPrad, yFPrad);   
}











/**
 * @brief      Convert from planar to distorted focal plane coordinates
 *
 * @param[in]  xFPmm  Planar focal plane x-coordinate [mm]
 * @param[in]  yFPmm  Planar focal plane y-coordinate [mm]
 *
 * @return     (xFPdist, yFPdist) distorted x and y coordinates [mm]
 */
pair<double, double> Camera::planarToDistortedFocalPlaneCoordinates(double xFPmm, double yFPmm)
{
    double xFPdist = polynomial(xFPmm);
    double yFPdist = polynomial(yFPmm);
    
    return make_pair(xFPdist, yFPdist);
}
