
#include "Camera.h"










/**
 * \brief      Constructor
 *
 * \param configParam   Configuration parameters for the Camera
 * \param hdf5file      HFD5 file to write the camera information to
 * \param telescope     Telescope on which the camera is mounted on
 * \param sky           Sky object to query which stars we are seeing
 */

Camera::Camera(ConfigurationParameters &configParam, HDF5File &hdf5file, Platform &platform, Telescope &telescope, Sky &sky)
: HDF5Writer(hdf5file), platform(platform), telescope(telescope), sky(sky), focalLength(nullptr), focalPlaneAngle(nullptr), 
  distortionCoef(nullptr), inverseDistortionCoef(nullptr), internalTime(0.0), includeFieldDistortion(true), 
  userGivenSkyBackground(-1.0), fluxOfV0Star(0.0) 
{
    // Create the groups in the HDF5 file where the different arrays generated by Camera will be saved.

    initHDF5Groups();

    // Parse the parameters from the configuration file.

    configure(configParam);

    // Get the equatorial sky coordinates of the Sun, which is know by platform since it's pointing its sunshield towards it.

    tie(raSun, decSun) = platform.getRADecSun();
}









/**
 * \brief  Destructor, free memory for psf
 */

Camera::~Camera()
{
    flushOutput();
    delete focalLength;
    delete focalPlaneAngle;

    // if includeDistortion was set to false, the following parameters were never
    // allocated, but the were initialised to null pointers in the constructor,
    // so it always OK to delete them.

    delete distortionCoef;
    delete inverseDistortionCoef;
}













/**
 * \brief Creates the group(s) in the HDF5 file where the star information will be stored. 
 *        These group(s) have to be created once, at the very beginning.
 */

void Camera::initHDF5Groups()
{
    Log.debug("Camera: initialising HDF5 groups");

    hdf5File.createGroup("/StarPositions");
    hdf5File.createGroup("/Background");
    hdf5File.createGroup("/TransmissionEfficiency");
}








/**
 * \brief      Collect and return the IDs of all stars that fall within the subField
 * 
 * \details    Note that this method pulls the detected stars from a map that is filled by 
 *             exposeDetector for each exposure. So, depending on when this method is called, 
 *             the returned set might be empty or incomplete.
 *             
 * \return     a set of unique star IDs that were detected in the subField
 */
set<unsigned int> Camera::getAllStarIDs()
{
    set<unsigned int> allStarIDs;            // A set<> stores only unique members

    for(auto timeMapPair: detectedStarInfo)
    {
        for (auto idArrayPair: timeMapPair.second)
        {
            allStarIDs.insert(idArrayPair.first);
        }
    }

    return allStarIDs;

}






/**
 * \brief Return the mean position on the CCD, and flux of the star with given ID for the last exposure.
 *
 * \details Mean refers to the mean position during the jittering during the exposure. If the star ID 
 *          is not found in the list, the value -1 is returned for each quantity.
 * 
 * \return A tuple with the following quantities: 
 *    timeStamp: the time stamp of the last exposure                              [s]
 *    xFPmean: mean (during the exposure) focal plane x-coordinate of the star    [mm]
 *    yFPmean: mean focal plane y-coordinate of the star                          [mm]
 *    rowPixMean: mean subfield (fractional) row coordinate                       [pix]
 *    colPixMean: mean subfield (fractional) column coordinate                    [pix]
 *    sumFlux: the integrated flux of the star during one exposure                [photons/exposure]
 */

tuple<double, double, double, double, double, double> Camera::getInfoForTheMostRecentExposureForStar(int starID)
{
    // The detected star info is stored in a map as:   map<double, map<unsigned int, array<double, 6>>> detectedStarInfo;
    // so that  detectedStarInfo[startTime][starID] contains the values (xFPmean, yFPmean, rowPixMean, colPixmean, sumFlux, Ndetections)
    // In C++ maps are sorted on key values (in ascending order). To find the time stamp of the most recent exposure, 
    // we simply need to access the last element. rbegin() is a reverse-iterator, starting with the last element

    double timeStamp = detectedStarInfo.rbegin()->first;

    // Find the map item with the given starID

    auto it = detectedStarInfo[timeStamp].find(starID);
    if (it == detectedStarInfo[timeStamp].end())
    {
        // The starID couldn't be found in the map. 

        return make_tuple(-1, -1, -1, -1, -1, -1);
    }
    else
    {
        double xFPmean    = detectedStarInfo[timeStamp][starID][0] / detectedStarInfo[timeStamp][starID][5];  //%% Added division by number to get real value
        double yFPmean    = detectedStarInfo[timeStamp][starID][1] / detectedStarInfo[timeStamp][starID][5];  //%% Added division by number to get real value
        double rowPixMean = detectedStarInfo[timeStamp][starID][2] / detectedStarInfo[timeStamp][starID][5];  //%% Added division by number to get real value
        double colPixMean = detectedStarInfo[timeStamp][starID][3] / detectedStarInfo[timeStamp][starID][5];  //%% Added division by number to get real value
        double sumFlux    = detectedStarInfo[timeStamp][starID][4];

        return make_tuple(timeStamp, xFPmean, yFPmean, rowPixMean, colPixMean, sumFlux);
    }

}






/**
 *  \brief return the begin and end iterator of the star info of detectedStarInfo[most_recent_time];
 */

pair<starInfoIterator, starInfoIterator> Camera::getInfoForTheMostRecentExposureForAllStars()
{
   // The detected star info is stored in a map as:   map<double, map<unsigned int, array<double, 6>>> detectedStarInfo;
    // so that  detectedStarInfo[startTime][starID] contains all the information.
    // In C++ maps are sorted on key values (in ascending order). To find the time stamp of the most recent exposure, 
    // we simply need to access the last element. rbegin() is a reverse-iterator, starting with the last element

    double timeStamp = detectedStarInfo.rbegin()->first;
    return make_pair(detectedStarInfo[timeStamp].begin(), detectedStarInfo[timeStamp].end());
}




/**
 * \brief Write all recorded information to the HDF5 output file
 * 
 */

void Camera::flushOutput()
{
    Log.info("Camera: Flushing output to HDf5 file.");

    // Extract and save the time points of all exposures 
    // Note: keyValuePair is (key, value) pair, where key is also a pair consisting of the startTime and StarID

    if (writeStarPositions)
    {
        vector<double> time;
        for(auto keyValuePair: detectedStarInfo) time.push_back(keyValuePair.first);
        if (!time.empty())
        {
            hdf5File.writeArray("StarPositions/", "Time", time.data(), time.size());
        }
        else
        {
            Log.warning("Camera: No star positions to write to HDF5 file.");
        }

        // For each of the exposures, make a subgroup and write the position and flux of all detected stars.
        // Because some stars at the edge may jitter in and out of the subfield from one exposure to the other,
        // the written arrays may not be equally long for each exposure.
    
    
        for (int n = 0; n < time.size(); n++)
        {
            // Make the subgroup group
    
            stringstream myStream;
            myStream << "Exposure" << setfill('0') << setw(6) << beginExposureNr + n;
            const string exposureGroupName = "/StarPositions/" + myStream.str();
            hdf5File.createGroup(exposureGroupName);
    
            // Collect the different time series. For the positions, we only compute the sum, so we still need
            // to divide by N to compute the average, where N is the number of times the star was detected to be
            // in the subfield during an exposure.
    
            vector<unsigned int> starIDs;
            vector<double> xFPmm;
            vector<double> yFPmm;
            vector<double> rowPix;
            vector<double> colPix;
            vector<double> flux;

            vector<double> temp;  //%% Added temperature for spectral dependency
    
            for(auto keyValuePair: detectedStarInfo[time[n]])
            {
                const unsigned int starID = keyValuePair.first;
                starIDs.push_back(starID);                       // list of starIDs for this exposure only
                xFPmm.push_back(detectedStarInfo[time[n]][starID][0] / detectedStarInfo[time[n]][starID][5]);
                yFPmm.push_back(detectedStarInfo[time[n]][starID][1] / detectedStarInfo[time[n]][starID][5]);
                rowPix.push_back(detectedStarInfo[time[n]][starID][2] / detectedStarInfo[time[n]][starID][5]);
                colPix.push_back(detectedStarInfo[time[n]][starID][3] / detectedStarInfo[time[n]][starID][5]);
                flux.push_back(detectedStarInfo[time[n]][starID][4]);

                temp.push_back(detectedStarInfo[time[n]][starID][6]);  //%% Added temperature for spectral dependency
            }
    
            // Write the time series to HDF5
    
            if(!starIDs.empty())
            {
                hdf5File.writeArray(exposureGroupName, "starID", starIDs.data(), starIDs.size());
                hdf5File.writeArray(exposureGroupName, "xFPmm",  xFPmm.data(),   xFPmm.size());
                hdf5File.writeArray(exposureGroupName, "yFPmm",  yFPmm.data(),   yFPmm.size());
                hdf5File.writeArray(exposureGroupName, "rowPix", rowPix.data(),  rowPix.size());
                hdf5File.writeArray(exposureGroupName, "colPix", colPix.data(),  colPix.size());
                hdf5File.writeArray(exposureGroupName, "flux",   flux.data(),    flux.size());    

                hdf5File.writeArray(exposureGroupName, "temp",   temp.data(),    temp.size());  //%% Added temperature for spectral dependency        
            }
        }
    }
    else {
        Log.warning("Camera: No star positions written to HDF5 file by user demand (see input file).");
    }

    // Write the total sky background flux values [photons/pixel/exposure] to HDF5 in a custom group

//%%	For spectral dependency: Convert one large 1D array (containing all wavebins for all exposures and all subsubfields) to a 2D Map, the axis being exposureNr all wavelengthBins and subsubfield
//%%	so e1b1,f1 - e1b1,fx; e1b2,f1 - e1b2,fx; e2b1,f1 ... ; Field numeration is x1y1,x1y2,x1y3,x2y1,x2y2 ...
    arma::Mat<float> skyBackground(numExposures * wavelengthBins, numsubsubfieldsx*numsubsubfieldsy);
    int i = 0;
    int k = 0;
    while (i<numExposures*wavelengthBins)
    {
	for (int l=0; l<numsubsubfieldsx*numsubsubfieldsy; l++)
	{
		skyBackground(i,l) = skyBackgroundValues[k];
		k = k+1; 
	}
	i = i+1;
    }

    hdf5File.writeArray("Background/", "skyBackground", skyBackground);  //%% Background is now an array due to above reasons

    // Write the transmissionEfficiency values for each exposureTime to HDF5 in a custom group

//%%	For spectral dependency: Convert one large 1D array (containing all wavebins for all exposures and all subsubfields) to a 2D Map, the axis being exposureNr all wavelengthBins and subsubfield
    arma::Mat<float> TransmissionEff(numExposures * wavelengthBins, numsubsubfieldsx*numsubsubfieldsy);
    i = 0;
    k = 0;
    while (i<numExposures*wavelengthBins)
    {
	for (int l=0; l<numsubsubfieldsx*numsubsubfieldsy; l++)
	{
		TransmissionEff(i,l) = transmissionEfficiencyValues[k];
		k = k+1; 
	}
	i = i+1;
    }

    hdf5File.writeArray("TransmissionEfficiency/", "transmissionEfficiency", TransmissionEff);  //%% TE is now an array due to above reasons

}












/**
 * \brief Configure the Camera object using the ConfigurationParameters
 * 
 * \param configParam: the configuration parameters 
 */

void Camera::configure(ConfigurationParameters &configParam)
{
    numExposures           = configParam.getInteger("ObservingParameters/NumExposures");
    beginExposureNr        = configParam.getInteger("ObservingParameters/BeginExposureNr");


    // The focal length can either be a fixed value, or given by a time series in a file
    
    string focalLengthSource = configParam.getString("Camera/FocalLength/Source");
    if (focalLengthSource == "ConstantValue")
    {
        double focalLengthValue = configParam.getDouble("Camera/FocalLength/ConstantValue") * 1000;     // [m] -> [mm]
        focalLength = new Parameter<double>(focalLengthValue);
    
        Log.info("Camera: Using a constant focal length: " + to_string(focalLengthValue) + " m");
    }
    else if (focalLengthSource == "FromFile")
    {
        string focalLengthInputFile = configParam.getAbsoluteFilename("Camera/FocalLength/FromFile");
        focalLength = new Parameter<double>(focalLengthInputFile, 1000);                                // [m] -> [mm]
    
        Log.info("Camera: Reading focal length values from " + focalLengthInputFile);
    }


    
    // The focal plane orientation can either be a fixed value, or given by a time series in a file
    
    string focalPlaneAngleSource = configParam.getString("Camera/FocalPlaneOrientation/Source");
    if (focalPlaneAngleSource == "ConstantValue")
    {
        double focalPlaneAngleValue = deg2rad(configParam.getDouble("Camera/FocalPlaneOrientation/ConstantValue")); // [deg]->[rad]
        focalPlaneAngle = new Parameter<double>(focalPlaneAngleValue);                                              // [rad]
    
        Log.info("Camera: Using a constant focal plane orientation: " + to_string(focalPlaneAngleValue) + " m");
    }
    else if (focalPlaneAngleSource == "FromFile")
    {
        string focalPlaneAngleInputFile = configParam.getAbsoluteFilename("Camera/FocalPlaneOrientation/FromFile");
        focalPlaneAngle = new Parameter<double>(focalPlaneAngleInputFile, deg2rad(1.0));                           // [deg]->[rad]
    
        Log.info("Camera: Reading focal plane orientation from " + focalPlaneAngleInputFile);
    }



    // The distortion coefficients can either be a fixed value, or given by a time series in a file
    // Idem for the inverse distortion coefficients.
    
    includeFieldDistortion = configParam.getBoolean("Camera/IncludeFieldDistortion");

    if (includeFieldDistortion)
    {
        distortionModel              = configParam.getString("Camera/FieldDistortion/Type");
        string fieldDistortionSource = configParam.getString("Camera/FieldDistortion/Source");
        if (fieldDistortionSource == "ConstantValue")
        {
            // Read the distortion coefficients from the yaml input file. Currently vector<>s are
            // being read while Parameter<> expects array<>s. So we'll have to do some overhead
            // to convert one to the other.
            
            vector<double> distortionCoefVector        = configParam.getDoubleVector("Camera/FieldDistortion/ConstantCoefficients");
            vector<double> inverseDistortionCoefVector = configParam.getDoubleVector("Camera/FieldDistortion/ConstantInverseCoefficients");
            array<double, 3> distortionCoefArray, inverseDistortionCoefArray;
            
            if ((distortionCoefVector.size() != 3) || (inverseDistortionCoefVector.size() != 3))
            {
                string msg = "Camera::configure(): number of (inverse) distortion coefficients in input yaml file != 3.";
                throw ConfigurationException(msg);
            }
            else
            {
                copy(distortionCoefVector.begin(), distortionCoefVector.end(), distortionCoefArray.begin());
                copy(inverseDistortionCoefVector.begin(), inverseDistortionCoefVector.end(), inverseDistortionCoefArray.begin());
            }

            distortionCoef        = new Parameter<double, 3>(distortionCoefArray);
            inverseDistortionCoef = new Parameter<double, 3>(inverseDistortionCoefArray);
        
            Log.info("Camera: Using a constant distortion law");
        }
        else if (fieldDistortionSource == "FromFile")
        {
            string distortionInputFile = configParam.getAbsoluteFilename("Camera/FieldDistortion/CoefficientsFromFile");
            string invDistortionInputFile = configParam.getAbsoluteFilename("Camera/FieldDistortion/InverseCoefficientsFromFile");
            distortionCoef = new Parameter<double, 3>(distortionInputFile, 1);
            inverseDistortionCoef = new Parameter<double, 3>(invDistortionInputFile, 1);
        
            Log.info("Camera: Reading distortion coefficients from " + distortionInputFile);
            Log.info("Camera: Reading inverse distortion coefficients from " + invDistortionInputFile);
        }
    }
    else
    {
        Log.info("Camera: Ignoring field distortion");
    }


    

    plateScale             = configParam.getDouble("Camera/PlateScale");
    throughputLambdaC      = configParam.getDouble("Camera/ThroughputLambdaC");  //%% Now used as reference wavelength for 0V mag with spectral dependency

    wavelengthBins	   = configParam.getInteger("Camera/WavelengthBins");  //%% Added for spectral dependency, total number of wavelength bins
    binWidth   		   = configParam.getDouble("Camera/BinWidth");  //%% Added for spectral dependency, width of wavebins
    binOrigin      	   = configParam.getDouble("Camera/BinOrigin");  //%% Added for spectral dependency, lower wavelength limit
    numsubsubfieldsx 	   = configParam.getInteger("SubField/NumSubSubFieldsRows");  //%% Added for spectral dependency, number of subsubfields in x direction 
    numsubsubfieldsy 	   = configParam.getInteger("SubField/NumSubSubFieldsColumns");  //%% Added for spectral dependency, number of subsubfields in y direction

    includeAberrationCorrection = configParam.getBoolean("Camera/IncludeAberrationCorrection");
    aberrationCorrectionType    = configParam.getString("Camera/AberrationCorrection/Type");


    fluxOfV0Star           = configParam.getDouble("ObservingParameters/Fluxm0");                 // [phot/s/m^2/nm]
    userGivenSkyBackground = configParam.getDouble("Sky/SkyBackground");          // [phot/pix/s]

    writeStarPositions     = configParam.getBoolean("ControlHDF5Content/WriteStarPositions");

}











/**
 * \brief Update the time dependent parameters of the Camera to their 
 *        value at the given time point
 *
 * \param time: current time
 *
 * \return 
 */

void Camera::updateParameters(double time)
{
    focalLength->updateValue(time);
    focalPlaneAngle->updateValue(time);
 
    if (includeFieldDistortion)
    {
        distortionCoef->updateValue(time);
        inverseDistortionCoef->updateValue(time);
    }
}










/** 
 * \brief      Specify the type of fit function used to fit the distortion
 *
 * \param      polynomial         The polynomial that describes the distortion
 * \param      inversePolynomial  The inverse polynomial
 */

//void Camera::setDistortionPolynomial(Polynomial1D &polynomial, Polynomial1D &inversePolynomial)
//{
//    this->polynomial = polynomial;
//    this->inversePolynomial = inversePolynomial;
//}













/**
 * \brief      Expose the subField to the Sky, i.e. add flux to the detector,
 *             add the sky background, and convolve with the PSF.
 *
 * \param[in]  detector      the Detector class
 * \param[in]  startTime     start time of the exposure [seconds]
 * \param[in]  exposureTime  duration of one exposure [seconds]
 * \param readoutTimeBeforeNextExposure Duration of the readout that takes place before the next exposure can start [seconds]
 */

pair<double, double> Camera::exposeDetector(Detector &detector, double startTime, double exposureTime, double readoutTimeBeforeNextExposure, int binnumber, int subsubfieldx, int subsubfieldy)  //%% Changed to double pair for split
{
    // Get the value for the degrading TransmissionEfficiency parameter at the startTime of this exposure

    //double transmissionEfficiency = telescope.getTransmissionEfficiency(startTime);

//%%	For wavelength dependency: Calculate the current wavelength being processed and select the according transmission efficiency
    double wavelength = binOrigin + binnumber * binWidth;  //%% Current wavelength
    vector<double> transmissionEfficiencyFull = telescope.getTransmissionEfficiency(startTime);  //%% Vector of all TE
    double transmissionEfficiency = transmissionEfficiencyFull[binnumber];  //%% Correct TE

    Log.debug("Camera: TransmissionEfficiency at time "+to_string(startTime)+" is "+to_string(transmissionEfficiency));


    // Get the focal plane coordinates of the center and the corners of the subfield (in [mm]).
    // To compute the diagonal length of the subfield, we only need the lower left (X00, Y00)
    // and the upper right (X11, Y11) corner of the subfield.

    double centerXmm, centerYmm;
    tie(centerXmm, centerYmm) = detector.getFocalPlaneCoordinatesOfSubfieldCenter(subsubfieldx, subsubfieldy); //%% Added subsubfield for spectral dependency

    double corner00Xmm, corner00Ymm, corner11Xmm, corner11Ymm, dummy;
    tie(corner00Xmm, corner00Ymm, dummy, dummy, corner11Xmm, corner11Ymm, dummy, dummy) = detector.getFocalPlaneCoordinatesOfSubfieldCorners(subsubfieldx, subsubfieldy); //%% Added subsubfield for spectral dependency

    // Convert the undistorted [mm] to distorted [mm] focal plane coordinates

    if (includeFieldDistortion)
    {
        Log.info("Camera: including field distortion");

        tie(centerXmm, centerYmm) = distortedToUndistortedFocalPlaneCoordinates(centerXmm, centerYmm);
        tie(corner00Xmm, corner00Ymm) = distortedToUndistortedFocalPlaneCoordinates(corner00Xmm, corner00Ymm);
        tie(corner11Xmm, corner11Ymm) = distortedToUndistortedFocalPlaneCoordinates(corner11Xmm, corner11Ymm);
    }

    Log.debug("Camera: center of subfield at (Xmm, Ymm) = (" + to_string(centerXmm) + ", " + to_string(centerYmm) + ") mm");
    Log.debug("Camera: lower left corner of subfield at (Xmm, Ymm) = (" + to_string(corner00Xmm) + ", " + to_string(corner00Ymm) + ") mm");
    Log.debug("Camera: upper right corner of subfield at (Xmm, Ymm) = (" + to_string(corner11Xmm) + ", " + to_string(corner11Ymm) + ") mm");


    // Convert the focal plane coordinates [mm] to (alpha, delta) equatorial sky coordinates [rad]

    double centerRA, centerDec;
    tie(centerRA, centerDec) = focalPlaneToSkyCoordinates(centerXmm, centerYmm);

    double corner00RA, corner00Dec;
    tie(corner00RA, corner00Dec) = focalPlaneToSkyCoordinates(corner00Xmm, corner00Ymm);

    double corner11RA, corner11Dec;
    tie(corner11RA, corner11Dec) = focalPlaneToSkyCoordinates(corner11Xmm, corner11Ymm);

    Log.debug("Camera: center of subfield at (alpha, delta) = (" + to_string(rad2deg(centerRA)) + ", " + to_string(rad2deg(centerDec)) + ") deg");
    Log.debug("Camera: lower left corner of subfield at (alpha, delta) = (" + to_string(rad2deg(corner00RA)) + ", " + to_string(rad2deg(corner00Dec)) + ") deg");
    Log.debug("Camera: upper right corner of subfield at (alpha, delta) = (" + to_string(rad2deg(corner11RA)) + ", " + to_string(rad2deg(corner11Dec)) + ") deg");


    // Compute the angular distance on the sky between the lower left and the upper right corner
    // of the subfield, to estimate the "radius" of the subfield.

    SkyCoordinates skyCoordinates00(corner00RA, corner00Dec, Angle::radians);
    SkyCoordinates skyCoordinates11(corner11RA, corner11Dec, Angle::radians);
    
    double radius = angularDistanceBetween(skyCoordinates00, skyCoordinates11, Angle::radians) / 2.0;

    Log.debug("Camera: semi-diagonal of subfield = " + to_string(rad2deg(radius)) + " deg");


    // Get a catalog of stars that fall on the subfield. Take the radius a bit larger so that the 
    // queried area includes possible small shifts of the projected subfield because of jitter.


//%% Spectral dependency: For the first wavebin get all stars 
    unsigned long Nstars;
    if (binnumber == 0)
    {
    Nstars = sky.selectStarsWithinRadiusFrom(centerRA, centerDec, radius * 1.1, Angle::radians);

    Log.info("Camera: Found " + to_string(Nstars) + " stars on and near the subfield");  

    if (includeAberrationCorrection)
    {
        Log.info("Camera: applying " + aberrationCorrectionType + " aberration correction to the selected stars in the subfield.");

        // The time at the middle of the time series is the time when the Sun is defined to be 180 degrees away from platform pointing

        double timeMiddle = numExposures * (exposureTime + readoutTimeBeforeNextExposure) / 2.0;

        // Get the apparent position of the stars, i.e. apply the differential aberration correction to
        // all the star positions in this starCatalog.

        // We do this calcuation only once per exposure as the effect is negligible within the exposure time
    
        sky.aberrateSelectedStarPositions(platform, aberrationCorrectionType, startTime, timeMiddle);
    }
//%% No need to recompute for all other wavebins, just read the length of the same array
    }
    else
    {
        Nstars = sky.selectStarsWithinRadius();
    }


    // If the telescope and/or platform show small variations (e.g. due to jitter) during the exposure,
    // the exposure time is split up in many small intervals, to track the effect of these variations
    // on the exposure. The largest time interval for which the variations can still be reliably tracked
    // is called the heartbeatInterval. The time step used should be either the heartbeat interval or the
    // expsosure time whatever is smallest. 

    double timeStep = min(telescope.getHeartbeatInterval(), exposureTime);


    // Later on we will have to convert from magnitudes to fluxes. Precompute a constant prefactor.
    // fluxOfV0Star is the photon flux [photons/s/m^2/nm] for a V=0 G2V-star.
    // Units of fluxFactor: [photons/s]
  
//%% The prefactor is now also altered depending on the current wavelength, for spectral dependency 
    double hc = Constants::CLIGHT * Constants::HPLANCK * 1.e9; 	// [J nm]
    double Ephoton = hc / wavelength;
    double ReferenceFlux = fluxOfV0Star * hc / throughputLambdaC;  //%% ThroughputLambdaC is used as reference wavelength
    double FluxAtWavelength = ReferenceFlux * pow(throughputLambdaC / wavelength, 5) / Ephoton;

    const double fluxFactor = FluxAtWavelength * binWidth * transmissionEfficiency * telescope.getLightCollectingArea(); 		

    // Update the internal clock

    internalTime = startTime;

   bool subsubfield = subsubfieldx + subsubfieldy;		//%% For spectral dependency, check if first subsubfield
   bool subsubfieldlast = ((subsubfieldx == numsubsubfieldsx-1) && (subsubfieldy == numsubsubfieldsy-1));  //%% For spectral dependency, check if last subsubfield

    // Take the flux of point sources (stars) into account.
    // Break up the exposure time in small intervals (hearbeat intervals) to track jitter while exposing.

    while (internalTime < startTime + exposureTime)
    {
        // Update the time-dependent parameters (if any) of some classes to to their value at the current time. 

        this->updateParameters(internalTime);
        telescope.updateParameters(internalTime, binnumber, subsubfield, subsubfieldlast);  //%% added wavebin and bool subsubfield for spectral dependency
        detector.updateParameters(internalTime);
        sky.updateParameters(internalTime);

        // Loop over all stars in the catalog, and add their flux to the subfield

        unsigned int NstarsInSubfield = 0;

        for (unsigned int n = 0; n < Nstars; n++)
        {
            // Compute the focal plane coordinates (in [mm]) of this particular star
           
            unsigned long starID;
            double RA, dec, Vmag, TempStar;  //%% Added Temperature for spectral dependency

            tie(starID, RA, dec, Vmag, TempStar) = sky.getSelectedStar(n);  //%% Added Temperature for spectral dependency
            
            double Xmm, Ymm;
            tie(Xmm, Ymm) = skyToFocalPlaneCoordinates(RA, dec);

            // If required, include field distortion

            if (includeFieldDistortion)
            {
                tie(Xmm, Ymm) = undistortedToDistortedFocalPlaneCoordinates(Xmm, Ymm);
            }

            // Compute the flux [photons] of this star
            // Photons are always an integer number, so round down.

//%%	Added for wavelength dependency: Take into account the temperature of the star, modifying the shape of the spectrum (BlackBody)
	    double tempFactor = (exp(hc/(throughputLambdaC*Constants::KBOLTZMANN*TempStar)) - 1) / (exp(Ephoton/(Constants::KBOLTZMANN*TempStar)) - 1);
            double flux = floor(fluxFactor * pow(10.0, -0.4 * Vmag) * tempFactor * timeStep);  //%% TempFactor added for spectral dependency

            // Let the detector add the flux to the appropriate pixel. 
            // Detector.flux() returns the pixel coordinates to which the flux was added.

            bool isInSubfield;
            double rowPix, colPix;    // subfield (not CCD) pixel coordinates

            tie(isInSubfield, rowPix, colPix) = detector.addFlux(Xmm, Ymm, flux, subsubfieldx, subsubfieldy);  //%% Added subsubfield for spectral dependency

            // If the star is indeed in the subfield, collect the following information to later write to HDF5
            //    1) average (Xmm, Ymm) coordinates of the star during the exposure                   [mm]
            //    2) average (row, col) pixel coordinates of the star on the CCD during the exposure  [pix]
            //    3) the total number of photons gathered of this star during the exposure            [photons]
            //    4) the total number of times that the star was in the subfield during the exposure
            //
            // Note: Due to jitter, the star can move in and out the subfield during the exposure

            if (isInSubfield)
            {
                NstarsInSubfield++;

                // If this is the first time we encounter this startTime, initialise the information

                if (detectedStarInfo.find(startTime) == detectedStarInfo.end())
                {
                    detectedStarInfo[startTime][starID] = {{Xmm, Ymm, rowPix, colPix, flux, 1.0, TempStar}};  //%% Added temperature for spectral dependency
                }
                else
                {
                    // If this is the first time that we encounter this star ID associated with this startTime,
                    // initialise the information. If not, just update the info.

                    if (detectedStarInfo[startTime].find(starID) == detectedStarInfo[startTime].end())
                    {
                        detectedStarInfo[startTime][starID] = {{Xmm, Ymm, rowPix, colPix, flux, 1.0, TempStar}};  //%% Added temperature for spectral dependency
                    }
                    else
                    {
                        detectedStarInfo[startTime][starID][0] += Xmm;      // Will be used to compute average Xmm during the exposure
                        detectedStarInfo[startTime][starID][1] += Ymm;      // Will be used to compute average Ymm during the exposure
                        detectedStarInfo[startTime][starID][2] += rowPix;   // Will be used to compute average pixel row during the exposure
                        detectedStarInfo[startTime][starID][3] += colPix;   // Will be used to compute average pixel column during the exposure
                        detectedStarInfo[startTime][starID][4] += flux;     // Total flux
                        detectedStarInfo[startTime][starID][5] += 1;        // # of times a star was on the subfield during an exposure 
                    }
                }
            }
        }

        Log.debug("Camera: at time " + to_string(internalTime) + ": incremented flux of " + to_string(NstarsInSubfield) + " stars in subfield");


        // Update the clock. Normally with 'timeStep', but if adding timeStep would overstep
        // the total exposure time, take the small rest time instead (but update the internal time first!).

        internalTime += timeStep;
        timeStep = min(timeStep, startTime + exposureTime - internalTime);
    }

    return make_pair(centerRA, centerDec);  //%% Used for spectral dependency, return coordinates
}





//%% Separately calculate the background to apply it after the convolution, to prevent edge effects due to the splitting of the subfield
void Camera::SkyBackground(Detector &detector, double startTime, double exposureTime, double readoutTimeBeforeNextExposure, int binnumber, double centerRA, double centerDec, int subsubfieldx, int subsubfieldy)
{
    // Take the flux of the stellar background and the zodiacal light into account. Use one value for the entire subfield.
    // A negative value for the user given sky background value [phot/pix/s] signals that we should compute it ourselves.
    // Note: - The output of sky.zodiacalFlux() is in [J s^{-1} m^{-2} sr^{-1} m^{-1}]
    //       - As wavelength range we take the entire throughput band.
    //       - Photons are always an integer number, thus round down.
    //
    // The small sky background contribution during the readout with open shutter is not taken into account here
    // but in the function Detector::applyOpenShutterSmearing().

    totalSkyBackground = 0.0;

//%%Tae the wavelength into account
    double wavelength = binOrigin + binnumber * binWidth;
    vector<double> transmissionEfficiencyFull = telescope.getTransmissionEfficiency(startTime);
    double transmissionEfficiency = transmissionEfficiencyFull[binnumber];

    double hc = Constants::CLIGHT * Constants::HPLANCK * 1.e9;	// [J nm]
    double Ephoton = hc / wavelength;


    if (userGivenSkyBackground < 0.0)
    {
//%%	The background is calculated within the same wavelength bin as the flux, so that the same throughput can be used
	const double energyOfOnePhoton = Ephoton;	// [J]
	const double lambda1 = wavelength * 1.e-9;	//[m]
	const double lambda2 = (wavelength + binWidth) * 1.e-9;	//[m]

        const double zodiacalFlux = sky.zodiacalFlux(centerRA, centerDec, lambda1, lambda2)                                   // [phot/exposure]
                                    * (exposureTime + readoutTimeBeforeNextExposure) * transmissionEfficiency * telescope.getLightCollectingArea()
                                    * detector.getSolidAngleOfOnePixel(plateScale) / energyOfOnePhoton; 

        const double stellarBackgroundFlux = sky.stellarBackgroundFlux(centerRA, centerDec, lambda1, lambda2)                 // [phot/exposure]
                                             * (exposureTime + readoutTimeBeforeNextExposure) * transmissionEfficiency * telescope.getLightCollectingArea()
                                             * detector.getSolidAngleOfOnePixel(plateScale) / energyOfOnePhoton;      


        totalSkyBackground = floor(zodiacalFlux + stellarBackgroundFlux);
        detector.addFlux(totalSkyBackground, subsubfieldx, subsubfieldy);  //%% For spectral dependence added subsubfield

        Log.debug("Camera: zodiacal flux level in subfield = " + to_string(zodiacalFlux) + " photons/pixel/exposure");
        Log.debug("Camera: stellar background flux level in subfield = " + to_string(stellarBackgroundFlux) + " photons/pixel/exposure");
    }
    else
    {

//%%	In case the background is constant, split it up evenly between the wavelength bins for ease of calculation
	totalSkyBackground = floor(userGivenSkyBackground * exposureTime * transmissionEfficiency / wavelengthBins);	

        detector.addFlux(totalSkyBackground, subsubfieldx, subsubfieldy);

        Log.debug("Camera: user-given sky background flux over exposure= " + to_string(userGivenSkyBackground * exposureTime) + " photons/pixel/exposure");
    }

    // Save the sky background value that we added. [photons/pix/exposure]

    skyBackgroundValues.push_back(totalSkyBackground);  //%% Due to spectral dependency this vector has all bins and all subsubfields for all exposures

    // Save the transmissionEfficiency value that was calculated for this exposure.

    transmissionEfficiencyValues.push_back(transmissionEfficiency);  //%% Due to spectral dependency this vector has all bins and all subsubfields for all exposures

    return;
}












/**
 * @brief      Calculate the gnomonic radial distance with respect to the optical axis in the focal plane
 *
 * @param[in]  xFP  Focal plane x-coordinate [mm]
 * @param[in]  yFP  Focal plane y-coordinate [mm]
 *
 * @return     the angular distance of the star w.r.t. the optical axis [rad]
 * 
 */
double Camera::getGnomonicRadialDistanceFromOpticalAxis(double xFP, double yFP)
{
    const double tanx = xFP / (*focalLength)();
    const double tany = yFP / (*focalLength)();

    double angularDistance = acos(1.0/sqrt(1.0 + tanx*tanx + tany*tany));

    // Take care that the angle is between [0, 2*PI]

    if (angularDistance < 0.0)
    {
        angularDistance += 2.0 * Constants::PI;
    }

    if (angularDistance > 2.0 * Constants::PI)
    {
        angularDistance -= 2.0 * Constants::PI;
    }

    // That's it!

    return angularDistance;
}











/**
 * \brief      Computes the (x,y) coordinates in the focal plane, of a star with given equatorial 
 *             sky coordinates, assuming a pinhole camera.
 *             
 * \details    The transformation is done with the 'current' orientations of the telescope and the platform.
 * 
 * \param raStar          Right ascension of the star [rad]
 * \param decStar         Declination of the star [rad]
 * \param useInitialOrientation  true: use initial orientation of telescope and platform (i.e. before first exposure)
 *                               false: use current (jittered and drifted) telescope and platform orientation   
 *
 * return pair (xFP,yFP): Cartesian coordinate of the projected star in the focal plane in the FP system.
 *                        The unit is the same as the one of the focal length, usually [mm].
 */

pair<double, double> Camera::skyToFocalPlaneCoordinates(double raStar, double decStar, bool useInitialOrientation)
{
    // Get the rotation matrices Equatorial -> Spacecraft and Spacecraft -> Telescope

    arma::mat rotEQ2SC;
    arma::mat rotSC2TL;

    if (useInitialOrientation)
    {
        rotEQ2SC = platform.getEquatorialToUnjitteredSpacecraftRotationMatrix();
        rotSC2TL = telescope.getPlatformToUndriftedTelescopeRotationMatrix();
    }
    else
    {
        rotEQ2SC = platform.getEquatorialToJitteredSpacecraftRotationMatrix();
        rotSC2TL = telescope.getPlatformToDriftedTelescopeRotationMatrix();
    }

    // Compute the rotation matrix to convert cartesian coordinates in the telescope reference frame to
    // cartesian coordinates in the focal plane reference frame

    arma::mat rotTL2FP;
    const double fpAngle = (*focalPlaneAngle)();
    rotTL2FP <<  cos(fpAngle) << sin(fpAngle) << 0 << arma::endr
             << -sin(fpAngle) << cos(fpAngle) << 0 << arma::endr
             <<     0         <<      0       << 1 << arma::endr;


    // Combine all the rotation matrices

    arma::mat rotEQ2FP = rotTL2FP * rotSC2TL * rotEQ2SC;

    // Compute the cartesian coordinates of the star in the equatorial reference frame

    arma::colvec starEQ = {cos(decStar)*cos(raStar), cos(decStar)*sin(raStar), sin(decStar)};

    // Transform these coordinates to the corresponding ones in the focal plane reference frame:

    arma::colvec starFP = rotEQ2FP * starEQ;

    // Convert the units to the one of focalLength (usually [mm]), and normalize the coordinates 
    // to take into account the pinhole camera projection.

    double xFP = - (*focalLength)() * starFP[0]/starFP[2];
    double yFP = - (*focalLength)() * starFP[1]/starFP[2];

    // That's it

    return make_pair(xFP, yFP);
}













/**
 * \brief Compute the equatorial sky coordinates of a star which has the given focal plane (FP) coordinates (x,y),
 *        assuming a pinhole camera model
 *        
 * \param xFP     Focal plane x-coordinate in the FP system [mm]
 * \param yFP     Focal plane y-coordinate in the FP system [mm]
 * \param useInitialOrientation  true: use initial orientation of telescope and platform (i.e. before first exposure)
 *                               false: use current (jittered and drifted) telescope and platform orientation  
 *                               
 * \return (alpha, delta)  Equatorial coordinates (RA & Dec) of the star [rad]
 */

pair<double, double> Camera::focalPlaneToSkyCoordinates(double xFP, double yFP, bool useInitialOrientation)
{    

    // Undo the reverse-image projection effect of the pinhole

    arma::colvec vecFP = {-xFP / (*focalLength)(), -yFP / (*focalLength)(), 1.0};

    // Compute the rotation matrix to convert cartesian coordinates in the focal plane reference frame to
    // cartesian coordinates in the telescope reference frame

    arma::mat rotFP2TL;
    const double fpAngle = (*focalPlaneAngle)();
    rotFP2TL << cos(fpAngle) << -sin(fpAngle) << 0 << arma::endr
             << sin(fpAngle) <<  cos(fpAngle) << 0 << arma::endr
             <<     0        <<       0       << 1 << arma::endr;

    // Get the rotation matrices Telescope -> Spacecraft and Spacecraft -> Equatorial

    arma::mat rotSC2EQ;
    arma::mat rotTL2SC;

    if (useInitialOrientation)
    {
        rotSC2EQ = platform.getUnjitteredSpacecraftToEquatorialRotationMatrix();
        rotTL2SC = telescope.getUndriftedTelescopeToPlatformRotationMatrix();
    }
    else
    {
        rotSC2EQ = platform.getJitteredSpacecraftToEquatorialRotationMatrix();
        rotTL2SC = telescope.getDriftedTelescopeToPlatformRotationMatrix();
    }

    // Combine all the rotation matrices

    arma::mat rotFP2EQ = rotSC2EQ * rotTL2SC * rotFP2TL;

    // Transform the unnormalized focal plane coordinates to the corresponding ones in the equatorial reference frame

    arma::colvec vecEQ = rotFP2EQ * vecFP;

    // Convert the cartesian equatorial coordinates to equatorial sky coordinates

    double norm = sqrt(vecEQ[0]*vecEQ[0] + vecEQ[1]*vecEQ[1] + vecEQ[2]*vecEQ[2]); 
    double decStar = Constants::PI/2.0 - acos(vecEQ[2]/norm);
    double raStar = atan2(vecEQ[1], vecEQ[0]);

    // Ensure that the right ascension is positive

    if (raStar < 0.0) { raStar += 2.*Constants::PI; }

    // That's it!

    return make_pair(raStar, decStar);
}














/**
 * @brief      Convert from undistorted to distorted focal plane coordinates
 *
 * @param[in]  xFPmm  Undistorted focal plane x-coordinate [mm]
 * @param[in]  yFPmm  Undistorted focal plane y-coordinate [mm]
 *
 * @return     (xFPdist, yFPdist) distorted x and y coordinates [mm]
 */
pair<double, double> Camera::undistortedToDistortedFocalPlaneCoordinates(double xFPmm, double yFPmm)
{
	const array<double, 3> coefficients = (*distortionCoef)();

    double alpha = atan2(yFPmm, xFPmm);  // Position angle on the focal plane [radians]
    
    double rFP = sqrt(xFPmm * xFPmm + yFPmm * yFPmm) / (*focalLength)();	// Undistorted radial distance [normalised pixels]
    double distortion = (coefficients[0] * pow(rFP, 3) + coefficients[1] * pow(rFP, 5) + coefficients[2] * pow(rFP, 7)) * (*focalLength)();	// Distortion [mm]

    double xFPdist = xFPmm + cos(alpha) * distortion;
    double yFPdist = yFPmm + sin(alpha) * distortion;

    return make_pair(xFPdist, yFPdist);
}











/**
 * @brief      Convert from distorted to undistorted focal plane coordinates
 *
 * @param[in]  xFPdist  Distorted focal plane x-coordinate [mm]
 * @param[in]  yFPdist  DIstorted focal plane y-coordinate [mm]
 *
 * @return     (xFPmm, yFPmm) distorted x and y coordinates [mm]
 */
pair<double, double> Camera::distortedToUndistortedFocalPlaneCoordinates(double xFPdist, double yFPdist)
{
	const array<double, 3> inverseCoefficients = (*inverseDistortionCoef)();

    double alpha = atan2(yFPdist, xFPdist);  // Position angle on the focal plane [radians]
    
    double rFP = sqrt(xFPdist * xFPdist + yFPdist * yFPdist) / (*focalLength)();	// Distorted radial distance [normalised pixels]
    double distortion = (inverseCoefficients[0] * pow(rFP, 3) + inverseCoefficients[1] * pow(rFP, 5) + inverseCoefficients[2] * pow(rFP, 7)) * (*focalLength)();	// Distortion [mm] -> negative
    
    double xFPmm = xFPdist +  cos(alpha) * distortion;
    double yFPmm = yFPdist + sin(alpha) * distortion;
    
    return make_pair(xFPmm, yFPmm);
}






/**
 * @brief   Returns the total sky background, expressed in photons / pixel / exposure.
 *
 * @ return  Total sky background [photons / pixel / exposure].
 */
vector<double> Camera::getTotalSkyBackground()
{
    if (skyBackgroundValues.size() != 0)
    {
	vector<double > backgroundWave(skyBackgroundValues.end() - wavelengthBins, skyBackgroundValues.end());	//%% Spectral dependency: the vector contains all exposures with #wavelengthBins*#subsubfields values each, one for each bin and subsubfield. Use the last exposure and last subsubfield (NOT IDEAL - AVERAGE?)
	return backgroundWave;
    }
    else
    {
        throw std::runtime_error( "Camera::getTotalSkyBackground() was called with no skybackground being available");
    }
}












/**
 * \brief Returns the focal length of the camera, expressed in mm.
 * 
 * \return Focal length of the camera, expressed in mm.
 */ 
double Camera::getFocalLength()
{
    return (*focalLength)();
}
